### ISSUE TITLE
Split the Graph API surface to smaller modules using module augmentation.

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#1024]
- [ ] Identify the splitting strategy for Graph APIs (path, TOC, types, [regex](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/config/ModulesMapping.jsonc), etc.)
- [ ] Post-kiota job to rearrange generated API Operations

**Comment by sebastienlevert** [comment]
Based on our discussions, this should happen via the paths.
