### ISSUE TITLE
PageIterator hangs or crashes after first fetch

### ISSUE THREAD

**Issue by WattsGreg** [microsoftgraph/msgraph-sdk-javascript#1044]
# Bug Report

## Prerequisites

-   [Yes] Can you reproduce the problem?
-   [Yes] Are you running the latest version?
-   [Yes] Are you reporting to the correct repository?
-   [Yes] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When fetching a large list of users (over 5000), PageIterator only successfully fetches the first request. Subsequent calls fail to execute, and only the first 100 (default amount I believe) records are retrieved.

**Console Errors:** There are no console errors or error messages/exceptions for this issue

## Steps to Reproduce

Use the suggested code that uses PageIterator to fetch records from a graph endpoint that pages data. You could use take() to limit the number per page.

**Expected behavior:** All paged data is fetched.

**Actual behavior:** Only the first fetch is returned.

## Additional Context

Rolling back to 3.0.0 has fixed the issue.
I expect the problem might be with some formatting of the nextLink URL inside the library. I passed the nextLink URL through the client directly and was returned with an internal server error from Azure. I did not try the nextLink directly in version 3.0.0

SDK Version - Latest (3.0.3)

**Comment by jsk01** [comment]
I also see the same issue.  v3.0.2 logic works as expected but when I update to 3.0.3 I only receive the initial default number of rows.  No errors generated.

**Comment by nikithauc** [comment]
@WattsGreg Thank you for reporting this issue! This should be fixed and expect a patch to be released soon.

**Comment by nikithauc** [comment]
@WattsGreg  @jsk01 Can you please check if issue is resolved with https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.4
or if the issue persists?

**Comment by WattsGreg** [comment]
> @WattsGreg @jsk01 Can you please check if issue is resolved with https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.4 or if the issue persists?

This is now working as expected on 3.0.4.

Thank you for fixing!

**Comment by nikithauc** [comment]
@WattsGreg Thank you for your prompt help in fixing the issue!
