### ISSUE TITLE
Upgrade to 1.2.0 of msgraph sdk results in failing pnp js odata parsing

### ISSUE THREAD

**Issue by ramonitor** [microsoftgraph/msgraph-sdk-javascript#106]
Upgrading the msgraph-sdk-javascript package to 1.2.0 results in a no longer working pnp js search parsing. 

Downgrading to version 1.0.0 makes it work again. 

With version 1.2.0 of this sdk, I get errors like 'TypeError: Cannot read property 'isUrlAbsolute' of undefined' or 'unexpected token in json at position 0' as result of doing a SharePoint Search via PnP JS. Tested with 1.1.2, 1.1.4 and 1.2.1 of pnp js.

**Comment by MIchaelMainer** [comment]
I'm sorry that you encountered this. Thank you for reporting this issue.

@ramonitor What call is being made? Can you capture and share the following:
- JS client calls
- sanitized (no PII) request and response URLs, headers, and bodies
- links to documentation that describe the functionality that you expect to work

**Comment by ramonitor** [comment]
@MIchaelMainer, I'll get back on this.

**Comment by ramonitor** [comment]
@MIchaelMainer , sorry for the late followup. I just put up a little code sample (https://github.com/ramonitor/graph-sdk-pnp-issue) to demonstrate the issue. As soon as you instantiate a Graph Client with a version > 1.0.0, the sp.search() via pnpjs no longer works;

```
 const client: GraphClient.Client = GraphClient.Client.init({
            authProvider: done => done(null, 'MyAccessToken')
        }); 
```
results in:

```
{
  "response": {
    "size": 0,
    "timeout": 0
  },
  "status": 403,
  "statusText": "Forbidden",
  "isHttpRequestError": true
}
```

Downgrading to version 1.0 of the MS Graph SDK makes the search query work fine. My guess is that is has something to do with the isomorphic-fetch dependency.

**Comment by muthurathinam** [comment]
@ramonitor Are you facing the same issue in [latest](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0) version i.e 1.6.0 ?

**Comment by muthurathinam** [comment]
Closing this as there is no response from the user. Re-open if the issue still persists.
