### ISSUE TITLE
Question: The specified object was not found in the store., The process failed to get the correct properties.

### ISSUE THREAD

**Issue by cbishop-fv** [microsoftgraph/msgraph-sdk-javascript#1065]
# Questions

## Prerequisites

-   [ ] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

## Description

We have an office outlook add-in and use https://github.com/AzureAD/microsoft-authentication-library-for-js for azure auth along with msgraph to make calls to perform mailbox actions for users in the addin.

We are seeing this error quite a bit.   

```
We have an office outlook add-in and use https://github.com/AzureAD/microsoft-authentication-library-for-js for azure auth along with msgraph to make calls to perform mailbox actions for users in the addin.
```

One function we use this for is to send a draft email and its attachments on behalf of the users. Maybe this error is coming from that flow. And I believe only from desktop clients. Possibly due to the attachment not being synced to the server. We have to put in a timeout / retried on the draft itself for this reason. We compare the attachments returned with the draft from graph against the desktop attachments and manually  add / remove items that are out of sync via the graph API. 

Any thoughts on what this error may be related to or how we can correct it?

**Screenshots:** [If applicable, add screenshots to help explain your problem]

![image](https://user-images.githubusercontent.com/56599161/203356714-11d5ee5a-29b0-48bd-a59e-a4dab83ca825.png)

SDK Version - [SDK version you are using]

    "@microsoft/microsoft-graph-client": "^3.0.0",

> Node Version - [The version of Node you are using]

    "node": "14.16.0",

**Comment by nikithauc** [comment]
@cbishop-fv . Thank you for reaching out!

This seems to be an issue with the Graph API and not the Graph JS library. 

I would recommend posting this issue  with Microsoft Graph tags on Microsoft Q & A -> https://learn.microsoft.com/en-us/answers/index.html or StackOverFlow.


Similar issues reported:
https://learn.microsoft.com/en-us/graph/outlook-immutable-id
https://stackoverflow.com/questions/60094417/in-microsoft-graph-api-message-id-has-changed-without-any-reason
https://stackoverflow.com/questions/70340385/ms-graph-mail-the-specified-object-was-not-found-in-the-store

**Comment by cbishop-fv** [comment]
> @cbishop-fv . Thank you for reaching out!
> 
> This seems to be an issue with the Graph API and not the Graph JS library.
> 
> I would recommend posting this issue with Microsoft Graph tags on Microsoft Q & A -> https://learn.microsoft.com/en-us/answers/index.html or StackOverFlow.
> 
> Similar issues reported: https://learn.microsoft.com/en-us/graph/outlook-immutable-id https://stackoverflow.com/questions/60094417/in-microsoft-graph-api-message-id-has-changed-without-any-reason https://stackoverflow.com/questions/70340385/ms-graph-mail-the-specified-object-was-not-found-in-the-store

Hello Thank you for the help.

I have implemented the header for prefer immutable ids but we are still seeing about a 12 to 15 percent error rate on our calls with this error. I can see the header is added in the requests. Do you have any other ideas how we may correct this?

`
    const iid = 'IdType="ImmutableId"';
    try {
      let res;
      switch (verb) {
        case 'GET':
          res = await graph.api(`${graphUrl}${path}`).header('Prefer', iid).get();
          break;
        case 'POST':
          res = await graph.api(`${graphUrl}${path}`).header('Prefer', iid).post(content, callback);
          break;
        case 'PUT':
          res = await graph.api(`${graphUrl}${path}`).header('Prefer', iid).put(content);
          break;
        case 'PATCH':
          res = await graph.api(`${graphUrl}${path}`).header('Prefer', iid).patch(content);
          break;
        case 'DELETE':
          res = await graph.api(`${graphUrl}${path}`).header('Prefer', iid).delete();
          break;
        default:
          throw new Error('Error unsupported request type');
`

**Comment by cbishop-fv** [comment]
It looks as if this error was coming from the outlook desktop client and the message item had not been synced to the server yet. We added an increasing timeout retry to resolve this.
