### ISSUE TITLE
API Endpoints are a fix set of inputs to the .api function

### ISSUE THREAD

**Issue by Thomas-Carlsen** [microsoftgraph/msgraph-sdk-javascript#1078]
Hi :)

It would be really cool if the type of `path` below is a finite set of string literals for each of the possible endpoints in the graph api:

![image](https://user-images.githubusercontent.com/45513175/196375958-2f5738bb-3881-455e-b4d3-fcd4dbdf612f.png)

And also if that specific endpoint could be linked to the `GraphRequest` return type - so that it is possible to get the type of what have been queried without have to explicit note it with the `as` syntax as here:

![image](https://user-images.githubusercontent.com/45513175/196376415-4d356fd2-fd4a-4bb4-877c-31235d4bd7cf.png)

Instead, it would know that `me` is accosiated to the `User` type so `response` above is having the type `User` when using the `.get()` method.

Thanks.

**Comment by ddyett** [comment]
closing this out as tracked by #979
