### ISSUE TITLE
Ability to use service / daemon process to get the contents of the files at an enterprise level 

### ISSUE THREAD

**Issue by Arvind6353** [microsoftgraph/msgraph-sdk-javascript#108]
Hi , 

I have a use case where in I need to use a service / background process to get the files present in one drive at an enterprise level . Can you guys please let me know the steps involved. 

For getting access token I assume there must be a way with out involving user (such as using a service account etc).

Thanks,
Arvindan

**Comment by muthurathinam** [comment]
Go through installation and usage in [README](https://github.com/microsoftgraph/msgraph-sdk-javascript#microsoft-graph-javascript-client-library) to setup and getting started with SDK in your application.

To get list of drives, to get all files or a file from OneDrive refer API Docs [[#1](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/drive_list), [#2](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_list_children) and [#3](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/driveitem_get)]
Note: Make sure you have necessary permissions for the account from which you are making request..!!

To explore Microsoft Graph APIs use "[Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)"

**Comment by Arvind6353** [comment]
Thanks for the info :) Will have a look at this.

**Comment by Arvind6353** [comment]
Hi @sibelius @muthurathinam : I created an app via azure  and got the access token . I tried to use the graph api "https://graph.microsoft.com/v1.0/me/drive/root/children" .
Am getting the below error : 

{
    "error": {
        "code": "BadRequest",
        "message": "Unable to retrieve user's mysite URL.",
        "innerError": {
            "request-id": "69434821-0fe6-435a-af52-3f88956b2d02",
            "date": "2018-09-18T03:24:16"
        }
    }
}

When I use the graph explorer and login with my app account , am able to see the results.

Kindly help with this .

**Comment by muthurathinam** [comment]
@Arvind6353 
Can you provide more details about your request and response:
1. Request headers (remember to hide your auth token)
2. Response headers
3. Complete response body

**Comment by Arvind6353** [comment]
Hi @muthurathinam ,
Please find the details below : 
**Request** :
GET /v1.0/me/drive/root/children HTTP/1.1
Host: graph.microsoft.com
Authorization: Bearer xxxxxx

**Response:**

**Response Header** :
Cache-Control →private
Content-Type →application/json
Date →Tue, 18 Sep 2018 03:35:54 GMT
Duration →2286.7285
Strict-Transport-Security →max-age=31536000
Transfer-Encoding →chunked
client-request-id →e996603c-aa63-4906-9ca3-2a73bca786e3
request-id →e996603c-aa63-4906-9ca3-2a73bca786e3
x-ms-ags-diagnostic →{"ServerInfo":{"DataCenter":"East Asia","Slice":"SliceC","Ring":"5","ScaleUnit":"001","Host":"AGSFE_IN_11","ADSiteName":"EAS"}}


**Response Body :** 
{
    "error": {
        "code": "BadRequest",
        "message": "Unable to retrieve user's mysite URL.",
        "innerError": {
            "request-id": "e996603c-aa63-4906-9ca3-2a73bca786e3",
            "date": "2018-09-18T03:35:54"
        }
    }
}

**Comment by muthurathinam** [comment]
@Arvind6353 Check [this](https://github.com/microsoftgraph/microsoft-graph-docs/issues/1354) out. It seems like a same scenario for you.!

**Comment by sibelius** [comment]
@Arvind6353 check this https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/114#issuecomment-421518305

as you are not using an user token

you do not have access to `/me`

you need to get `/users` and get data from an specific user

**Comment by Arvind6353** [comment]
Hi @muthurathinam @sibelius  I have got the access from admin and /users works now . 

I have a question . Is there an endpoint which gives me the list of drives present . 

What is the best way to get the list of all documents present in the one drive in an enterprise level .?

Thanks,
Arvindan

**Comment by sibelius** [comment]
You need to iterate through all the users

**Comment by muthurathinam** [comment]
@Arvind6353 Please close this issue if your request is addressed. In future do post any issues with respect to this library in here and post your queries like this in Stackoverflow.
