### ISSUE TITLE
Uploading files larger than 4 MB

### ISSUE THREAD

**Issue by DavidCannon** [microsoftgraph/msgraph-sdk-javascript#111]
Hi @muthurathinam, I was wondering if you could provide a sample of how to upload a file that is larger than 4 MB using a browser?

**Comment by muthurathinam** [comment]
@DavidCannon To upload a file to OneDrive..?

**Comment by DavidCannon** [comment]
Yes. I'm actually uploading to SharePoint, but SharePoint and OneDrive for Business are pretty much the same. So what works for OneDrive should be fine. Thank you!

**Comment by muthurathinam** [comment]
@DavidCannon 
Support for [Large File uploading](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/94) to OneDrive is implemented and will be available in our next release.

Thank you for your patience till our next release. We really appreciate it!

**Comment by DavidCannon** [comment]
Thank you for this, but I'm afraid OneDrive for Business and SharePoint do not work, even though they are supported in the Graph API. The reason is because you have the "me" drive hard-coded, rather than allowing us to provide the drive ID. Here's an example of where it is hard-coded:

`return encodeURI(`/me/drive/root:${path}${fileName}:/createUploadSession`);`

Found here: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/1.3.0/src/tasks/OneDriveLargeFileUploadTask.ts#L100

Instead, we should be allowed to provide an options driveId, which then make the endpoint like this:

`/drives/${driveId}/root:${path}${fileName}:/createUploadSession`

And the endpoint to retrieve items from the root folder of a SharePoint drive would look something like this:

`/drives/${driveId}/root/children`

It would be great if this SDK supported SharePoint (and OneDrive for Business). Thanks for all your hard work! 👍

**Comment by muthurathinam** [comment]
@DavidCannon Thanks for notifying, Will work on this.

**Comment by muthurathinam** [comment]
@jplevene yes we have 4MB limitation for emails. Also we have plan to support emails larger than 4MB and  I cannot give you the ETA as of now, this is going to take some time.

**Comment by songpr** [comment]
@muthurathinam could you please allow us to pass option "@microsoft.graph.conflictBehavior": "replace" as well, since I want to replace it rather than rename

**Comment by muthurathinam** [comment]
@songpr Thank you for the ask. Will look into this.

**Comment by xkLander** [comment]
Hi, just want to remind the issue of 4MB+ files, we chose microsoft for storing, but our use case requires to uplaod files greater than 4mb, which complicates things, may I know the ETA now?.
Thanks

**Comment by Pjata** [comment]
Any update on this issue? We would like to use OneDrive as our document storage and this would greatly affect our decision.

**Comment by muthurathinam** [comment]
@Pjata  Will fix this in next release which is scheduled to be released before end of April.

**Comment by muthurathinam** [comment]
@DavidCannon @jplevene @songpr @Pjata Your ask is done in this [preview release](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.7.0-Preview.3). Please try and let me know. Refer [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md#uploading-with-custom-options) guide.

**Comment by jplevene** [comment]
Slight "error" I'm affraid.  On the version site it says to load the script use:
`<script src="https://secure.aadcdn.microsoftonline-p.com/lib/<version>/js/msal.min.js"></script>`
Changing version to anything above 0.2.4 doesn't work.

**Comment by jplevene** [comment]
> @DavidCannon @jplevene @songpr @Pjata Your ask is done in this [preview release](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.7.0-Preview.3). Please try and let me know your feedback. Refer [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md#uploading-with-custom-options) guide.

Slight "error" I'm affraid. On the version site it says to load the script use:
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/<version>/js/msal.min.js"></script>
Changing version to anything above 0.2.4 doesn't work.

**Comment by muthurathinam** [comment]
@jplevene The package depends on the particular version. you can refer msal version number under devDependencies in package.json. Are your application depends on some other version of msal ?

**Comment by muthurathinam** [comment]
Fixed in [1.7.0](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/1.7.0) release.

**Comment by DharmendraNaberly** [comment]
How to upload 5 files of 1MB each, as attachment in Outlook.
