### ISSUE TITLE
Need a way to search through all the sharepoint site

### ISSUE THREAD

**Issue by Anandks1993** [microsoftgraph/msgraph-sdk-javascript#1128]
We are building a teams app with sharepoint site and we have a feature to search globally. Is there any existing Graph api to achieve this functionality?

**Example:** Let's say we have 2 lists and 2 document libraries, if we search for `support` and if any of the list/document libraries have `support` in any of the columns, we should get those data.

**Comment by nikithauc** [comment]
@Anandks1993  this would be a good question for the [Microsoft Q & A](https://learn.microsoft.com/en-us/answers/index.html) and StackOverFlow. You would find more information on those platform. This space is targeted for Graph JS library issues.
