### ISSUE TITLE
avoid polyfill fetch and promise

### ISSUE THREAD

**Issue by sibelius** [microsoftgraph/msgraph-sdk-javascript#113]
Polyfills should be in user land

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/GraphRequest.ts#L2

can we remove those and let the user polyfill them?

**Comment by muthurathinam** [comment]
@sibelius 
Is this suggestion is for the browser environments(polyfills will add more weight to the js files) ? or is this something more specific about a certain advantage ?

**Comment by JSteunou** [comment]
I second @sibelius 

libraries should document requirements, but let users add polyfills if they need it, not force it.

**Comment by JSteunou** [comment]
I think that's a good choice that satisfy everyone. I also noticed `"main": "lib/src/index.js"` in the package.json, so using a builder like webpack should include only what's necessary.

:+1:

**Comment by JSteunou** [comment]
Buuuuuuut it does not work because of https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/lib/src/GraphRequest.js#L3

So I'm in favour of #122 because usually, webpack users do know what they do, and know when and how include polyfills.

I prefer when the build with polyfills is the exception rather than the build without.

**Comment by sibelius** [comment]
You can throw an error if polyfill was not included

**Comment by muthurathinam** [comment]
By with and without polyfills I meant these two files [#1](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/lib/graph-js-sdk-web.js) and [#2](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/lib/graph-js-sdk-core.js).

@JSteunou This particular change will be a breaking change. So some good, supporting explanation and reference to some legitimate good practices document would be nice to take better decision.

**Comment by JSteunou** [comment]
@muthurathinam I could use those files, if I was using `<script>` directly. But I'm building a complex app and using webpack as a builder. Builders rely on the `main` entry in the package.json by default. I could work around that by importing the *file* without the polyfills, but I would lose possible tree shaking, nice developer help and link thanks to .ts, etc.

That's a workaround, but that's not a nice workaround. Like I said, I prefer when the without polyfill is the standard, and the with polyfill is the exception, rather the opposite. And I think it's the way JavaScript works nowadays, so please jump on board :)

**Comment by muthurathinam** [comment]
@JSteunou Thank you for the explanation. I cannot take this up as of now. If you got time to get it done first, raise a pull request, am happy to review.

**Comment by JSteunou** [comment]
I think the PR you need is #122 from @sibelius

**Comment by muthurathinam** [comment]
I have already requested changes in that pull request. Please make those changes.

**Comment by muthurathinam** [comment]
Released a preview with the fix : https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1

**Comment by muthurathinam** [comment]
Stable release is published: https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0
