### ISSUE TITLE
enable authProvider to accept a promise

### ISSUE THREAD

**Issue by sibelius** [microsoftgraph/msgraph-sdk-javascript#114]
this would make things easy to get new tokens

instead of using callback style programming

**Comment by muthurathinam** [comment]
@sibelius Thank you for your suggestion.
How this eases the way of getting new tokens, wouldn't it just be an another way ?
Can you please provide code sample of how this implementation would look like ?

**Comment by muthurathinam** [comment]
@sibelius 
This would introduce a breaking change also we have a plan to provide the integration of auth library to the SDK this will ease the way of getting auth token.
Till then you could do a workaround by handling your promise settlement in the authProvider function and then calling the callback.

**Comment by sibelius** [comment]
It makes sense, maybe adding this to the docs should help newcomers 

Tks
