### ISSUE TITLE
How to get the mail body beyond 255 characters ?

### ISSUE THREAD

**Issue by suresh1271** [microsoftgraph/msgraph-sdk-javascript#117]
Hello All, I am retrieving mails through the following code. But I am getting 255 characters only instead the whole body. Is there any way to remove this limit. Please let me know if there is any way.

const api =client
			.api('/me/mailfolders/inbox/messages')     
			.top(10)
			.select('subject,from,receivedDateTime,isRead,bodyPreview')
			.orderby('receivedDateTime DESC')
			
			.get((err, res) => {
			if (err) 
			{
					console.log('getMessages returned an error: '+err.message);
			} 
			else 
			{
					console.log('Mails are retrieving...');

					res.value.forEach(function(message) 
					{
					  console.log(message.bodyPreview);

					});
			}

	});

**Comment by muthurathinam** [comment]
Post these kinds of questions in the Stackoverflow in future. In your request you are requesting for preview of the mail body which is limited. Try removing and `bodyPreview` from the select query.

**Comment by suresh1271** [comment]
@muthurathinam sorry for late reply... How can I print mail body if I remove bodyPreview. Actually the mail body is limited to 255 charcters in this query. I dont how to see the full body which is more that 255 characters. Please help me out.

**Comment by muthurathinam** [comment]
@suresh1271  Please this post your question to StackOverflow with the microsoft-graph and microsoft-graph-sdks tags. After you've posted your question on StackOverflow, please provide a link here back to your StackOverflow post. That way, the question will be found by more people.

**Comment by suresh1271** [comment]
@muthurathinam please find the question in stackoverflow https://stackoverflow.com/questions/52531146/how-to-get-the-mail-body-beyond-255-characters

**Comment by muthurathinam** [comment]
Answered and accepted in Stackoverflow.
