### ISSUE TITLE
file preview get bad request response

### ISSUE THREAD

**Issue by jasontianxie** [microsoftgraph/msgraph-sdk-javascript#119]
hi,
when i send a request to get a preview of a file ,it will get a bad request 

1、Request URL:https://graph.microsoft.com/v1.0/me/drive/items/....!180/preview

2、Response Headers:
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id
Cache-Control:private
client-request-id:56.....bfc7c19
Content-Type:application/json
Date:Wed, 26 Sep 2018 09:21:37 GMT
Duration:587.4917
request-id:56....-4a63ebfc7c19
Strict-Transport-Security:max-age=31536000
Transfer-Encoding:chunked
x-ms-ags-diagnostic:{"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceC","Ring":"5","ScaleUnit":"002","Host":"AGSFE_IN_24","ADSiteName":"WEU"}}

3、Request Headers：
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
Authorization:Bearer ....
Cache-Control:no-cache
Connection:keep-alive
Content-Length:2
content-type:application/json
Host:graph.microsoft.com
Origin:https://online.ja....oo.com
Pragma:no-cache
Referer:https://online.jaso...coo.com/_/4.9...../index.html
SdkVersion:graph-js-1.2.0
User-Agent:Mozil.....7.36

4、error response:
{
  "error": {
    "code": "invalidRequest",
    "message": "API not found",
    "innerError": {
      "request-id": "5688f6....c7c19",
      "date": "2018-09-26T09:21:38"
    }
  }
}

**Comment by muthurathinam** [comment]
@jasontianxie Can you provide the usage document for the api call that you are making ?

**Comment by jasontianxie** [comment]
@muthurathinam 
i got the usage from here:https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online

i used like this: this.onedrive.api('/me/drive/items/' + fileId + '/preview').post({}).then....

**Comment by muthurathinam** [comment]
@jasontianxie Is this reproducible ? Actually its working fine for me.

Give me some details to learn more about your issue:
1. Repro steps
2. Your request body
3. Are you getting the same response in [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) ?

**Comment by jasontianxie** [comment]
@muthurathinam 
request body is an empty object{} ,from https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online ,every filed is optional

and in Graph Explorer still get the same problem，here is a screen shot：https://view.axel.org/item/96e21ac48201dd00

**Comment by muthurathinam** [comment]
@ificator  Is there any recent changes to this API ?

**Comment by ificator** [comment]
I believe this is a documentation issue - the `preview` API is currently only available for OneDrive Business. If you try to use it against a OneDrive Consumer account it'll fail like this.

We'll look into updating the documentation so that it's more clear.

**Comment by jasontianxie** [comment]
@muthurathinam @ificator ,thanks
