### ISSUE TITLE
How to remove headers when using client?

### ISSUE THREAD

**Issue by JRJvV** [microsoftgraph/msgraph-sdk-javascript#1192]
Is it possible to remove request headers from the Client?

When creating requests the Accept-Language header is automatically added which is causing some issues on certain MS Graph requests.
If any advise or guidance can be provided

![image_2023-02-27_154016271](https://user-images.githubusercontent.com/22495325/221578640-430de457-eba2-4621-82f2-c285621c3f79.png)

**Comment by sebastienlevert** [comment]
Can you share examples of endpoints that are failing because of this header? I'm unaware that we are adding this header in the JS SDK (Or any other SDK AFAIK)

**Comment by ddyett** [comment]
closing a stale issue.
