### ISSUE TITLE
Implement RedirectHandler

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-javascript#1199]
https://github.com/microsoftgraph/msgraph-sdk-design/blob/master/middleware/RedirectHandler.md

**Comment by baywet** [comment]
@sebastienlevert we already have that https://github.com/microsoft/kiota-typescript/blob/main/packages/http/fetch/src/middlewares/redirectHandler.ts

**Comment by sebastienlevert** [comment]
So we moved the handler from core to kiota. Anything Graph-specific we should be aware of the generic version is enough?

**Comment by baywet** [comment]
Correct.
No the only ones that are graph specific are:
- telemetry
- me mapping
- authentication
This is why they live in graph core to the exception of authentication which is a design change

**Comment by sebastienlevert** [comment]
Closing as duplicate and already implemented in kiota
