### ISSUE TITLE
Is it possible to go with Promise / async await form...

### ISSUE THREAD

**Issue by JSteunou** [microsoftgraph/msgraph-sdk-javascript#121]
...instead of old callback (err, res) form?

I found it weird that you want Promise but does not leverage it on API level. Would be so much more comfortable to be able to use async / await in 2018 :)

**Comment by muthurathinam** [comment]
@JSteunou 
We do have support for both callback and promise for API actions. Please refer the [calling pattern](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/README.md#calling-pattern) in readme

**Comment by JSteunou** [comment]
My bad I did not see it :pray:

**Comment by jlippold** [comment]
Where is CallingPattern.md? I've search git history and can't find it anywhere

**Comment by muthurathinam** [comment]
Hi @JSteunou , Sorry that you have encountered this.
Here is the [link](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a87d98097b712a619ede2a2f7a6c26e8c2edd4bf/README.md#calling-pattern), Also I have updated the above broken link.
