### ISSUE TITLE
Accept-Language: * and owners@odata.bind together, causes 500 Internal server error

### ISSUE THREAD

**Issue by drdkmkkr** [microsoftgraph/msgraph-sdk-javascript#1225]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [ ] Are you reporting to the correct repository?
> Unsure where to report the issue, as this seems to be an API issue, rather than an issue with this library.
-   [x] Did you perform a cursory search?
> Could possibly relate to: https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/1192

## Description

I'm getting an error from the API when calling the `POST /v1.0/groups` endpoint with `owners@odata.bind` defined in the body, but only when the `Accept-Language` header has an value of `*`.

Node.js internal `fetch` API seems to add the `Accept-Language: *` header as default. But overriding the header seems to work.

Removing `owners@odata.bind` from the body will also fix the issue.

## Steps to Reproduce

1. Create the POST request  with `owners@odata.bind` defined
```js
await client.api("/groups")
        .post({
          ...
          "owners@odata.bind": [
              `https://graph.microsoft.com/v1.0/servicePrincipals/${SERVICE_PRINCIPAL_ID}`
          ]
});
```
2. This will return an error like:
```json
{
    "error": {
        "code": "Service_InternalServerError",
        "message": "Encountered an internal server error.",
        "innerError": {
            "date": "2023-03-27T08:23:54",
            "request-id": "256820de-5cdd-4279-afc4-40817788794c",
            "client-request-id": "...."
        }
    }
}
```

3. Add an empty `Accept-Language` header, or something else than `*`
```js
await client.api("/groups")
        .header('Accept-Language', '') // This fixes an issue where the API returns 500.
        .post({
          ...
          "owners@odata.bind": [
              `https://graph.microsoft.com/v1.0/servicePrincipals/${SERVICE_PRINCIPAL_ID}`
          ]
});
```
4. Now it works.

### Alternative

The issue can also be reproduced in Postman.

**Comment by sebastienlevert** [comment]
Thank you for reporting this issue! 

This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags, that way it will get routed to the appropriate team for them to triage.

Please let us know if this helps!
