### ISSUE TITLE
How i can upload files to my own Microsoft one drive from my website 

### ISSUE THREAD

**Issue by usamamashkoor** [microsoftgraph/msgraph-sdk-javascript#123]
Hi i have a website and on the website i have my employees and i want my employees to upload their documents to my Microsoft one drive directly without any login.

is their a way i can do this because i want my users to feel like they are just uploading a file without any Microsoft login but in the back end i want the files to be uploaded to my Microsoft One drive is their a way i can achieve this using JavaScript or Node.js ...?

I have search the google but in the stack over flow i can only find the examples which require user login.

as you can see in this example in the client declaration it asks for Auth Token but it is my One drive so i dont want to ask for login i want my employees to upload their files directly to my OneDrive  

[Large Upload](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md)

any help would be great.

Thanks & Regards

**Comment by muthurathinam** [comment]
@usamamashkoor 

>Before your app can make requests to OneDrive, it needs a user to authenticate and authorize the application to have access to their data.

https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/authentication?view=odsp-graph-online
Every call that is been made to the OneDrive needs to be authenticated, So as this upload.

**Comment by muthurathinam** [comment]
Closing as no response

**Comment by bimesh** [comment]
Can someone confirm if uploading to a shared folder requires a web-based authentication flow?
