### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by muthurathinam** [microsoftgraph/msgraph-sdk-javascript#124]
Moving [this](https://github.com/microsoftgraph/msgraph-typescript-typings/issues/26) issue from [msgraph-typescirpt-typings](https://github.com/microsoftgraph/msgraph-typescript-typings)

Missing types in @microsoft/microsoft-graph-client's 1.3.0 release:

node_modules/@microsoft/microsoft-graph-client/lib/src/common.d.ts(41,39): error TS2304: Cannot find name 'RequestInit'.
node_modules/@microsoft/microsoft-graph-client/lib/src/content/BatchRequestContent.d.ts(11,14): error TS2304: Cannot find name 'Request'.
node_modules/@microsoft/microsoft-graph-client/lib/src/content/BatchRequestContent.d.ts(21,38): error TS2304: Cannot find name 'RequestInit'.
node_modules/@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent.d.ts(54,41): error TS2304: Cannot find name 'Response'.
node_modules/@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent.d.ts(59,33): error TS2304: Cannot find name 'Response'.
node_modules/@microsoft/microsoft-graph-client/lib/src/content/BatchResponseContent.d.ts(64,55): error TS2304: Cannot find name 'Response'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask.d.ts(42,28): error TS2304: Cannot find name 'File'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask.d.ts(93,44): error TS2304: Cannot find name 'Blob'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask.d.ts(107,42): error TS2304: Cannot find name 'Blob'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/LargeFileUploadTask.d.ts(107,49): error TS2304: Cannot find name 'File'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTask.d.ts(44,41): error TS2304: Cannot find name 'Blob'.
node_modules/@microsoft/microsoft-graph-client/lib/src/tasks/OneDriveLargeFileUploadTask.d.ts(44,57): error TS2304: Cannot find name 'File'.

cc: @casz

**Comment by muthurathinam** [comment]
@casz 
Help me with the following:
1. Is this something reproducible. If so please provide the repro steps.
2. What is the editor that you are using.
3. These are the typing which are available in the typescript's lib.dom.d.ts, have included this in you project

**Comment by sylvaingirardbe** [comment]
Ok, changing tsconfig.js to use `"lib": ["es6", "dom"],` did the trick.

**Comment by muthurathinam** [comment]
Closed as no response from the user cc: @casz

**Comment by midgethoen** [comment]
the readme says it can be user serverside. so I don't want to include "dom" in my tsconfig. isnt there a better solution for this?

**Comment by silentorb** [comment]
In a Node.js server project I ended up requiring this module instead of importing it to work around the type errors.

This module needs correct server typings.

**Comment by matthew-carey-kidsloop** [comment]
It is still an issue and the above solution does work, but it is not nice.

**Comment by dmitry-yudakov** [comment]
I managed to solve it using [@tsconfig/node16](https://www.npmjs.com/package/@tsconfig/node16), seemingly because of _skipLibCheck_ setting in it. 

```
"skipLibCheck": true
```
