### ISSUE TITLE
TelemetryHandler incompatible with OneDrive API CORS settings

### ISSUE THREAD

**Issue by dluc** [microsoftgraph/msgraph-sdk-javascript#1247]
TelemetryHandler adds a `client-request-id` header to outgoing requests, e.g.

```
client-request-id: b48eb1a9-4b0f-4b18-875a-cbdd171d3711
```

which is not allowed by graph.microsoft.com CORS headers settings, e.g. when working with OneDrive

e.g. Request 

`OPTIONS https://graph.microsoft.com/v1.0/me/drive/root:/MyFolder:/createUploadSession`

returns an error

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at https://api.onedrive.com/rup/...[truncated]... (Reason: 
header ‘client-request-id’ is not allowed according to header 
‘Access-Control-Allow-Headers’ from CORS preflight response).
```

Is this a bug or is there an option to turn off the extra headers?

The telemetry handler middleware doc says this is a mandatory middleware, so we're currently working around this problem creating a different client that doesn't include it, which defeats the purpose of the whole idea I think, i.e. you won't be able to collect usage data to improve the SDK.

**Comment by ddyett** [comment]
closing stale issues.
