### ISSUE TITLE
Unable to run using DeviceCodeCredential in TypeScript

### ISSUE THREAD

**Issue by mihaibirsan** [microsoftgraph/msgraph-sdk-javascript#1275]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

The following script has been put together based on the latest available documentation.

```ts
import "isomorphic-fetch";
import { DeviceCodeCredential } from '@azure/identity';
import { Client } from '@microsoft/microsoft-graph-client';
import { TokenCredentialAuthenticationProvider } from '@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials';

const clientId = '...REDACTED...';
const tenantId = 'common';
const scopes = ['User.Read'];

const credential = new DeviceCodeCredential({
    clientId,
    tenantId,
    userPromptCallback: (deviceCodeInfo) => {
        console.log(deviceCodeInfo);
    },
});

const authProvider = new TokenCredentialAuthenticationProvider(credential, {
    scopes
});

const client = Client.initWithMiddleware({
    debugLogging: true,
    authProvider
});

async function main() {
    let user = await client.api('/me').get();
    console.log(user);
}

main().catch((error) => {
    console.error('Error:', error);
});
```

Expected: log the `user` object.

**Console Errors:**

```
> npx ts-node index.ts
https://graph.microsoft.com/v1.0/me
{
  userCode: undefined,
  deviceCode: undefined,
  verificationUri: undefined,
  expiresIn: undefined,
  interval: undefined,
  message: undefined
}
Error: AuthenticationRequiredError: post_request_failed: Post request failed from the network, could be a 4xx/5xx or a network unavailability. Please check the exact error code for details.: invalid_grant
    at MsalDeviceCode.handleError (C:\Users\jm\Workspace\MSGraphPlayground\node_modules\@azure\identity\src\msal\utils.ts:214:12)
    at MsalDeviceCode.doGetToken (C:\Users\jm\Workspace\MSGraphPlayground\node_modules\@azure\identity\src\msal\nodeFlows\msalDeviceCode.ts:49:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.withSpan (C:\Users\jm\Workspace\MSGraphPlayground\node_modules\@azure\core-tracing\src\tracingClient.ts:70:22) {
  statusCode: -1,
  code: 'AuthenticationRequiredError',
  requestId: null,
  date: 2023-05-08T12:53:34.096Z,
  body: 'AuthenticationRequiredError: post_request_failed: Post request failed from the network, could be a 4xx/5xx or a network unavailability. Please check the exact error code for details.: invalid_grant',        
  headers: undefined
}
```

## Steps to Reproduce

1. Save above code as `index.ts`
2. Run using `npx ts-node index.ts`

**Expected behavior:** Should ask to login using https://microsoft.com/devicelogin or a generated URL.

**Actual behavior:** See "Console errors" above.

## Additional Context

Documentation used:
- [Create a Microsoft Graph client - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/sdks/create-client?tabs=Javascript)
- [Make API calls using the Microsoft Graph SDKs - Microsoft Graph | Microsoft Learn](https://learn.microsoft.com/en-us/graph/sdks/create-requests?tabs=TypeScript)

## Usage Information

SDK Version
```json
{
  "dependencies": {
    "@azure/identity": "^3.1.4",
    "@microsoft/microsoft-graph-client": "^3.0.5"
  }
}
```

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v18.16.0

**Comment by mihaibirsan** [comment]
Thank you for testing!

That's been enabled in the app configuration in Entra.
![Screenshot_20230508-183203](https://user-images.githubusercontent.com/294335/236866184-be4e3411-acab-44dc-b1ca-b9370f0c5676.png)

What node version are you using? After reading through the most recent issues, I'm suspecting the node version.

**Comment by sebastienlevert** [comment]
I'm actually using Node v19... I thought the same but then I was very confused. This seems to be at the auth level before it even hits any of our code in the JS SDK. Check with this project and see if it reproes?

https://github.com/sebastienlevert/msgraph-typescript-node/tree/1275

**Comment by mihaibirsan** [comment]
I was able to confirm it works as expected with the project you've suggested. I'm currently inspecting any obvious differences in configuration.

**Comment by mihaibirsan** [comment]
Ruled out TypeScript version and everything else matches my environment. It's most likely the application configuration. I noticed your project is configured to authenticate other than personal accounts. I'd like to use my scripts to access my own account, so I've configured it for personal accounts only.

Here is my configuration:
![Screenshot of Personal scripts Authentication configuration](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/294335/0d96b70d-e5e8-4279-b0a4-3ae4be520d60)

At this point this might be more suitable for the `@azure/identity` maintainers, correct?

**Comment by mihaibirsan** [comment]
Confirmed this is an auth issue using the Postman collection found here:
- [OAuth 2.0 device authorization grant - Microsoft Entra | Microsoft Learn](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code); link to highlight: [¶](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#:~:text=Try%20executing%20this%20request%20and%20more%20in%20Postman)

Thanks for you help @sebastienlevert!
