### ISSUE TITLE
getStream without callback

### ISSUE THREAD

**Issue by sylvaingirardbe** [microsoftgraph/msgraph-sdk-javascript#128]
Hi,

I'm unable to call the `getStream` function without specifying a callback param in TS and just have it return a promise.

The signature is `getStream(callback: GraphRequestCallback): Promise<any>;`. Has this perhaps been an oversight?

**Comment by muthurathinam** [comment]
@sylvaingirardbe Thanks for reporting. You should be required to pass in a callback or just have it to return a promise. Will fix this in our next update.

**Comment by muthurathinam** [comment]
Fixed in v1.5.2
