### ISSUE TITLE
FindMeetingTimes: Error 

### ISSUE THREAD

**Issue by bsdaniel** [microsoftgraph/msgraph-sdk-javascript#130]
Hi, I am utilizing the findMeetingTimes API in microsoft graph. As expected when utilizing the API the response returns in the terminal. However, one error that I have is that once the API is called the meeting time slot returns [Object] instead of the time specified in the request body, the attendeeAvailablity returns [Array] instead of the emails specified in the request body as well. Any suggestions or fixes would be a major help. I am using nodejs to accomplish this. Thanks.

**Comment by MIchaelMainer** [comment]
This doesn't appear to be an issue with the client library. Please post questions like this to StackOverflow and use the microsoft-graph tag. You'll get more help that way. Provide a link back to your question in this issue. Make sure you provide both the request and response - that will help with an answer.

The meeting time slot in the response is supposed to return an object. The object contains the suggested meeting time for that single suggestion. Are you saying that the time specified in the request body within the timeConstrant\timeSlots doesn't match what is returned in the response?

**Comment by bsdaniel** [comment]
![screenshot 95](https://user-images.githubusercontent.com/35406006/50667617-0cad9600-0f6f-11e9-86b5-61ebf5043666.png)
See image above. When the same URL is called in the Graph Explorer it displays the details of the meeting time slot etc. such as datetime, timezone. Also it lists the attendees in the Graph Explorer. I have posted my question in stackoverflow. Link: https://stackoverflow.com/questions/54011892/meetingtimesuggestionresult-doesnt-return-all-expected-results

**Comment by MIchaelMainer** [comment]
This is not a client issue. This has to do with how Node outputs to console. There is a link in the StackOverflow answer for more info.

**Comment by bsdaniel** [comment]
MAJOR HELP! Thanks Michael.
