### ISSUE TITLE
Fail to add mail.send scope

### ISSUE THREAD

**Issue by MelodyWuIsLearning** [microsoftgraph/msgraph-sdk-javascript#1315]
Here is my code
```
const options: AuthCodeMSALBrowserAuthenticationProviderOptions = {
    account: account, // the AccountInfo instance to acquire the token for.
    interactionType: InteractionType.Popup, // msal-browser InteractionType
    scopes: ["user.read", "mail.send"], // example of the scopes to be passed
  };

  // Pass the PublicClientApplication instance from step 2 to create AuthCodeMSALBrowserAuthenticationProvider instance
  const authProvider = new AuthCodeMSALBrowserAuthenticationProvider(
    msalInstance,
    options
  );

  // Initialize the Graph client
  const graphClient = Client.initWithMiddleware({
    authProvider,
  });

  return graphClient;
```

It will always fail when I add "mail.send" scope, but it works when I remove it.
![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/129166378/d1c9e037-53fb-4c58-a3ce-eb5403e942fd)

And I already add "mail.send" scope in azure portal
![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/129166378/d3e0d4d7-76eb-4aa1-8081-0e6071149996)

**Comment by andrueastman** [comment]
Thanks for raising this @MelodyWuIsLearning 

It is possible that the tenant admin has changed the user consent settings for your organization to prevent apps from accessing the data without admin approval. Any chance you can confirm with the tenant admin on this?

The documentation at the link below sheds some light on how these settings can be changed. 
https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?pivots=portal#configure-risk-based-step-up-consent
