### ISSUE TITLE
How to measure MS Graph JS Client's latency in production environment 

### ISSUE THREAD

**Issue by JimmyLS** [microsoftgraph/msgraph-sdk-javascript#1317]
# Feature Request

## Is your feature request related to a problem? 

Currently while we didn't see a way in MS Graph JS client to get the latency when sending out request. We could not know when the request is sent out, when the response is received and how long it costs.   

One of my customer was using below way now to measure the latency. He found occasionally it costs over 60s in getting a response. 

```
    // performance the graph request
    const startTime = Date.now();
    const graphResRaw = await graphReq.responseType(ResponseType.RAW).get();
    const endTime = Date.now();
    logger.infom(`apiListUsersDelta request id: ${graphResRaw.headers.get('request-id')}, cost: ${endTime - startTime}ms`);
```

We don't know if the delay is caused by MS Graph Client or other component. 

## Describe the solution you'd like

We should give customer an option to enable verbose/informational logging in MS Graph Client which will records the detailed timestamp sending out each request, and getting response. 

## Describe alternatives you've considered

We are suggesting customer to send out the request through a outbound proxy which can help measure the latency. 

## Additional context

N/A

**Comment by sebastienlevert** [comment]
Thanks for the request! You'll be happy to hear that we are working on our V4 implementation that will be fully instrumented with OpenTelemetry (https://opentelemetry.io/docs/instrumentation/js/) where you will be able to get specific numbers for this use case. (https://github.com/microsoft/kiota-typescript/pull/427) This will happen through our new client library Kiota that will replace some internal libraries used by the Graph SDK. We are doing good progress on v4 and should have it available before the end of the year and don't expect new features to be added to v3 from now on. Hopefully this will help with your scenario! Closing for now, but definitely re-open if you want to re-engage on this topic! Thanks!

**Comment by JimmyLS** [comment]
Thanks a lot! That's indeed what we want
