### ISSUE TITLE
Microsoft Sentiment Analysis API 

### ISSUE THREAD

**Issue by md0501** [microsoftgraph/msgraph-sdk-javascript#1328]
Hi, 

I recently setup a single page application using  this documentation. It allows a user to sign and view their emails. How could I modify the code in vscode to send the body of the emails to a microsoft sentiment analysis api and return the score? I would like the results/score to be visible in the single page application.

https://learn.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-javascript-spa

**Comment by sebastienlevert** [comment]
You will need to use the sentiment analysis service from the Azure AI Service : https://learn.microsoft.com/en-us/azure/ai-services/language-service/sentiment-opinion-mining/quickstart?tabs=windows&pivots=programming-language-javascript. I'll close this issue as it's not related to the Graph SDK. Thanks!
