### ISSUE TITLE
/me/sendMail "flag" for follow up not setting dueDateTime or startDateTime in Outlook. The email is showing as "No Date"

### ISSUE THREAD

**Issue by croeber** [microsoftgraph/msgraph-sdk-javascript#1342]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I am trying to use the /me/sendMail api POST endpoint using the @microsoft/microsoft-graph-client library to send emails that are flagged for follow up, but the emails are coming into my outlook as having "No Date" instead of having the dueDateTime that was passed into the request.

Here is my api request from the Chrome Network tab. 

```
Client.api('/me/sendMail').post({
   "message": {
      "subject": "SOMESUBJECT",
      "body": { "contentType": "HTML", "content": "SOMEBODY" },
      "toRecipients": [         {
            "emailAddress": { "address": "example@domain.com" } }
      ],
      "isReadReceiptRequested": false,
      "isDeliveryReceiptRequested": false,
      "flag": {
         "completedDateTime": null,
         "dueDateTime": { "dateTime": "2023-07-07T23:59:59.0000000", "timeZone": "America/New_York" },
         "flagStatus": "flagged",
         "startDateTime": { "dateTime": "2023-06-28T2023-06-28T11:37:49.0000000", "timeZone": "America/New_York" }
      }
   },
   "saveToSentItems": "false"
})
```

**Console Errors:** [Is there any console error]

None

**Screenshots:** [If applicable, add screenshots to help explain your problem]

![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/15783987/55614254-5ea7-442c-bde4-b291f2195761)

## Steps to Reproduce

1. Execute the /me/sendMail POST api endpoint that specifies the startDateTime and dueDateTime
2. Open your Outlook and find the email you just sent in your Tasks
3. Notice that the email is showing as having "No Date" 

**Expected behavior:** [What you expected to happen]

I expect that when the email comes to my outlook that it is flagged with a due date that is in the future

**Actual behavior:** [What actually happened]

The email came to my outlook with no due date and shows in Outlook Tasks as "No Date"

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

No Error

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

Chrome

> Version - [The version of the browser you are using]

114.0.5735.134

**Comment by sebastienlevert** [comment]
My understanding is that this is only possible on an existing message and not when sending the message. 

We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags, that way it will get routed to the appropriate team for them to triage.

Please let us know if this helps!

**Comment by ddyett** [comment]
closing as responded to.

**Comment by croeber** [comment]
It seems to me that this should just work. Unless you are going to return a unique identifier so that it can be flagged after the email is sent. But it seems like this should just work the first time. 

I posted this question to the Microsoft Q&A here

[https://learn.microsoft.com/en-us/answers/questions/1336717/me-sendmail-flag-for-follow-up-not-setting-duedate](https://learn.microsoft.com/en-us/answers/questions/1336717/me-sendmail-flag-for-follow-up-not-setting-duedate)

**Comment by cythrault** [comment]
The documentation on the API does suggest that it should work on new messages. I have the exact same issue using the current Graph PowerShell module.

**Comment by ansalls** [comment]
Still seems to be an issue.
