### ISSUE TITLE
Initializing Video call from bot with ability to share screen

### ISSUE THREAD

**Issue by IAM5K** [microsoftgraph/msgraph-sdk-javascript#1384]
# Background
I am developing a bot that will have the ability to initiate a call between 2 people. In the current ability of app, it is able to initiate calls between User A and User B. When the call is initialization is done the bot also joins the call.

# Problem
After both people join the call, out of the participants list there is no presenter there. Both User A and User B are unable to present the screen or turn their video on.

## Code/Function
Code implementation as per create service based VoIP calls [documentation](https://learn.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=javascript#tabpanel_1_javascript)
``` typescript
    async makeCall(data) {
        let targetMembers: callTarget[] = [
            {
                '@odata.type': '#microsoft.graph.invitationParticipantInfo',
                identity: {
                    '@odata.type': '#microsoft.graph.identitySet',
                    user: {
                        '@odata.type': '#microsoft.graph.identity',
                        displayName: data.userA.name,
                        id: data.userA.aadObjectId,
                        tenantId: data.userA.tenantId
                    }
                }
            },
            {
                '@odata.type': '#microsoft.graph.invitationParticipantInfo',
                identity: {
                    '@odata.type': '#microsoft.graph.identitySet',
                    user: {
                        '@odata.type': '#microsoft.graph.identity',
                        displayName: data.userB.name,
                        id: data.userB.aadObjectId,
                        tenantId: data.userB.tenantId
                    }
                }
            }

        ]

        const call = {
            '@odata.type': '#microsoft.graph.call',
            direction: 'outgoing',
            subject: data.topic,
            callbackUri: config.callBackUri + "/call-callback",
            source: {
                '@odata.type': '#microsoft.graph.participantInfo',
                identity: {
                    '@odata.type': '#microsoft.graph.identitySet',
                    application: {
                        '@odata.type': '#microsoft.graph.identity',
                        displayName: 'App for Teams',
                        id: 'xxxxxx-xxxx-xxxx-xxxx-botIdxxxxb23'
                    }
                }
            },
            targets: targetMembers,
            requestedModalities: ['audio', 'video', 'videoBasedScreenSharing'],
            mediaConfig: {
                '@odata.type': '#microsoft.graph.serviceHostedMediaConfig',
                removeFromDefaultAudioGroup: false
            },
            tenantId: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxtenentId'
        };

        try {
            const response = await this.graphClient.api('/communications/calls').post(call);
        } catch (error) {
            console.log(error);
        }
    }
```
Using the above method we are able to initialize the call successfully. Issues are with video and screen sharing.

# What we tried.
- Adding  ['audio', 'video', 'videoBasedScreenSharing'] in requested modalities and also in active modalities
- Adding user as co-organizer
- Additional function that takes id as a parameter and makes a patch for sharing content. As per the documentation given [here](https://learn.microsoft.com/en-us/graph/api/call-changescreensharingrole?view=graph-rest-1.0&tabs=javascript)
``` typescript
    async enableSharing(callId) {
        const changeScreenSharingRole = {
            role: 'sharer'
          };
          
        try {
            const response = await this.graphClient.api(`/communications/calls/${callId}/changeScreenSharingRole`).post(changeScreenSharingRole);
            console.log(response);

        } catch (error) {
            console.log(error); // Handle any errors that occur during the API call
        }
    }
```
In this case also I am getting error 500 with code 999

``` console
GraphError: Encountered exception during changing screen sharing role.
    at new GraphError (E:\CallngBot\Deployment\CallngBot\bot\node_modules\@microsoft\microsoft-graph-client\src\GraphError.ts:63:3)
    at Function.GraphErrorHandler.constructErrorFromResponse (E:\CallngBot\Deployment\CallngBot\bot\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:77:18)
    at Function.<anonymous> (E:\CallngBot\Deployment\CallngBot\bot\node_modules\@microsoft\microsoft-graph-client\src\GraphErrorHandler.ts:104:31)
    at step (E:\CallngBot\Deployment\CallngBot\bot\node_modules\tslib\tslib.js:193:27)
    at Object.next (E:\CallngBot\Deployment\CallngBot\bot\node_modules\tslib\tslib.js:174:57)
    at E:\CallngBot\Deployment\CallngBot\bot\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (E:\CallngBot\Deployment\CallngBot\bot\node_modules\tslib\tslib.js:163:16)
    at Function.GraphErrorHandler.getError (E:\CallngBot\Deployment\CallngBot\bot\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (E:\CallngBot\Deployment\CallngBot\bot\node_modules\@microsoft\microsoft-graph-client\src\GraphRequest.ts:391:55) {
  statusCode: 500,
  code: '9999',
  requestId: 'dee2344b-6341-439d-bd04-8b2a7dc1e795',
  date: 2023-07-31T21:39:01.000Z,
  body: '{"code":"9999","message":"Encountered exception during changing screen sharing role.","innerError":{"date":"2023-08-01T03:09:01","request-id":"dee2344b-6341-439d-bd04-8b2a7dc1e795","client-request-id":"7a5551fc-6fed-3d1e-5ddf-361c327dca5b"}}',
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      'transfer-encoding': [Array],
      'content-type': [Array],
      'content-encoding': [Array],
      vary: [Array],
      'strict-transport-security': [Array],
      'request-id': [Array],
      'client-request-id': [Array],
      'x-ms-ags-diagnostic': [Array],
      date: [Array],
      connection: [Array]
    }
  }
}
```

# Requirement / Questions
- How to create a service-based VoIP call if the documentation has some issues?
- How to enable screen sharing
- How can we make such a bot work cross-tenant? Do we have to make modifications in tenant id like instead of ID we have to keep it `common`? Here cross tenant means, If the app is developed in Organization A then when globally deployed Organization B should be able to use it.
- There are details missing in the documentation about additional parameters that need to pass in case additional enabling sharing and camera later. Please provide a detailed function if exists else suggest changes in the function provided above.

Thanks for your time and support in advance. Hope we can find a solution to this.

**Comment by sebastienlevert** [comment]
Thanks @IAM5K for logging this issue with us. As the SDK team, we do not own our docs and / or the service behind these APIs. I suggest that the best way to get this one resolved would be to head over to https://developer.microsoft.com/en-us/graph/support and either ask a question Microsoft Q&A or create a support ticket on Azure or Microsoft 365. I'm sorry I can't help further but I really think you'll be served by these other ways.

I'll be closing the issue for now but please feel free to re-open it it needed.

Thanks!

**Comment by IAM5K** [comment]
It would be great if you could resolve the other queries asked. Like why the video call and screen sharing not working.

**Comment by sebastienlevert** [comment]
I would love to, and that is why I shared the other feedback channels. The SDK is a "simple" wrapper on our APIs, but we don't own or have deep knowledge of every endpoint. The https://developer.microsoft.com/en-us/graph/support will be the best place to start. Thanks!
