### ISSUE TITLE
Convert with comments markup

### ISSUE THREAD

**Issue by MB0125987** [microsoftgraph/msgraph-sdk-javascript#1386]
I'd like to programmatically convert a doc or a docx file to pdf while keeping its comments just like what MS word does. Is there a way to do so via the graph API or by using any other solution/NPM package?
![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/141507272/cb41153e-672b-4f16-9714-1af6696082cc)

**Comment by sebastienlevert** [comment]
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=microsoft-graph-*) tags, that way it will get routed to the appropriate team for them to triage.

Please let us know if this helps!
