### ISSUE TITLE
createWithMiddleware method in HttpClientFactory is not public

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-javascript#140]
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/1ccd751dc6775b52f377b178fe3c59062b3217b1/src/HTTPClientFactory.ts#L45

In the comments it says it should be public.  Which is correct?

**Comment by muthurathinam** [comment]
@darrelmiller 
Actually, the access specifier for a member of a class defaults to public. So the createWithMiddleware is public.

Was adding public for more readability and missed with this method. Fix will be merged with the PR from [Linter_and_Prettier](https://github.com/microsoftgraph/msgraph-sdk-javascript/tree/Linter_and_Prettier) branch.

**Comment by muthurathinam** [comment]
Fixed in v1.5.2
