### ISSUE TITLE
Getting Resource not found error on create user

### ISSUE THREAD

**Issue by kenlthai** [microsoftgraph/msgraph-sdk-javascript#1404]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Calling create user API as per [documentation](https://learn.microsoft.com/en-us/graph/api/user-post-users?view=graph-rest-1.0&tabs=http) result in error. Not sure why it would be the case given the same API work fine last month.

**Console Errors:** 

{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource '' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2023-08-15T08:49:22",
            "request-id": "0eebcbcc-5249-48a8-acf6-1b2dbc75f4f4",
            "client-request-id": "dc20a426-cf48-d984-dc5e-d6f59bc880c0"
        }
    }
}

## Steps to Reproduce

Use the sample code provided on the documentation

**Expected behavior:**

New user is created on Azure AD

**Actual behavior:** 

Receive error "Resource '' does not exist or one of its queried reference-property objects are not present."

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - 0eebcbcc-5249-48a8-acf6-1b2dbc75f4f4

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK) v3.0.5 as well as the Graph Explorer

> Node Version - v18.16.1

**Comment by sebastienlevert** [comment]
Can you provide how you are using the SDK, the actual call that is being made and the configuration of the body of the payload? A repro project would be even better. Without these, we can't debug, even with the request-id. Thanks!

**Comment by kenlthai** [comment]
Thanks @sebastienlevert for your quick reply. Please find attached the sample code of how I'm using the SDK. 

Note: Get user work flawlessly, and create user used to work fine. It just decide to throw me the error this week with no code change from my end. 

[Archive.zip](https://github.com/microsoftgraph/msgraph-sdk-javascript/files/12354316/Archive.zip)

**Comment by kenlthai** [comment]
Figured out the issue. There was a small typo in my object. I accidentally send "accountEnable" but API required "accountEnabled". Guess it was tunnel vision problem after looking at it for too long.

Having said that, the error message return provide 0 hints toward solving the issue. Would love that to provide just a little more insight into the problem.

**Comment by sebastienlevert** [comment]
Thanks for reporting back @kenlthai. We also provide types for our models (https://www.npmjs.com/package/@microsoft/microsoft-graph-types). Are you using them?

**Comment by kenlthai** [comment]
Hi @sebastienlevert ,

Unfortunately, the project where we utilised SDK was written in pure Node JS at the moment, so we are not using the types. When it is time to convert it to Typescript, we will look into the types lib you mention. Appreciate your help and quick response.

Cheers,
