### ISSUE TITLE
Version 3.0.6 breaks pagination

### ISSUE THREAD

**Issue by apnsngr** [microsoftgraph/msgraph-sdk-javascript#1426]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

The `PaginationIterator` no longer works correctly in version 3.0.6. Instead of paging through all the results it only returns the first page.

**Console Errors:** None

**Screenshots:** N/A

## Steps to Reproduce

1. Find or create a group in Azure AD that contains more than 100 members (also without any nested groups)
2. Use this library to fetch the group members with the pagination helper
3. Print out the length of the members

```javascript
const groupId = 'REPLACE_WITH_GROUP_ID';
const client = Client.initWithMiddleware({
  authProvider: new MsalClientCredentialsProvider(options),
});

const results = [];
const res = await client.api(`/groups/${groupId}/members`.get();
const pageIterator = new PageIterator(this.graph, res, (data: T) => {
  results.push(data);
  return true;
});
await pageIterator.iterate();
console.log(results.length);
```

**Expected behavior:** I expect the length of the group members to match the count shown in Azure AD.

**Actual behavior:** The length of the group members is only the default page size, 100.

## Additional Context

It is inconvenient that 3.0.6 is not tagged and does not have release notes in Github.

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - 3.0.6

-   [x] Node (Check, if using Node version of SDK)

> Node Version - 18.17.1

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by sebastienlevert** [comment]
Hello @apnsngr. We are very sorry for the inconvenience. We didn't mean to ship this release and we are currently working on forward rolling a patch that will fix this issue and get us to speed with some other improvements that we made in the last 8 months.

I 100% agree with you around the broken communication. We should absolutely tag and create release notes on every release and this is what we've done in the past (even though, I believe our release notes were a little bit light...). As soon as 3.0.7 is ready for showtime, we'll do it the right way and you'll see the notes and the tag + the package will be available on npm.

Thanks!

**Comment by stephannielsen** [comment]
As this is now known since 2 weeks, how about pulling the buggy 3.0.6 version from npm so that users don't update to it anymore?
I am all for rolling forward, but that should happen soon and if not possible, at least pull the broken version so that not more users run into the issues.

**Comment by sebastienlevert** [comment]
Thanks for the nudge. I'll need to check where we are with all of this as I believe the work was done. I'll check on why the npm package was not published. Thanks!

**Comment by halljus** [comment]
> As soon as 3.0.7 is ready for showtime, we'll do it the right way and you'll see the notes and the tag + the package will be available on npm.

~3.0.7 is now on npm, but no release notes or tag. 😞~ That said, pagination appears to work again.

**Comment by sebastienlevert** [comment]
It's all there now! It just needed some approval to push the release notes and tags! Thanks! I'll be closing this issue for now! Thanks!
