### ISSUE TITLE
HttpsProxy does not work correctly because fetch seems runs unexpectedly in node backend environment

### ISSUE THREAD

**Issue by xzf0587** [microsoftgraph/msgraph-sdk-javascript#1437]
# Bug Report
I tried to put a https proxy (for example fiddler) for graph client in node environment.
But I found the request seems not sent to the proxy, as I cannot observe the request in fiddler.
I tried to **import "isomorphic-fetch";** as the guide shows, but it still failed.

If I customize the graph client by specifying the http message handler to **use fetch from "isomorphic-fetch"**. 
It works as I could observe the request in fiddler.

Here is the code. Using node 18
```
import { Client, Context, Middleware } from "@microsoft/microsoft-graph-client";
import { HttpsProxyAgent } from "hpagent";
import fetch from "isomorphic-fetch";

class HTTPMessageHandler implements Middleware {
	/**
	 * @public
	 * @async
	 * To execute the current middleware
	 * @param {Context} context - The request context object
	 * @returns A promise that resolves to nothing
	 */
	public async execute(context: Context): Promise<void> {
		context.response = await fetch(context.request, context.options);
	}
}

async function main() {
    try {
        const agent = new HttpsProxyAgent({
            proxy: 'http://127.0.0.1:8888', // Fiddler proxy address
            rejectUnauthorized: false,
          })

        const graphClient = Client.initWithMiddleware({middleware: new HTTPMessageHandler()});
        const api  = graphClient.api("/me")
        const result = await api.option("agent", agent).get();
        console.log(result);
    } catch (error: any) {
        console.log(error.message);
    }
}

main();
```

**Comment by sebastienlevert** [comment]
The best approach here would be to provide your own `ProxyMiddleware` that is injected in the regular middleware chain. It would become something like this (I built it as I was curious!).

```ts
import { Middleware, MiddlewareFactory, Context } from "@microsoft/microsoft-graph-client";
import { HttpsProxyAgent } from "hpagent";
import "isomorphic-fetch";

class ProxyMiddleware implements Middleware {
  private url: string;

  private nextMiddleware!: Middleware;

  public constructor(url: string) {
    this.url = url;
  }

  public async execute(context: Context): Promise<void> {
    if (context.options) {
      context.options.agent = new HttpsProxyAgent({
        proxy: this.url,
        rejectUnauthorized: false,
      });
    }

    return await this.nextMiddleware.execute(context);
  }

  public setNext(next: Middleware): void {
    this.nextMiddleware = next;
  }
}

async function main() {
  try {
    const middleware = MiddlewareFactory.getDefaultMiddlewareChain(authProvider);
    middleware.splice(-1, 0, new ProxyMiddleware("http://127.0.0.1:8888"));

    const client = Client.initWithMiddleware({
      middleware: middleware,
    });
    
    const result = graphClient.api("/me").get();
    console.log(result);
  } catch (error: any) {
    console.log(error.message);
  }
}

main();
```

Let us know if that works for you!

**Comment by xzf0587** [comment]
@sebastienlevert 
Thanks for your reply. 
I tried the code provided but there is no traffic in the fiddler proxy. 
I found that the fetch in nodejs 18 does not support proxy yet. 
https://stackoverflow.com/questions/72306101/make-a-request-in-native-fetch-with-proxy-in-nodejs-18

**Comment by sebastienlevert** [comment]
It doesn't by default. But it does when passing in a middleware. The code I shared should work if you import isomorphic-fetch (updated the snippet). Please test and let us know!

**Comment by xzf0587** [comment]
I tried it and does not work.
Here is the code and dependency package version
```
import { UsernamePasswordCredential } from "@azure/identity";
import { Middleware, MiddlewareFactory, Context, Client } from "@microsoft/microsoft-graph-client";
import { TokenCredentialAuthenticationProvider } from "@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials";
import { HttpsProxyAgent } from "hpagent";
import "isomorphic-fetch";

const tenantId = "some tenantId";
const clientId = "some clientId";
const username = "username";
const password = "password";
const scopes = "https://graph.microsoft.com/.default";

class ProxyMiddleware implements Middleware {
  private url: string;

  private nextMiddleware!: Middleware;

  public constructor(url: string) {
    this.url = url;
  }

  public async execute(context: Context): Promise<void> {
    if (context.options) {
      context.options.agent = new HttpsProxyAgent({
        proxy: this.url,
        rejectUnauthorized: false,
      });
    }

    return await this.nextMiddleware.execute(context);
  }

  public setNext(next: Middleware): void {
    this.nextMiddleware = next;
  }
}

async function main() {
  try {
    const credential = new UsernamePasswordCredential(tenantId, clientId, username, password);
    const authProvider = new TokenCredentialAuthenticationProvider(credential, { scopes: [scopes] });

    const middleware = MiddlewareFactory.getDefaultMiddlewareChain(authProvider);
    middleware.splice(-1, 0, new ProxyMiddleware("http://127.0.0.1:8888"));

    const client = Client.initWithMiddleware({
      middleware: middleware,
    });
    
    const result = await client.api("/me").get();
    console.log(result);
  } catch (error: any) {
    console.log(error.message);
  }
}

main();
```

```
dependencies:
  '@azure/identity':
    specifier: ^3.3.0
    version: 3.3.0
  '@microsoft/microsoft-graph-client':
    specifier: ^3.0.6
    version: 3.0.6(@azure/identity@3.3.0)
  axios:
    specifier: ^1.5.0
    version: 1.5.0
  hpagent:
    specifier: ^1.2.0
    version: 1.2.0
  https-proxy-agent:
    specifier: ^6.2.1
    version: 6.2.1
  isomorphic-fetch:
    specifier: ^3.0.0
    version: 3.0.0
  node-fetch:
    specifier: ^2.7.0
    version: 2.7.0
  proxy-agent:
    specifier: ^6.3.1
    version: 6.3.1
  tunnel:
    specifier: ^0.0.6
    version: 0.0.6
````

**Comment by sebastienlevert** [comment]
Can you try with this app? https://github.com/sebastienlevert/msgraph-typescript-node/tree/test/1473

When running my app, I see the following in my console (I'm using the [m365proxy](aka.ms/m365/proxy) as the proxy to see that stuff is really going through. Please adjust in the `package.json` if you want to change the proxy you want to use and it's URL.

```bash
npm run start:proxy

> msgraph-typescript-node@1.0.0 start:proxy
> cross-env HTTP_PROXY=http://127.0.0.1:8000 HTTPS_PROXY=http://127.0.0.1:8000 npm-run-all --parallel proxy start


> msgraph-typescript-node@1.0.0 start
> npx ts-node src/index.ts


> msgraph-typescript-node@1.0.0 proxy
> m365proxy -a 429 -f 50

Mock responses for 0 url patterns loaded from /home/slevert/m365-developer-proxy/responses.json
Listening on 0.0.0.0:8000...
  WARNING: Configure your operating system to use this proxy's port and address
Press CTRL+C to stop the Microsoft 365 Developer Proxy

To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ~~~ to authenticate.
 request     GET https://graph.microsoft.com/v1.0/me
     api   ╭ Passed through
           ╰ GET https://graph.microsoft.com/v1.0/me
{
  '@odata.context': 'https://graph.microsoft.com/v1.0/$metadata#users/$entity',
  businessPhones: [ '514-555-0100' ],
  displayName: 'Sebastien Levert',
  givenName: 'Sebastien',
  jobTitle: 'Senior Program Manager',
  mail: 'admin@M365x55726300.OnMicrosoft.com',
  mobilePhone: '514-555-0101',
  officeLocation: 'MTL-0073',
  preferredLanguage: 'en-US',
  surname: 'Levert',
  userPrincipalName: 'admin@M365x55726300.onmicrosoft.com',
  id: '02b1868e-37e7-4c0e-a956-846dadaab298'
}
```

I'm seeing you are referencing axios and node-fetch. I'm wondering if this plays a role here.

**Comment by xzf0587** [comment]
@sebastienlevert it is nice to know you are using m365 proxy for testing. 
Actually, I encountered this problem when I tried the m365 proxy with graph client. 
I tried the project you provided. But it still does not work.

And I tried another way. 
<img width="354" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/16380704/f7b06d74-8bfb-43fe-96f1-1c514c3dd2ff">
<img width="582" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/16380704/2435cd36-6f98-457f-95c2-2ffe8934b0e6">
I updated the `HTTPMessageHandler` by specifying to import `fetch` from `isomorphic-fetch`
It can work.
The issue seems that in my environment, the fetch does not work by default but can work by explicit import.

**Comment by sebastienlevert** [comment]
Interesting. On my side I'm using Node 18 LTS. If that helps! With the current setup, were you able to make it work? Thanks!

**Comment by xzf0587** [comment]
> Interesting. On my side I'm using Node 18 LTS. If that helps! With the current setup, were you able to make it work? Thanks!

Yes. It can work with the updated step. I'm using Node v18.13.0.
I debugged it and found that the global.fetch is existing before isomorphic-fetch import, so the set from  isomorphic-fetch is not executed. 
<img width="513" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/16380704/36048ad2-e300-4cb4-a5cd-e76f53114bfc">
<img width="629" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/16380704/757c45db-3e15-4513-8d6e-d2a26f9c7064">

**Comment by sebastienlevert** [comment]
Interesting. I don't know what's different between our environments. But glad you got it working! I'll close this issue for now, feel free to re-open! Thanks!

**Comment by lotfi-on-github** [comment]
> @sebastienlevert it is nice to know you are using m365 proxy for testing. Actually, I encountered this problem when I tried the m365 proxy with graph client. I tried the project you provided. But it still does not work.
> 
> And I tried another way. <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/16380704/269189941-f7b06d74-8bfb-43fe-96f1-1c514c3dd2ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjUyNzgsIm5iZiI6MTcwMzYyNDk3OCwicGF0aCI6Ii8xNjM4MDcwNC8yNjkxODk5NDEtZjdiMDZkNzQtOGJmYi00M2ZlLTk2ZjEtMWM1MTRjM2RkMmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NjdhMTQ0YTYyNTkwN2Q1MGZiOWNhY2ZlN2VkZjQ5N2VjMmMxMDYyYzQ1YTlmMDNlMWI4NTEzY2U3MTQ5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zCH2XsUbt437z8f9hf1pzvsD0x7DgIjIBSrJRX7wWVg"> <img alt="image" width="582" src="https://private-user-images.githubusercontent.com/16380704/269189984-2435cd36-6f98-457f-95c2-2ffe8934b0e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MjUyNzgsIm5iZiI6MTcwMzYyNDk3OCwicGF0aCI6Ii8xNjM4MDcwNC8yNjkxODk5ODQtMjQzNWNkMzYtNmY5OC00NTdmLTk1YzItMmZmZTg5MzRiMGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDIxMDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmZjY0MTg4YTg4NzY5ZjlkOWNkODkyMTZkYTgwYzVjOWUxZTA4NDNlYzFjZWVmOTU0NmI3OTNhNzZjODk5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J3e-dgW_tPtCnAJsFRng6B_x8j1c4icvYjAf2ua2Tls"> I updated the `HTTPMessageHandler` by specifying to import `fetch` from `isomorphic-fetch` It can work. The issue seems that in my environment, the fetch does not work by default but can work by explicit import.

Hello @xzf0587 
Well done !

I'm new in typescript and MS graph, coud you please share a full code to fix the fetch issue. I've the same problem when trying to use devproxy.
Thank you in advance :)

Lotfi

**Comment by xzf0587** [comment]
@lotfi-on-github Sorry for late reply.
The root cause for this issue is that the native fetch in node.js does not work correctly for proxy setting. You can get more information here [make-a-request-in-native-fetch-with-proxy-in-nodejs-18](https://stackoverflow.com/questions/72306101/make-a-request-in-native-fetch-with-proxy-in-nodejs-18)

What I did is to replace the native fetch with **fetch from node-fetch** and use the **HttpsProxyAgent from hpagent**. The highlight lines are what I did to set proxy for graph client.
<img width="715" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/16380704/eb12dc03-e986-4962-908e-69a804c8f94d">

My project is a Teams app built by Teams Toolkit. It will use proxy for browser and node environment. There is no extra code change for browser but the node environment needs code change.
https://github.com/xzf0587/teams-toolkit-app-without-graph-mock/blob/dev/api/getUserProfile/Hook.ts

If you have any further question, please ping me.

**Comment by lotfi-on-github** [comment]
Thank a lot @xzf0587 👍 
I'll check that on our project and update here.
