### ISSUE TITLE
documentation confusion

### ISSUE THREAD

**Issue by tanekim77** [microsoftgraph/msgraph-sdk-javascript#145]
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md

documentation is not working in typescript

import { AuthenticationProvider } from "@microsoft/microsoft-graph-client";

does not work, because it says AuthenticationProvider doesn't exists

**Comment by darrelmiller** [comment]
@tanekim77 The AuthenticationProvider work has not yet been released to NPM.  It should be out in a couple of weeks.
