### ISSUE TITLE
TypeError: Invalid URL when attempting to construct BatchRequestStep object in Node

### ISSUE THREAD

**Issue by halljus** [microsoftgraph/msgraph-sdk-javascript#1451]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

This may be a usage problem on my end rather than a bug. When attempting to batch requests with path-relative URLs per the docs and examples, I get an Invalid URL error (I suspect this is because a Request cannot be constructed with path-relative URLs in Node and these requests are being evaluated prior to being serialized).

**Console Errors:** `TypeError: Invalid URL`

**Screenshots:** 

![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/102833203/a0849ec5-4424-4a87-b095-c571a06e2bd6)

## Steps to Reproduce

1. Construct BatchRequestStep object in Node
2. Observe `TypeError: Invalid URL` at runtime

**Expected behavior:** I would expect it to work as advertised and not throw an error.

**Actual behavior:** Request construction is being evaluated and thus throwing an Invalid URL error.

## Additional Context

I am attempting to make a batch request from a [Remix](https://remix.run/) action, specifically inside a [Zod](https://zod.dev/) [`superRefine`](https://zod.dev/?id=superrefine) method, inside a [Conform](https://conform.guide/) [`parse`](https://conform.guide/api/zod#parse) function (all running on the server, in Node - not the browser). That said, I don't think that matters and I don't see how you could construct a new Request with a path-relative URL like the docs indicate without it being evaluated and getting the Invalid URL error, regardless of where you're calling it.

Here is the actual code for the function I'm calling:

```typescript
export async function resolveGraphUserIds(userIds: string[]): Promise<GraphUserResolution[]> {
  const requests = userIds.map<BatchRequestStep>((id) => ({
    id,
    // TypeError: Invalid URL
    request: new Request(`/users/${id}?$select=id,displayName,onPremisesSamAccountName`, {
      method: 'GET',
    }),
  }));
  const batchRequestContent = new BatchRequestContent(requests);
  const batchResponse = await graphClient.api('/$batch').post(batchRequestContent);
  const batchResponseContent = new BatchResponseContent(batchResponse);

  return Promise.all(
    userIds.map(async (id) => {
      const response = batchResponseContent.getResponseById(id);
      if (response.ok) {
        const user: MaybeGraphUserSummary = await response.json();
        if (isGraphUserSummary(user)) {
          return { kind: 'success', user };
        }
        return {
          kind: 'failure',
          id,
          message: `Microsoft Graph user with id "${id}" was missing necessary fields`,
        };
      }
      return { kind: 'failure', id, message: `Microsoft Graph user with id "${id}" not found` };
    }),
  );
}
```

## Usage Information

Request ID - N/A

SDK Version - 3.0.5 (because 3.0.6 [is broken](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/1426#issuecomment-1706695475))

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v18.17.1

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - N/A

> Version - N/A

**Comment by drloloto** [comment]
Same for me, any news on this issue?

**Comment by drloloto** [comment]
> # Bug Report
> 
> 
> 
> ## Prerequisites
> 
> 
> 
> -   [X] Can you reproduce the problem?
> 
> -   [x] Are you running the latest version?
> 
> -   [x] Are you reporting to the correct repository?
> 
> -   [x] Did you perform a cursory search?
> 
> 
> 
> For more information, see the `CONTRIBUTING` guide.
> 
> 
> 
> ## Description
> 
> 
> 
> This may be a usage problem on my end rather than a bug. When attempting to batch requests with path-relative URLs per the docs and examples, I get an Invalid URL error (I suspect this is because a Request cannot be constructed with path-relative URLs in Node and these requests are being evaluated prior to being serialized).
> 
> 
> 
> **Console Errors:** `TypeError: Invalid URL`
> 
> 
> 
> **Screenshots:** 
> 
> 
> 
> ![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/102833203/a0849ec5-4424-4a87-b095-c571a06e2bd6)
> 
> 
> 
> ## Steps to Reproduce
> 
> 
> 
> 1. Construct BatchRequestStep object in Node
> 
> 2. Observe `TypeError: Invalid URL` at runtime
> 
> 
> 
> **Expected behavior:** I would expect it to work as advertised and not throw an error.
> 
> 
> 
> **Actual behavior:** Request construction is being evaluated and thus throwing an Invalid URL error.
> 
> 
> 
> ## Additional Context
> 
> 
> 
> I am attempting to make a batch request from a [Remix](https://remix.run/) action, specifically inside a [Zod](https://zod.dev/) [`superRefine`](https://zod.dev/?id=superrefine) method, inside a [Conform](https://conform.guide/) [`parse`](https://conform.guide/api/zod#parse) function (all running on the server, in Node - not the browser). That said, I don't think that matters and I don't see how you could construct a new Request with a path-relative URL like the docs indicate without it being evaluated and getting the Invalid URL error, regardless of where you're calling it.
> 
> 
> 
> Here is the actual code for the function I'm calling:
> 
> 
> 
> ```typescript
> 
> export async function resolveGraphUserIds(userIds: string[]): Promise<GraphUserResolution[]> {
> 
>   const requests = userIds.map<BatchRequestStep>((id) => ({
> 
>     id,
> 
>     // TypeError: Invalid URL
> 
>     request: new Request(`/users/${id}?$select=id,displayName,onPremisesSamAccountName`, {
> 
>       method: 'GET',
> 
>     }),
> 
>   }));
> 
>   const batchRequestContent = new BatchRequestContent(requests);
> 
>   const batchResponse = await graphClient.api('/$batch').post(batchRequestContent);
> 
>   const batchResponseContent = new BatchResponseContent(batchResponse);
> 
> 
> 
>   return Promise.all(
> 
>     userIds.map(async (id) => {
> 
>       const response = batchResponseContent.getResponseById(id);
> 
>       if (response.ok) {
> 
>         const user: MaybeGraphUserSummary = await response.json();
> 
>         if (isGraphUserSummary(user)) {
> 
>           return { kind: 'success', user };
> 
>         }
> 
>         return {
> 
>           kind: 'failure',
> 
>           id,
> 
>           message: `Microsoft Graph user with id "${id}" was missing necessary fields`,
> 
>         };
> 
>       }
> 
>       return { kind: 'failure', id, message: `Microsoft Graph user with id "${id}" not found` };
> 
>     }),
> 
>   );
> 
> }
> 
> ```
> 
> 
> 
> ## Usage Information
> 
> 
> 
> Request ID - N/A
> 
> 
> 
> SDK Version - 3.0.5 (because 3.0.6 [is broken](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/1426#issuecomment-1706695475))
> 
> 
> 
> -   [x] Node (Check, if using Node version of SDK)
> 
> 
> 
> > Node Version - v18.17.1
> 
> 
> 
> -   [ ] Browser (Check, if using Browser version of SDK)
> 
> 
> 
> > Browser Name - N/A
> 
> 
> 
> > Version - N/A
> 
> 

Same for me, any news or workarounds on this issue?

**Comment by halljus** [comment]
> Same for me, any news or workarounds on this issue?

Nope, I just gave up doing it at all until someone responds here.

**Comment by drloloto** [comment]
> > Same for me, any news or workarounds on this issue?
> 
> Nope, I just gave up doing it at all until someone responds here.

Ok thanks.

So I'm still a beginner and maybe I'm misunderstanding something but I think the ms library requires on the one hand the standard Request with "new Request" on the other hand it only accepts relative urls and
the Request constructor fails, if its an relative url.

The simple workaround is to generate the batch request by yourself:


```typescript
export interface batchContent {
	requests: Request[];
}

export interface Request {
	id: string;
	method: string;
	url: string;
}


const constructBatchJson = async (arrayContent: Value[]): Promise<batchContent> => {
	const batchContent = arrayContent.map((element: Value) => {
		return {
			id: element.id,
			method: 'GET',
			url: `/deviceManagement/detectedApps('${element.id}')/managedDevices`
		};
	});
	return { requests: batchContent };
};

const callBatch = async (batchContent: batchContent) => {
	const request = await graphClient.api(`/$batch`).version('beta').post(batchContent);
	return request;
};
```
reference: https://learn.microsoft.com/en-us/graph/json-batching

**Comment by sebastienlevert** [comment]
Hello all! Sorry for the long delay here, it really slipped and we missed the issue. 

@drloloto is right and this seems to be related to latest versions of Node (Initially, this library was created with Node 10 IIRC) and `Request` introduced breaking changes along the way in Node 18 (you can test it in Node 16 right now and it works). As of today, the workaround @drloloto provided is probably the best way to make it happen without too much trouble. It will work with the provided Graph client and the set version (beta or v1, for instance). 

We are currently working hard at building the v4 of this library and I'm not expecting us to fix this issue on v3 unless there is significant demand. Thanks for your understanding! I'll mark this one as closed as @drloloto provided a great solution.

You can see a working workaround here also: https://github.com/sebastienlevert/msgraph-typescript-node/blob/bug/1451/src/index.ts

We'll be pushing updates to the documentation. Thanks!

**Comment by jasonjoh** [comment]
So I did some digging here because @sebastienlevert asked me to update the doc snippets. It turns out, there's a much simpler workaround: add `https://graph.microsoft.com` in front of your URLs. The key here is to **NOT** include the version segment in the URL. There was a bug in the `BatchRequestContent` logic to sanitize URLs where it failed to strip the version. There's an unreleased fix for this already committed to the repo: https://github.com/microsoftgraph/msgraph-sdk-javascript/commit/19f4ac2ab797a5349e6e407cc2f48987943670e5

So in 3.0.7, this will work:

```typescript
request: new Request(`https://graph.microsoft.com/users/${id}?$select=id,displayName,onPremisesSamAccountName`, {
  method: 'GET',
}),
```

Once the fix is released, that will no longer work, but the **correct** full URL for the API will:

```typescript
request: new Request(`https://graph.microsoft.com/v1.0/users/${id}?$select=id,displayName,onPremisesSamAccountName`, {
  method: 'GET',
}),
```

**Comment by halljus** [comment]
@jasonjoh I've already implemented drloloto's workaround, so it's not blocking me or anything, but I tried your suggestion and still get `GraphError: Invalid batch payload format.` in 3.0.7 when using the `https://graph.microsoft.com` URL prefix (no version segment) - see below. I'm curious why it would work for you and not for me. 🤔 Does this code look right?

```ts
export async function resolveGraphUserIds(userIds: string[]): Promise<GraphUserResolution[]> {
  const requests = userIds.map<BatchRequestStep>((id) => ({
    id,
    request: new Request(
      `https://graph.microsoft.com/users/${id}?$select=id,displayName,onPremisesSamAccountName`,
      {
        method: 'GET',
      },
    ),
  }));
  const batchRequestContent = new BatchRequestContent(requests);
  const batchResponse = await graphClient.api('/$batch').post(batchRequestContent);
  const batchResponseContent = new BatchResponseContent(batchResponse);

  return Promise.all(
    userIds.map(async (id) => {
      const response = batchResponseContent.getResponseById(id);
      if (response.ok) {
        const graphUserResponse: GraphUserResponse = await response.json();
        if (isGraphUserSummary(graphUserResponse)) {
          const { id, displayName, onPremisesSamAccountName } = graphUserResponse;
          const user: GraphUserSummary = { id, displayName, onPremisesSamAccountName };
          return { kind: 'success', user };
        }
        return {
          kind: 'error',
          id,
          message: `Microsoft Graph user with id "${id}" was missing necessary fields`,
        };
      }
      return { kind: 'error', id, message: `Microsoft Graph user with id "${id}" not found` };
    }),
  );
}
```

**Comment by jasonjoh** [comment]
It looks like you're missing a call to `batchRequestContent.getContent()`, which gives you a `BatchRequestBody`, which is what you should be passing to the `.post` call:

```typescript
const content = await batchRequestContent.getContent();

const batchResponse = await graphClient.api('/$batch').post(content);
```

**Comment by halljus** [comment]
Dang, totally missed that somehow. Works now, thanks!
