### ISSUE TITLE
Will the skiptoken expire?

### ISSUE THREAD

**Issue by classmatewu** [microsoftgraph/msgraph-sdk-javascript#1463]
I learned from the [documentation](https://learn.microsoft.com/en-us/graph/query-parameters?tabs=http#skiptoken-parameter) that pagination can be done through skipToken. I want to record the current request progress by saving the @odata.nextLink return value of each current request in the database so that I can request the remaining data next time.
But the document does not explain whether skipToken will expire. It contains "token" and seems to have a certain validity period. How to specify its expiration time? What are the rules? Is there any detailed documentation?
thanks a lot.

**Comment by sebastienlevert** [comment]
There is not validity period on this token. You should be able to use it later without issues as long as your provide a valid bearer token!

**Comment by classmatewu** [comment]
Thanks a lot.

**Comment by classmatewu** [comment]
I think skipToken is similar to skip, it records the skip number, but why is it designed to be opaque?

**Comment by sebastienlevert** [comment]
It depends on the API you are calling. Some of they will be cursors in some data structures, others simple skip values. This will give you all the details : https://learn.microsoft.com/en-us/graph/paging?tabs=http. So to your initial question, the tokens will not expire as they are very specific in where they point in our index. Closing for now, feel free to reopen!
