### ISSUE TITLE
PageIterator iterating initial return instead of nextlinks

### ISSUE THREAD

**Issue by pinesh** [microsoftgraph/msgraph-sdk-javascript#1464]
# Bug Report

## Prerequisites

-   [ ] Can you reproduce the problem?
-   [ ] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

The PageIterator doesn't seem to be working as intended when trying to iterate through the List Groups api.

[Description of the bug or feature]
Instead of iterating through pages and providing a callback of each page as expected from reading of docs and the experience of other users, PageIterator seems to make the requests, but instead iterate the first return from the response.

## Steps to Reproduce

Write a typescript API function closely mirroring that from the docs. 
```
export async function getGroupsPaged(authProvider: AuthCodeMSALBrowserAuthenticationProvider): Promise<Event[]> {
    ensureClient(authProvider);
    const response: PageCollection = await graphClient!.api('/groups')
        .count(true)
        .header('ConsistencyLevel','eventual')
        .select('id,displayName,description')
        .orderby('id').top(5)
        .get();

// A callback function to be called for every item in the collection.
// This call back should return boolean indicating whether not to
// continue the iteration process.
    const callback: PageIteratorCallback = (data: any) => {
        console.log(data);
        return true;
    };

// Creating a new page iterator instance with client a graph client
// instance, page collection response from request and callback
    const pageIterator = new PageIterator(
        graphClient,
        response,
        callback,
    );

// This iterates the collection until the nextLink is drained out.
    await pageIterator.iterate();

    return;

}
```

**Expected behavior:** [What you expected to happen]
Expected the callback data to be the contents of each page, such that I could append all groups to a single list and return it

for a remote collection of groups with a length of 17, where ID is 1-> 17. 
-> Initial get, returns {nextlink, [1,2,3,5]}
-> start page iterator
-> page itererator makes the get request (browser reports response was 200 and contained objects [6,7,8,9,10]
-> page interator callback logged object   [6,7,8,9,10]
-> page itererator makes the get request (browser reports response was 200 and contained objects [11,12,13,14,15]
-> page interator callback logged object  [11,12,13,14,15]
-> page itererator makes the get request (browser reports response was 200 and contained objects [16,17]
-> page interator callback logged object [16,17]

**Actual behavior:** [What actually happened]
While all GET requests were made to the graph-api and returned next pages, the callback itself iterated through the data objects from the initial get and didn't provide access to any subsequent pages

to clarify, 
for a remote collection of groups with a length of 17, where ID is 1-> 17. 

-> Initial get, returns {nextlink, [1,2,3,5]
-> start page iterator
-> page interator callback logged object  [1]
-> page interator callback logged object  [2]
-> page interator callback logged object  [3]
-> page interator callback logged object  [4]
-> page interator callback logged object  [5]
-> page itererator makes the get request (browser reports response was 200 and contained objects [6,7,8,9,10]
-> page itererator makes the get request (browser reports response was 200 and contained objects [11,12,13,14,15]
-> page itererator makes the get request (browser reports response was 200 and contained objects [16,17]

## Usage Information

Using npm "@microsoft/microsoft-graph-client": "^3.0.6", in Typescript 

Effect is in both firefox and chrome (latest)

**Comment by pinesh** [comment]
Edit, Spotted an earlier report that referenced this issue from a couple of weeks ago, closing this issue as a duplicate and downgrading myself to 3.0.5,

**Comment by sebastienlevert** [comment]
3.0.7 should also fix this. Please confirm if you can upgrade to the latest. Thanks!

**Comment by pinesh** [comment]
> 3.0.7 should also fix this. Please confirm if you can upgrade to the latest. Thanks!

Upgrading to the latest has sorted this.

 Kicking myself just a little bit for writing a report the day after the fix is released!

**Comment by sebastienlevert** [comment]
Do not, just enjoy the new release 🥳
