### ISSUE TITLE
filenames with leading space

### ISSUE THREAD

**Issue by pfeux** [microsoftgraph/msgraph-sdk-javascript#1465]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I have a file containing filename in the beginning and somewhat the code trim the filename and path which can be seen here
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/2867554a1793ac1b6b1f9f556ae5c6c5aea9e198/src/tasks/OneDriveLargeFileUploadTask.ts#L88

```
	private static constructCreateSessionUrl(fileName: string, path: string = OneDriveLargeFileUploadTask.DEFAULT_UPLOAD_PATH): string {
		fileName = fileName; // by removing trim() from fileName would help fixing my issue
		path = path; // by removing trim from path would help fixing my issue.
		if (path === "") {
			path = "/";
		}
		if (path[0] !== "/") {
			path = `/${path}`;
		}
		if (path[path.length - 1] !== "/") {
			path = `${path}/`;
		}
		// we choose to encode each component of the file path separately because when encoding full URI
		// with encodeURI, special characters like # or % in the file name doesn't get encoded as desired
		return `/me/drive/root:${path
			.split("/")
			.map((p) => encodeURIComponent(p))
			.join("/")}${encodeURIComponent(fileName)}:/createUploadSession`;
	}
```

![image](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/29030616/e2c3b6ac-1e49-431c-83ac-6ef921aac111)

Is there anyway to upload large files with such leading space?
## Steps to Reproduce

1. Create any file with a space either in beginning or at the end and try to upload the file using OneDriveLargeFileUploadTask function

**Expected behavior:** File should successfully gets uploaded.

**Actual behavior:** It's throwing an error `Name specified in the path doesn't match the name specified in the request body`

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - [SDK version you are using]

-   [X] Node (Check, if using Node version of SDK)

> Node Version - v20.2.0

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - N/A

> Version - N/A

**Comment by sebastienlevert** [comment]
As per the OneDrive / SharePoint documentation, leading and trailing spaces aren't supported in the service: https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters.

Closing for now.
