### ISSUE TITLE
Creating a MSGraph Client with an already-existing accessToken

### ISSUE THREAD

**Issue by tyteen4a03** [microsoftgraph/msgraph-sdk-javascript#1481]
I am trying to access MSGraph based on an access token. All of the tutorials seem to gear towards also fetching the access token for me, which I don't need.

Are there any examples where I can just pass in an access token to get to a client?

**Comment by tyteen4a03** [comment]
I ended up doing this:

```
export const createAccessTokenClient = (accessToken: string): Client => {
    const authProvider = new (class implements AuthenticationProvider {
        async getAccessToken() {
            return accessToken;
        }
    })();

    return Client.initWithMiddleware({
        debugLogging: true,
        authProvider: authProvider,
    });
};
```

**Comment by sebastienlevert** [comment]
You did exactly the right thing! Providing your own authProvider is the right approach! I'll be closing it for now!

**Comment by tyteen4a03** [comment]
> You did exactly the right thing! Providing your own authProvider is the right approach! I'll be closing it for now!

Can this be included in the documentation?

**Comment by sebastienlevert** [comment]
We have it as part of the repo docs: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md
