### ISSUE TITLE
npm package v1.5.1 doesn't contain any sources

### ISSUE THREAD

**Issue by real-artswan** [microsoftgraph/msgraph-sdk-javascript#149]
# Bug Report

## Steps to Reproduce

1. npm install @microsoft/microsoft-graph-client
2. ls ./node_modules/@microsoft/microsoft-graph-client/
`CHANGELOG.md  LICENSE  package.json  README.md`

**Comment by muthurathinam** [comment]
Hi @real-artswan , its fixed in v1.5.2. Please update the package to same version.
