### ISSUE TITLE
beta api is not working with 1.5.2

### ISSUE THREAD

**Issue by juchom** [microsoftgraph/msgraph-sdk-javascript#151]
# Bug Report

beta api is not working with 1.5.2 release but is with 1.4.0

## Prerequisites

-   [X] Can you reproduce the problem? 
-   [X] Are you running the latest version? 
-   [X] Are you reporting to the correct repository? 
-   [X] Did you perform a cursory search? 

## Description

beta api is not working with 1.5.2 release but is with 1.4.0

**Console Errors:**

There is no error, it's like there is an exception that has been swallowed.

## Steps to Reproduce

With npm package 1.4.0 & 1.5.2:
Running this code on v1.0 works fine

```typescript
var AuthenticationContext = require('adal-node').AuthenticationContext;
var MicrosoftGraph = require("@microsoft/microsoft-graph-client");
require("isomorphic-fetch");

var client = MicrosoftGraph.Client.init({
    //defaultVersion: 'beta',
    authProvider: function (done) {
        done(null, 'mytoken');
    }
});

client
    .api('/users')
    .version('v1.0')
    .get()
    .then(function (res) {
    console.log(res);
})["catch"](function (err) {
    console.log(err);
});
```
With npm package 1.4.0:
Running this code on beta works:
With npm package 1.5.2:
Running this code on beta doesn't work:

```typescript
var AuthenticationContext = require('adal-node').AuthenticationContext;
var MicrosoftGraph = require("@microsoft/microsoft-graph-client");
require("isomorphic-fetch");

var client = MicrosoftGraph.Client.init({
    //defaultVersion: 'beta',
    authProvider: function (done) {
        done(null, 'mytoken');
    }
});

client
    .api('/applications')
    .version('beta')
    .get()
    .then(function (res) {
    console.log(res);
})["catch"](function (err) {
    console.log(err);
});
```
**Expected behavior:** 
It outputs the application list

**Actual behavior:** 
Nothing at all, no application, no error.

## Additional context

Calling, the beta api with postman or pure javascript works.

**Comment by MIchaelMainer** [comment]
In your first example that targets /user, does it work on both v1.0 and beta? 

In the second example that is not working with beta when using 1.5.2, can you share the error that you see?

**Comment by muthurathinam** [comment]
@juchom  It would better if you provide the required information by following the available template while reporting the bug. It also reduces the back and forth communication to get the necessary information about the bug. Ultimately helps in resolving bug quickly.

**Comment by juchom** [comment]
@MIchaelMainer the first example works on beta with 1.4.0 but it's not working with 1.5.2.

**Comment by stevkan** [comment]
I am also experiencing issues using 1.5.2.

## Description

API calls using 1.5.2 fail with "Response is not defined". In my case, this is true whether using API version "v1.0" or "beta". Here are the calls I am making and the (same) resultant error that is produced after each.

```js
const { Client } = require('@microsoft/microsoft-graph-client');

class SimpleGraphClient {
    constructor(token) {
        if (!token || !token.trim()) {
            throw new Error('SimpleGraphClient: Invalid token received.');
        }

        this._token = token;

        // Get an Authenticated Microsoft Graph client using the token issued to the user.
        this.graphClient = Client.init({
            authProvider: (done) => {
                done(null, this._token); // First parameter takes an error if you can't get an access token.
            }
        });
    }

    async sendMail(toAddress, subject, content) {
        if (!toAddress || !toAddress.trim()) {
            throw new Error('SimpleGraphClient.sendMail(): Invalid `toAddress` parameter received.');
        }
        if (!subject || !subject.trim()) {
            throw new Error('SimpleGraphClient.sendMail(): Invalid `subject`  parameter received.');
        }
        if (!content || !content.trim()) {
            throw new Error('SimpleGraphClient.sendMail(): Invalid `content` parameter received.');
        }

        const mail = {
            body: {
                content: content, // `Hi there! I had this message sent via MS Graph. - Your friend, ${ graphData.displayName }!`,
                contentType: 'Text'
            },
            subject: subject, // `Message from MS Graph!`,
            toRecipients: [{
                emailAddress: {
                    address: toAddress
                }
            }]
        };

        return await this.graphClient
            .api('/me/sendMail')
            .post({ message: mail }, (error, res) => {
                if (error) {
                    throw error;
                } else {
                    return res;
                }
            });
    }

    async getRecentMail() {
        return await this.graphClient
            .api('/me/messages')
            .version('v1.0')
            .top(5)
            .get()
            .then((res) => {
                return res;
            })
            .catch((err) => {
                console.log(err);
            });
    }

    async getMe() {
        return await this.graphClient
            .api('/me')
            .version('v1.0')
            .get()
            .then((res) => {
                console.log(res);
                return res;
            })
            .catch((err) => {
                console.log(err);
            });
    }

    async getManager() {
        return await this.graphClient
            .api('/me/manager')
            .version('v1.0')
            .select('displayName')
            .get()
            .then((res) => {
                return res;
            })
            .catch((err) => {
                console.log(err);
            });
    }

    async getPhoto() {
        return await this.graphClient
            .api('/me/photo/$value')
            .responseType('ArrayBuffer')
            .version('v1.0')
            .get()
            .then((res) => {
                return res;
            })
            .catch((err) => {
                console.log(err);
            });
    }
}
```

Downgrading to 1.4.0 and the API calls succeed.

**Console Errors:**

```
ReferenceError: Response is not defined
    at Function.<anonymous> (C:\...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:127:48)
    at step (C:\...\node_modules\tslib\tslib.js:133:27)
    at Object.next (C:\...\node_modules\tslib\tslib.js:114:57)
    at C:\...\node_modules\tslib\tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\...\node_modules\tslib\tslib.js:103:16)
    at Function.GraphErrorHandler.getError (C:\...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:122:24)
    at GraphRequest.<anonymous> (C:\...\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:227:84)
    at step (C:\...\node_modules\tslib\tslib.js:133:27)
    at Object.throw (C:\...\node_modules\tslib\tslib.js:114:57)
```

## Steps to Reproduce

1. Install NPM package v1.5.2
2. Make the API calls
3. Observe the errors

**Expected behavior:**
Values should be returned via MS Graph for the various API calls.

**Actual behavior:**
Receive "Response is not defined" error.

**Comment by muthurathinam** [comment]
Same issue reported in stackoverflow: https://stackoverflow.com/questions/55106776/microsoft-graph-api-beta-not-working-with-node

**Comment by muthurathinam** [comment]
@juchom 
Is it happening with all the urls ?
Can you help me in reproducing the issue with the environment in which you are getting this issue ?
if its node, then with node version and if its in browser environment then the browser and its version ?

**Comment by muthurathinam** [comment]
@stevkan I fell its a different issue. Can you create a new bug for the same ? and provide me the environment information to reproduce the issue because its works fine with my setup.

**Comment by juchom** [comment]
The sample is done with node js v11.11.0

I've tried with two urls and I have the same behavior, no error, no  output.

**Comment by muthurathinam** [comment]
Thank you @juchom 
* Can you help me with the urls that you have tried ?
* verify whether you have necessary permissions to access the data.
* Try setting the .responseType(MicrosoftGraph.ResponseType.RAW) and check whether you are getting the response or not ?
like this,
```js
try {
    client
        .api('/applications')
        .version('beta')
        .responseType(MicrosoftGraph.ResponseType.RAW)
        .get()
        .then(function (res) {
            console.log(res);
        })
        .catch(function (err) {
            console.log(err);
        });
} catch(err) {
    console.log(err);
}
```
* Also check whether you are getting any exception ?

**Comment by juchom** [comment]
verify whether you have necessary permissions to access the data:
This works fine with postman

Try setting the .responseType(MicrosoftGraph.ResponseType.RAW) and check whether you are getting the response or not ?

Here is the response

```
https://graph.microsoft.com/beta/applications
Body {
  url: 'https://graph.microsoft.com/beta/applications',
  status: 200,
  statusText: 'OK',
  headers:
   Headers {
     _headers:
      { 'cache-control': [Array],
        'transfer-encoding': [Array],
        'content-type': [Array],
        'content-encoding': [Array],
        vary: [Array],
        'request-id': [Array],
        'client-request-id': [Array],
        'x-ms-ags-diagnostic': [Array],
        'odata-version': [Array],
        duration: [Array],
        'strict-transport-security': [Array],
        date: [Array],
        connection: [Array] } },
  ok: true,
  body:
   Gunzip {
     _writeState: Uint32Array [ 0, 0 ],
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: true,
        emitClose: true,
        autoDestroy: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] {
        prefinish: [Function: prefinish],
        end: [Function],
        unpipe: [Function: onunpipe],
        drain: [Function: pipeOnDrainFunctionResult],
        error: [Function: onerror],
        close: [Function],
        finish: [Function] },
     _eventsCount: 7,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 15737,
        writing: true,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: [Function: nop],
        writelen: 15737,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 1,
        prefinished: false,
        errorEmitted: false,
        emitClose: true,
        autoDestroy: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: true,
     _transformState:
      { afterTransform: [Function: bound afterTransform],
        needTransform: false,
        transforming: true,
        writecb: [Function: bound onwrite],
        writechunk:
         <Buffer 1f 8b 08 00 00 00 00 00 04 00 ed bd 07 60 1c 49 96 25 26 2f 6d ca 7b 7f 4a f5 4a d7 e0 74 a1 08 80 60 13 24 d8 90 40 10 ec c1 88 cd e6 92 ec 1d 69 47 ... 15687 more bytes>,
        writeencoding: 'buffer' },
     _hadError: false,
     bytesWritten: 0,
     _handle:
      Zlib {
        onerror: [Function: zlibOnError],
        buffer:
         <Buffer 1f 8b 08 00 00 00 00 00 04 00 ed bd 07 60 1c 49 96 25 26 2f 6d ca 7b 7f 4a f5 4a d7 e0 74 a1 08 80 60 13 24 d8 90 40 10 ec c1 88 cd e6 92 ec 1d 69 47 ... 15687 more bytes>,
        cb: [Function: bound afterTransform],
        availOutBefore: 16384,
        availInBefore: 15737,
        inOff: 0,
        flushFlag: 0,
        [Symbol(owner)]: [Circular] },
     _outBuffer:
      <Buffer 7b 22 40 6f 64 61 74 61 2e 63 6f 6e 74 65 78 74 22 3a 22 68 74 74 70 73 3a 2f 2f 67 72 61 70 68 2e 6d 69 63 72 6f 73 6f 66 74 2e 63 6f 6d 2f 62 65 74 ... 16334 more bytes>,
     _outOffset: 0,
     _chunkSize: 16384,
     _defaultFlushFlag: 0,
     _finishFlushFlag: 4,
     _nextFlush: -1,
     _defaultFullFlushFlag: 3,
     _info: undefined,
     _level: -1,
     _strategy: 0 },
  bodyUsed: false,
  size: 0,
  timeout: 0,
  _raw: [],
  _abort: false }
```

**Comment by muthurathinam** [comment]
@juchom I am not able to reproduce the issue. The same code with the node version 11.11.0 just works fine.
Can you try to delete your node_modules folder and package-lock.json file and try intall your dependencies again ? Am just suspecting that installation or update of the package might not happened properly.

**Comment by juchom** [comment]
It's not working, in my folder I have this two files

package.json

```
{
  "name": "graphts",
  "devDependencies": {
    "@types/node": "latest"
  },
  "dependencies": {
    "@microsoft/microsoft-graph-client": "=1.5.2",
    "adal-node": "^0.1.28"
  }
}
```
index.js
```
var AuthenticationContext = require('adal-node').AuthenticationContext;
var MicrosoftGraph = require("@microsoft/microsoft-graph-client");

var client = MicrosoftGraph.Client.init({
    //defaultVersion: 'beta',
    debugLogging: true,
    authProvider: function (done) {
        done(null, 'TOKEN');
    }
});

try
{
client
    .api('/applications')
    .version('beta')
    .responseType()
    .get()
    .then(function (res) {
    console.log(res);
})["catch"](function (err) {
    console.log(err);
});
}catch(err) {
    console.log(err);
}
```

I type the following commands
npm install

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN graphts@ No description
npm WARN graphts@ No repository field.
npm WARN graphts@ No license field.

added 70 packages from 119 contributors and audited 90 packages in 6.404s
found 0 vulnerabilities
```

node index.js
```
https://graph.microsoft.com/beta/applications
```

There is no result

**Comment by juchom** [comment]
Also, it's no working on another machine with node v10.13.0.

**Comment by juchom** [comment]
Same code running on Ubuntu (WSL) same result.

**Comment by muthurathinam** [comment]
@juchom 
Confirm me these things once again:
1. With the same set of setup you have in this https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/151#issuecomment-473240911 its not working for 1.5.2 but its working for 1.4.0 ?
2. With the same setup is it working with v1.0 ? only the beta APIs are not working ?
3. With **`debugLogging: true`** in client init. you should be getting the request url **`https://graph.microsoft.com/beta/applications`** being printed in the console. are you getting this console output ?
4. If above is not true then, have should make sure that the code above actually executes ?
In order verify the above.. comment out all your adal-node related code and try to get your token from [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) by,
* log in with your account
* open developer console by pressing F12 or selecting inspect element from right click menu and navigating to console tab
* type `tokenPlease()` in the console
* copy the token and paste it in authProvider callback in init
* run `node index.js`

**Comment by muthurathinam** [comment]
You can debug your index.js in vscode to make sure your code actually makes calls to graph library by,
* Add the below file under `.vscode` folder in the name `launch.json`
```JSON
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "node",
			"request": "launch",
			"name": "Run index.js",
			"program": "${workspaceRoot}/index.js",
			"cwd": "${workspaceRoot}",
			"outFiles": [],
			"internalConsoleOptions": "openOnSessionStart"
		}
	]
}
```
* Navigate to Debug tab
* Select `Run index.js` in the top left
* Run the debugger
* In order to break, place your break points.

**Comment by juchom** [comment]
1. With the same set of setup you have in this #151 (comment) its not working for 1.5.2 but its working for 1.4.0 ? YES

2. With the same setup is it working with v1.0 ? YES only the beta APIs are not working ? YES

3. With debugLogging: true in client init. you should be getting the request url https://graph.microsoft.com/beta/applications being printed in the console. are you getting this console output ? YES

4. If above is not true then, have should make sure that the code above actually executes ?
In order verify the above.. comment out all your adal-node related code and try to get your token from Graph Explorer by, 
log in with your account
open developer console by pressing F12 or selecting inspect element from right click menu and navigating to console tab
type tokenPlease() in the console
copy the token and paste it in authProvider callback in init
run node index.js

With step 4 I have more information on this issue:

Using a token from my app principal:
https://graph.microsoft.com/v1.0/users -> OK
https://graph.microsoft.com/beta/users -> NOT WORKING

Using a token with my personal login (from graph explorer):
https://graph.microsoft.com/v1.0/users -> OK
https://graph.microsoft.com/beta/users -> OK

Is there a way to configure the graph client to use fiddler?

**Comment by muthurathinam** [comment]
Check whether this helps capturing request in fiddler?
```js
var HTTPProxyAgent = require("https-proxy-agent");
client
	.api("/me")
	.version("beta")
        .option("agent", new HTTPProxyAgent("http://127.0.0.1:8888"))
	.get()
	.then(function(res) {
		console.log(res);
	})
	.catch(function(err) {
		console.log(err);
	});
```

**Comment by juchom** [comment]
Before fiddler:
Using a token from my app principal:
https://graph.microsoft.com/v1.0/users -> OK
https://graph.microsoft.com/beta/users -> NOT WORKING

Looking in fiddler I have this now:
https://graph.microsoft.com/v1.0/users -> OK
https://graph.microsoft.com/beta/users -> OK

But the console still shows nothing in beta. 
The returned payload size are:
- v1.0 -> 30 897 chars
- beta -> 192 692 chars

Not sure where to go from here. Let me know.

**Comment by juchom** [comment]
Here is a sample of my response with v1.0/users

```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
    "value": [
        {
            "businessPhones": [],
            "displayName": "account",
            "givenName": null,
            "jobTitle": null,
            "mail": "account@hotmail.com",
            "mobilePhone": null,
            "officeLocation": null,
            "preferredLanguage": null,
            "surname": null,
            "userPrincipalName": "account_hotmail.com#EXT#@mytenant.onmicrosoft.com",
            "id": "906dd29a-a1d3-4745-b0e7-a82675c97a38"
        }
    ]
}
```

And here with beta/users:

```
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#users",
    "value": [
        {
            "id": "906dd29a-a1d3-4745-b0e7-a82675c97a38",
            "deletedDateTime": null,
            "accountEnabled": true,
            "ageGroup": null,
            "businessPhones": [],
            "city": null,
            "createdDateTime": "2018-02-08T09:38:08Z",
            "companyName": null,
            "consentProvidedForMinor": null,
            "country": null,
            "department": null,
            "displayName": "account",
            "employeeId": null,
            "faxNumber": null,
            "givenName": null,
            "imAddresses": [],
            "isResourceAccount": null,
            "jobTitle": null,
            "legalAgeGroupClassification": null,
            "mail": "account@hotmail.com",
            "mailNickname": "account_hotmail.com#EXT#",
            "mobilePhone": null,
            "onPremisesDistinguishedName": null,
            "officeLocation": null,
            "onPremisesDomainName": null,
            "onPremisesImmutableId": null,
            "onPremisesLastSyncDateTime": null,
            "onPremisesSecurityIdentifier": null,
            "onPremisesSamAccountName": null,
            "onPremisesSyncEnabled": null,
            "onPremisesUserPrincipalName": null,
            "otherMails": [
                "account@hotmail.com"
            ],
            "passwordPolicies": null,
            "passwordProfile": null,
            "postalCode": null,
            "preferredDataLocation": null,
            "preferredLanguage": null,
            "proxyAddresses": [
                "SMTP:account@hotmail.com"
            ],
            "refreshTokensValidFromDateTime": "2018-02-08T09:38:08Z",
            "showInAddressList": false,
            "signInSessionsValidFromDateTime": "2018-02-08T09:38:08Z",
            "state": null,
            "streetAddress": null,
            "surname": null,
            "usageLocation": null,
            "userPrincipalName": "account_hotmail.com#EXT#@mytenant.onmicrosoft.com",
            "externalUserState": "Accepted",
            "externalUserStateChangeDateTime": "2018-02-08T09:39:15Z",
            "userType": "Guest",
            "assignedLicenses": [],
            "assignedPlans": [],
            "deviceKeys": [],
            "onPremisesExtensionAttributes": {
                "extensionAttribute1": null,
                "extensionAttribute2": null,
                "extensionAttribute3": null,
                "extensionAttribute4": null,
                "extensionAttribute5": null,
                "extensionAttribute6": null,
                "extensionAttribute7": null,
                "extensionAttribute8": null,
                "extensionAttribute9": null,
                "extensionAttribute10": null,
                "extensionAttribute11": null,
                "extensionAttribute12": null,
                "extensionAttribute13": null,
                "extensionAttribute14": null,
                "extensionAttribute15": null
            },
            "onPremisesProvisioningErrors": [],
            "provisionedPlans": []
        }
    ]
}
```

**Comment by muthurathinam** [comment]
> Looking in fiddler I have this now:
https://graph.microsoft.com/v1.0/users -> OK
https://graph.microsoft.com/beta/users -> OK

Here in OK for beta/users are you getting the 200 OK response ?

**Comment by juchom** [comment]
Here in OK for beta/users are you getting the 200 OK response ? YES

**Comment by amistry79** [comment]
I am facing the same issue. I tried downgrading to v1.4.0 and it does not work for both the versions of API

graph API : "v1.0": Error
graph API: "beta" : Error
Node v11.12
See the below error: 

ReferenceError: Response is not defined
    at Function.<anonymous> (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:127:48)
    at step (D:\workspace\myapp\node_modules\tslib\tslib.js:133:27)    at Object.next (D:\workspace\myapp\node_modules\tslib\tslib.js:114:57)
    at D:\workspace\myapp\node_modules\tslib\tslib.js:107:75    at new Promise (<anonymous>)
    at Object.__awaiter (D:\workspace\myapp\node_modules\tslib\tslib.js:103:16)    at Function.GraphErrorHandler.getError (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:122:24)
    at GraphRequest.<anonymous> (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:227:84)
    at step (D:\workspace\myapp\node_modules\tslib\tslib.js:133:27)    at Object.throw (D:\workspace\myapp\node_modules\tslib\tslib.js:114:57)
    at rejected (D:\workspace\myapp\node_modules\tslib\tslib.js:105:69)    at process.internalTickCallback (internal/process/next_tick.js:77:7)Error at setUserProfileAccessor after login.. ReferenceError: Response is not defined
    at Function.<anonymous> (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:127:48)    at step (D:\workspace\myapp\node_modules\tslib\tslib.js:133:27)    at Object.next (D:\workspace\myapp\node_modules\tslib\tslib.js:114:57)
    at D:\workspace\myapp\node_modules\tslib\tslib.js:107:75    at new Promise (<anonymous>)
    at Object.__awaiter (D:\workspace\myapp\node_modules\tslib\tslib.js:103:16)    at Function.GraphErrorHandler.getError (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphErrorHandler.js:122:24)
    at GraphRequest.<anonymous> (D:\workspace\myapp\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js:227:84)    at step (D:\workspace\myapp\node_modules\tslib\tslib.js:133:27)
    at Object.throw (D:\workspace\myapp\node_modules\tslib\tslib.js:114:57)    at rejected (D:\workspace\myapp\node_modules\tslib\tslib.js:105:69)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

**Comment by muthurathinam** [comment]
@juchom Can you update the library to latest version i.e 1.6.0 and check whether same issue is reproducing ?

**Comment by juchom** [comment]
Hi @muthurathinam , I've just tried the same code with 1.6 and it's still not working.

**Comment by darrelmiller** [comment]
@juchom Has this issue been resolved for you in our latest release?

**Comment by muthurathinam** [comment]
@darrelmiller #152 was fixed in latest release. This issue is related to #169, Fix for this is not yet released.

**Comment by muthurathinam** [comment]
Fixed in this preview release: https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1

**Comment by muthurathinam** [comment]
Fixed in this preview release: https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1
@juchom @amistry79 Can you try and provide your feeback ?

**Comment by juchom** [comment]
With the same script I've tried this:

Updated to 1.7.0: => doesn't work

Updated to 2.0.0-Preview.1 and 2.0.0-Preview.2: => I have this error

```
C:\dev\graphts\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:95
            throw error;
            ^

PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.
    at Object.exports.validatePolyFilling (C:\dev\graphts\node_modules\@microsoft\microsoft-graph-client\lib\src\ValidatePolyFilling.js:27:21)
    at new Client (C:\dev\graphts\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:36:35)
    at Function.Client.initWithMiddleware (C:\dev\graphts\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:92:20)
    at Function.Client.init (C:\dev\graphts\node_modules\@microsoft\microsoft-graph-client\lib\src\Client.js:81:23)
    at C:\dev\graphts\index.js:24:36
    at C:\dev\graphts\node_modules\adal-node\lib\token-request.js:157:11
    at C:\dev\graphts\node_modules\adal-node\lib\cache-driver.js:516:7
    at MemoryCache.add (C:\dev\graphts\node_modules\adal-node\lib\memory-cache.js:75:3)
    at C:\dev\graphts\node_modules\adal-node\lib\cache-driver.js:515:17
    at C:\dev\graphts\node_modules\adal-node\lib\cache-driver.js:440:9 {
  name: 'PolyFillNotAvailable'
}
```

**Comment by muthurathinam** [comment]
@juchom It is expected error. Since there are some breaking changes in 2.0.0-Preview.x. 
Please follow [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/wiki/Migration-from-1.x.x-to-2.x.x) migration guide

**Comment by juchom** [comment]
Ok, adding isomorphic-fetch to my script is fine.

With 2.0.0-Preview.1 and 2.0.0-Preview.2 my script is working fine!

Thanks

**Comment by muthurathinam** [comment]
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0
