### ISSUE TITLE
Running browser sample in Chrome causes continuous browser login pop-ups

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-javascript#153]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Running the browser sample causes a login popup to display.  

## Steps to Reproduce
1. Run the browser sample
2. Selecting an account from the login popup. Will need to enable popups.
3. Enter entering credentials, and hit ok
4. Attempt to select account on new popup that has apppeared
5.  Repeat endlessly 

**Expected behavior:** 
Only to see the popup once.

**Actual behavior:**
Repeatedly appears.

## Additional context
The profile picture appears after the first popup but other data does not.  
The sample works fine in Edge.

**Comment by muthurathinam** [comment]
@darrelmiller I will look into this.

**Comment by MIchaelMainer** [comment]
I've seen this outside of our samples. I forget what it was. I think it was an internal lob app.

**Comment by muthurathinam** [comment]
Fixed in this release: https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/1.6.0
