### ISSUE TITLE
Graph client not showing recurring meetings

### ISSUE THREAD

**Issue by sanjcherrydev** [microsoftgraph/msgraph-sdk-javascript#155]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

Thanks for this package, it's been really great so far!

MS Graph Explorer on the web does show recurring meetings but when using this JS SDK I don't get recurring meetings returning after the seriesMaster.

If I go to the web explorer:

https://developer.microsoft.com/en-us/graph/graph-explorer

And enter a valid query it returns all one-off events and recurring events, including the seriesMaster and occurences of the master.

But when I use this package and make a similar get request I only get one-off meetings and the seriesMaster of a recurring meeting if it happens to be in the time I filter for.

What I'd like to be able to do is filter for today's events and get recurring meetings too.  Is this possible and if so, how please?

This is my SDK query
```
.api(`users/${user}/calendar/events`)
        .select("subject,organizer,start,end,location,id,attendees,type,seriesMasterId,recurrence")
        .filter(`start/dateTime ge ${currentDateFormatted()} and end/dateTime lt ${tomorrowDateFormatted()}`)
        .top(99)
        .orderby("start/dateTime")
        .get();
```

**Comment by muthurathinam** [comment]
@sanjcherrydev Can you help me with the query that you have executed in the graph-explorer ?

**Comment by sanjcherrydev** [comment]
@muthurathinam Thanks very much for your response!  This is an example query that I used:

```
https://graph.microsoft.com/v1.0/users/${user}/calendar/calendarView?startdatetime=2019-04-05T09:00:00.000Z&enddatetime=2019-04-06T22:00:00.000Z&$select=subject,organizer,start,end,location,id,attendees&$orderby=start/dateTime%20asc
```

Using the `calendarView` endpoint works to return recurring event instances and private events, but the `events` endpoint does not, and that is the behaviour we're seeing from this SDK's `.api` method.

**Comment by muthurathinam** [comment]
@sanjcherrydev  Did both `calenderView` and `events` endpoints work in graph explorer ? and `calenderView` endpoint is working and `events` endpoint alone not working in SDK?

**Comment by MIchaelMainer** [comment]
@sanjcherrydev That is expected behavior. The calendarview expands recurring meetings so that you every instance of the meeting, as you would see in Outlook. The events endpoint **returns the event 'master'**. The 'master' event contains information about individual and recurring meetings. Recurring meetings are not expanded with the /events resource. The events resource returns the master meetings with their recurrence patterns so that the recurrence pattern for the meeting can be altered. We can't change meetings, recurring or not, from the calendarview. You can change recurring meetings with the recurring master item returned from the events resource.

**Comment by MIchaelMainer** [comment]
Oh, I see what you want. Okay, start with the calendarview for the day you want to target. Get the IDs of the meetings in the calendarview. Then, using those IDs, call the /events end point for each of those IDs to access the recurring master. Now, off the top of my head, I don't know if you request recurring instance whether you get the recurring master or not. We'd have to check the documentation or see what properties are returned.

**Comment by sanjcherrydev** [comment]
@muthurathinam @MIchaelMainer Thank you for your responses, it's much appreciated.  That is sort of similar to the solution we're thinking about.

To get and set events via the `events` endpoint with this client, but since that doesn't return recurring and private events for the queried day we intend to supplement the original data from the `calendarView` REST endpoint.

It would however be really nice to have a single destination with this client to get all the above events.

**Comment by muthurathinam** [comment]
@sanjcherrydev This is not an SDK issue and this should be directed to StackOverflow with the microsoft-graph and microsoft-graph-sdks tags.
