### ISSUE TITLE
sendMail always throws an error

### ISSUE THREAD

**Issue by domihagen** [microsoftgraph/msgraph-sdk-javascript#156]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Version
1.5.2

## Description
When i am sending Mails via the sendMail-Route it always throws an error "invalid json response body at https://graph.microsoft.com/v1.0/users/MY_USER_ID/sendMail reason: Unexpected end of JSON input"

**Code-Example**
```javascript
const mailMessage = {
  message: {
    subject: 'My Mail-Subject',
    body: {
      contentType: 'Text',
      content: 'My Mail-Content only Text.'
    },
    from: {
      emailAddress: {
        address: 'from@domain.com'
      }
    },
    toRecipients: [
      {
        emailAddress: {
          address: 'to@domain.com'
        }
      }
    ]
  },
  saveToSentItems: false
}

try {
  await client.api(`/users/${userId}/sendMail`).post(mailMessage)
} catch (e) {
  console.error(JSON.stringify(e, undefined, 4))
}
```

**Console Errors:** 
```json
 {
    "statusCode": 202,
    "code": "FetchError",
    "message": "invalid json response body at https://graph.microsoft.com/v1.0/users/MY_USER_ID/sendMail reason: Unexpected end of JSON input",
    "requestId": null,
    "date": "2019-03-27T15:12:20.964Z",
    "body": "FetchError: invalid json response body at https://graph.microsoft.com/v1.0/users/MY_USER_ID/sendMail reason: Unexpected end of JSON input"
}
```

## Steps to Reproduce

1. Sending POST-Request via client to sendMail-Route
2. When the response come back, it falls into the catch-block with statusCode 202 and the message from above

**Expected behavior:** 
Finish without throwing an error.

**Actual behavior:**
Throwing an error, but mails was sent.

**Comment by muthurathinam** [comment]
Hi @domihagen ,
Thank you for reporting the issue. Will fix this. 
Meanwhile use this as a workaround. Set the responseType to "raw" and you will be able to get the raw response.

```js
const mailMessage = {
  message: {
    subject: 'My Mail-Subject',
    body: {
      contentType: 'Text',
      content: 'My Mail-Content only Text.'
    },
    from: {
      emailAddress: {
        address: 'from@domain.com'
      }
    },
    toRecipients: [
      {
        emailAddress: {
          address: 'to@domain.com'
        }
      }
    ]
  },
  saveToSentItems: false
}

try {
  await client.api(`/users/${userId}/sendMail`).responseType("raw").post(mailMessage)
} catch (e) {
  console.error(JSON.stringify(e, undefined, 4))
}
```

**Comment by muthurathinam** [comment]
@domihagen Released a preview with fix https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0-Preview.2 
Try it out and provide your feedback. Install Preview package with
`npm i @microsoft/microsoft-graph-client@Preview`

**Comment by PopGoesTheWza** [comment]
@muthurathinam FYI, I am experiencing the same `202` error with the DriveItem copy endpoint:
`POST /drives/${driveId}/items/${itemId}/copy`
I will try to test your workaround tomorrow.

**Comment by muthurathinam** [comment]
Hey @PopGoesTheWza try making your request with [this](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0) new version 1.6.0, should resolve the issue.

**Comment by domihagen** [comment]
@muthurathinam Sorry for my late answer, but I was on vacation. I tested it with the latest version (1.6.0) and it works.

Thanks!
