### ISSUE TITLE
Authorization Header Missing with different scope

### ISSUE THREAD

**Issue by dcarvalh04** [microsoftgraph/msgraph-sdk-javascript#1562]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

Trying to use a "https://management.azure.com/.default" as scope leads to the following error:

**graphservice.js**:

![CleanShot 2023-12-22 at 17 27 13@2x](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/132361946/0691e3d2-0e40-44c6-bd81-7c39e2600801)

**normal graph client works, mgmt doesn't**
![CleanShot 2023-12-22 at 17 28 06@2x](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/132361946/9f3c1934-a611-462e-b4ad-a8843510680e)

**Console Errors:**

`GraphError: Authentication failed. The 'Authorization' header is missing.
    at new GraphError (xxxx/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphError.js:34:28)
    at GraphErrorHandler.constructErrorFromResponse (xxxx/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:63:22)
    at Function.<anonymous> (xxxx/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:91:48)
    at step (/xxxx/node_modules/tslib/tslib.js:195:27)
    at Object.next (xxxx/node_modules/tslib/tslib.js:176:57)
    at xxxx/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (xxxx/node_modules/tslib/tslib.js:165:16)
    at GraphErrorHandler.getError (xxxx/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:87:24)
    at GraphRequest.<anonymous> (xxxx/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:315:84) {
  statusCode: 401,
  code: 'AuthenticationFailed',
  requestId: null,
  date: 2023-12-22T15:56:33.856Z,
  body: {"code":"AuthenticationFailed","message":"Authentication failed. The Authorization header is missing."},
  headers: HeadersList {
    cookies: null,
    [Symbol(headers map)]: Map(14) {
      'cache-control' => [Object],
      'pragma' => [Object],
      'content-type' => [Object],
      'expires' => [Object],
      'www-authenticate' => [Object],
      'x-ms-failure-cause' => [Object],
      'x-ms-request-id' => [Object],
      'x-ms-correlation-request-id' => [Object],
      'x-ms-routing-request-id' => [Object],
      'strict-transport-security' => [Object],
      'x-content-type-options' => [Object],
      'date' => [Object],
      'connection' => [Object],
      'content-length' => [Object]
    },
    [Symbol(headers map sorted)]: null
  }
}`

## Steps to Reproduce

1. Init graph client with https://management.azure.com/.default as scope
2. Query for example "/subscriptions?api-version=2022-12-01"

**Expected behavior:** 
Get list of subscriptions

**Actual behavior:** 
Error thrown "GraphError: Authentication failed. The 'Authorization' header is missing"

## Additional Context

Using the SDK with same token works:

`const credential = new DefaultAzureCredential();
      const client = new SubscriptionClient(credential);
      const resArray = new Array();
      for await (let item of client.subscriptions.list()) {
        resArray.push(item);
      }
      console.log(resArray);`

The following also works on Insomnia:

![CleanShot 2023-12-22 at 17 36 44@2x](https://github.com/microsoftgraph/msgraph-sdk-javascript/assets/132361946/a49ae1db-29d5-4311-a0e3-ab0c9ccd4681)

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - "@microsoft/microsoft-graph-client": "^3.0.7",

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v20.10.0

**Comment by dcarvalh04** [comment]
Okay, found the culprit.

AuthenticationHandler.js:
`if (!((0, GraphRequestUtil_1.isGraphURL)(url) || (context.customHosts && (0, GraphRequestUtil_1.isCustomHost)(url, context.customHosts)))) return [3 /*break*/, 2];
`

isGraphURL returns isValidEndpoint(url) which checks for constant "GRAPH_URLS" which is equal to:
`exports.GRAPH_URLS = new Set(["graph.microsoft.com", "graph.microsoft.us", "dod-graph.microsoft.us", "graph.microsoft.de", "microsoftgraph.chinacloudapi.cn", "canary.graph.microsoft.com"]);`

Workaround:

add `customHosts: new Set(["management.azure.com"])` to my client config:

`this.azMgmtClient = await GraphService.initializeGraphClient(
      "https://management.azure.com/.default",
      {
        baseUrl: "https://management.azure.com/",
        customHosts: new Set(["management.azure.com"]),
        defaultVersion: "",
      }
    );`


Suggestion would be to throw a more specific error in AuthenticationHandler.prototype.execute

**Comment by sebastienlevert** [comment]
Can you expand on why you are leveraging the Graph Client to access Azure Management resources? It's definitely something that isn't officially supported and we don't expect to support these scenarios anytime soon. I assume it's to leverage the existing auth capabilities?

**Comment by dcarvalh04** [comment]
Hi @sebastienlevert 

Yes, in fact it allows me to use the existing auth capabilities and avoid a scenario where my codebase would have:
- graph sdk for creating groups and access reviews
- my own implementation for management.azure.com to create subscriptions
- Azure SDK for specific resources 

the graph sdk already has a lot done in terms of auth and http requests that is easily reusable to call management.azure.com.

so my final choice will be to either use graph sdk only to manage groups, users, eapps and azure sdk only for managing subscriptions and other azure resources OR use graph sdk to do both as I'm doing as of now.

In my app, I need to not only manage groups, app assignments and access reviews but also manage azure resource groups, subscriptions and rbac. That's why I need both api endpoints. 

In node.js for groups, app assignements i can either use graph sdk or my own implementation and for azure resources i can either use azure arm sdk, implement my own http requests to management.azure.com or leverage Graph SDK. 

Graph SDK may not be officially supported but simplifies my codebase with less packages and ways to call api. Also more freedom with graph api than arm sdk.

Using the ARM SDK is officially supported but means i need graph sdk for azure groups+apps and azure arm sdk for azure management.

**Comment by sebastienlevert** [comment]
Thanks for the context here, I really appreciate it! With the `customHosts` approach I think you are in good shape then!
