### ISSUE TITLE
Response with `content-type: text/plain` is not being handled correctly

### ISSUE THREAD

**Issue by AdriVanHoudt** [microsoftgraph/msgraph-sdk-javascript#165]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [ ] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I'm trying to fetch the raw message from the api.
`GET https://graph.microsoft.com/beta/me/messages/[MESSAGE ID]/$value`
This works in the graph explorer and returns with `content-type: text/plain`

When doing this request through this sdk it fails to parse the body on version 1.4.x and throws on version 1.5.x .

**Console Errors:**

We are using version 1.4 so no error but also no response body.
On 1.5:
```js
{ Error: authenticationProvider.getAccessToken is not a function
    at Object.internals.wrapError (.../unimail/lib/unimail-office365.js:1118:17)
    at client.api.get (.../unimail/lib/unimail-office365.js:113:55)
    at Function.<anonymous> (.../unimail/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:145:29)
    at step (.../unimail/node_modules/tslib/tslib.js:133:27)
    at Object.next (.../unimail/node_modules/tslib/tslib.js:114:57)
    at .../unimail/node_modules/tslib/tslib.js:107:75
    at new Promise (<anonymous>)
    at Object.__awaiter (.../unimail/node_modules/tslib/tslib.js:103:16)
    at Function.GraphErrorHandler.getError (.../unimail/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphErrorHandler.js:122:24)
    at GraphRequest.<anonymous> (.../unimail/node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js:227:84)
    at step (.../unimail/node_modules/tslib/tslib.js:133:27)
    at Object.throw (.../unimail/node_modules/tslib/tslib.js:114:57)
    at rejected (.../unimail/node_modules/tslib/tslib.js:105:69)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:122:5)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  isBoom: true,
  isServer: true,
  data: null,
  output: 
   { statusCode: 500,
     payload: 
      { statusCode: 500,
        error: 'Internal Server Error',
        message: 'An internal server error occurred' },
     headers: {} },
  reformat: [Function] }
undefined
(node:64167) UnhandledPromiseRejectionWarning: undefined
(node:64167) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:64167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

```js
const accessToken = [TOKEN];
const client = MicrosoftGraph.init({
        defaultVersion:'beta',
        authProvider: (done) => {
            done(null, accessToken);
        }
    });

client.api(`/me/messages/${id}/$value`)
 .get((err, message, rawResponse) => {

 if (err) {
    return callback(err);
 }

// Both err and message are null/undefined

// What I have to do now to get the actual body
// I can't do rawResponse.text() since body is already used
 return callback(null, rawResponse._raw.toString());
});
```

On 1.4 the problem is that `responseType` is undefined here https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/1.4.0/src/GraphRequest.ts#L467
And then it tries to default to .json here https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/1.4.0/src/GraphRequest.ts#L500

I haven't dug into where it would go wrong in 1.5

**Expected behavior:**

It returns the plain text body.

**Actual behavior:** [What actually happened]

1.4: nothing gets returned
1.5: throws

## Additional context

Add any other context about the problem here..

**Comment by muthurathinam** [comment]
let me know did you get the same error in this preview build..
https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0-Preview.3
install preview build by `npm i @microsoft/microsoft-graph-client@Preview`

**Comment by muthurathinam** [comment]
@AdriVanHoudt FYI: Stable version ([1.6.0](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/1.6.0)) is released for the 1.6.0-Preview.3

**Comment by AdriVanHoudt** [comment]
I can confirm that 1.6.0 fixes the issue. What exactly changed in 1.6.0, the releases page is not super clear to me?

**Comment by muthurathinam** [comment]
@AdriVanHoudt That release page is auto generated, which basically pulls out all the commits that have been pushed.
There was a bug in response handler that is fixed now.
