### ISSUE TITLE
Large responses fail to resolve on Node.js

### ISSUE THREAD

**Issue by forivall** [microsoftgraph/msgraph-sdk-javascript#169]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [ ] Are you reporting to the correct repository? - technically, this is a by-design issue of node-fetch, but it can be mitigated
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Large responses fail on Node.js - see upstream issue https://github.com/bitinn/node-fetch/issues/396 and https://github.com/bitinn/node-fetch/issues/151

In https://github.com/bitinn/node-fetch/blob/master/LIMITS.md, note the line:
> * If you are using res.clone() and writing an isomorphic app, note that stream on Node.js have a smaller internal buffer size (16Kb, aka highWaterMark) from client-side browsers (>1Mb, not consistent across browsers).

This was introduced in 03e530c

**Console Errors:** None appear

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Use msgraph-sdk-javascript in node
2. Fetch a large response, such as groups or applications
3. The response does not resolve.

**Expected behavior:** The response should return successfully

**Actual behavior:** No response was resolved, as the highWaterMark was hit on the stream created during the `clone()`

## Additional context

See https://github.com/bitinn/node-fetch/pull/142 for some example tests for this issue

**Comment by mattschoch** [comment]
Ran into this as well.
A workaround that appears to work, get the raw response:

```
await client.api(`/me/calendarview`)
      .responseType(ResponseType.RAW) // Using raw response to address this error: https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/169
      .get()
      .then(res => res.json());
```

**Comment by gi-joe-moto** [comment]
Several of our API calls never resolve when using 1.7.  This is a major bug.  I'm reverting to 1.6.

**Comment by darrelmiller** [comment]
@gi-joe-moto Are you seeing the issue when using the RAW responsetype as suggested by @mattschoch in the comment above?

**Comment by gi-joe-moto** [comment]
I'll have to check in a couple of weeks... on a different project atm and won't have time till late June.

**Comment by hakan0xFF** [comment]
@darrelmiller We are having the same issue and using `.responseType(ResponseType.RAW)` as suggested by @mattschoch seems to resolve it.

**Comment by muthurathinam** [comment]
Fix is out in the [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.1) preview release.
@hakan0xFF  @gi-joe-moto @forivall Can you try the preview and let me know your feedback.

**Comment by mannharleen** [comment]
This is Fixed and due with v2.0.0 releaes - https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/170#issuecomment-494650127

**Comment by forivall** [comment]
Unfortunately, I'm no longer working at the company where I ran into this issue, so I cannot try the preview without going through the hoops of setting up a new azure subscription. So I'll have to leave the verification up to someone else.

**Comment by muthurathinam** [comment]
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0
