### ISSUE TITLE
Get a Sharepoint site Logo via API

### ISSUE THREAD

**Issue by pedrolourencoribeiro** [microsoftgraph/msgraph-sdk-javascript#1703]
# Feature Request

## Is your feature request related to a problem?
We're building an integration between sharepoint and our app and we would like to download the site Logo to show our clients.
We know that we can get this using the SharepointAPI but we don't want to request more permissions. Since we're using the Site.Selected that involves some manual work with Powershell/REST calls from the client we want to avoid also requesting the same permission but for Sharepoint...

## Describe the solution you'd like
Ideally we would be able to use the Microsoft Graph API to retrieve the site Logo using the Site.Selected permission via an app

## Describe alternatives you've considered
Get that using the Sharepoint API but that will require us to ask our clients for more permissions

**Comment by koros** [comment]
Hi @pedrolourencoribeiro, 
Are you using an SDK? If so, which one? Based on what you've described, the SDK needs the appropriate permissions for a call to be successful. I doubt there's a workaround on the SDK side.
