### ISSUE TITLE
Error: Cannot find module '../../lib/src/index.js' while running the node sample

### ISSUE THREAD

**Issue by rajivsr23** [microsoftgraph/msgraph-sdk-javascript#173]
I am trying to run the node sample by following the Instructions listed here [https://github.com/microsoftgraph/msgraph-sdk-javascript/tree/dev/samples/node](url)

But I get an error while running the command listed on step 2. ii. **node ./samples/node/main.js** 

The Error Message that I get is "Error: Cannot find module '../../lib/src/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)"

When I check the lib folder, I can't find the src folder or the index.js file. The only file that exists is .npmignore

**Comment by muthurathinam** [comment]
@rajivsr23 You need to run `npm install` and `npm run build` before running the sample. `npm run build` builds the files in the lib folder.
