### ISSUE TITLE
Is it possible to join the meet in my own website?

### ISSUE THREAD

**Issue by ShoshanP** [microsoftgraph/msgraph-sdk-javascript#1735]
i want to embed meet of teams using graph api and client js.
is it possible? how?

**Comment by koros** [comment]
Hi @ShoshanP,

First, you'll need to identify the appropriate API endpoint. You can refer to the [Microsoft Teams API Overview](https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-1.0) for guidance.

Remember, the SDK allows you to call existing APIs. If the API you need isn't available, you'll have to request the Teams team to add it.
