### ISSUE TITLE
How can i upload files from onedrive or sharepoint to my web app

### ISSUE THREAD

**Issue by rachitsakhidas** [microsoftgraph/msgraph-sdk-javascript#174]
Hi,

I want to sync OneDrive or Sharepoint files with my web application.

So how can i import or upload OneDrive or Sharepoint files into my web application ?

So can you suggest what things i need to follow.

Thanks & Regards
Rachit V. Sakhidas

**Comment by muthurathinam** [comment]
As this is not a JS client library issue, so please post such questions in StackOverflow with tags `microsoft-graph` and `microsoft-graph-sdks`.
