### ISSUE TITLE
empty /lib

### ISSUE THREAD

**Issue by dkorobov** [microsoftgraph/msgraph-sdk-javascript#175]
Starting with version 1.5 or so i'm not seeing any file under /lib. documentation seems to suggest that's where the libraries are. What am i missing?

**Comment by muthurathinam** [comment]
Files under `/lib` is present only in the npm package not in the source control.
I can guide you based on your requirement for `lib` folder. let me know why you are looking for?

**Comment by dkorobov** [comment]
gotcha I'll get them from npm then. Thanks.
