### ISSUE TITLE
Where is graph-js-sdk-web.js? 

### ISSUE THREAD

**Issue by tox777** [microsoftgraph/msgraph-sdk-javascript#176]
Hi! I downloaded this project to work on javascript but I can not to locate graph-js-sdk-web.js file.
Where's located?

**Comment by muthurathinam** [comment]
@tox777 You have to run `npm install` and `npm run build` to build the graph-js-sdk-web.js file.
if you require only graph-js-sdk-web.js fille, you can download the same from the [npm package](https://www.npmjs.com/package/@microsoft/microsoft-graph-client) or you can download it from the [CDN](https://unpkg.com/@microsoft/microsoft-graph-client/lib/graph-js-sdk-web.js).
