### ISSUE TITLE
List items request dies somewhere

### ISSUE THREAD

**Issue by latonita** [microsoftgraph/msgraph-sdk-javascript#177]
# Bug Report

## Prerequisites

-   [x ] Can you reproduce the problem?
-   [x ] Are you running the latest version?
-   [x ] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I need to get attributes information from document library items, so i'm trying to get list items of respective list.
Created two simple request in graph explorer:
```
1. https://graph.microsoft.com/v1.0/sites/companyname.sharepoint.com:/sites/EBO:/lists/dceceae4-e812-4246-9ae0-f6f1647575ac
and 
2. https://graph.microsoft.com/v1.0/sites/companyname.sharepoint.com:/sites/EBO:/lists/dceceae4-e812-4246-9ae0-f6f1647575ac/items 
```
Graph explorer works okay, gives me list info and gives me first xxx items and link to next page.

When i'm calling this from nodejs only first request works.
Second request - nothing happens. I neither getting into .then nor into .catch sections.

**Console Errors:** 
no errors in console, i just see full url printed out for this request

## Steps to Reproduce
```
function run() {
    client.api("https://graph.microsoft.com/v1.0/sites/companyname.sharepoint.com:/sites/EBO:/lists/dceceae4-e812-4246-9ae0-f6f1647575ac/items")
        .get()
        .then(res => {
            console.log(res);
        })
        .catch(err => {
            console.log(`ERROR ${err}`);
        });
}
```
**Expected behavior:**
I shall enter either then or catch section to get either results or error

**Actual behavior:**
not then or catch. tried await - didnt help

**Comment by muthurathinam** [comment]
@latonita I am sorry that you have encountered this. Can you help me with the following details ?
* what is the node version that you are using ?
* what is the expected size of the response ? is it greater than 2MB ?
* Can you elaborate what you mean by `When i'm calling this from nodejs only first request works.` ?

**Comment by latonita** [comment]
@muthurathinam 
- nodejs 8.16.0
- good question, looks like its bigger than 2mb
- above i gave two examples: one is to get list info, another to get items from that list. first one works well, second one - dies. 
today i tried to make "raw" request and it works okay, just need to resolve json.

look like request which returns more than 2Mb is not properly resolved if it is not 'raw' request.

**Comment by latonita** [comment]
so now i think it is a duplicate of #169 and can be closed

**Comment by muthurathinam** [comment]
Yeah it sounds like #169. So closing.
