### ISSUE TITLE
Minification causes issues

### ISSUE THREAD

**Issue by WieserSoftware** [microsoftgraph/msgraph-sdk-javascript#180]
# Bug Report
If you try to build a release build of the react sample in Microsoft-graph-toolkit, the minification causes login not to work from this package.  This would be the same with any sample that uses minification of this package.

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Minification causes the use of Object.name to return similar values across the project.  This renders the use of that idiom ineffective.

## Steps to Reproduce

1. Start with Microsoft-graph-toolkit react sample
2. Insert your app Id, and change provider to use msalProvider
3. Try to login.  It won't work.

**Expected behavior:** It should work.

**Actual behavior:** The minified version uses the AuthenticationProviderOptions as a TelemetryHandlerOptions.

## Additional context

None

**Comment by muthurathinam** [comment]
@WieserSoftware Thanks for reporting will look into issue and your PR.

**Comment by muthurathinam** [comment]
Fix is released in [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0-Preview.2) preivew.

**Comment by muthurathinam** [comment]
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0
