### ISSUE TITLE
calenderview api call times out

### ISSUE THREAD

**Issue by markg85** [microsoftgraph/msgraph-sdk-javascript#186]
Hi,

My exact API call is:
```const data = await client.api(`/me/calendarview?StartDateTime=${moment().toISOString()}&EndDateTime=${moment().add(7, 'days').toISOString()}`).get()```

Here `client` is the return of `graph.Client.init` and graph is:
`let graph = require('@microsoft/microsoft-graph-client');`

`moment` is obviously moment.js :)

Now if i do an API call like "/me/events" i just get events. But they seem lacking as not all recurrent events are in there (i'm new to this API, i have no clue why they are missing), but calling `calenderview` seems to be the recommended way to get a list of events that you would also see in your actual calendar. Which is why i'm trying that. That API call requires you to set the date range so therefore you see those two dates in the call url.

I'm sure i'm doing "something" wrong in that call, but i'm not getting the output to even know what that might be (it just times out). I hope some of you can help me here.

Regards,
Mark

**Comment by markg85** [comment]
I might have solved this myself...
So i did find some places that use `/me/calendarview`, but the official documentation uses `/me/calendar/calendarView`. I don't know why that is done, specially since both work! Anyhow, i picked the one from the documentation (thus /me/calendar/calendarView)

That didn't fix it yet though.
Apparently there were a few calendar events with a lot of possible people to attend. Here i again don't know if that maters, but limiting the output to: `.select(['categories', 'start', 'end', 'subject'])` did make it work for me.

I'ill leave it open, just curious if there is an explanation for the above. But feel free to close it.

**Comment by muthurathinam** [comment]
Basically its the design of the API. Refer these comments https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/155#issuecomment-481562072 and https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/155#issuecomment-481562924
