### ISSUE TITLE
ReferenceError: Request is not defined

### ISSUE THREAD

**Issue by dejue** [microsoftgraph/msgraph-sdk-javascript#189]
## Description
When using the MS Graph Client Library v1.7.0, we're not seeing any request being sent to https://graph.microsoft.com/v1.0/me.

We're doing the following: 
1. We downloaded [sample code](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/24.bot-authentication-msgraph).
2. We installed npm packages
3. We updated the MS App ID, MS App Password, and the Connection Name in the .env file
4. We ran the code locally

**Expected behavior:** 
When sending "me", we expect to see a call being made out to the Graph API to retrieve the information we're seeing at the [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).

**Actual behavior:** 
When sending "me", we are going to GraphRequest.prototype.get which is then calling GraphRequest.prototype.send and finally returning to HTTPClient.prototype.sendRequest. However, when looking through Fiddler, we're not seeing any request being made to https://graph.microsoft.com/v1.0/me and we're getting a ReferenceError: Request is not defined exception at tslib.js.

\node_modules\@microsoft\microsoft-graph-client\lib\src\GraphRequest.js
![image](https://user-images.githubusercontent.com/38996171/59231915-f653d800-8ba7-11e9-9460-b30a59719c8f.png)
![image](https://user-images.githubusercontent.com/38996171/59232178-fd2f1a80-8ba8-11e9-8532-bff24d682bf2.png)

Once we enter the GraphRequest.prototype.send method, this fails immediately and complains about the request object. From the comments, we know that the request is a request USL string or the request object value. From live debugging, the request is passing in "https://graph.microsoft.com/v1.0/me". Why is this URL not accepted here?

**Comment by muthurathinam** [comment]
@dejue This issue is fixed in the version 1.7.0. My guess is that it should be a problem of node_modules cache. Can you delete `node_modules` and `package-lock.json` in the same sample code and reinstall using `npm install` and try making request once more?

**Comment by dejue** [comment]
@muthurathinam After trying this twice, it looks like I'm running into the same error described above. I believe I am using the correct dependency version: 
    "dependencies": {
        "@microsoft/microsoft-graph-client": "^1.7.0",

**Comment by muthurathinam** [comment]
@dejue How to debug this scenario? When I login from the emulator the popup appears and disappears after few seconds. it doesn't show any indication that it is signed in. When I send a `me` message after that it doesn't show reply anything. Need your help on this.

**Comment by muthurathinam** [comment]
Fixed in the latest preview version of the library 2.0.0-Preview.4.
