### ISSUE TITLE
Angular app does not work on IE11 after installing microsoft-graph-client package

### ISSUE THREAD

**Issue by vivekdevaraju** [microsoftgraph/msgraph-sdk-javascript#190]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
Yes
-   [x] Are you running the latest version?

Yes
-   [x] Are you reporting to the correct repository?
Yes
-   [x] Did you perform a cursory search?
Yes
For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]
Angular App 
Version : 7.1.3

Not working on IE11, please find the below error.

Added Polyfills for IE and Targeted to ES5

**Console Errors:** [Is there any console error]
![image](https://user-images.githubusercontent.com/28860996/59357688-e6272e80-8d48-11e9-9554-28bab70904a5.png)

![image](https://user-images.githubusercontent.com/28860996/59357765-0b1ba180-8d49-11e9-98fc-c2aa8ea839f0.png)

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Additional context

Add any other context about the problem here..

**Comment by muthurathinam** [comment]
@vivekdevaraju 
`Added Polyfills for IE and Targeted to ES5`
Can you explain me or post how you target to ES5 ?

**Comment by arunprasathv** [comment]
@muthurathinam Im also getting this error ? is it possible to call the graph api directly without using the library ? 

my polyfills.ts 

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
//import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';
import 'zone.js/dist/zone';  // Included with Angular CLI.

**Comment by muthurathinam** [comment]
@arunprasathv Sorry for the delay in the response.
* What is the library version that you are using ?
* Your screenshot shows that your vendor.js code contains classes in it? did you verify that your build process actually transpiled the sdk to es5 ?

**Comment by arunprasathv** [comment]
Your screenshot shows that your vendor.js code contains classes in it? did you verify that your build process actually transpiled the sdk to es5 ?

How do I verify that? I've given you the tsconfig.json , is that what you meant by verifying? 

I  just do -  ng build  --prod 

If the library isn't working , how can i call graph api ? when i do http get , i was getting below error,

Error: InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217.

Code:

const headers = new HttpHeaders().set('Authorization', 'Bearer ' + token );

    console.log('header ' + JSON.stringify(headers));
    this.getData('https://graph.microsoft.com/v1.0/me/', headers).subscribe(data =>  {
            console.log( 'reeeees ' + data);
    });

**Comment by muthurathinam** [comment]
> How do I verify that? I've given you the tsconfig.json , is that what you meant by verifying?

From your screenshot I believe you are using the es6 folder in the library. I am just wondering did you do any transpiling for vendor files from es6 to es5 ? Do you have any build configuration file to do that ?

> If the library isn't working , how can i call graph api ? when i do http get , i was getting below error

The example snippet that you have shown is not specific to this library.

```
this.getData('https://graph.microsoft.com/v1.0/me/', headers).subscribe(data =>  {
        console.log( 'reeeees ' + data);
});
```

I don't understand the above piece of code that you have posted. Can you explain me that that `getData` and `subscribe` does ?

**Comment by arunprasathv** [comment]
I just did npm install and started using the library, this is what I have in node modules. 

![image](https://user-images.githubusercontent.com/7142390/60186426-b9b7eb80-97f9-11e9-94b2-3f86a7f4661d.png)

yes, i want to call graph api as any other api using http get.  I'm trying to make a get call to talk to graph api. did you try to make a get call to the graph api from angular ? any simple demo ? 

  public getData(serviceUrl: string, headers?: HttpHeaders): Observable<any> {
      CommonUtil.log(
            'Invoking getData() HTTP GET network service call for [ serviceUrl = %o ] and [ options = %o ]',
        serviceUrl,
        headers
      );

      if (CommonUtil.isNull(headers)) {
        headers = new HttpHeaders().set('Content-Type', 'application/json'); }

     return this.http
       .get(serviceUrl, { headers })
            .map(this.extractData)
            .catch((err, caught) => {
                this.handleRestServiceError(err, serviceUrl);
                return Observable.throw(err + '==>' + serviceUrl);
            }
        );
    }

**Comment by muthurathinam** [comment]
Correct me if I am wrong. You are making direct call to the graph service. So if this is the case then you don't require this library to make such call.

**Comment by arunprasathv** [comment]
I'm trying to make a call to graph API without using a library. Since the library isn't working in IE 11, im taking this approach. So im trying two different things here, 1. making library to work 2. call graph api from the code like anyother API.

**Comment by arunprasathv** [comment]
@muthurathinam Could you please tell me how to make it working in IE11.

**Comment by muthurathinam** [comment]
@arunprasathv
Follow these steps:
1. Install the latest preview of the library (which is light weight) with `npm install -S @microsoft/microsoft-graph-client@Preview` to install the latest preview version of v2.0
2. Use the [README.md](https://github.com/microsoftgraph/msgraph-sdk-javascript#installation) as your reference guide to initialize and make requests.
3. If you are using the es version of the library (it seems you are, I can see this from your attachment. i.e your vender.js file is not transpiled properly) transpile the code to es5 in your building system. (Just transpiling will not make your code work in IE). you have to add the necessary polyfills. (Refer [this](https://hackernoon.com/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423) document to understand the difference between transpiling and polyfilling)

**Comment by arunprasathv** [comment]
does the preview has the fix for IE 11?

**Comment by muthurathinam** [comment]
Actually the reason for SDK not working in IE11 is that your building process need to transpile the vendor js file to es5. Refer [this](https://hackernoon.com/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423) document to understand the difference between transpiling and polyfilling.

The preview doesn't have the fix for your issue. It does have improved compilation process to transpile and bundle library which eases the integration for IE11.

**Comment by arunprasathv** [comment]
Do you have any sample that works in IE11 , I think that would help better. my  tsconfig is targetting to es5.

why can't i call graph api myself as this is just a get call.

**Comment by arunprasathv** [comment]
@muthurathinam Could you please provide an update on IE 11 example.

**Comment by arunprasathv** [comment]
@muthurathinam @yinaa 
Team,

In general, having an ES6 code published to npm is a very bad practice and should be avoided at all costs.  Could you please fix this and publish it to npm. 

Thanks
Arun

**Comment by muthurathinam** [comment]
@arunprasathv The library is shipped with both **es5** and **es6** code. The main reason for this is to fulfill the need of users based on their requirement. If your requirement is to directly use the **es5** code then stick to using es5 instead of es6.

**Comment by arunprasathv** [comment]
@muthurathinam I'm consuming 15 different libraries and never had this issue. Not sure why this library is special.  Could you please fix IE11 issue that we are reporting. looks like we won't get the fix anytime soon.. Please let me know when this can be fixed. 

To your other comment, (since the library isn't working in IE11) I'm trying this approach

Correct me if I am wrong. You are making direct call to the graph service. So if this is the case then you don't require this library to make such call.

Yes, I try to make an API call but  it always fails with the below error though i pass an valid token. 

Error: InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217.

**Comment by muthurathinam** [comment]
> ERROR Error: Uncaught (in promise): PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.PolyFillNotAvailable: Library cannot function without fetch. So, please provide polyfill for it.

The library depends on Promise and fetch, in case if your your environment doesn't have support for fetch and promise you need to polyfill them. In your case IE doesn't have support for both, so you have to polyfill them. Refer [installation](https://github.com/microsoftgraph/msgraph-sdk-javascript#installation) section in the readme page of the library.

>ERROR Error: Uncaught (in promise): ReferenceError: regeneratorRuntime is not defined
ReferenceError: regeneratorRuntime is not defined

This error is associated with your polyfilling. Refer (this](https://github.com/babel/babel/issues/5085)

**Comment by muthurathinam** [comment]
> Error: InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217.

Refer [this](https://github.com/OfficeDev/outlook-dev-docs/issues/508#issuecomment-459720747) issue thread.

**Comment by arunprasathv** [comment]
I solved my problem without using the library by making calls directly.   Thanks!.

**Comment by malinkody** [comment]
I had the same issue. According to the docs:

 `import { Client } from "@microsoft/microsoft-graph-client";` is meant for the node environment

and

`const Client = MicrosoftGraph.Client;` is meant for browser usecases. 

This doesn't help if you want to use npm and types provided by "@microsoft/microsoft-graph-client" in a typescript build for browsers and **_not a script tag_**. 

After some experimentation I found the **_answer_**:

`import { Client, ImplicitMSALAuthenticationProvider, MSALAuthenticationProviderOptions } from "@microsoft/microsoft-graph-client/lib/src/browser";`

This solved the IE11 issues for my usecase. I am unsure if this is the intended way of importing the browser sdk, but it works.
