### ISSUE TITLE
I made Office Onenote addin with React, but dont connection graph server.

### ISSUE THREAD

**Issue by nakawankuma** [microsoftgraph/msgraph-sdk-javascript#192]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]
```javascript
 async getSchedule(){
  const msal= this.state.msal;
  const acc=msal.getAccount();
  console.log(acc);

  const scope = ["user.read"];
  const loginRequest = {
    scopes: scope//, "mail.send"] // optional Array<string>,
  };
  // msal.acquireTokenPopup(loginRequest).then(async function (tokenResponse) {
  const authProvider = new MSALAuthenticationProvider(msal, scope);
  const options = {
    authProvider, // An instance created from previous step
  };
  const client = Client.initWithMiddleware(options);
  try {
    let userDetails = await client.api("/me").get();
    console.log(userDetails);
  } catch (error) {
    throw error;
  }

```

I got acquiring token other button(this.state.masl).
I took getAccount data correctly.

But client.api.get() is not http request.
I don't take Promise result.

I'm not convinced that this is a bug.
What's going on?

**Comment by muthurathinam** [comment]
@nakawankuma I believe you have initialized the msal instance like [this](https://github.com/microsoftgraph/msgraph-sdk-javascript#creating-an-instance-of-msalauthenticationprovider-in-browser-environment). 

Can you post in any errors that you got while making request ?
```
But client.api.get() is not http request.
I don't take Promise result.
```
I don't understand this part. can you elaborate this ?

**Comment by muthurathinam** [comment]
Closing the issue as there is no response from the user. @nakawankuma Please reopen if necessary.
