### ISSUE TITLE
InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by arunprasathv** [microsoftgraph/msgraph-sdk-javascript#194]
@dylank @muthurathinam  
Want to call Graph API from Angular, but getting the error CompactToken parsing .    Im calling it without using the library since  Graph Library is not working in IE 11. Getting syntax error at Client.ts so trying to call the api directly.

Error: InvalidAuthenticationToken: CompactToken parsing failed with error code: 80049217. 
Code: 
          const headers =  new HttpHeaders().set('Authorization', 'Bearer ' + token );

        console.log('header ' + JSON.stringify(headers));
        this.getData('https://graph.microsoft.com/v1.0/me/', headers).subscribe(data =>  {
                console.log( 'reeeees ' + data);
        });

Library Error

![image](https://user-images.githubusercontent.com/7142390/59738611-d2d7ff80-922f-11e9-9398-387247ec6aa6.png)

Could you please help with the fix.

**Comment by arunprasathv** [comment]
@muthurathinam @dylank  Could you please provide an update on this ?

**Comment by muthurathinam** [comment]
Classes are not supported in IE11. @arunprasathv did you verify that transpiled your vendor.js to es5 ?
