### ISSUE TITLE
Problem with downloading a file from OneDrive

### ISSUE THREAD

**Issue by coloeus** [microsoftgraph/msgraph-sdk-javascript#195]
I'm trying to download a file but instead of the actual size of around 100mb file I only get a 32kb file and no error shows up.

Already tried to download the file by path but got the same result.
```
async function testDownload(client: Client, name: string) {
    const id = await OneDriveManager.findIdOfFileByName(client, name);
    console.log(id); // the id is logged correctly
    client.api('/me/drive/items/' + id + '/content')
        .getStream() //Eg: test.pdf
        .then((stream) => {
            let writeStream = fs.createWriteStream('D:\\testDownload\\' + id); // Eg: test.pdf
            stream.pipe(writeStream).on("error", (err: Error) => {
                console.log(err);
                throw err;
            });
            writeStream.on("finish", () => {
                console.log("Downloaded");
            });
            writeStream.on("error", (err: Error) => {
                throw err;
            });
        })
        .catch((error) => {
            console.log(error);
        });

}
```

```
testDownload(client, 'test.bin')
    .then();
```
 
[AB#7542](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7542)

**Comment by muthurathinam** [comment]
@coloeus Sorry that you have encountered this. can you help me with the following details to debug ?
* What is the version of the library that you are using ?
* Is your item id is valid ?

Actually its not reproducible at my end ? can you share me the exact environment that you are getting this error ? like version of the nodejs if you are running the code in nodejs.

**Comment by coloeus** [comment]
> What is the version of the library that you are using ?

I tried it with 1.6.0 and 1.7.0

> Is your item id is valid ?

Yes

I changed my code for testing so it matches the example written here:
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/Actions.md#getstream

I'm using Typescript 3.4.5 and Node v10.15.3

My complete transpiled code is this:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const microsoft_graph_client_1 = require("@microsoft/microsoft-graph-client");
const MyAuthenticationProvider_1 = require("./MyAuthenticationProvider");
const fs = require("fs");
const clientOptions = {
    // MyCustomAuthenticationProvider is the user's own authentication provider implementing AuthenticationProvider interface
    authProvider: new MyAuthenticationProvider_1.MyAuthenticationProvider(),
};
const client = microsoft_graph_client_1.Client.initWithMiddleware(clientOptions);
client
    .api("/me/drive/root/children/ubuntu-mate-18.04.2-desktop-amd64.iso/content")
    .getStream() //Eg: test.pdf
    .then((stream) => {
    let writeStream = fs.createWriteStream("D:\\ubuntu-mate-18.04.2-desktop-amd64.iso"); // Eg: test.pdf
    stream.pipe(writeStream).on("error", (err) => {
        throw err;
    });
    writeStream.on("finish", () => {
        console.log("Downloaded");
    });
    writeStream.on("error", (err) => {
        throw err;
    });
})
    .catch((error) => {
    throw error;
});

```
The file at the path exists.

If I'm changing "/me/drive/root/children/ubuntu-mate-18.04.2-desktop-amd64.iso/content" to 
"/me/drive/root/children/ubuntu-mate-18.04.2-desktop-amd64.iso"
a to 2kb file which is the .json representation of the file is downloaded and the "finish" event is thrown.

**Comment by muthurathinam** [comment]
@coloeus All your details aligns with mine. Did you try downloading the other files ? Just wanted to know whether this is happening only for that particular file.

**Comment by coloeus** [comment]
@muthurathinam 
Yes, I tried different files with different locations but always with the same result.

**Comment by muthurathinam** [comment]
> If I'm changing "/me/drive/root/children/ubuntu-mate-18.04.2-desktop-amd64.iso/content" to
"/me/drive/root/children/ubuntu-mate-18.04.2-desktop-amd64.iso"
a 2kb file which is the .json representation of the file is downloaded and the "finish" event is thrown.

Yes, making request without `/content` will bring back the details about the file in json format.

Downloading large file over 1GB results same for me. We might have to understand the proper way to download the large files. @ificator do we have to download such files as chunks? any reference document  on how to download large files would be much helpful.

**Comment by ificator** [comment]
There's nothing special when it comes to downloading - we'll return the entire fire by default, but support the `Range` header for partial content. I cannot think of a service side reason for only getting 32KiB back..

**Comment by muthurathinam** [comment]
@ificator Thanks for the info. @coloeus will investigate more into this issue.

**Comment by nikithauc** [comment]
Cannot reproduce this issue.
