### ISSUE TITLE
Token Refresh Failing Silently - Causing CompactToken parsing failed with error code: 80049217

### ISSUE THREAD

**Issue by NoPhaseNoKill** [microsoftgraph/msgraph-sdk-javascript#198]
# Bug Report
-   [N ] Can you reproduce the problem?
-   [2.0.0-Preview.1] Are you running the latest version?
-   [Y ] Are you reporting to the correct repository?
-   [N ] Did you perform a cursory search?

## Description

Intermittent issue. After a certain amount of time, it looks like the auth token is expiring. However, when the token has expired, it is still trying to silently log-in, and not prompting user to re-log and/or refresh the token. Error being returned to error token: AADSTS50058: A silent sign-in request was sent but no user is signed in.

This means that when that same user goes to make a request to any graph endpoint, they get 403: CompactToken parsing failed with error code: 80049217.

Request header when 403 error comes contains: Bearer undefined - indicating that the issue stems from the failed refresh/not prompting user to re-auth - with this end error message being the result.

**Console Errors:** 
403: CompactToken parsing failed with error code: 80049217

**Expected behavior:** [What you expected to happen]
Expect user to be prompted to re-auth/log-in after token expires.
**Actual behavior:** [What actually happened]
Does not prompt user to re-auth or log-in, and fails auth silently.

edit: clarity.

**Comment by muthurathinam** [comment]
@NoPhaseNoKill Can try the new preview version `i.e Preview.4` and let me know were you getting the same error. Basically this preview is rolled out with bug fixing the possibility of returning `undefined` value in auth provider this could possibly be a reason for the above issue.
To install latest preview version use `npm install @microsoft/microsoft-graph-client@Preview`.

**Comment by muthurathinam** [comment]
Published stable release for the same
https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0
