### ISSUE TITLE
Improve downloading chat message attachments

### ISSUE THREAD

**Issue by kaaloo** [microsoftgraph/msgraph-sdk-javascript#200]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When using the list chat messages api `/teams/{id}/channels/{id}/messages` each chat message has an `attachments` property where each attachment can contain a `contentUrl` when the `contentType` is `reference` as below:

```
{
    "id": "a8736182-1fce-465b-bc02-a6de87706e89",
    "contentType": "reference",
    "contentUrl": "https://xyz-my.sharepoint.com/personal/xyz_onmicrosoft_com/Documents/Microsoft Teams Chat Files/document.pdf",
    "content": null,
    "name": "document.pdf",
    "thumbnailUrl": null
}
```

Using the graphClient to download the attachment using `contentUrl` returns a 401 status code.  Unlike drive item content urls which can be obtained by calling the content api `/drives/{drive-id}/items/{item-id}/content`, the attachment content urls don't carry a `uniqueId` query parameter which presumably allows (in my case) graphClient to get the content at the xyz-my.sharepoint.com endpoint without authentication.

It is possible but awkward to get the attachment content by using the drive item download file api because the attachment's drive item id is not present in the attachment structure.  There is an attachment id, but it's just a UUID and can't be used for this purpose.

It would be great to have a `@microsoft.graph.downloadUrl` property in the chat message attachment that could be used to download the attachment content without authentication.

## Steps to Reproduce

Make sure you have a Teams chat message with an pdf attachment.

1. List chats using /me/chats and get the relevant chat id
2. List chat messages using /chats/{chat-id}/messages
3. Find chat message with attachment your are testing and find the pdf attachment.
4. Attempt to download attachment using it's `contentUrl`, for instance:

```
try {
  const result = await graphClient.api(contentUrl)
      .responseType(ResponseType.ARRAYBUFFER)
      .get();
  return result;
} catch (err) {
  console.log(`Cannot get content: ${contentUrl}.`);
  throw err;
}
```

**Expected behavior:** `result` should be an array buffer with the attachment content.

**Actual behavior:** error is thrown with statusCode 401.

**Comment by kaaloo** [comment]
I ended up using the following workaround to construct a url which will return an object with a `@microsoft.graph.downloadUrl`  that can then be used to download the content as above.

```
function getDownloadUrl(attachment: ChatMessageAttachment, team?: Team): string {
  const url = new URL(attachment.contentUrl as string);
  const path = url.pathname.split('/').slice(4).join('/');
  if (team) {
    return `/groups/${team.id}/drive/root:/${path}`;
  } else {
    return `/me/drive/root:/${path}`;
  }
}
```

It's a hack and I'm not sure how stable this mapping will be moving forward.  It would be great to have native support for a `@microsoft.graph.downloadUrl` property in chat message attachments.

**Comment by muthurathinam** [comment]
Hi @kaaloo , Thanks you for the ask but unfortunately the ask cannot be fulfilled from the SDK end. Can you please post the question in StackOverflow with the tag microsoft-graph so that the Graph Service team will respond.

**Comment by kaaloo** [comment]
Sure, I posted my question here:

https://stackoverflow.com/questions/57036458/how-to-download-teams-chat-message-attachments-using-the-microsoft-graph-beta-ap

**Comment by ashishtank** [comment]
@kaaloo Thanks a lot for work around. I have search a lot but could not find realiable way to download the files. Your work around seems will work for me.

**Comment by jamie-everlaw** [comment]
I've submitted a feature request for this [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-downloadurl-to-teams-chatmessageattachment/idi-p/3766995#M1656)

For anyone still needing a workaround, I've found that kaaloo's doesn't always work. User's can attach files from their personal OneDrive in channel messages and can attach file from any site drive to any chat or channel if they have a shortcut to the site drive in their personal OneDrive.

AFAICT, a "complete" workaround seems to be building a map from drive URLs to drive IDs, then splitting `contentUrl` into the drive URL and file path. Drive ID and file path is one of the options to get a `driveItem`. https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http#http-request

You can build the map by listing all sites, then for each site, listing its drives. This doesn't include sites created for private channels, however, so you also need to get all teams, for each team, get all private channels, then for each channel [get its file folder](https://learn.microsoft.com/en-us/graph/api/channel-get-filesfolder?view=graph-rest-1.0&tabs=http)

**Comment by yusufkhan07** [comment]
I can download the file using the "contentUrl" in a browser, but when I try the same URL in Postman, I get a 403 error. If I use the Access Token from the Graph SDK, I get a 401 error instead. Why can I download the file in the browser, but not in Postman?
