### ISSUE TITLE
downloadUrl not in the properties of driveItem when using search

### ISSUE THREAD

**Issue by jelohipolitocruz** [microsoftgraph/msgraph-sdk-javascript#201]
# Bug Report

## Prerequisites

-   [X ] Can you reproduce the problem?
-   [ ] Are you running the latest version?
-   [ ] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Using search parameter to get drive items

**Console Errors:** No console errors

**Screenshots:** 
https://graph.microsoft.com/v1.0/sites/{site-id}/drive/root/search(q='')?$select=id,name,file,folder,size,lastModifiedDateTime,@microsoft.graph.downloadUrl
![image](https://user-images.githubusercontent.com/18521848/61203328-59c2af80-a6ea-11e9-88df-2fad4750471b.png)

## Steps to Reproduce

1. Use the search query to get driveItems
2. Check if there is a @microsoft.graph.downloadUrl data

**Expected behavior:** There should be a @microsoft.graph.downloadUrl

**Actual behavior:** It doesn't have the downloadUrl, or maybe I'm missing something

## Additional context

Add any other context about the problem here..

**Comment by krototype** [comment]
@jelohipolitocruz it looks like this feature is not supported by the API, so it doesn't seem to be an SDK issue.
You can post the same query on stackoverflow with the tag microsoft-graph for this purpose.
