### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by aslanovsergey** [microsoftgraph/msgraph-sdk-javascript#203]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description
`
import { ImplicitMSALAuthenticationProvider } from "./node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";`

Doesn't work

Also what library MicrosoftGraph class is part of? 

> const options = new **MicrosoftGraph**.MSALAuthenticationProviderOptions(graphScopes);
> const authProvider = new **MicrosoftGraph**.ImplicitMSALAuthenticationProvider(msalApplication, options);

**Comment by muthurathinam** [comment]
Hi @aslanovsergey Can you help with the following information ?
1. what is the version of the library that you are using?
>import { ImplicitMSALAuthenticationProvider } from "./node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";

2. Can you verify that your node_modules and your source file in which you are importing are in the same directory?

> Also what library MicrosoftGraph class is part of?

This is a global object of the library, in case if you are using the library in browser by including the minified file of the library in html file.

**Comment by aslanovsergey** [comment]
- 1.7.0
- Yes, src and node_modules have the same parent folder (my project's folder)
- I'm going to use this library in browser but I use npm package import instead of add script tag to add library on the page

**Comment by eredisg** [comment]
Hello, I am getting the same issue when attempting to import **ImplicitMSALAuthenticationProvider**. 

@microsoft/microsoft-graph-client version: 1.7.0
msal version: ^1.0.0

I get the following error: 
> Error: Cannot find module './node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider'

**Comment by aslanovsergey** [comment]
@eredisg because we are looking at the docs for version 2, switch release to 1.7 and you will find answer https://github.com/microsoftgraph/msgraph-sdk-javascript/tree/1.7.0

**Comment by rogercodes1** [comment]
This is still a recurring issue on 2.0 or 1.7. 
`Cannot find module './node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider'.`

**Comment by malinkody** [comment]
You can use [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/190#issuecomment-580765040) answer if you are trying to import classes from the sdk-client in a typescript environment targeted for browsers.

`import { Client, ImplicitMSALAuthenticationProvider, MSALAuthenticationProviderOptions } from "@microsoft/microsoft-graph-client/lib/src/browser";`
