### ISSUE TITLE
Missing Changelog Updates

### ISSUE THREAD

**Issue by MarkHerhold** [microsoftgraph/msgraph-sdk-javascript#205]
I can't find the summary of changes for `@microsoft/microsoft-graph-client@1.7.0`.
Could the changelog be updated for those of us that are upgrading? Thanks!

**Comment by muthurathinam** [comment]
@MarkHerhold Refer the releases section for the change log. https://github.com/microsoftgraph/msgraph-sdk-javascript/releases
