### ISSUE TITLE
Msgraph client fails silently when getting schedule for more than one email

### ISSUE THREAD

**Issue by sajangurung** [microsoftgraph/msgraph-sdk-javascript#215]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

getSchedule fails when queried with schedules greater than one

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Make a graph query using more than one schedules (emails).

**Expected behavior:** Get valid response

**Actual behavior:** Fails silently.

## Additional context

Gets response with this request
`const params = {
                Schedules: ['correct.email1@example.com'],
                StartTime: {
                    dateTime: '2019-07-31T14:00:00Z',
                    timeZone: 'UTC'
                },
                EndTime: {
                    dateTime: '2019-08-31T13:59:59Z',
                    timeZone: 'UTC'
                },
                availabilityViewInterval: 15
            };`

Fails silently with this
`const params = {
                Schedules: ['correct.email1@example.com', 'correct.email2@example.com'],
                StartTime: {
                    dateTime: '2019-07-31T14:00:00Z',
                    timeZone: 'UTC'
                },
                EndTime: {
                    dateTime: '2019-08-31T13:59:59Z',
                    timeZone: 'UTC'
                },
                availabilityViewInterval: 15
            };`

**Comment by sajangurung** [comment]
To provide some context to above, 
NodeJs version: 8.10
Permission Type: Application (not tried with Delegated)
Url: /users/{id|userPrincipalName}/calendar/getSchedule where id used is the first email in Schedules

**Comment by krototype** [comment]
We are looking into this issue

**Comment by sajangurung** [comment]
Currently waiting on this issue. As a workaround, I've decided to use the direct http endpoint but would appreciate a proper solution in the client itself.

**Comment by krototype** [comment]
@sajangurung 
If you are using the stable version, try to use the current Preview Version as it has some fixes (there won't be any breaking change).
Please provide the exact code that you are using.
What is the exact response(if any) that you are getting?
_(we are planning for a stable release in the near future)_
