### ISSUE TITLE
Consistently getting -1 statusCode with "Failed to fetch" message

### ISSUE THREAD

**Issue by etyp** [microsoftgraph/msgraph-sdk-javascript#222]
# Bug Report

## Prerequisites

-   [ ] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

We're using Graph for Mail.Send and Mail.ReadWrite and keep consistently seeing users getting cryptic error messages in our error monitoring system. They'll often make a bunch of requests with no issue, but eventually we see the errors from API calls which have a statusCode of -1 and message of "Failed to fetch".

**Console Errors:**

We see the same error across the following API calls:
https://graph.microsoft.com/v1.0/me/messages
https://graph.microsoft.com/v1.0/me/mailFolders
https://graph.microsoft.com/v1.0/me/mailFolders/{folderId}/messages

The error looks like:
```
{
body: TypeError: Failed to fetch, 
code: TypeError, 
date: 2019-08-24T19:09:54.758Z, 
message: Failed to fetch, 
requestId: None, 
statusCode: -1
}
```

## Steps to Reproduce

We're unable to reproduce the issue, but we see it happening very consistently across a lot of our customer accounts. We've invested a lot of time attempting to reproduce but have had no luck.

## Usage Information

SDK Version - 1.7.0

-   [ ] Node

> Node Version - N/A

-   [x] Browser

> Browser Name - We've seen it happen on Chrome, Safari, Mobile Safari, IE, Edge. Does not seem browser-related.

> Version - Chrome 76, Safari 12.1.2, IE 11, Edge 17.17134

**Comment by krototype** [comment]
Are you setting any particular ResponseType in your code?

**Comment by krototype** [comment]
@etyp this seems to be an error due to the Network issues, if we have a raw responseType, we just return the response that we get from the service.

**Comment by krototype** [comment]
Closing this issue, for now, feel free to open this, if needed.
