### ISSUE TITLE
Incorrect redirect (or missing file) in the unpkg.com cdn. 

### ISSUE THREAD

**Issue by CrushYar** [microsoftgraph/msgraph-sdk-javascript#224]
# Bug Report

https://unpkg.com/@microsoft/microsoft-graph-client/lib/graph-js-sdk-web.js 
redirects to the missing
https://unpkg.com/@microsoft/microsoft-graph-client@2.0.0/lib/graph-js-sdk-web.js

## Prerequisites

-   [v ] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [v ] Are you reporting to the correct repository?
-   [v] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

In our project we did used url 
https://unpkg.com/@microsoft/microsoft-graph-client/lib/graph-js-sdk-web.js
to load MS Graph js API library  .
Last week it started redirect (302) to the 
https://unpkg.com/@microsoft/microsoft-graph-client@2.0.0/lib/graph-js-sdk-web.js

But this url return 404. Therefore our application fail to load library and can not work. 

We know that CDN was changed for 2.0 version. But what about applications whio uses old url with old cdn? 
We expect correct redirect at least. 

## Steps to Reproduce

1. Open https://unpkg.com/@microsoft/microsoft-graph-client/lib/graph-js-sdk-web.js 
 in browser
2. Check response.

**Expected behavior:** [What you expected to happen]
Expect library to load . 2.0 or 1.7 version should be loaded. 

**Actual behavior:** [What actually happened]
Library is not loaded, 404 error returned.

**Comment by darrelmiller** [comment]
There was a rename of the package file during the 2.0 release.  It is now called `https://unpkg.com/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js`  We documented this in the release [blog post](https://developer.microsoft.com/en-us/graph/blogs/microsoft-graph-sdk-for-javascript-2-0-0/) and in the [release notes](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/2.0.0).  Sorry for the inconvenience.
