### ISSUE TITLE
Office 365 - not able to access user calendar availablity 

### ISSUE THREAD

**Issue by praveenp2** [microsoftgraph/msgraph-sdk-javascript#228]
# Bug Report

## Prerequisites

-   [ ] Can you reproduce the problem? Yes
-   [ ] Are you running the latest version? Yes
-   [ ] Are you reporting to the correct repository? Yes
-   [ ] Did you perform a cursory search? Yes

For more information, see the `CONTRIBUTING` guide.

We have integrated office 365 and accessing user's calendar using below graph api.
https://graph.microsoft.com/v1.0/users/XXXX/calendarView?$select=start,end&startDateTime=2019-09-16T04:00:00.000Z&endDateTime=2019-09-20T04:00:00.000Z

We are seeing below issues and not clear on permission. our application uses below scopes
  SCOPES: ['openid https://graph.microsoft.com/calendars.read https://graph.microsoft.com/calendars.readwrite \
            https://graph.microsoft.com/calendars.read.shared https://graph.microsoft.com/calendars.readwrite.shared \
            https://graph.microsoft.com/User.Read https://graph.microsoft.com/Mail.Send']
{
	"error": {
		"statusCode": 404,
		"code": null,
		"message": null,
		"requestId": null,
		"date": "2019-09-13T12:52:25.624Z",
		"body": "{\r\n  \"error\": {\r\n    \"code\": \"ErrorItemNotFound\",\r\n    \"message\": \"The specified object was not found in the store.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"5b828e7a-9192-454a-b4cf-2c8bac064ce9\",\r\n      \"date\": \"2019-09-13T12:52:25\"\r\n    }\r\n  }\r\n}"
	}
}

{
	"error": {
		"statusCode": 403,
		"code": null,
		"message": null,
		"requestId": null,
		"date": "2019-09-12T21:37:33.254Z",
		"body": "{\r\n  \"error\": {\r\n    \"code\": \"ErrorAccessDenied\",\r\n    \"message\": \"Access is denied. Check credentials and try again.\",\r\n    \"innerError\": {\r\n      \"request-id\": \"2958d15e-85da-4400-89e6-c80443c9fd1f\",\r\n      \"date\": \"2019-09-12T21:37:33\"\r\n    }\r\n  }\r\n}"
	}
}

**Comment by praveenp2** [comment]
[https://docs.microsoft.com/en-us/graph/api/user-list-calendarview?view=graph-rest-1.0&tabs=http](url)

**Comment by krototype** [comment]
@praveenp2 
The 404 error can be due to the user not found (maybe invalid userId) / resource not found error.
The 403 is due to Access Denied issue.

If you still face such kind of error even after verifying such cases or face any other error, feel free to report.

**Comment by MIchaelMainer** [comment]
Are you using this client library? 
Is this issue occurring on all users all of the time? 
Are you using delegated or application permissions?

**Comment by praveenp2** [comment]
> Are you using this client library? Yes
> Is this issue occurring on all users all of the time? No, some users.
> Are you using delegated or application permissions? Delegated permission.

**Comment by SKumarSpace** [comment]
Is there an update to this? I am also seeing this issue.

**Comment by ddyett** [comment]
issue is a limitation of the service so closing as we cannot address.
