### ISSUE TITLE
ImplicitMSALAuthenticationProvider is not exported in index.js

### ISSUE THREAD

**Issue by darrelmiller** [microsoftgraph/msgraph-sdk-javascript#230]
We should add this file to the list of files we export.

Currently you need to export the file explicitly like this:

```js
import { ImplicitMSALAuthenticationProvider }  from "@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";

```

Ideally we should be able to do

```js
import * as MicrosoftGraph from "@microsoft/microsoft-graph-client";
```

**Comment by pl4nty** [comment]
Worth noting MSALAuthenticationProviderOptions isn't exported either, even though the Authentication section of the readme uses `new MicrosoftGraph.MSALAuthenticationProviderOptions(graphScopes);`

**Comment by sowvikr** [comment]
How the code is not reviewed and merged into the master?

**Comment by JackAdams** [comment]
> Worth noting MSALAuthenticationProviderOptions isn't exported either, even though the Authentication section of the readme uses `new MicrosoftGraph.MSALAuthenticationProviderOptions(graphScopes);`

So how do you access `MSALAuthenticationProviderOptions`?  Is it this:

```
import { MSALAuthenticationProviderOptions }  from '@microsoft/microsoft-graph-client/lib/src/MSALAuthenticationProviderOptions'
```
