### ISSUE TITLE
Provide docs for init client without using MSAL

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/msgraph-sdk-javascript#231]
# Feature Request

## Describe the solution you'd like

Current docs on README.md & in the /docs folder only show how to init the SDK when using an auth provider, specifically MSAL. Would be nice if you showed how to init WITHOUT MSAL as MSAL is not available in many scenarios. 

For instance, MSAL.js won't work with custom Microsoft Teams solutions as they run in an IFRAME and MSAL.js at the present doesn't work with IFRAMES... you must use ADAL or hand-roll auth.

## Describe alternatives you've considered

Using the Graph REST API.

**Comment by krototype** [comment]
You can use [Custom Authentication Provider](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md) and create an Authentication provider according to the need.

**Comment by krototype** [comment]
This issue seems to be resolved if there is still a problem, please feel free to reopen the issue
