### ISSUE TITLE
Docs point to @types/microsoft-graph for TS type declarations?

### ISSUE THREAD

**Issue by andrewconnell** [microsoftgraph/msgraph-sdk-javascript#232]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

## Description

The current docs point to the [old repo](https://github.com/microsoftgraph/msgraph-typescript-typings) used for Microsoft Graph TypeScript type declarations, but the new library is in the @types scope. Shouldn't you point to this new one?

https://www.npmjs.com/package/@types/microsoft-graph 
[AB#7543](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7543)

**Comment by sseppola** [comment]
Thanks for leaving this message, I was puzzled by the usage and point of `msgraph-typescript-typings` as I basically still had to type the return types manually. Which is really odd coming from the org that created TypeScript 🙄

**Comment by nikithauc** [comment]
We are currently maintaining both https://github.com/microsoftgraph/msgraph-typescript-typings and https://www.npmjs.com/package/@types/microsoft-graph. Users can chose any source for downloading the typings.
