### ISSUE TITLE
Unable to create a Client on Word-Add-In locally

### ISSUE THREAD

**Issue by Mathyaku** [microsoftgraph/msgraph-sdk-javascript#233]
Hello, i'm having problems to set up the msgraph-sdk-javascript using word-addin locally.

![image](https://user-images.githubusercontent.com/12189704/65674880-f04e0e00-e055-11e9-878e-9a6def301359.png)

![image](https://user-images.githubusercontent.com/12189704/65675023-2b504180-e056-11e9-9826-2f29ab44ae95.png)

Using my add-in on office365 online works perfectly. Any tips how can I handle it locally ?

**Comment by darrelmiller** [comment]
This appears to be more related to an Office add-in issue.  Perhaps a question on StackOverflow questions with an `office-js` tag would get a more informative response.
