### ISSUE TITLE
Issue with the tutorial

### ISSUE THREAD

**Issue by TimboBl** [microsoftgraph/msgraph-sdk-javascript#234]
# Description
Hello, 
I am trying to create an app that will read Microsoft Planner Tasks from a board. 
However when trying to get the Graph API working nothing is working as it should. 
I have followed the README.md from this repository for Node even though I am working on a React app. The Browser Tutorial was of even less use I have to say. 
I registered my application, then I am trying to authenticate with the Graph Service. 

As a response I get a status Code of -1 and the error message: ```Cannot read property 'length' of undefined```

I have spent the last four hours trying to find a solution on google. It is entirely possible, that I missed something but I am frustrated.

Can someone please tell me what I am missing in order to request data through the Graph Service?

Please find my code below.

```javascript
import {UserAgentApplication} from "msal";
import {ImplicitMSALAuthenticationProvider} from "../../node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider";
import {Client} from "@microsoft/microsoft-graph-client";

export const login = () => {
    const clientId = "my-client-id";
    const callback = (errorDesc, token, error, tokenType) => {};
    // An Optional options for initializing the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#configuration-options
    const options = {
        redirectUri: "http://localhost:3000",
    };
    const graphScopes = ["user.read"]; // An array of graph scopes
    
    // Initialize the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#initialization-of-msal
    const userAgentApplication = new UserAgentApplication(clientId, undefined, callback, options);
    const authProvider = new ImplicitMSALAuthenticationProvider(userAgentApplication, graphScopes);

    const client = Client.initWithMiddleware({authProvider});

    client.api("/planner/plans/the-board-id").get().then(details => {
        console.log("LOL", details);
    }).catch(err => {
        console.log("There was an error when fetching", err);
    });
}
```

The error is here

```
GraphError {statusCode: -1, code: "TypeError", message: "Cannot read property 'length' of undefined", requestId: null, date: Thu Sep 26 2019 15:24:34 GMT+0200 (Mitteleuropäische Sommerzeit), …}
body: "TypeError: Cannot read property 'length' of undefined"
code: "TypeError"
date: Thu Sep 26 2019 15:24:34 GMT+0200 (Mitteleuropäische Sommerzeit) {}
message: "Cannot read property 'length' of undefined"
requestId: null
statusCode: -1
__proto__: Object
```

If you need more information please let me know. I am willing to provide it as long as I can solve this issue

**Comment by darrelmiller** [comment]
I made the exact same mistake when I was going through the React tutorial last week.  The second parameter in the constructor of ImplicitMSALAuthenticationProvider is an `options` object that has a scopes property.  You can't pass the scopes directly.

```js
const authProvider = new ImplicitMSALAuthenticationProvider(this.userAgentApplication, { 
        scopes: graphScopes 
      });
```

**Comment by TimboBl** [comment]
Thank you so much! That at least removed that issue. The hunt continues.
