### ISSUE TITLE
Add authority option to MSALAuthenticationProviderOptions

### ISSUE THREAD

**Issue by arsnyder16** [microsoftgraph/msgraph-sdk-javascript#235]
# Feature Request
Add authority option to MSALAuthenticationProviderOptions

## Is your feature request related to a problem? Please describe

Without being able to set the authority,  UserAgentApplication.aquireTokenSilent can result in an error `The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements like authority` ImplicitMSALAuthenticationProvider  should forward the authority to acquireTokenSilent

Work around
```js
const client = Client.initWithMiddleware({
        authProvider: {
          getAccessToken() {
            return agent.acquireTokenSilent({
              scopes   : ['Files.Read.All'],
              authority: 'https://login.microsoftonline.com/common/',
            }).then(({ accessToken }) => accessToken);
          }
        } 
      });
```

**Comment by darrelmiller** [comment]
You can set the `authority` whilst instantiating the UserAgentApplication object.  See details here https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-initializing-client-applications#configuration-options  e.g.

```js
msalConfig = {
	auth: {
		clientId: "your_client_id"; // Client Id of the registered application
		redirectUri: "your_redirect_uri",
                authority: 'https://login.microsoftonline.com/common/'
	},
};
const graphScopes = ["user.read", "mail.send"]; // An array of graph scopes

const msalInstance = new Msal.UserAgentApplication(msalConfig);
const options = new MicrosoftGraph.MSALAuthenticationProviderOptions(graphScopes);
const authProvider = new MicrosoftGraph.ImplicitMSALAuthenticationProvider(msalInstance, options);
```

**Comment by arsnyder16** [comment]
I am setting `authority` on UserAgentApplication but as i mention in the issue `ImplicitMSALAuthenticationProvider should forward the authority to acquireTokenSilent` but it does not

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/edbec9454111c417f39ec381a9f780e83cd14d25/src/ImplicitMSALAuthenticationProvider.ts#L72

**Comment by darrelmiller** [comment]
@arsnyder16  That seems broken.  I'll bring this up with the MSAL.js team.  If the value isn't changing per request it seems unnecessary to pass it on every call.

**Comment by arsnyder16** [comment]
I agree `acquireTokenSilent` could implicitly use the option value passed in on `UserAgentApplication` creation but it only looks at what is passed through `acquireTokenSilent` parameters

**Comment by ddyett** [comment]
not something we can handle in this sdk.
