### ISSUE TITLE
'Symbol' is undefined error in IE11

### ISSUE THREAD

**Issue by whydrae** [microsoftgraph/msgraph-sdk-javascript#236]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Hello! I'm facing with "Symbol is not defined" issue when use api calls of the Client in IE11.

**Console Errors:** 'Symbol' is undefined

**Screenshots:**

![image](https://user-images.githubusercontent.com/19683635/66322160-5aa26080-e92a-11e9-8f4b-aee14898993f.png)

In the built verion of graph-js-sdk.js I found two places with the following code:

![image](https://user-images.githubusercontent.com/19683635/66322698-32ffc800-e92b-11e9-812d-8e77cb8a135e.png)

Here, Symbol is used without any checking.

## Steps to Reproduce

1. Execute MicrosoftGraph.Client.api(...) in application from IE11.

**Expected behavior:** Request returns data without errors.

**Actual behavior:** Request is not triggered with error in the console.

## Additional Context

Is that somehow related with this issue https://github.com/babel/babel/issues/7597?

## Usage Information

SDK Version - 2.0.0

-   [X] Browser (Check, if using Browser version of SDK)

es6-promise and fetch polyfills are loaded.

> Browser Name - Internet Explorer

> Version - 11

**Comment by krototype** [comment]
Thanks for reporting the issue, we are looking into it.
