### ISSUE TITLE
Initializers are not allowed in ambient contexts in common.d.ts

### ISSUE THREAD

**Issue by itaydemri** [microsoftgraph/msgraph-sdk-javascript#24]
Hi Dan,
in version 0.3.0, there's an build error due to the assignments:

common.d.ts:
export declare const DEFAULT_VERSION **= "v1.0"**;
export declare const GRAPH_BASE_URL **= "https://graph.microsoft.com/"**;

i'd love to start working with this library :-)
Itay

**Comment by dan-silver** [comment]
Interesting, I'm not seeing that error. What version of typescript are you using and are you building with tsc (global) or the npm run build command?

TypeScript 2.1 is required as a dev dependency in the package.json

**Comment by itaydemri** [comment]
I guess you're right! i'm using 2.0.9 currently.

i'll have to upgrade my project which might take a while cause I see some new build errors after upgrading to 2.1.4 :-(

Since 2.1 was just released in November, i would have consider supporting typescript ^2.0.0 versions for a while if possible.

Thanks for your help Dan! and i'm sure i'll use this package very soon.
Itay

**Comment by dan-silver** [comment]
Glad we're able to figure this out!  I'll look into making this compatible with typescript ^2.0.0.

Also, I think you mentioned in the other thread that you're waiting on the types (https://github.com/microsoftgraph/msgraph-typescript-typings) to migrate away from typings and support @types.  That project was also just updated and although we don't publish to @types, you can save it as a dev dependency in package.json so it should work the same.

Let me know if you find any other issues with either of these projects!
