### ISSUE TITLE
Intercept Graph Api Requests

### ISSUE THREAD

**Issue by Mathyaku** [microsoftgraph/msgraph-sdk-javascript#240]
Hello,

Is there anyway to Intercept Graph Api Requests, using Javascript SDK ?
I would like to use a loader when the request is beeing processed, is there anyway to do that ?

**Comment by krototype** [comment]
@Mathyaku 
- What do you exactly mean by intercept?
- Are you using js sdk right now?
- At what stage do you exactly want your request to be processed?

**Comment by Mathyaku** [comment]
@krototype 

* I would like a hability to know when the request is being processed or not, like on AXIOS Interceptor (https://github.com/axios/axios). 

* Yes, I'm building a Word Addin and using React/Javacript @microsoft/microsoft-graph-client lib

* As Axios did, on every request/response from a graph client, I wanna execute some code.

![image](https://user-images.githubusercontent.com/12189704/66911889-1a259f80-f01a-11e9-8bb4-2216c29f1809.png)

**Comment by krototype** [comment]
@Mathyaku,
You can look into building a middleware of your own and building a custom middleware chain out of it, using which you can intercept the request before the request is being sent to the Graph server, similarly you can intercept the response before you actually pass it back to the client.
This [doc](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomMiddlewareChain.md
) will guide you in building the middleware and custom middleware chain.

**Comment by Mathyaku** [comment]
It worked, thanks.

But I used the latest [documentation](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/1.7.0/docs/CustomMiddlewareChain.md)
