### ISSUE TITLE
default count() param to true

### ISSUE THREAD

**Issue by OlivierCuyp** [microsoftgraph/msgraph-sdk-javascript#241]
# Feature Request

## Is your feature request related to a problem? Please describe

I don't understand why we should specify `true` in the `.count()` method.
If you call, it means you want it.
If you don't specify it, you get this error:

```
Cannot read property 'toString' of undefined at GraphRequest.count
```

PS: I'm not using typescript and I'm not the only one ;)

## Describe the solution you'd like

Default the param to `true` here:
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/7baaf98790ffc3d18a5033c40db1aed7afc315f4/src/GraphRequest.ts#L493

That way you stay compatible with previous version and in the new version this param is optional.

**Comment by krototype** [comment]
We have set it to false according to the original behavior of the graph, where if you don't specify true or false, the returned response doesn't contain any parameter of count (which is the same behavior as that of false).

**Comment by OlivierCuyp** [comment]
@krototype, thanks for the update, and the fix.

Regarding default behavior I find it weird to default to **false**.
Because, if you call the method `.count()`, it really means you want the count.

Usually in CLI for boolean argument when you don't specify any value it is defaulted to **true**.
This logique is often kept for APIs.

**Comment by OlivierCuyp** [comment]
@darrelmiller since I have no answer from @krototype. I was hoping you could help me to understand the vision for this SDK.
Now with the PR #243 `.count()` is not erroring, that's cool but:

- `.count()` === `.count(false)`, which is totally useless and confusing
- if I want to get the count, I need to do `.count(true)`, why ?

If I do `.count()` the intention is clear, I want the count ...
When would I use `.count(false)` (or even the current `.count()`), since it is the same result if I don't call it at all ...

**Comment by darrelmiller** [comment]
@OlivierCuyp  I agree with you.  I will investigate.

**Comment by OlivierCuyp** [comment]
@darrelmiller any news ?

**Comment by darrelmiller** [comment]
Hey @OlivierCuyp 

So, I'm torn. I agree that the behavior you describe makes sense. However, consider the two following requests.

```
https://graph.microsoft.com/v1.0/me/messages?$count
https://graph.microsoft.com/v1.0/me/messages?$count=true
```
The first does not return the count and the second does.  This also feels like the wrong behavior to me, however, that is how it is explicitly defined by the OData spec https://docs.oasis-open.org/odata/odata/v4.01/csprd06/part1-protocol/odata-v4.01-csprd06-part1-protocol.html#_Toc21423812

As much as I want to change .Count() to set $count=true, I am reluctant to be inconsistent with the specification.   Hey @MIchaelMainer   what do you think?

**Comment by OlivierCuyp** [comment]
@darrelmiller in a REST interface query params are always key/value pairs.
So I completely agree with the REST interface, this makes no sense:

```
https://graph.microsoft.com/v1.0/me/messages?$count
```

But here you are building a programatic SDK with aims to simplify the usage of  the REST API.
`.count()` is a method not a key/value pair.
This kind of method adding a boolean query param should always default to `true` IMO.

**Comment by darrelmiller** [comment]
@OlivierCuyp Technically there is nothing wrong with that query string.  Although [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.4) mentions key value pairs as a common way of encoding query parameters, in no way is that required.

Having said that, having .count() in a programming language fluent interface mean "do not count" is just completely unnatural.  I think the OData spec made a bad choice.  I will bring it up at our next SDK meeting.

**Comment by OlivierCuyp** [comment]
@darrelmiller I just meant for the API it is less weird to have `count=true` since query params are interpreted as a key/value hash.
But `.count()` is method not a hash it feels much more unnatural as you said.

**Comment by ddyett** [comment]
@darrelmiller was there an action decided on here?

**Comment by OlivierCuyp** [comment]
@darrelmiller & @darrelmiller I already made a PR hoping you'll decide anytime soon in favor of this change ;)

**Comment by nikithauc** [comment]
[10/9 2:30 PM] Michael Mainer
    I think it should default to true. If a customer specifically uses count(bool shouldTryRequestCount = true), they want to get the count, and the default should be true. If they specifically do not want the count, which by the way I think there are very few APIs that return it by default, then I think it is reasonable for them to turn off count with count(false). The likeliest use case is they want the count, so lets make that default.

**Comment by Licantrop0** [comment]
@nikithauc / @darrelmiller / @OlivierCuyp how the raw count is then implemented?
`https://graph.microsoft.com/v1.0/me/messages/$count`

I would like to propose this:

### In-line count (returning the count as an odata annotation)
`https://graph.microsoft.com/v1.0/me/messages?$count=true`
would be retrieved like this:
`myRequest.Count(out <count variable>)`
(I don't know if with Java you can have `out` variables like in C#)

### Raw count (returning just a raw number)
`https://graph.microsoft.com/v1.0/me/messages/$count`
would be retrieved like this:
`myRequest.RawCount()`
And the return type is an integer directly.

**Comment by nikithauc** [comment]
@Licantrop0 Thank you for your suggestion! This proposal will be reviewed and I will get back to you. 

cc: @sebastienlevert
