### ISSUE TITLE
AWS Lambda function call graph api

### ISSUE THREAD

**Issue by EricZhengJun** [microsoftgraph/msgraph-sdk-javascript#249]
Hi, I use "@microsoft/microsoft-graph-client" in my AWS lambda function to call Graph API to get email, but cannot get any response. Dose Graph API support AWS lambda?

**Comment by MIchaelMainer** [comment]
Yes, you can call the Microsoft Graph API from AWS lambda, or any other serverless computing options.

**Comment by CaseGuide** [comment]
@MIchaelMainer @EricZhengJun  We're also experiencing this phenomenon. When trying to use the Microsoft Graph API to get change notifications (webhook subscription).  We appear to get nothing back from MS graph API from lambda using a flask app that runs fine locally and in testing using Postman. 

Are you aware of any examples using AWS lambda and microsoft graph?

**Comment by nikithauc** [comment]
@CaseGuide  Please direct this issue to [Microsoft Graph Docs](https://github.com/microsoftgraph/microsoft-graph-docs) , [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) with Microsoft Graph tag for help with this issue.
