### ISSUE TITLE
Cannot import with SystemJS

### ISSUE THREAD

**Issue by bradley-dotnet** [microsoftgraph/msgraph-sdk-javascript#25]
I am trying to load the SDK into a Angular2/Typescript application that is using SystemJS. I started with the code from the typescript sample.

`import { Client as GraphClient } from "msgraph-sdk-javascript";`

Works in the typescript file using the library but I get a 404: cannot access localhost:8080/msgraph-sdk-javscript. If I add this map to my systemjs.config.js:

`'msgraph-sdk-javascript': 'node_modules/msgraph-sdk-javascript',`

Then I get a 503 unauthorized on the node_modules/msgraph-sdk-javascript directory (why it is trying to access the directory directly is unknown to me).  I have also tried aliasing the map to "msgraph" and then adding a package to systemjs.config.js

            msgraph: {
                main: 'lib/graph-js-sdk-web.js',
                defaultExtension: 'js'
            },

But that seems to mess up all of the other relative paths loaded by the library itself. How can this library be loaded into such an application?

**Comment by dan-silver** [comment]
Hi @bradley-dotnet ! I'm not too familiar with SystemJS, but I tried importing the SDK and got the same errors that you described.  I'll continue investigating and I'm also trying to find someone that's already familiar with SystemJS.

**Comment by dan-silver** [comment]
I'd love to investigate this more, but I unfortunately can't commit to a time frame. Did you happen to find a workaround to this issue that we can share with others? I'll leave this open so others know there's a known issue importing this library with SystemJs.

**Comment by bradley-dotnet** [comment]
@dan-silver My workaround at present is to manually load the SDK on my index.html and declare the Client object as an "any" global to use it (same thing I have to do for SignalR at the moment). I could post some sample code this evening for readers until this is fixed.

**Comment by sbiaudet** [comment]
@bradley-dotnet could you post a sample code ? I've always an undefined error. Thanks

**Comment by sbiaudet** [comment]
Ok I've found my mistake. I forgot delegate...

With this syntax it's ok

> declare var MicrosoftGraph:any;

**Comment by muthurathinam** [comment]
@bradley-dotnet 
Are you still getting this error ? if so can you educate me to reproduce with the versions of dependencies that you use ?

**Comment by muthurathinam** [comment]
Closing this as no response from the user.
