### ISSUE TITLE
Get 'Access to OData is disabled' error even though User-Agent is set in header

### ISSUE THREAD

**Issue by fangzhoulu-hiretual** [microsoftgraph/msgraph-sdk-javascript#252]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description
We are trying to create subscription on a exchange server whose EWS settings is `EwsApplicationAccessPolicy : EnforceAllowList` with `EWSAllowList` including our USER_AGENT,.However, we keeps getting **Access to OData is disabled** error.

The code is like:
```
const response = await client.api('/subscriptions').header('User-Agent', USER_AGENT).post({
  changeType: 'created',
  notificationUrl: process.env.OUTLOOK_WEBHOOK_URL,
  resource: '/me/messages',
  expirationDateTime: moment().add(SUBSCRIPTION_EXPIRE_TIME, 'minutes'),
  clientState: 'Something'
});
```
From the server log, the user agent inside header is still empty.
Refer: https://blogs.msdn.microsoft.com/wushuai/2017/04/01/how-to-fix-access-to-odata-is-disabled-when-calling-graph-api/

Error code:
```
{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"9af7d935-5ddc-4f2a-aa15-e7d35aa235b1","date":"2019-11-18T14:55:33.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"request-id\":\"9af7d935-5ddc-4f2a-aa15-e7d35aa235b1\",\"date\":\"2019-11-18T14:55:33\"}}"}
```

**Comment by MIchaelMainer** [comment]
Are you using an on-premise Exchange Server? You can't use Microsoft Graph API with on-premise Exchange.

**Comment by fangzhoulu-hiretual** [comment]
It does work with this email server until the EwsApplicationAccessPolicy is changed.
I think it is hybrid.

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Hi Michael, we are using O365 which is cloud-based.

**Comment by MIchaelMainer** [comment]
Just to be clear, let me know if I understand correctly...

This is targeting a user's mailbox (delegated permissions) and may be part of a hybrid environment where some users are hosted on an on-premise Exchange Server and others in Exchange Online.  Microsoft Graph subscriptions that target /messages work as expected when the `EwsApplicationAccessPolicy` is not set. When EwsApplicationAccessPolicy : EnforceAllowList with EWSAllowList is set, this no longer works and you see the error message you previously reported. Is my understanding correct?

**Comment by hongtaozhang233** [comment]
Hi Michael,

**Comment by MIchaelMainer** [comment]
@hongtaozhang233 

Thank you for the response. Can you confirm that the User Agent string sent over the wire matches the one set in the EWSAllowList? Can you provide a requestId from the error response so I can look this up?

**Comment by hongtaozhang233** [comment]
@MIchaelMainer 
Hi Michael, Yes the User Agent is 'HiretualApp/*' and the EWSAllowList is set as '*Hiretual*'. Actually we tried several cases like "HiretualApp*", "HiretualApp/*" but none of them work.

**Comment by MIchaelMainer** [comment]
Can you provide a requestId from the error response so I can look this up?

**Comment by hongtaozhang233** [comment]
@MIchaelMainer 29c5406e-08f0-47fa-b8b8-024a858817c2

**Comment by MIchaelMainer** [comment]
@hongtaozhang233 This issue is being worked on and tracked.

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Cool thanks Michael!

**Comment by MIchaelMainer** [comment]
@hongtaozhang233 Is it working for you now? It looks like you updated the EWSAllowList to use wild cards, `*HiretualApp*`.

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Nope. It was updated before.We tried several cases: '*HiretualApp*', '*Hiretual*', 'HiretualApp*', 'HiretualApp/*' but none of them worked.

**Comment by MIchaelMainer** [comment]
When did you last send the request? The EWSAllowList was updated today. I don't know what the value was when you issued that request above on June 30th.  Can you send the request with `Hiretual/*` and `Hiretual` as the User-Agent and share with me the error response?

**Comment by hongtaozhang233** [comment]
Let me check with our engineers. We tested it one week ago and got these errors:
`{
	"statusCode": 403,
	"code": "ExtensionError",
	"message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]",
	"requestId": "f41fabda-5d81-44db-a3e6-a0fc43c9a5ac",
	"date": "2020-06-30T21:58:03.000Z",
	"body": "{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T21:58:03\",\"request-id\":\"f41fabda-5d81-44db-a3e6-a0fc43c9a5ac\"}}"
}`
`{
	"statusCode": 403,
	"code": "ExtensionError",
	"message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]",
	"requestId": "1599125a-18af-4bb2-94ea-2aeb97bc0c61",
	"date": "2020-06-30T23:07:00.000Z",
	"body": "{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T23:07:00\",\"request-id\":\"1599125a-18af-4bb2-94ea-2aeb97bc0c61\"}}"
}`
`{
	"statusCode": 403,
	"code": "ExtensionError",
	"message": "Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]",
	"requestId": "29c5406e-08f0-47fa-b8b8-024a858817c2",
	"date": "2020-06-30T23:47:49.000Z",
	"body": "{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T23:47:49\",\"request-id\":\"29c5406e-08f0-47fa-b8b8-024a858817c2\"}}"
}`
`{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"01a22a81-b767-41c3-8202-35aa55bff1ee","date":"2020-06-30T23:48:15.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T23:48:15\",\"request-id\":\"01a22a81-b767-41c3-8202-35aa55bff1ee\"}}"}`
`{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"ba2ae337-df65-4f24-95e3-9f254c729ee3","date":"2020-06-30T23:47:38.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T23:47:38\",\"request-id\":\"ba2ae337-df65-4f24-95e3-9f254c729ee3\"}}"}`
`{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"2fe4afef-8e4f-4b23-99e7-68e4683a390c","date":"2020-06-30T23:19:41.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-06-30T23:19:41\",\"request-id\":\"2fe4afef-8e4f-4b23-99e7-68e4683a390c\"}}"}`

Sorry that I cannot map those errors to which EWSAllowList we tested.

**Comment by hongtaozhang233** [comment]
Are you able to see that if the request's 'User-Agent' header was set correctly as 'HiretualApp/*'?

**Comment by MIchaelMainer** [comment]
Yes, it was reported to me that 'HiretualApp/*' was set as the header. The examples above are from 6/30. The EwsAllowList has *HiretualApp* set. What I can't determine is whether it is fixed as the allow list was last updated 7/7/2020 6:51:28 PM UTC. I'd like to see a request-response made after the last time EwsAllowList was set to see whether this is resolved or not by that change.

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Hi Michael, we just tried again today and it returns the same error. Here is the request-response.
`{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"407df549-a0b3-4107-bdfc-268eee6a228d","date":"2020-07-14T19:23:25.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-07-14T19:23:25\",\"request-id\":\"407df549-a0b3-4107-bdfc-268eee6a228d\"}}"}`

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Hi Michael, any update/findings from your side?

**Comment by MIchaelMainer** [comment]
@hongtaozhang233 I'm sorry to ask this again, can you issue that request again? Service engineering isn't seeing any clear reason why the request is failing. The org configuration has changed since the request above on 7/14 was sent. The configuration last changed on 7/20 so service engineering is requesting another request to investigate.

`get-organizationconfig deleted.onmicrosoft.com |fl *when*` the output states `WhenChanged : 7/20/2020 10:49:23 PM`

**Comment by hongtaozhang233** [comment]
@MIchaelMainer, Please check this response: `{"statusCode":403,"code":"ExtensionError","message":"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]","requestId":"71228cec-7ef4-4d2d-bdb9-aa1f6a1aa518","date":"2020-07-30T17:59:40.000Z","body":"{\"code\":\"ExtensionError\",\"message\":\"Operation: Create; Exception: [Status Code: Forbidden; Reason: Access to OData is disabled.]\",\"innerError\":{\"date\":\"2020-07-30T17:59:40\",\"request-id\":\"71228cec-7ef4-4d2d-bdb9-aa1f6a1aa518\"}}"}`

**Comment by hongtaozhang233** [comment]
@MIchaelMainer Hi Michael, is there any updates from your side?

**Comment by MIchaelMainer** [comment]
@hongtaozhang233 I've requested a look from service engineering on why this is still blocked. Do you have a support contract? It may be more effective to open a support ticket on this. I don't know how this is done, but perhaps this is something that your tenant admin can do on your behalf.

**Comment by MIchaelMainer** [comment]
This is an issue in your configuration: Request was blocked due to a Tenant-Configured UserAgent AllowList being set for this **User**.

The two entries in the allowlist need review. The first entry is "\*Hiretual\*. Note the leading quote. The second entry is one long line that was intended to be different entries. Your admin needs to go back and review all of the ewsAllowList configurations. Have them run Get-CASMailbox on this user and have them review the allow list.

This is not an API issue, just a creative misconfiguration.
