### ISSUE TITLE
.getStream() never triggers 'finish' or 'end' 

### ISSUE THREAD

**Issue by technicallynick** [microsoftgraph/msgraph-sdk-javascript#253]
# Bug Report

## Prerequisites

-   [Y] Can you reproduce the problem?
-   [Y] Are you running the latest version?
-   [Y] Are you reporting to the correct repository?
-   [Y] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When attempting to pull a user thumbnail via the npm package "microsoft-graph-client", I am unable to parse the results in to a base64 encoded string for storage. Additional logging revealed that neither the `stream.on('finish')` or the `stream.on('end')` ever fire. There are no errors in the logs. All current examples of `getStream()` that I can find show the process for writing a stream directly to a file via `pipe`. However, in my use-case, I have no desire (as it would be significantly out of my way to) write the image to a file as I'm wanting to instead store the base64 encoded results as a string in my own local database.

## Steps to Reproduce

1. Setup an Azure app that can query users photos via Node.js and the "microsoft-graph-client" npm package. 
2. Call a function that queries AAD for a users photo such as the below:
```
const getAzureThumbnail = async (userPrincipalName) => {
  try {
    const { access_token: accessToken } = JSON.parse(await request.post({ url: `${credentials.auth.tokenHost}/${credentials.auth.tokenPath}`, form: requestParams }));
    const client = graph.Client.init({
      authProvider: (done) => {
        done(null, accessToken);
      },
    });
   
    const stream = await client
      .api(`/users/${userPrincipalName}/photo/$value`)
      .getStream();
    const thumbnail = await streamToString(stream);

    console.log(thumbnail);
    return thumbnail;
  } catch (err) {
    return (Error(err));
  }
};
const streamToString = (stream) => {
  const chunks = [];
  return new Promise((resolve, reject) => {
    stream.on('data', (chunk) => {
      chunks.push(chunk);
      console.log(chunks);
    });
    stream.on('error', reject);
    stream.on('end', () => {
      console.log('stream ended!');
      resolve(Buffer.concat(chunks).toString('base64'));
    });
    stream.on('finish', () => {
      console.log('stream finished!');
      resolve(Buffer.concat(chunks).toString('base64'));
    });
  });
};
```

**Expected behavior:**
I expect that at some point the 'end' or 'finish' listeners (one or the other at least) would eventually be triggered. 
**Actual behavior:**
Neither the 'finish' or 'end' listeners are ever triggered. 

**Additional Information:**
While my testing is being done primarily with v1.7.0 of the microsoft-graph-client package. When I update to v2.0 (current latest) the above function fails completely with no errors. All that is returned is an empty object.

SDK Version - [SDK version you are using]
-   [Y] Node (Check, if using Node version of SDK)
> Node Version - [The version of Node you are using]
$ node -v
v10.16.3
 
[AB#7545](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7545)

**Comment by semasdev** [comment]
Works fine for me with Node 12.16.1 and Graph SDK 2.0.0
You actually solved one of my  problems with getStream(), thank you.

**Comment by ddyett** [comment]
let's double check this is working properly.

**Comment by nikithauc** [comment]
Cannot reproduce this.
