### ISSUE TITLE
Request to memberOf or transitiveMemberOf never returns a response

### ISSUE THREAD

**Issue by technicallynick** [microsoftgraph/msgraph-sdk-javascript#254]
# Bug Report
## Prerequisites

-   [Y] Can you reproduce the problem?
-   [Y] Are you running the latest version?
-   [Y] Are you reporting to the correct repository?
-   [Y] Did you perform a cursory search?

## Description
When attempting to call the API for `/users/${userPrincipalName}/transitiveMemberOf | memberOf` no response is returned. When enabling debug logging, it only logs the URL being requested and nothing else. When utilizing the NPM package `request` instead of the client, but with the same accessToken that's retrieved for the client, the request always returns results.

**Console Errors:**
No errors are found. No response is returned.
 
## Steps to Reproduce

1. Setup Node.js environment
2. Install `@microsoft/microsoft-graph-client` and `request-promise` (for promisified requests)
3. Obtain a valid access token:
```
const { access_token: accessToken } = JSON.parse(await request.post({ url: https://login.microsoftonline.com/f5.onmicrosoft.com/oauth2/v2.0/token, form: {
  grant_type: 'client_credentials',
  client_id: process.env.AZURE_APP_ID,
  client_secret: process.env.AZURE_APP_PASSWORD,
  scope: 'https://graph.microsoft.com/.default'
} }));
```
4. Initialize the MS Graph client:
```
const graph = require('@microsoft/microsoft-graph-client');
const client = await graph.Client.init({
      authProvider: (done) => {
        done(null, accessToken);
      },
    });
```
5.  Make request to graph for transitiveMemberOf
```
const result = await client
      .api(`/users/${userPrincipalName}/transitiveMemberOf`)
      .get();
console.log(result)
```
6. Witness no response (error or results) ever occurs. 

**Expected behavior:**
I expect to either see an error or the results returned to the requesting client. If an error occurs, I expect a meaningful error that can be traced back to a root cause.

**Actual behavior:**
Nothing. No response. 

## Usage Information

SDK Version - 1.7 and 2.0 both produce this

-   [Y] Node (Check, if using Node version of SDK)

> Node Version - v10.16.3

**Comment by nikithauc** [comment]
@technicallynick  Is this issue still reproducible?

**Comment by nikithauc** [comment]
Tried `/users/${userPrincipalName}/transitiveMemberOf` in graph explorer and in a node sample and worked fine. Not able to reproduce this issue.
