### ISSUE TITLE
interactive mode

### ISSUE THREAD

**Issue by quantrpeter** [microsoftgraph/msgraph-sdk-javascript#261]
Hi
   Doesn't this lib supports "interactive mode" (popup a browse to login) and "username/password" mode?
thanks
Peter

**Comment by peombwa** [comment]
We currently have built in support for implicit grant auth flow using MSAL JS.
Here is the [roadmap](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki#roadmap) for MSAL JS, please submit a feature request to them.
