### ISSUE TITLE
Addition of fields into the API

### ISSUE THREAD

**Issue by PlayMa256** [microsoftgraph/msgraph-sdk-javascript#266]
# Feature Request

## Is your feature request related to a problem? Please describe
Not sure if this applies to this repository!

We are trying to access the graph api (at first on the graph explorer) and i could not find some crucial information that diverges from the powershell api.

What i mean by that:

Whenever i run: `Get-CSOnlineUser` i get the list of users with all its atributes, but on the graph api, few fields are lacking: `Department, Title, City, Phone, OnPremLineURI, HostedVoiceMail, EnterpriseVoiceEnabled, VoiceRoutingPolicy`

## Describe the solution you'd like

Are these fields possible to be added?

(please, correct me if this is the wrong place to be opening this issue).

**Comment by MIchaelMainer** [comment]
`Get-CSOnlineUser` calls a Skype endpoint, not the Microsoft Graph endpoint. 

https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps

You will need to ask for this feature from the feedback link in that topic.
