### ISSUE TITLE
PageIterator 

### ISSUE THREAD

**Issue by rachaelsingleton** [microsoftgraph/msgraph-sdk-javascript#267]
# Bug Report
PageIterator not working.. 

## Description

 ReferenceError: Cannot access 'pageIterator' before initialization

## Steps to Reproduce

Copied exact code from https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/PageIterator.md

**Expected behavior:** Iterates through pages

**Actual behavior:** Console error (ReferenceError: Cannot access 'pageIterator' before initialization)

**Comment by qu4d** [comment]
@rachaelsingleton You just need to import/require PageIterator from library.
`const { PageIterator } = require("@microsoft/microsoft-graph-client")`
