### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module' (ImplicitMSALAuthenticationProvider, MSALAuthenticationProviderOptions)

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [microsoftgraph/msgraph-sdk-javascript#271]
# Bug Report

## Prerequisites

-   [ x ] Can you reproduce the problem?
-   [ x ] Are you running the latest version?
-   [ x ] Are you reporting to the correct repository?
-   [ x ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Getting error when building my project with gulp.

**Console Errors:** [Is there any console error]

    /node_modules/@microsoft/microsoft-graph-client/lib/es/ImplicitMSALAuthenticationProvider.js:7
    import * as tslib_1 from "tslib";
    ^
    ParseError: 'import' and 'export' may appear only with 'sourceType: module'

    /node_modules/@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProviderOptions.js:12
    export class MSALAuthenticationProviderOptions {
    ^
    ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

Just trying instantiate the Client following documentation

    import {ImplicitMSALAuthenticationProvider} from "@microsoft/microsoft-graph-client/lib/es/ImplicitMSALAuthenticationProvider";
    import {MSALAuthenticationProviderOptions} from "@microsoft/microsoft-graph-client/lib/es/MSALAuthenticationProviderOptions";
    import {Client} from "@microsoft/microsoft-graph-client";

**Expected behavior:** [What you expected to happen]
App builds without errors

**Actual behavior:** [What actually happened]
Build fails.

## Additional Context

ReactJS project. Ubuntu server.

## Usage Information

SDK Version - [SDK version you are using]
2.0.0

-   [ x ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]
node v7.5.0(npm v4.1.2)

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by ddyett** [comment]
you need to add sourcetype: module to the project.
