### ISSUE TITLE
Chat problems when joining an existing meeting made using microsoft graph

### ISSUE THREAD

**Issue by martininvillia** [microsoftgraph/msgraph-sdk-javascript#274]
# Bug Report

## Prerequisites

-   [X ] Can you reproduce the problem?
-   [X ] Are you running the latest version?
-   [X ] Are you reporting to the correct repository?
-   [X ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

We created an application with integration with microsoft graph and we are having some problems.

In the frontend application we are using the microsoft-teams sdk.

**WEB/BROWSER MICROSOFT TEAMS**: When the user enters the meeting via the web, I create a window.open and it works normally with the meeting chat appearing

**APP/DESKTOP MICROSOFT TEAMS**: When the user is using the microsoft teams application and tries to join a meeting, I use the deep link with the meeting link, but the chat does not appear

> 
example:
meetingTeams.meeting_join_web_url = https://teams.microsoft.com/l/meetup-join/19:meeting_MDNmOTA3NmUtZDhmMi00YzRmLTgyYjMtYzU4YzI2MDU5ZDQ4@thread.v2/
meetingTeams.meeting_join_url = https://teams.microsoft.com/l/meetup-join/19:meeting_MDNmOTA3NmUtZDhmMi00YzRmLTgyYjMtYzU4YzI2MDU5ZDQ4@thread.v2/

             microsoftTeams.initialize();
             microsoftTeams.getContext((context => {
                if (context.hostClientType === "web") {
                    window.open(meetingTeams.meeting_join_web_url, "_blank")
                    return;
                }

                const joinUrl = encodeURI(meetingTeams.meeting_join_url);
                microsoftTeams.executeDeepLink(joinUrl); }));

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Join meeting existing on desktop

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by MIchaelMainer** [comment]
@zihzhan Do you have insight here on this issue?

**Comment by zihzhan** [comment]
I don't really know join meeting through Teams Client side but it seems the joinUrl should contains more info to perform as a deep link, as a parameter of **executeDeepLink**. 
I did a quick search and @ydogandjiev might know this.

**Comment by ddyett** [comment]
not an issue with the sdk itself so closing.
