### ISSUE TITLE
PageIterator returns duplicate records from contacts collection

### ISSUE THREAD

**Issue by qu4d** [microsoftgraph/msgraph-sdk-javascript#275]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description
We are using PageIterator for getting contacts from contact folders.
PageIterator always returns correct number of records (using count?), but some of records can be duplicated.
The number of duplicate records almost every time equals x10. It looks like PageIterator returns the same page twice or thrice.
Tested on 500+ records.

## Code example
``` 
const graphContacts = [];

const pageCollection = await graphConnection
  .api(`/users/${userId}/contactFolders/${folderId}/contacts`)
  .expand("extensions($filter=Id eq 'contactId')")
  .get();
const pageIterator = new PageIterator(graphConnection, pageCollection, data => {
  graphContacts.push(data);
  return true;
});
await pageIterator.iterate();
```

## Usage Information

Heroku
SDK Version - 2.0.0
-   [x] Node (Check, if using Node version of SDK)
> Node Version - v10.19.0

**Comment by MIchaelMainer** [comment]
This is likely a service issue. Can you repro and capture a requestId from a response so I can ask for an investigation?

**Comment by ddyett** [comment]
not enough information to reproduce at this point so not currently actionable.
