### ISSUE TITLE
MSGraphClient PUT missing JSON Content-Type header

### ISSUE THREAD

**Issue by JBoman32768** [microsoftgraph/msgraph-sdk-javascript#277]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [ ] Are you reporting to the correct repository? - Not sure.
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Using this library via an SPFX webpart to create a Team.  Webpart has been in production for a long time, and has just recently started reporting errors for PUT operations via the MSGraphClient.

Example:

``await msgraphclient.api(`/groups/${groupId}/team`).put(JSON.stringify(body));``

Results in 400 error because of the missing header.  
I can confirm the request is sent with content-type: application/octet-streaminstead of application/json

All POST and GET operations succeed in the same session and same client object with correct headers - but not PUT.

**Console Errors:** 

Graph correctly responds with:
> Entity only allows writes with a JSON Content-Type header.

## Steps to Reproduce

1. Create SPFX webpart that uses the Graph API
2. Get the Graph Client fro mthe Webpart context:
`var client = await this.spContext.msGraphClientFactory.getClient()`
3. Call a PUT
``client.api(`/groups/${groupId}/team`).put(JSON.stringify(body));``

Will cause request to be sent to Graph with incorrect content type header.

**Expected behavior:** PUT request is sent with Content-Type: application/json

**Actual behavior:** PUT Request is sent with content-type: application/octet-stream

## Additional Context

Webpart has been in PROD for a fair while on SPFX 1.9.0

## Usage Information

SDK Version - [SDK version you are using]

SPFX 1.9.0

-   [x] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

Node version v8.12.0

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

Chromium Edge

> Version - [The version of the browser you are using]

Canary 84.0.495.0

**Comment by JBoman32768** [comment]
Have confirmed that changing the code in production rectifies the issue:

From:
``var createTeamResponse = await (await this.graphClient()).api(`/groups/${groupId}/team`, ).put(JSON.stringify(body));``

To:
``var createTeamResponse = await (await this.graphClient()).api(`/groups/${groupId}/team`, ).header('Content-Type','application/json').put(JSON.stringify(body));``

**Comment by ddyett** [comment]
still should look at why it was added as a stream content type.

**Comment by nikithauc** [comment]
[Fix](https://github.com/microsoftgraph/msgraph-sdk-javascript/commit/3b0edb32bf57c4c29ae98e1e21f19e9405ba10ef). This should be fixed in [Microsoft Graph JS SDK Client](https://github.com/microsoftgraph/msgraph-sdk-javascript/releases Version 2.0.0)
