### ISSUE TITLE
URL endpoint to access on-premise mailbox

### ISSUE THREAD

**Issue by jschwartzenberg** [microsoftgraph/msgraph-sdk-javascript#278]
What's the endpoint to access MS Graph on an on-premise MS Exchange installation? So far I have only come across the O365 URL https://graph.microsoft.com/v1.0/me/

EWS is outdated SOAP, but of course I do not want to rely on O365 just because I'd like to use a REST API instead of SOAP :)

**Comment by trs80** [comment]
Apparently the MS Graph API proxies requests to on-prem /api so you don't need to do anything in a hybrid environment: https://lecafedeva.wordpress.com/2019/03/15/deep-dive-how-to-configure-exchange-on-premise-server-hybrid-integration-with-office-365-test-rest-api-calls/

For purely on-prem I guess try /api and see what's in there

**Comment by MIchaelMainer** [comment]
To be specific, it proxies for Exchange based APIs, not any of the other service APIs.

**Comment by jschwartzenberg** [comment]
When I try `/api` I get unauthorized. @MIchaelMainer could you explain how this proxy works how the Microsoft Graph API is typically accessed directly on an Exchange server?
