### ISSUE TITLE
Invalid Select Parsing

### ISSUE THREAD

**Issue by BrennanAldridge** [microsoftgraph/msgraph-sdk-javascript#279]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [X] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [X] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description
When consuming the Graph API for SharePoint List Items (in this case via [MSGraphClient](https://docs.microsoft.com/en-us/javascript/api/sp-http/msgraphclient?view=sp-typescript-latest)), I am unable to use Select to narrow fields returned in response.

Here is an example endpoint that is valid through Graph Explorer:
https://graph.microsoft.com/v1.0/sites/{GUID}/lists('Test List')/items?$expand=fields($select=Title)

When this request is executed, the path parsed on equal signs and results in something like this:
https://graph.microsoft.com/v1.0/sites/{GUID}/lists('Test List')/items?$expand=fields($select=

When using MSGraphClient's built in select wrapper, it incorrectly formats the path like this:
https://graph.microsoft.com/v1.0/sites/{GUID}/lists('Test List')/items?$expand=fields&$select=Title
... or select fields/Title (either way it doesn't work, as select must be attribute of expanded fields.

Looking at the source, perhaps this is the result of GraphRequest.ts around line 171:
`const queryParams = path.substring(queryStrPos + 1, path.length).split("&");
			for (const queryParam of queryParams) {
				**const qParams = queryParam.split("=");**
				const key = qParams[0];
				const value = qParams[1];
				if (oDataQueryNames.indexOf(key) !== -1) {
					this.urlComponents.oDataQueryParams[key] = value;
				} else {
					this.urlComponents.otherURLQueryParams[key] = value;
				}
			}`

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]
![GraphRequest - Parse Path on Equal Sign](https://user-images.githubusercontent.com/45017512/81074396-8e3c6d80-8eae-11ea-9a39-94bb092ef1e3.jpg)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
I would like to provide a full valid path via MSGraphClient and have it not mess up my path :). If I know the complete url needed to perform select, filtering, top, etc... I should be able to plug that in and get the same response as when using it in Graph Explorer.

**Actual behavior:** [What actually happened]
See above... it's parsing the path incorrectly.

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by MIchaelMainer** [comment]
The client doesn't currently support select statements within the expand method unless you put the select string in the expand method.

**Comment by BrennanAldridge** [comment]
@MIchaelMainer,

Right. That's what the issue is. You CAN put the select statement inside expand with expand($select...). This return results in Graph Explorer / browser...

The issue is that the JavaScript SDK (which is called from MSGraphClient for SPFX) appears to incorrectly parse the path, dropping everything after select=
