### ISSUE TITLE
Access is denied. Check credentials and try again

### ISSUE THREAD

**Issue by faizan1990** [microsoftgraph/msgraph-sdk-javascript#282]
I am using `/user/id/events` endpoints using the documentation here:

https://docs.microsoft.com/en-us/graph/api/user-list-events?view=graph-rest-1.0&tabs=http

These are my current permissions:

```
Calendars.Read (Admin consent granted)
Group.Read.All (Admin consent granted)
User.Read.All (Admin consent granted)
```

This is the error I am getting when I am hitting the endpoint using your NodeJS SDK:

`Access is denied. Check credentials and try again.`

Please advise

**Comment by MIchaelMainer** [comment]
Looks like you got it working with https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/283.

**Comment by faizan1990** [comment]
@MIchaelMainer No I have not mate! Please reopen this one too. Thank you

**Comment by sundariragavan** [comment]
@faizan1990 I'm also facing the same issue. can you please explain how you fixed this issue ?

**Comment by faizan1990** [comment]
Hi @sundariragavan I am not sure the exact error your are getting. Please have a look at https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/283 as advised by Michael. If that doesn't fix your problem then this issue needs to be reopened as I have already requested on 8 May 2020. All the best
