### ISSUE TITLE
Invalid Client in MS Graph Node JS Mail endpoint

### ISSUE THREAD

**Issue by faizan1990** [microsoftgraph/msgraph-sdk-javascript#283]
![Screen Shot 2020-05-08 at 12 31 31 am](https://user-images.githubusercontent.com/13532645/81306867-53f7e980-90c3-11ea-98bf-119376f968a4.png)

I am using the QuickStart as documented here: https://developer.microsoft.com/en-us/graph/get-started/node.js

Everything is working as expected. I am able to see `/users` and `/groups` endpoints working perfectly fine. However, the moment I add `Mail.ReadBasic.All` in the `.env` file of my Node JS App, I get `invalid_client` error as soon the sign in process finishes. Removing it makes everything back to normal. These are my current permissions setup in Azure App Registration:

Calendars.Read (Admin consent granted)
Group.Read.All (Admin consent granted)
User.Read.All (Admin consent granted)
Mail.Read (Admin consent granted)
Mail.ReadBasic (Admin consent granted)
Mail.ReadBasic.All (Admin consent granted)

Please help!

**Comment by MIchaelMainer** [comment]
`Mail.ReadBasic.All` is not supported for delegated permissions; it is app-only.

**Comment by faizan1990** [comment]
@MIchaelMainer Where in my question I mentioned that I have set it up for delegated permissions mate? Those all permissions are application-level only and I am still getting that `invalid_client` error as soon I put `mail.readbasic.all` in `.env` file. Please re-open the issue as it is not resolved for me

**Comment by MIchaelMainer** [comment]
@faizan1990 You are starting with this, https://github.com/microsoftgraph/msgraph-training-nodeexpressapp, correct? This is a web application where the user logs in which means the user delegated permission to the application to act on behalf of the user. Mail.ReadBasic.All is not supported for delegated permissions; it is app-only. A user cannot consent to or use Mail.ReadBasic.All.

https://docs.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=http

**Comment by faizan1990** [comment]
@MIchaelMainer No I am not using that first link you shared. If you go to the link I shared in my initial question, it contains:
1. Quick Start
2. Build your first application
3. Download the SDK

I am using Quick Start to get it setup.

Regardless of that, my API permissions in Azure are set to application level (they are NOT delegated) and **consent has been granted by Admin with green ticks on all of them**.

I am not trying to use Mail.ReadBasic.All as a delegated user. I am only using it from an app.

**Comment by MIchaelMainer** [comment]
The quickstart link you provided is the first step on the path to eventually download a zip file of the contents of the repo I linked to, [msgraph-training-nodeexpressapp](https://github.com/microsoftgraph/msgraph-training-nodeexpressapp).

![image](https://user-images.githubusercontent.com/8527305/81357973-fe531b00-9089-11ea-8a13-e44a0ebf2981.png)

It doesn't matter that an admin granted the Mail.ReadBasic.All permission for that application as that is an Application permission, and this webapp is operating under the context of the user. A user cannot use an Application permission. A user can use Delegated permissions. The openid configuration set in .env is for user authentication, so Mail.ReadBasic.All should not be in there. Try adding another permission in .env that is a Delegated permission. It will work.

Now then, your application registration has admin consent for those Application permissions; Calendars.Read, Group.Read.All, Mail.Read, Mail.ReadBasic, Mail.ReadBasic.All, and User.Read.All. Your application can make calls that use those permissions. You will need to implement client credential flow to have your application make calls without a user context. Please take a look at [Microsoft identity platform and the OAuth 2.0 client credentials flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) for more information.

**Comment by faizan1990** [comment]
I think I partially understand what you are trying to say. Can you please clarify for me that this

```
https://login.microsoftonline.com/common/adminconsent?client_id=6731de76-14a6-49ae-97bc-6eba6914391e&state=12345&redirect_uri=http://localhost/myapp/permissions
```

is not same as this:

![grant-admin-perms](https://user-images.githubusercontent.com/13532645/81364675-90f6c700-9129-11ea-9f1d-51862064fc13.png)

Secondly, when I am trying to to hit this URL:

https://login.microsoftonline.com/common/adminconsent?client_id=6731de76-14a6-49ae-97bc-6eba6914391e&state=12345&redirect_uri=http://localhost/myapp/permissions

with my client_id and redirect_uri, I get 404 not found in callback. Please advise.

**Comment by MIchaelMainer** [comment]
Using the admin consent URL and granting admin consent from within the Azure Portal has the same effect: that application has been granted Application permissions to access the tenant. 

The second part is not important for you at this point as you only need to grant permission once. At this point, you should focus on enabling client credential flow to access the functionality you want in mail.readbasic.all.

**Comment by faizan1990** [comment]
If using the /adminconsent URL and Granting permission via GUI is the same thing, then I am not sure what to look at in the link you sent (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow)

Can you please tell me how exactly to enable client credential flow to access the functionality I want in mail.readbasic.all? Is there any documentation on Graph site about that?

Thanks a lot!

**Comment by faizan1990** [comment]
Okay, I have finally managed to get it working! I must say, unfortunately the documentation is not very clear, not for me at least. The whole logic to get your app working as a service is hidden deep within one of the authentication-related docos, whereas it should have been more prominent in the API reference. For those who are still seeking a solution and have same problem as mine, simply:

1. Make a GET request to `https://login.microsoftonline.com/{tenant}/adminconsent?` with `client_id`, `state`, and `redirect_uri`

2. Then make a POST request to `https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token` with `client_id`, `client_secret`, `scope`, and `grant_type` as `body` and `Content-Type: application/x-www-form-urlencoded` has `header` of POST request. You will be provided with a Bearer token

3. Use that token to make Application privileged API endpoints!
