### ISSUE TITLE
Is it possible to use loginRedirect with ImplicitMSALAuthenticationProvider?

### ISSUE THREAD

**Issue by ajzeigert** [microsoftgraph/msgraph-sdk-javascript#286]
I noticed this note in the documentation that when initializing the `UserAgentApplication` in the section titled **2. Authenticate for the Microsoft Graph service** :

```
// Important Note: This library implements `loginPopup` and `acquireTokenPopup` flow, remember this while initializing the `msal` agent.
```

Is this a necessary limitation? Is there any way to use `loginRedirect` and `acquireTokenRedirect`?

**Comment by MIchaelMainer** [comment]
This is supported. The old Graph Explorer application uses redirect. 

https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/646a4cf589735c07b418bf3bb3087dadf206ed40/src/app/services/graph-client/msal-service.ts

https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/646a4cf589735c07b418bf3bb3087dadf206ed40/src/app/services/graph-client/msal-agent.ts
