### ISSUE TITLE
question VerifyIdToken

### ISSUE THREAD

**Issue by FridMehdi** [microsoftgraph/msgraph-sdk-javascript#288]
From my front (React) I get tokenId (rawToken.....) with msal.js; 
I want to send this to my ServerApi(NodeJs) endpoint and verify this tokenId with my appId then do my logic of login... 
```
FYI accessToken = Null // InFront 
```
Question : After some research I find that probably I need to use @microsoft/microsoft-graph client, but I didn't find how to verify my tokenId ?
```
for example google-auth-library provides a function(OAuth2)
named verifyIdToken make me able to do this kind of staff   
```

**Comment by ddyett** [comment]
apologies for not responding here due to staffing issues.  From what I understanding this is outside of the js sdk so i'm closing this issue.
