### ISSUE TITLE
Using within Electron

### ISSUE THREAD

**Issue by MichaelRoger** [microsoftgraph/msgraph-sdk-javascript#289]
Hi,
i tried to use the client within an electron-app.
but always get an error, because it opens up an PopUp what the electron-app could not handle.

hope you got an solution.

**Comment by ddyett** [comment]
can you provide a code sample of what you are calling in the SDK?

**Comment by MichaelRoger** [comment]
`export class Office365API {
    private msalConfig: Msal.Configuration = {
        auth: {
            clientId: "....", // Client Id of the registered application
            redirectUri: "http://localhost:3000/",
            authority: "https://login.microsoftonline.com/.....",

        }, cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: false
        }
    };
    private graphScopes = ["user.read", "user.readwrite"]; // An array of graph scopes

    private msalApplication = new Msal.UserAgentApplication(this.msalConfig);
    private options = new MSALAuthenticationProviderOptions(this.graphScopes);
    private authProvider = new ImplicitMSALAuthenticationProvider(this.msalApplication, this.options);
    private clientOptions: MicrosoftGraph.ClientOptions;

    private client: MicrosoftGraph.Client;

    static readonly Instance: Office365API = new Office365API();
    private constructor() {
        this.clientOptions = {
            authProvider: this.authProvider // An instance created from previous step
        };

        this.client = MicrosoftGraph.Client.initWithMiddleware(this.clientOptions);


    }
}`

**Comment by MichaelRoger** [comment]
Found a solution:

new BrowserWindow({
    width: 900,
    height: 680,
    webPreferences: {
      nodeIntegration: true,
      nativeWindowOpen: true,
      safeDialogs: false,
      webSecurity: true
    }
  });

i had to configure electron...

thanks
