### ISSUE TITLE
URLs containing escaped or unescaped equals characters are truncated or extraneous text added

### ISSUE THREAD

**Issue by markwahl-msft** [microsoftgraph/msgraph-sdk-javascript#291]
**Describe the bug**
A partner reports that the new Graph Explorer fails to submit the following GET request:

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/88b35805-6815-4334-ae57-ef2010e4c855?$expand=accessPackageAssignmentPolicies,accessPackageResourceRoleScopes($expand=accessPackageResourceRole,accessPackageResourceScope)

It seems to only request the following url, truncating the end:

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/88b35805-6815-4334-ae57-ef2010e4c855?$expand=accessPackageAssignmentPolicies,accessPackageResourceRoleScopes($expand=

The url works with other tools.

When attempting to use escape characters, I observed an even more surprising behavior, when I put into the URI field "%3D" in place of the "=" character (I changed the GUID to that from one or my tenants), then what it sent had a spurious "=undefined" at the end?

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/09378296-4cc6-4ce2-ab73-94fd2c4fdaff?$expand%3DaccessPackageAssignmentPolicies,accessPackageResourceRoleScopes($expand%3DaccessPackageResourceRole,accessPackageResourceScope)=undefined

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/graph/graph-explorer and sign in as an administrator user in a tenant where entitlement management is configured. 
2. Provide in the URI field the string

https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/?$expand=accessPackageAssignmentPolicies,accessPackageResourceRoleScopes($expand=accessPackageResourceRole,accessPackageResourceScope)

and click "Run query". 
4. See error of bad request returned.  In modern Edge, F12 shows that the request that was sent had
been truncated to https://graph.microsoft.com/beta/identityGovernance/entitlementManagement/accessPackages/?$expand=accessPackageAssignmentPolicies,accessPackageResourceRoleScopes($expand

**Expected behavior**

The URI that is entered by the user is sent to the service.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari]  Edge
 - Version [e.g. 22] 83.0.478.37 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MIchaelMainer** [comment]
This is likely in the JS client expansion.
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a4d34d640477edf917efd6b2fc839c588f5608c5/src/GraphRequest.ts#L193
