### ISSUE TITLE
Occasional "connect ETIMEDOUT" on different API endpoints

### ISSUE THREAD

**Issue by ChristianZerbes** [microsoftgraph/msgraph-sdk-javascript#292]
# Bug Report

## Description

I get occasional timeout errors on different API endpoints using this library. I would say 1 out of ~ 10 calls fail. Paths I tried, that fail from time to time: 

- GET /subscriptions
- GET /me/calendars/{id}/events/{id}

**Console Errors:** 
```
    GraphError {
      statusCode: -1,
      code: 'FetchError',
      message: 'request to https://graph.microsoft.com/v1.0/subscriptions failed, reason: connect ETIMEDOUT 40.126.9.51:443',
      requestId: null,
      date: 2020-06-13T07:10:11.076Z,
      body: 'FetchError: request to https://graph.microsoft.com/v1.0/subscriptions failed, reason: connect ETIMEDOUT 40.126.9.51:443'
    }
```

This is the code I'm using for the API call (with async/await): 
`response = await client.api("/subscriptions").get()`

When implementing a manual retry with a while loop it works the second time. 

**Expected behavior:** [What you expected to happen]
The API calls work every time without a timeout. 

**Actual behavior:** [What actually happened]
Timeouts occur from time to time (1 out of ~ 10 times)

## Additional Context
The call to /subscriptions is with a cyclic cron job, the call to /me/calendars/{id}/events/{id} is after receiving an event via the [subscribed notifications](https://docs.microsoft.com/en-us/graph/webhooks) and after trying to fetch the event data of the event id. 

## Usage Information

> SDK Version - 2.0.0
> Node Version - 12.16.3

**Comment by MIchaelMainer** [comment]
@baywet Can you take a look at this?

**Comment by baywet** [comment]
@MIchaelMainer this looks like a networking issue/client issue between client and AGS. I don't think the request gets to the AGS (and then to subscription store) at this point.

@ChristianZerbes do you have request ids to provide us so we can check the logs?

**Comment by baywet** [comment]
@MIchaelMainer Can you close this one due to lack of activity please?

**Comment by sirarchi** [comment]
Hello,

Could you help me with a similar situation? The problems occurs only in the Azure Functions environment, on local machine process ends without any problems.

"@microsoft/microsoft-graph-client": "3.0.2"

`FetchError: request to https://graph.microsoft.com/v1.0/groups/<IDHidden>/owners failed, reason: connect ETIMEDOUT 40.126.32.101:443at ClientRequest.<anonymous> (D:\home\site\wwwroot\node_modules\node-fetch\lib\index.js:1491:11)at ClientRequest.emit (events.js:314:20)at TLSSocket.socketErrorListener (_http_client.js:427:9)at TLSSocket.emit (events.js:314:20)at emitErrorNT (internal/streams/destroy.js:92:8)at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)at processTicksAndRejections (internal/process/task_queues.js:84:21) {statusCode: -1,code: 'FetchError',requestId: null,date: 2022-03-30T14:18:05.015Z,body: 'FetchError: request to https://graph.microsoft.com/v1.0/groups/<IDHidden>/owners failed, reason: connect ETIMEDOUT 40.126.32.101:443'}`

**Comment by sebastienlevert** [comment]
Looping in @nikithauc 

Do you have a repro @sirarchi? What are the endpoint your are calling? this really seems like a connectivity issue between your Azure Function and Graph. I would advise to catch this error and retry?

**Comment by sirarchi** [comment]
@sebastienlevert - Unfortunately, the code of this application is stored on the customer's private GitLab. If you want I can paste a part where requests are called.

I use endpoints: https://graph.microsoft.com/v1.0/groups/<GroupID>/owners and https://graph.microsoft.com/v1.0/groups/<GroupID>/members

Azure Functions is stored on Azure App Service Free Trier.

I tried to defer requests by pagination arrays to maximum 100 entries in "package", and it worked till last month.

**Comment by nikithauc** [comment]
@sirarchi may be this will help https://stackoverflow.com/questions/51523378/node-fetch-connect-etimedout-error ? 

> I tried to defer requests by pagination arrays to maximum 100 entries in "package", and it worked till last month.

Did any configuration change recently?  Did you update/modify the version of Graph JS SDK?
