### ISSUE TITLE
getEmailActivityCounts returns broken image

### ISSUE THREAD

**Issue by Hongbo-Miao** [microsoftgraph/msgraph-sdk-javascript#294]
When I try to run
GET https://graph.microsoft.com/beta/reports/getEmailActivityCounts(period='D7')

Graph Explorer shows an broken image (it returns csv file, so might because not support render csv file)

Same post, postman can show the result:
Report Refresh Date,Send,Receive,Read,Report Date,Report Period
2018-02-26,,1,,2018-02-26,7
2018-02-26,,,,2018-02-25,7
2018-02-26,,2,,2018-02-24,7
2018-02-26,,,,2018-02-23,7
2018-02-26,,,,2018-02-22,7
2018-02-26,,1,,2018-02-21,7
2018-02-26,,1,,2018-02-20,7
[AB#6000](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6000)

**Comment by MIchaelMainer** [comment]
Tracked in https://github.com/microsoftgraph/microsoft-graph-explorer-v4/issues/626.

**Comment by nikithauc** [comment]
No changes required for now.
