### ISSUE TITLE
Redirects and Browsers

### ISSUE THREAD

**Issue by finsharp** [microsoftgraph/msgraph-sdk-javascript#295]
When using msgraph-sdk-javascript in a browser the redirect handler is not registered, this means apps that depend on the js sdk, such as Graph Explorer cannot download file content that is provided through the redirect process. 

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a4d34d640477edf917efd6b2fc839c588f5608c5/src/HTTPClientFactory.ts#L57

**Comment by ddyett** [comment]
same as #294

**Comment by finsharp** [comment]
Closing
