### ISSUE TITLE
Is there a way to implement a "cancel token" feature?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-javascript#296]
In some scenarios you might have the necessity to implement a cancel token pattern to avoid executing HTTP calls if they are no more valid.
An example for such a scenario might be a people picker that executes HTTP call requests but stops once the state for the typed in values has changed.
You can find here an example how such a cancel token might work in react and Axios: https://stackoverflow.com/questions/42896831/cancel-axios-get-request-when-typing-reactjs
Is there a way to have a similar pattern implemented with the Graph SDK?
[AB#5998](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5998)

**Comment by MIchaelMainer** [comment]
Yes, this would be helpful for us to support in the client. Thank you for bringing this up.

**Comment by nikithauc** [comment]
@plamber. It is possible can a request currently when using the MS Graph JS SDK. 

References to cancel a fetch request - 
You can use the interface [FetchOptions](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/IFetchOptions.ts).
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal

Example -
```javascript
const AbortController = require('abort-controller');

const controller = new AbortController();
const timeout = setTimeout(() => {
	controller.abort();
}, 140);

const fetchOptions = {
	signal: controller.signal // set the fetchOptions Signal
}


const client = Client.initWithMiddleware({
		debugLogging: true,
		authProvider,
		fetchOptions // Set the fetch options here. 
		
});
```

**Comment by mitani** [comment]
@nikithaqprevent won't this only work if you use 1 client per request. I would have assumed the timeout would need to wrap around an abort controller for each request, and each request would need to have it's own fetch options so that it resets the timer per request.

**Comment by nikithauc** [comment]
@mitani 

You can also use the `options()` api in the GraphRequest ,that is, `client.api().options().get()` instead of setting the `options` while initializing the client. 

Is that what you are looking for?

**Comment by mitani** [comment]
Yes,  thank you @nikithauc it would be great if the example also reflected that use case.
