### ISSUE TITLE
retry-after set to 1 on every 429

### ISSUE THREAD

**Issue by gregory** [microsoftgraph/msgraph-sdk-javascript#297]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

We are receiving a "retry-after" set to 1 on v1 endpoint anytime we hit a 429. 

**Console Errors:** [Is there any console error]

{\"cache-control\":\"private\",\"content-type\":\"application/json\",\"retry-after\":\"1\",\"request-id\":\"02403262-4063-455c-9c8f-54f442b31343\",\"client-request-id\":\"02403262-4063-455c-9c8f-54f442b31343\",\"x-ms-ags-diagnostic\":\"{\\\"ServerInfo\\\":{\\\"DataCenter\\\":\\\"East US\\\",\\\"Slice\\\":\\\"SliceC\\\",\\\"Ring\\\":\\\"5\\\",\\\"ScaleUnit\\\":\\\"001\\\",\\\"RoleInstance\\\":\\\"AGSFE_IN_12\\\"}}\",\"preference-applied\":\"IdType=ImmutableId\",\"strict-transport-security\":\"max-age=31536000\",\"date\":\"Tue, 30 Jun 2020 16:14:48 GMT\",\"content-length\":\"255\"}","v":1}

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Hit endpoint until you have 429. 
2. Check the response headers. 

**Expected behavior:** 
I'd expect retry-after to be increasingly different 

**Actual behavior:** retry-after is always set to 1

**Comment by MIchaelMainer** [comment]
Which endpoint are you targeting when you receive this response?

**Comment by gregory** [comment]
/messages  @MIchaelMainer  - you can easily simulate the issue by running this query in the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer): 

```js
{"requests":[
{"url":"/me/messages?$select=subject&$top=1","method":"GET","id":"1"},
{"url":"/me/messages?$select=subject&$top=1","method":"GET","id":"2"},
{"url":"/me/messages?$select=subject&$top=1","method":"GET","id":"3"},
{"url":"/me/messages?$select=subject&$top=1","method":"GET","id":"4"},
{"url":"/me/messages?$select=subject&$top=1","method":"GET","id":"5"}
]}
```

which is going to return one 429: 
```js
{
    "responses": [
        {
            "id": "1",
            "status": 429,
            "headers": {
                "Retry-After": "1",
                "Cache-Control": "private"
            },
            "body": {
                "error": {
                    "code": "ApplicationThrottled",
                    "message": "Application is over its MailboxConcurrency limit.",
                    "innerError": {
                        "date": "2020-07-03T23:17:51",
                        "request-id": "1b613e8e-3aca-4871-a9b1-88ae09e5831d"
                    }
                }
            }
        },
```

**Comment by MIchaelMainer** [comment]
What happens when you respect the retry after 1 second? I'd expect that the request would succeed. If the retry consistently didn't work after 1 second, then I'd expect for the retry-after value to increase.

**Comment by gregory** [comment]
As far as i can see, it's always 1...

**Comment by MIchaelMainer** [comment]
So does respecting retry-after always result in another retry-after?

**Comment by gregory** [comment]
yeah it looks like it.

**Comment by MIchaelMainer** [comment]
That retry-after isn't being responsive to the number of connections. I don't think it could be since the throttling mechanism can't know how long a connection will need to complete. I suspect that the issue here is that Microsoft Graph is opening a connection for each request, and since all of the requests are targeting the same user mailbox on Exchange, it is quickly exhausting the connection count for that mailbox. In other words, the batch request isn't passed through to Exchange. The other issue is that the response can't be returned until all of the requests complete so this may actually be slower than making the requests in parallel **without** batch.

**Comment by ddyett** [comment]
this issue is not actionable by this team.  Closing with the service label to pass on.
