### ISSUE TITLE
ServerError auth.js

### ISSUE THREAD

**Issue by titodevera** [microsoftgraph/msgraph-sdk-javascript#310]
Hi all!

We are experimenting an issue when trying to auth in the Microsoft Graph API throught the Javascript SDK.
Our web application worked as expected for few months, until some days ago...

The login popup fires, but after introducing the email, the browser console throughts the error below:
`ServerError: The request is not valid for the application's 'userAudience' configuration.`

We are trying to consume the `https://graph.microsoft.com/beta/me/outlook/tasks?$top=100&$filter=status ne 'completed'` endpoint.

![Captura de pantalla 2020-08-05 a las 14 14 09](https://user-images.githubusercontent.com/11556124/89411598-f9a01080-d725-11ea-90f2-664a7d73f7e5.png)

Thank you so much!

**Comment by MIchaelMainer** [comment]
I suggest that you try cross posting this question in the MSAL GitHub repo.

https://github.com/AzureAD/microsoft-authentication-library-for-js

**Comment by titodevera** [comment]
Set the value "AzureADandPersonalMicrosoftAccount" for the property "signInAudience" in the manifest solves the issues.
![audience](https://user-images.githubusercontent.com/11556124/89775666-9ab50f80-db08-11ea-95c2-abddcbdbf848.png)

**Comment by isleven** [comment]
> Set the value "AzureADandPersonalMicrosoftAccount" for the property "signInAudience" in the manifest solves the issues.
> ![audience](https://user-images.githubusercontent.com/11556124/89775666-9ab50f80-db08-11ea-95c2-abddcbdbf848.png)

it works.
