### ISSUE TITLE
PageIterator should allow for sending headers with each page request

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-javascript#311]
Feature Request
PageIterator should expose an option to include headers each time it makes a nextLink request. Currently using PageIterator with calendar list requests when you also use the Prefer: outlook.timezone="" header causes a problem. The results in the first page (that you make yourself and include the header), return dateTime values in the requested time zones. Results in subsequent pages do not.
Describe the solution you'd like
Add this to PageIterator. One suggestion would be:
await pageIterator.iterate().withHeaders({
  "Prefer": "outlook.timezone=\"Pacific Standard Time\""
});

Describe alternatives you've considered
Additional context
Repro code:
const startOfWeek = '2020-08-02T07:00:00';
const endOfWeek = '2020-08-09T07:00:00';

let response = await graphClient
  .api('/me/calendarview')
  // Set the Prefer=outlook.timezone header so date/times are in
  // user's preferred time zone
  .header("Prefer", `outlook.timezone="Pacific Standard Time"`)
  // Add the startDateTime and endDateTime query parameters
  .query({ startDateTime: startOfWeek, endDateTime: endOfWeek })
  // Select just the fields we are interested in
  .select('subject,organizer,start,end')
  // Sort the results by start, earliest first
  .orderby('start/dateTime')
  // Maximum 50 events in response
  .top(5)
  .get();

// If there are more results, use a PageIterator to get them all
if (response['@odata.nextLink']) {
  console.log('Need to iterate');
  let events = [];

  const pageIterator = new MicrosoftGraph.PageIterator(
    graphClient, response, (event) => {
      events.push(event);
      return true;
    }
  );

  await pageIterator.iterate();

  console.log(JSON.stringify(events));
} else {
  console.log(JSON.stringify(response.value));
}

You'll note that the first 5 events have the times correct in Pacific, but the rest are in UTC.
[AB#5628](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5628)

**Comment by jasonjoh** [comment]
I did come up with a workaround, but it requires a lot of extra code I shouldn't have to write :D. Basically I have to create a custom HTTP handler:

```
const authHandler = new MicrosoftGraph.AuthenticationHandler(authProvider);

const httpHandler = {
  nextMiddleWare: undefined,

  execute: async(context) => {
    // ASSUMPTION: context.options will always be defined
    // This is gonna crash if not.
    if (context.options.headers) {
      // ASSUMPTION: The Prefer header isn't already set. This will overwrite
      // if it is
      context.options.headers = Object.assign(context.options.headers, {
        Prefer: 'outlook.timezone="Pacific Standard Time"'
      });
    } else {
      context.options.headers = {
        Prefer: 'outlook.timezone="Pacific Standard Time"'
      };
    }
    try {

      let response = await fetch(context.request, context.options);
      context.response = response;
      return;
    } catch (error) {
      throw error;
    }
  },

  setNext: (middleware) => {
    this.nextMiddleWare = middleware;
  }
};

authHandler.setNext(httpHandler);

const timezoneGraphClient = MicrosoftGraph.Client.initWithMiddleware({
  defaultVersion: 'v1.0',
  middleware: authHandler
});
```

**Comment by ddyett** [comment]
Thanks for reporting
