### ISSUE TITLE
How to use my own access token?

### ISSUE THREAD

**Issue by mjuliefr** [microsoftgraph/msgraph-sdk-javascript#315]
I am using firebase with Microsoft oauth provider. My user is successfully logged in and I want to get details on the user login via msgraph.

async function signInMS() {

  console.log("signInMS called");
  var provider = new firebase.auth.OAuthProvider('microsoft.com');

  provider.addScope('User.Read');
     
  firebase.auth().signInWithPopup(provider)
    .then( function (result) {
      alert("user authenticated");
    });
    
    const options = {
      provider, // An instance created from previous step
      };
      const Client = MicrosoftGraph.Client;
      const client = Client.initWithMiddleware(options);

    try {
      let userDetails = await client.api("/me").get();
      console.log(userDetails);
    } catch (error) {
      throw error;
    } 
}
I am getting this error ... Please provide either authentication provider

graph-js-sdk.js:1 Uncaught (in promise) InvalidMiddlewareChain: Unable to Create Client, Please provide either authentication provider for default middleware chain or custom middleware chain
    at new e (https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js:1:54501)
    at Function.value (https://cdn.jsdelivr.net/npm/@microsoft/microsoft-graph-client/lib/graph-js-sdk.js:1:55025)
    at signInMS (http://localhost:5500/public/scripts/auth-provider.js:78:29)
    at HTMLButtonElement.onclick (http://localhost:5500/public/index.html:86:66)
Provider is defined via Firebase, so I am not sure what is wrong.

**Comment by mjuliefr** [comment]
Hi,

I tried few things but it does not work. I have an access token from firebase. This access token is actually an Microsoft OAuth access token. How can I use this token, please?

I found two interesting issues which could help me:
https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/253 where the access token seems to be specified
https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/265 mentioning a way to initialize the client if you have accessToken already.

The code I tried with both alternatives (not at the same time but one after another) but it seems that I can succeed to impose my token and initialize the client.
I would really appreciate some help, please.

```
async function signInMS() {
// Firebase Provider setup
  var provider = new firebase.auth.OAuthProvider('microsoft.com');
  provider.addScope('User.Read');
  provider.addScope('Files.ReadWrite.All');
  provider.addScope('offline_access');
  provider.addScope('MailboxSettings.ReadWrite');
// Firebase SignIn  
  firebase.auth().signInWithPopup(provider)
    .then( async function (result) {
      alert("user authenticated");
     var token = result.credential.idToken;
      var pToken = result.credential.accessToken;
      console.log("token===", pToken);   // the MS token 

// Alternative 1 from issue 253
       const getMe = async (userPrincipalName) => {
 try {
         /* const { access_token: accessToken } = JSON.parse(await request.post({ url: `${credentials.auth.tokenHost}/${credentials.auth.tokenPath}`, form: requestParams })); */
// change to : 
 const { access_token: accessToken } = pToken ; 
          const client = graph.Client.init({
            authProvider: (done) => {
              done(null, accessToken);
            },
          });          
          let userDetails = await client.api("/me").get();
          console.log("Me===",userDetails);
          return userDetails;
        } catch (err) {
          console.log("err===", err);
          return (Error(err));
        }
      };
 
// Or Alternative 2 from issue 265
 try {
      const authenticationHandler = new AuthenticationHandler(provider);
      const retryHandler = new RetryHandler(new RetryHandlerOptions());
      const httpMessageHandler = new HTTPMessageHandler();
      authenticationHandler.setNext(retryHandler);
      retryHandler.setNext(httpMessageHandler);
      let client = Client.initWithMiddleware({
          middleware: authenticationHandler
      });   
           let userDetails = await client.api("/me").get();
           console.log(userDetails);
         } catch (error) {
           throw error;
         }
    });    
} // end MSSignIn
```

**Comment by nikithauc** [comment]
Hello Julie,

Thank you for providing the your code snippets in the explanation! 

1. Please check if the following links are helpful -

- [Creating Client Instance](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CreatingClientInstance.md)
- [Custom Authentication Provider](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md)


2. If you wish to run a simple code example like `client.api(/me).get()` I would suggest the following -

- Go to [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) . Login with the valid credentials. After a successful login, please find the access token option highlight in the image and copy paste the access token in your code.
![image](https://user-images.githubusercontent.com/23219007/90991237-79b6da80-e55c-11ea-80b5-7f2c703df45b.png)

- Use this access token to run a sample code (Alternative 1 from issue 253) in your project. Example - [Node Code Example](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/node/main.js), [Node ReadMe](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/node/README.md) , [Browser Code Example](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/browser/src/main.js), [Browser Readme](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/browser/README.md)

Please let me know if you have more questions.

Regards,
Nikitha

**Comment by mjuliefr** [comment]
Hi Nikitha,

Thanks a lot!
I am able to fetch my data.
