### ISSUE TITLE
CORS Issue when using Hosted WorkBench

### ISSUE THREAD

**Issue by mikebedwards1** [microsoftgraph/msgraph-sdk-javascript#316]
Bug Report
Prerequisites

 Can you reproduce the problem?
 Are you running the latest version?
 Are you reporting to the correct repository?
 Did you perform a cursory search?

Description
Trying to access a file contents using MSGraphClient - getting a 403 CORS error when using the hosted workbench. API Call works ok from deployed app in catalog, but not the hosted workbench on the same site collection.
URL I am using is
`	.api('/sites/{tenant}.sharepoint.com,{guid},{guid}/lists/{guid}/items/1/driveitem/content'}
Works in app catalog and Graph explorer - but not in hosted workbench.
`
Console Errors: [Is there any console error]
403 Forbidden / CORS / Access denied
Screenshots: [If applicable, add screenshots to help explain your problem]
Steps to Reproduce

Create a SPFX solution that uses msGraphClientFactory
Pass Graph API Url that access an existing file in a SP Library, console.log the response object
build and package, upload to app catalog, embed in a sharepoint site - observe the response object as expected
run gulp server --no browser
Go to hosted workbench on same site collection, embed webpart
Observe error message - 403, cors
[AB#5996](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/5996)

**Comment by MIchaelMainer** [comment]
@baywet

**Comment by baywet** [comment]
@nikithauc let me know if you want to setup 30 minutes so I can help you get started with SPFx

**Comment by nikithauc** [comment]
Looks like this is related to https://github.com/microsoftgraph/microsoft-graph-docs/issues/43. 
@mikebedwards1 Please check if the workaround suggested in the [comment ]( https://github.com/microsoftgraph/microsoft-graph-docs/issues/43#issuecomment-161519722) works for you. 

Please check if the  following workaround works for you
Get the download URL for the item you wish to access as follows -

Example - 
`https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')?$select=@microsoft.graph.downloadUrl` and use the URL to download the file.

@finsharp  Thank you for your help with this workaround! 

More information - 
https://stackoverflow.com/questions/3749231/download-file-using-javascript-jquery/3749395#3749395
https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/16

**Comment by nikithauc** [comment]
Closing this as this is a known issue. Shall update if the CORS issue gets resolved.
