### ISSUE TITLE
Support for msal.js 2.0+

### ISSUE THREAD

**Issue by kunalkankariya** [microsoftgraph/msgraph-sdk-javascript#317]
Is there a plan to support msal.js 2.0+?

Since implicit grant flow is no longer recommended and auth code flow with PKCE is recommended.

**Comment by nikithauc** [comment]
This is being looked into. I will let you know how we will plan to support Auth Code.

**Comment by nikithauc** [comment]
Hi @kunalkankariya,

The plan to support MSAL 2.0 is still under discussion. However, currently we are working on including [@azure/identity](https://www.npmjs.com/package/@azure/identity) into Microsoft Graph JavaScript SDK. That should  support auth code flow. 

Please let me know if you have more questions.

**Comment by kunalkankariya** [comment]
Thank you @nikithauc for the updates. 

Does this mean that auth code flow will be used without PKCE? What will be the lifetime of refresh tokens then?

**Comment by nikithauc** [comment]
Hello @kunalkankariya ,

You can use a credential class which suits your requirement. JS SDK will be implementing an authProvider class with  [TokenCredential](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/core/core-auth/src/tokenCredential.ts) property and a method to get the access token.  
Also, if you do not find a credential class that suits your requirement, you can implement a custom authentication provider. [Doc](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md)
References which could help -
[Credential classes](https://www.npmjs.com/package/@azure/identity#credential-classes)
[Documentation reference](https://docs.microsoft.com/en-us/javascript/api/@azure/identity/authorizationcodecredential?view=azure-node-latest)
[Azure Identity GitHub Sample](https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/identity/identity/samples/authorizationCodeSample.ts)

**Comment by nikithauc** [comment]
Closing this issue. Please let me know if there are more questions.
