### ISSUE TITLE
Expose function to convert from Windows time zones to IANA time zones

### ISSUE THREAD

**Issue by ldorner** [microsoftgraph/msgraph-sdk-javascript#327]
# Feature Request

## Is your feature request related to a problem? Please describe

It's often necessary to convert from Windows time zones (which are expected by and returned from the MSGraph API) to IANA time zones (which are utilized by most other services). In the past, we have solved this problem by maintaining our own mapping of Windows <-> IANA time zones within our projects. However, this approach is cumbersome and susceptible to bugs due to unintentionally missing time zones, updates, etc. It seems like it would be more reasonable for the SDK to provide this functionality than for consumers to recreate these mappings individually.

## Describe the solution you'd like

It would be ideal if the MSGraph SDK could expose functions to convert between Windows time zones and IANA time zones. For example, something like:
`toIanaTimeZone(windowsTimeZone)` // takes a Windows time zone and returns the equivalent IANA time zone ID
`fromIanaTimeZone(ianaTimeZone)` // takes an IANA time zone and returns the equivalent Windows time zone

## Describe alternatives you've considered

We have maintained our own mapping of Windows <-> IANA time zones within our projects, but this is cumbersome and susceptible to bugs. There is also at least one external library that attempts to fulfill this need; however, I have the same concerns regarding correctness and reliability.

**Comment by MIchaelMainer** [comment]
Here's the related .NET implementation:

https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/src/Microsoft.Graph/Models/Extensions/DateTimeZoneExtensions.cs

**Comment by baywet** [comment]
@MIchaelMainer were we expecting the bot to close that issue?

**Comment by MIchaelMainer** [comment]
@baywet Yes, I expected the bot to close this as we tagged this with Needs: Author Feedback which assumes that we were asking the author for more information and didn't provide it so they must not be interested in the issue any longer. 

I will reopen.

**Comment by baywet** [comment]
thanks. Apparently I setup the tag for a reason I don't remember. Sorry about that.

**Comment by jpbufe3** [comment]
@baywet @MIchaelMainer - any updates or ETAs on this?

**Comment by ldorner** [comment]
Thanks for reopening! We're still interested in this feature. Please let me know if there is any additional information that I can provide.

**Comment by nikithauc** [comment]
@ldorner @jpbufe3 I will add this in my to-do tasks and see if I can release this feature soon.

**Comment by nikithauc** [comment]
@idorner @jpbufe3  After some discussions on this feature, we feel that this feature does not align with the current scope of the JavaScript SDK, therefore we will not be including this in our roadmap.
 
Thank you for submitting the request! Please do let us know of any other requests you might have.

**Comment by baywet** [comment]
FYI people, there are a few libraries to do that for you like [this one](https://github.com/rubenillodo/windows-iana)

**Comment by wallind** [comment]
> 
> 
> FYI people, there are a few libraries to do that for you like [this one](https://github.com/rubenillodo/windows-iana)

this recommendation is 🔥. The alternative I was looking at was just not harvesting timezone data. If you need IANA timezones from the `/mailboxSettings/timeZone` endpoint data this answer is your answer
