### ISSUE TITLE
Graph API not granting requested permissions in the first time

### ISSUE THREAD

**Issue by kayvee25** [microsoftgraph/msgraph-sdk-javascript#328]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

My application is calling the Graph API to exchange a code for the access token in the OAuth flow. 
I followed the steps in [this documentation](https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph/api/1.0) to implement this flow.
The application is not being granted all the permissions that it has requested the first time around, when the consent screen is shown to the user for the first time. When the same process is repeated (consent screen is not shown), the application receives all the permissions that were requested from the Azure portal. 

**Console Logs:** 
Response from Graph API after the first call: 

```
data: {
  token_type: 'Bearer',
  scope: 'profile openid email https://graph.microsoft.com/.default',
  expires_in: 3599,
  ext_expires_in: 3599,
  access_token: 'ey...',
  refresh_token: '0.AA...'
}
```

Response from Graph API after the second call:
```
data: {
  token_type: 'Bearer',
  scope: 'email openid profile https://graph.microsoft.com/Team.ReadBasic.All https://graph.microsoft.com/TeamsAppInstallation.ReadWriteSelfForTeam https://graph.microsoft.com/User.Read https://graph.microsoft.com/User.ReadBasic.All https://graph.microsoft.com/.default',
  expires_in: 3599,
  ext_expires_in: 3599,
  access_token: 'ey...',
  refresh_token: '0.AA...'
}
```

## Steps to Reproduce

1. Set up an application in Azure portal
2. Set up the server and implement the OAuth flow:
Sample code: 
Function used to get the access token
```
async function getAccessToken(authCode) {
    const { APP_ID: client_id, APP_PWD: client_secret, REDIRECT_URI } = this.config
    const postData = {
        client_id,
        client_secret,
        scope: 'https://graph.microsoft.com/.default',
        grant_type: 'authorization_code',
        redirect_uri: `${REDIRECT_URI}api/web/redirect`,
        code: authCode,
    }
    axios.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded'
    const { data } = await axios.post(
        'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        qs.stringify(postData)
    )
    return data
}
```
3. Pass the authorization code from Graph API to the above function and check the data that is returned

**Expected behavior:** Every call of this function should return an access token with all the scopes that are configured in the Azure portal

**Actual behavior:** The first call of this function returns an access token with none of the requested scopes, but every subsequent call returns the requested permissions

## Usage Information

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - 8.17.0

 
[AB#7547](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7547)

**Comment by MIchaelMainer** [comment]
Please ask this question using the feedback link at the bottom of this page:

https://docs.microsoft.com/en-us/graph/auth-v2-user?context=graph/api/1.0

You may want to review this as well:
https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-node

This repo is specifically for the Microsoft Graph library issues you encounter once you have a valid access token.
