### ISSUE TITLE
How to get the selected event Id in outlook calendar Add Ins

### ISSUE THREAD

**Issue by sundariragavan** [microsoftgraph/msgraph-sdk-javascript#332]
I have added Add Ins in Outlook Calendar. I want to get the selected event id. If i use /me/events I'm getting multiple events. I need selected event id only. How to get the selected event id ??

**Comment by sundariragavan** [comment]
https://stackoverflow.com/questions/64157819/is-it-possible-to-programmatically-access-the-selected-appointment-event-in-ou 
Is it possible to programmatically access the selected appointment (event) in outlook using Office Add In

**Comment by ddyett** [comment]
Have you tried /me/events/{event-id}?

**Comment by MIchaelMainer** [comment]
This is a great question for StackOverflow. You'll get many more eyes on your question there with both the Outlook addins and MicrosoftGraph tags. Please put a link to your post here.

**Comment by MIchaelMainer** [comment]
Closing as this is primarily a question about Office add-ins. See github.com/officedev for more information, including samples.
