### ISSUE TITLE
OData query options without $. 

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#341]
> On the beta endpoint, the $ prefix is optional. For example, instead of $filter, you can use filter. On the v1 endpoint, the $ prefix is optional for only a subset of APIs - [Source](https://docs.microsoft.com/en-us/graph/query-parameters).

The JS-client client currently considers <query option> & <$query option> as two different query param keys. Should this be changed? Or do we wait till the service consistently allows a query option with/without $ for all endpoints? 
[Discussion](https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/338#discussion_r501660359) 
[AB#7548](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7548)

**Comment by baywet** [comment]
I'm not sure the AGS team has been actively working on that recently or plans to.
My opinion on the matter is that the SDK should not get "in the way" of people. If they want to work with select (without $), and the service accepts it (even partially), it should just work. That's also a way to future proof our SDK for the day the change rolls out consistently.

**Comment by ddyett** [comment]
closing older issue
