### ISSUE TITLE
Cannot fetch chat ids: It's malformed and fires multiples onConversationUpdate events

### ISSUE THREAD

**Issue by aailenm** [microsoftgraph/msgraph-sdk-javascript#343]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I'm having some issues when attempting to fetch the chat id for a specific user using this request:

GET /beta/users/{USER-ID}/teamwork/installedApps/{installation-id}/chat

The one returned doesn't match with the original one (gotten from the onConversationUpdate event), and doesn't work if I try to send a notification to it
It fires at least one "onConversationUpdate" event for that user (Sometimes fires two or three)
Is that the expected behavior for this operation?

## Steps to Reproduce

https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=csharp#enable-proactive-app-installation-and-messaging

**Expected behavior:** 
The response of that request returns the chat id between the user and the application.

**Actual behavior:**
- The response returns a chat id that has the same shape of a chat id, but it fails with HTTP STATUS 400 
BAD REQUEST when attempting to send a proactive notification
- When the GET is fired, the application receives at least one `onConversationUpdate` event. The payload of this event contains the correct chat id. Sometimes, it fires two or three events for the same person.

## Usage Information

SDK Version - 2.0.0

-   [X] Node (Check, if using Node version of SDK)

> Node Version - 10.16.0

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - N/A
> Version - N/A

**Comment by MIchaelMainer** [comment]
I suggest that you create this issue with a link at the bottom of the page as it looks like this may be an issue in the sample.

https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?tabs=javascript#view-additional-code-samples

Once you create that issue, please post a link to this issue.
