### ISSUE TITLE
Error in a request to download a file from a drive

### ISSUE THREAD

**Issue by victorreis** [microsoftgraph/msgraph-sdk-javascript#344]
# Error in a request to download a file from a drive

## Prerequisites

-   [x] Can you reproduce the problem? Yes.
-   [X] Are you running the latest version? Yes.
-   [X] Are you reporting to the correct repository? Yes.
-   [X] Did you perform a cursory search? Yes.

## Description

I'm developing a API to manage files from a drive and I'm getting error when I try to download a file by his ID. There is no error when trying in Postman or when trying via Axios.

The request is:
GET `https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')/content`

## Here is my code:

The Microsoft Graph Client, configured to get the token:
![image](https://user-images.githubusercontent.com/8744178/96654430-aba4ad00-1311-11eb-8bda-820f5c2f3c2d.png)

Here is where I'm trying to download the file:
![image](https://user-images.githubusercontent.com/8744178/96655935-1dcac100-1315-11eb-97bd-682f9cb3d916.png)

## Console Errors:

![image](https://user-images.githubusercontent.com/8744178/96654241-36d17300-1311-11eb-985f-b4a034febaed.png)

## DEBUGGING PERCEPTIONS:

Here is the correct functioning of the .get(), the token is present. I got this example of other request that works fine:
![image](https://user-images.githubusercontent.com/8744178/96653898-85324200-1310-11eb-8a5e-9673dd05eb6b.png)

Here is the wrong functioning of the .get(), the token is not present and then I get an Error:
![image](https://user-images.githubusercontent.com/8744178/96654150-07226b00-1311-11eb-9dcb-6c99e7bb78b7.png)

## Usage Information

@microsoft/microsoft-graph-client version - 2.1.0
Node Version - 12.18.4

**Comment by nikithauc** [comment]
@victorreis  Thank you for reporting this issue. 
Can you please give me the steps  to reproduce this issue?  In the description of this issue you mentioned 'I'm getting error when I try to download a file by his ID.' Can you give me some specifics of the type of account/access token or the ID you are describing here? 

Are you querying the 'Graph API' directly through Postman with the url 'https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')/content' and facing the same issue?

**Comment by victorreis** [comment]
Hi @nikithauc ,

The steps to reproduce are below:

Call this orchestrator function:
![image](https://user-images.githubusercontent.com/8744178/96867634-58327c00-1443-11eb-949d-074289fa6aea.png)

That gets the site details: [token works fine here]
![image](https://user-images.githubusercontent.com/8744178/96867695-700a0000-1443-11eb-89fc-a3e1e6ce6b8f.png)

That get drive details: [token works fine here]
![image](https://user-images.githubusercontent.com/8744178/96867757-831cd000-1443-11eb-82b9-3282bcd0efeb.png)

And then tries to download the file: [token wasn't get there]
![image](https://user-images.githubusercontent.com/8744178/96867950-be1f0380-1443-11eb-807b-b4869f65b71c.png)

---

The "authProvider" function calls this function, that responds the type of authorization:
![image](https://user-images.githubusercontent.com/8744178/96869511-ee67a180-1445-11eb-919a-a78cc3668e73.png)

**Maybe this is caused by 3 consecutive calls of token. I don't know how Microsoft Graph Client manages the "authProvider" calls. There are a recommended way to store the token in my ExpressJS API?**

---

In Postman I'm trying the same URL and it works fine:
https://graph.microsoft.com/v1.0/sites('fadepe.sharepoint.com,50f624f6-f611-4673-a395-95372361278a,6f4e18b8-1cbf-41e0-b648-62e27b341416')/drives('b!9iT2UBH2c0ajlZU3I2EnirgYTm-_HOBBtkhi4ns0FBYeH0RbzD2-RICyt_5R8AH-')/items('01EDJ7RTUWZ7Y7MEYE6JHYQEUQJXUJ56A2')/content

And if I get the code generated by Postman it will works fine in my code, but I makes Microsoft Graph useless.
![image](https://user-images.githubusercontent.com/8744178/96869846-6cc44380-1446-11eb-8a8f-90e808a36a8c.png)

**Comment by victorreis** [comment]
Hi @nikithauc ,

I tested put the ids and the token hard coded and the error persists, the token isn't sent.
I don't understanding why msGraphClient calls authProvider correctly (I checked) and do not put the token just in this case of the download a file.

Even when I put the skip token with a hard coded token it doesn't work.
![image](https://user-images.githubusercontent.com/8744178/96875675-e01d8380-144d-11eb-8256-24974effeaf8.png)

**Comment by nikithauc** [comment]
https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/265

**Comment by nikithauc** [comment]
@victorreis  Are you testing this on a personal account? 

Authorization being set as undefined is an expected behavior and it happens in case of a redirection that is when the Graph API redirects to another endpoint. 

I am looking into why you are getting an empty error body as in the following screenshot.  https://user-images.githubusercontent.com/8744178/96654241-36d17300-1311-11eb-985f-b4a034febaed.png

**Comment by nikithauc** [comment]
@victorreis  Can you verify the scopes that is set? https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http 
Can you please provide a fiddler trace if possible of request and response between the graph JS client sdk and Graph API?

**Comment by victorreis** [comment]
> @victorreis Are you testing this on a personal account?
I'm used my job account with permissions granted by the administrator of my organization to set the configs to "get access without a user". With the ClientId, CliendSecret and TenantId I get the token.
 
> Authorization being set as undefined is an expected behavior and it happens in case of a redirection that is when the Graph API redirects to another endpoint.
I don't know why it's happening, because in the Postman and in the Axios code it works fine.

> I am looking into why you are getting an empty error body as in the following screenshot. https://user-images.githubusercontent.com/8744178/96654241-36d17300-1311-11eb-985f-b4a034febaed.png
Thank you! 👍

**Comment by victorreis** [comment]
> @victorreis Can you verify the scopes that is set? https://docs.microsoft.com/en-us/graph/api/driveitem-get-content?view=graph-rest-1.0&tabs=http

![image](https://user-images.githubusercontent.com/8744178/97169686-37329980-1769-11eb-85c7-a6edd92d898d.png)
![image](https://user-images.githubusercontent.com/8744178/97169721-43b6f200-1769-11eb-9e0c-678fcc6523e0.png)

> Can you please provide a fiddler trace if possible of request and response between the graph JS client sdk and Graph API?

How can I do that? I installed the "Fiddler Everywhere" and I sent the request via Postman to my local server, but the fiddler doesn't log the internal server request (that uses the microsoft-graph-client).

**Comment by nikithauc** [comment]
@victorreis  I appreciate your patience and your response to my questions. Thank you! 

I came across other issues with respect to CORS issues with file content download such as follows -

https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/265#issuecomment-579654141
https://github.com/microsoftgraph/microsoft-graph-docs/issues/5464

A similar issue with respect to CORS error during a file upload was reported -https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/265.
Can you try if the following client setting code works for you?
`const authenticationHandler = new AuthenticationHandler(authProvider);
		const retryHandler = new RetryHandler(new RetryHandlerOptions());
		const httpMessageHandler = new HTTPMessageHandler();

		authenticationHandler.setNext(retryHandler);
		if (//you are using a node environment) {
			const redirectHandler = new RedirectHandler(new RedirectHandlerOptions());
			retryHandler.setNext(redirectHandler);
			redirectHandler.setNext(httpMessageHandler);
		} else {
			retryHandler.setNext(httpMessageHandler);
		};
let client = Client.initWithMiddleware({
    middleware: authenticationHandler
});`

I want to see if your issue is related to the CORS issue reported. Please let me know if you have more questions.

**Comment by nikithauc** [comment]
@victorreis  I was able to reproduce this issue. Thank you @peombwa  for the help!

The fix for this is will be included in the next release. 

A suggested work around is to as follows- 

Get the download url for the item you wish to access as follows -
`https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')?$select=@microsoft.graph.downloadUrl` and use the url to download the file. 
Refer - https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/16.

Please let me know if you have more questions.

**Comment by victorreis** [comment]
> @victorreis I was able to reproduce this issue. Thank you @peombwa for the help!
> 
> The fix for this is will be included in the next release.
> 
> A suggested work around is to as follows-

Thank you! I'm glad to help improve the SDK. 👍 

> Get the download url for the item you wish to access as follows -
> `https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')?$select=@microsoft.graph.downloadUrl` and use the url to download the file.
> Refer - #16.

In my case I need to download the file to my API and pass thought the frontend client because the @microsoft.graph.downloadUrl allows any user with the link to download the file. I don't want to give this possibility to the final user.

> Please let me know if you have more questions.

No more questions, I just need to thank you! Good job! 💯

**Comment by victorreis** [comment]
@nikithauc , I have a question, maybe you can help me. I'm trying to get the response headers, but it doesn't works in the SDK, just in Postman, Axios etc. Here is the code:

![image](https://user-images.githubusercontent.com/8744178/97727719-7d606380-1aaf-11eb-8a46-cdc83d241425.png)

I need to get the `response.headers.location`, that informs me the link to have the information about the status of the async copy. But response is `undefined`.

Do you want me to open another issue?

**Comment by nikithauc** [comment]
@victorreis  Thank you for pointing this issue! 

I have opened  a new issue for this https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/349.
