### ISSUE TITLE
Can't get file preview from drive with id but can with path

### ISSUE THREAD

**Issue by marcolarosa** [microsoftgraph/msgraph-sdk-javascript#352]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?

-   [x] Are you running the latest version?

-   [x] Are you reporting to the correct repository?

-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Using the client to get a preview of a one drive file fails when using the ID but not when referencing the path.

With path to file:
```
let link = `/me/drive/root:${this.path}:/preview`
link = await client.api(link).post({})
```
No errors - works as expected.

With ID:
```
let link = `/me/drive/items/${this.itemId[0]}/preview`
link = await client.api(link).post({})
```

Where this.itemId[0] = 'b!-4xxhXFx5kKSQwwAu ... 4QGAuTlRxZhQ59yKADIuZ49#01K7QV4XM ... ZOOIF6Z'

Result:
400 Bad Request - Error: Invalid request (no other useful information as to why)

But, the error in the console shows the URL as:
https://graph.microsoft.com/v1.0/me/drive/items/b!-4xxhXFx5kKSQwwAu ... 4QGAuTlRxZhQ59yKADIuZ49

Notice everything after the '#' in the original ID has been removed?

![error](https://user-images.githubusercontent.com/2639995/98622761-5da62680-235e-11eb-949c-027ced298e78.png)

## Usage Information

SDK Version - @microsoft/microsoft-graph-client@2.1.0

> Browser Name - Firefox 

> Version -82.02

**Comment by nikithauc** [comment]
@marcolarosa Thank you for reporting this issue! 

Can you please verify if  'b!-4xxhXFx5kKSQwwAu ... 4QGAuTlRxZhQ59yKADIuZ49#01K7QV4XM ... ZOOIF6Z' is the drive id or the item id? Because the id mentioned seems to have to have a drive item id format. 

References for more help -
https://docs.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http
https://stackoverflow.com/questions/61321342/how-to-find-onedrive-item-id-associated-with-microsoft-sharepoint-document
https://blog.atwork.at/post/Access-files-in-OneDrive-or-SharePoint-with-Microsoft-Graph-and-the-Excel-API

**Comment by marcolarosa** [comment]
It's the itemId. The part before the '#' is the drive id and the part after is the item id.

**Comment by nikithauc** [comment]
Can you try sending only  the part after the # in the request and see the outcome? 

Example 
```
client.api('https://graph.microsoft.com/v1.0/me/drive/items/01-------------------N/preview')
    .post({})
        .then((res) => {
            console.log("response");
      console.log(res);
  })
  .catch((err) => {
      console.log(err);
  });
```

**Comment by marcolarosa** [comment]
OK - that works. But it doesn't make sense. Why would just that part work without identifying the target drive?

I was following the docs @ https://docs.microsoft.com/en-us/graph/api/driveitem-preview?view=graph-rest-1.0

And on that page there are routes like:
```
POST /drives/{driveId}/items/{itemId}/preview
```

Which suggests that when using the /me/drive route (like I am) the item id would be the full driveid#itemid form (when I log in to onedrive I can see two drives so that's why I thought I needed the full form).

**Comment by nikithauc** [comment]
Difference between POST /drives/{driveId}/items/{itemId}/preview  and POST /me/drive/items/{itemId}/preview -
The first one isn't called in the context of a user. It may only work with Application permission type.
The second should only be applicable with Delegated permission type.

**Comment by marcolarosa** [comment]
It might be worth making that point clearer in the documentation. As I said, I see two drives when I log in so i assumed that even though I was using the /me route, the item-id would need to also include the drive id in order to specify the drive to lookup.

Thanks for the help!

**Comment by nikithauc** [comment]
I agree.  Let me see if the documentation can be updated.
