### ISSUE TITLE
SPO can NOT scan virus when upload by Microsoft Graph API

### ISSUE THREAD

**Issue by lethinh0510** [microsoftgraph/msgraph-sdk-javascript#354]
# Bug Report

## Prerequisites

-   [x ] Can you reproduce the problem?
-   [x ] Are you running the latest version?
-   [x ] Are you reporting to the correct repository?
-   [ x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I have a problem in SPO scan virus.
When I upload virus file to SPO in browser. It scan OK.
But when I using Microsoft Graph API upload in FE. It didn't detected it virus.

**Console Errors:** [Is there any console error]

**Screenshots:**
![tempsnip](https://user-images.githubusercontent.com/10781387/98624354-2f195300-2340-11eb-8e32-b2f2fa3e5539.png)

## Steps to Reproduce

1. Upload file virus by Microsoft Graph API
2. Upload file virus by Browser
Download virus file in link https://www.eicar.org/

**Expected behavior:** Detect all file if it's virus

**Actual behavior:** It didn't detected it virus when upload by Microsoft Graph API

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by nikithauc** [comment]
@lethinh0510  This repo is for issues specific to Microsoft JavaScript Client SDK. 
Please post this question in Microsoft Q & A using  tags for SharePoint and  StackOverFlow for help with this issue.
