### ISSUE TITLE
Error: Cannot find module 'msal'

### ISSUE THREAD

**Issue by whatl3y** [microsoftgraph/msgraph-sdk-javascript#361]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Building my app in a docker container and running v2.2.0 of `@microsoft/microsoft-graph-client` in Node.js 14.13.1.

This is a new error that I didn't experience last week when building the container, but I didn't notice any recent changes to `package.json` or `ImplicitMSALAuthenticationProvider.ts` that would cause this.

**Console Errors:** [Is there any console error]

```
Error: Cannot find module 'msal'
Require stack:
- /usr/app/node_modules/@microsoft/microsoft-graph-client/lib/src/ImplicitMSALAuthenticationProvider.js
- /usr/app/node_modules/@microsoft/microsoft-graph-client/lib/src/index.js
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]

N/A

## Steps to Reproduce

1. Add `@microsoft/microsoft-graph-client` to your Node.js project.
2. `import { Client } from '@microsoft/microsoft-graph-client'` from a file in your project
3. See error

**Expected behavior:** [What you expected to happen]

Not error

**Actual behavior:** [What actually happened]

Error above

## Additional Context

Add any other context about the problem here..

## Usage Information

SDK Version - [SDK version you are using]

v2.2.0

-   [x] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

14.13.1

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by whatl3y** [comment]
Adding `msal` to my package.json dependencies (`npm install -s msal`) temporarily resolves this, but that's not a long term solution obviously.

**Comment by nikithauc** [comment]
@whatl3y  Thank you for reporting the issue!  Will look into the issue.

**Comment by Srokap** [comment]
Seeing same issue, looks like installed ms graph lib has only those 2 as dpendencies
```
  "dependencies": {
    "@babel/runtime": "^7.4.4",
    "tslib": "^1.9.3"
  },
```
And in `node_modules/@microsoft/microsoft-graph-client/lib/es/ImplicitMSALAuthenticationProvider.js` there is:
```
import { InteractionRequiredAuthError } from "msal";
```
on line 11.

Seems to me that msal should be a production dependency unless you meant to make it a peer dependency. Also notice that msal is currently a devDependency, so that's likely why it got missed.

**Comment by raimille1** [comment]
Same issue here!

**Comment by nikithauc** [comment]
@whatl3y @Srokap @raimille1  hotfix #362  has been deployed in version [2.2.1](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/2.2.1)
