### ISSUE TITLE
Is there an example how to render photos returned by the BatchRequestContent?

### ISSUE THREAD

**Issue by plamber** [microsoftgraph/msgraph-sdk-javascript#367]
Hello,
I verified the example [here](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a95a762b9b7f66fb843aa1e134014f4214bc093a/docs/content/Batching.md) on how to retrieve people photos using the BatchResponseContent.

Unfortunately, I am failing when rendering the results in the browser.

I am using this syntax to render the blob:

__const response = contents.getResponseById("idofBatchResponse");
if (response.ok) {
  const url = window.URL || window.webkitURL;
  const blobUrl = url.createObjectURL(await response.blob());
  ...
  // assign the blobUrl to an img
}_

Do you have any suggestions how to do this? It would be nice to see how to interpret these results.

Thank you,
Patrick

**Comment by baywet** [comment]
Hey @plamber ! I hope you're doing well.
Wouldn't this work? (I haven't tested this code)

(the casting isn't required, it only helps further down with compile time validation and auto-completion)

```TypeScript
const batchResponseContent = (await this.getAuthenticatedClient().api("/$batch").post(content)) as BatchResponseContent;
const photoResponse = batchResponseContent.getResponseById(downloadId);
const blob = await photoResponse.blob();
const blobUrl = window.URL.createObjectURL(blob);
```

**Comment by plamber** [comment]
Hi @baywet,
thank you for your help.

I tried this before reaching you out. I already generated a blobURL but failed in rendering it when passing it to the <img> tag.

I do not have the problem when calling the same resource using this code.
```
let blob = await client
          .api(`/users/${resourceId}/photos/64x64/$value`)
          .get();
const blobUrl = window.URL.createObjectURL(blob)
```

Can't figure out what I am missing. 

Thank you for your feedback,
Patrick

**Comment by joaojmendes** [comment]
Hi all,

Here my implementation in SPFx using msggraphclient


I have a function get user info and photo and save data in local cache  with msgraph batch I use to function to converto b64 to blob and the blob to base64 that I use to src in image tag.



/**
   *  Get User Data
   * @param user
   */
  const getUserId = async (user: string): Promise<IUserInfo> => {

    const _batchRequests:IBatchRequest[] = [
      {
        id: "1",
        url: `/users/${user}`,
        method: "GET",
        headers:  {
          "ConsistencyLevel": "eventual"
        }
      },
      {
        id: "2",
        url:  `/users/${user}/photo/$value`,
        headers:{ "content-type": "img/jpg"},
        method: "GET",
      },

    ];

    let _userInfo: IUserInfo = undefined;
    let _blobPhoto = undefined;
    let _usersResults: User  = undefined;
     try {
       _userInfo = await cache.get(`${user}`);
      return _userInfo;
    } catch (error) {
      // execute batch
      const _batchResults:any   = await _msgGraphclient
        .api(`/$batch`)
        .version("v1.0")
        .post({requests: _batchRequests}) ;

        // get Responses
        const _responses:any = _batchResults.responses;
        // load responses
        for ( const _response of _responses){
          // user info
              if (_response.id === "1"){
                _usersResults = _response.body;
              }
              // user photo
              if (_response.id === "2"){
                // convert binary64 to blob // photo
                const _binToBlob   =_response?.body ? await b64toBlob((_response?.body),'img/jpg'  ) : undefined;
                _blobPhoto   =  await blobToBase64(_binToBlob) ?? undefined;
              }
        }
        // save userinfo
         _userInfo = { ... _usersResults, userPhoto: _blobPhoto };
          await cache.put(`${user}`,_userInfo);
         return _userInfo;
      }
  };


export const b64toBlob = async (b64Data:any, contentType:string, sliceSize?:number):Promise<Blob>  => {
  contentType = contentType || 'image/png';
  sliceSize = sliceSize || 512;

  let byteCharacters:string = atob(b64Data);
  let byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    let slice = byteCharacters.slice(offset, offset + sliceSize);

    let byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
        byteNumbers[i] = slice.charCodeAt(i);
    }

    let byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  let blob = new Blob(byteArrays, {type: contentType});
  return blob;
};

 export const  blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = reject;
    reader.onload = _ => {
      resolve(reader.result as string);
    };
    reader.readAsDataURL(blob);
  });
};

Cheers!

Have a nice year of 2021!

**Comment by baywet** [comment]
yep the base64 decode of the response was the next thing I was about to suggest. I don't thing the Batch content response handler applies other handlers to the responses like the regular response handler does. Additionally this information is base64 encoded because it's part of a string response (json) and not a binary one (image/jpeg).

**Comment by baywet** [comment]
thanks for helping @joaojmendes !

**Comment by joaojmendes** [comment]
Wellcome! 😊

**Comment by plamber** [comment]
Thank you @joaojmendes. Your solution works.

Here the snippet for future reference.

```
export const b64toBlob = async (b64Data:any, contentType:string, sliceSize?:number):Promise<Blob>  => {
  contentType = contentType || 'image/png';
  sliceSize = sliceSize || 512;

  let byteCharacters:string = atob(b64Data);
  let byteArrays = [];

  for (let offset = 0; offset < byteCharacters.length; offset += sliceSize) {
    let slice = byteCharacters.slice(offset, offset + sliceSize);

    let byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
        byteNumbers[i] = slice.charCodeAt(i);
    }

    let byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }

  let blob = new Blob(byteArrays, {type: contentType});
  return blob;
};

export const blobToBase64 = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = reject;
    reader.onload = _ => {
      resolve(reader.result as string);
    };
    reader.readAsDataURL(blob);
  });
};
```

```
// build a batch request with the desired photos
const requests : BatchRequestStep[] = resourceIds.map((resourceId) => {
const request : BatchRequestStep = {
  id: resourceId,
  request: new Request(`/users/${resourceId}/photos/64x64/$value`, {
    method: "GET",
  })
};
return request;
})

const batchRequestContent = new BatchRequestContent(requests);
const content = await batchRequestContent.getContent();
const response = await client.api("/$batch").post(content);

.....
.....
.....

// in the people picker then retrieve the desired picture

const response = contents.getResponseById(${resourceId});
if (response.ok) {
  var data = await response.text();
  const _binToBlob = await b64toBlob((data),'img/jpg');
  const blobUrl = await blobToBase64(_binToBlob);
  person.picture = blobUrl;
}
```

Hope this helps.

Thank you all.

Closing the issue.

Wish you a great 2021

**Comment by baywet** [comment]
@plamber would you mind PRing the docs you were pointing to in the initial message please? just adding a comment about the base64 encoding when it's in a batch as well as adding a sample of decoding. I'm sure it'll help others with the same goal and it'll be easier to find than here.
No worries if you can't, and it doesn't have to be right now.

**Comment by nikithauc** [comment]
Reopening this so that this example is sampled.

**Comment by plamber** [comment]
Hi @baywet,
do you want me to change the docs or do I just have to open a PR?

br,

**Comment by baywet** [comment]
My original thoughts were that you could PR [this](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/content/Batching.md) unless you had a better proposition?

**Comment by baywet** [comment]
@nikithauc thanks for reopening!

**Comment by plamber** [comment]
@baywet will do it asap

**Comment by plamber** [comment]
Just created a PR with an example. The example compiles and was tested on my environment. I haven't created automated tests for the example

**Comment by nikithauc** [comment]
Thank you for the PR @plamber ! Appreciate your contribution :)
