### ISSUE TITLE
Add support for MSAL Browser (MSAL.js v2) and MSAL Node

### ISSUE THREAD

**Issue by jasonnutter** [microsoftgraph/msgraph-sdk-javascript#373]
# Feature Request

I'm Jason from the MSAL.js team, and I am reaching out to see how we can help add support for our new libraries, [MSAL Browser](https://www.npmjs.com/package/@azure/msal-browser) and [MSAL Node](https://www.npmjs.com/package/@azure/msal-node).

## Is your feature request related to a problem? Please describe

For client-side auth, this library includes support for the Implicit Flow via MSAL.js v1. We are now recommending that applications switch to the Auth Code Flow w/ PKCE for SPAs, which mitigates problems caused by third-party cookie blocking in browsers such as Safari and Chrome Incognito. Furthermore, MSAL Browser includes lots of other great features (e.g. multiple account support, proof-of-possession, etc.).

For server-side auth, we now have a fully featured library for Node environments, MSAL Node. 

## Describe the solution you'd like

I'd love to find out if adding support for these libraries has been considered, and what our team can do to help (including making contributions). 

Thanks!
 
[AB#7551](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7551)

**Comment by MIchaelMainer** [comment]
@thewahome as well for GE

**Comment by baywet** [comment]
FYI @nikithauc already started some of that work here #371

**Comment by nikithauc** [comment]
@jasonnutter  Thank you for in this issue!
We are currently  working on supporting authentication with the `@azure/identity` which depends on the  MSAL Node. 
I agree that MSAL Node and MSAL Browser have great features. 
Is there a timeline when MSAL V1 will be deprecated?

**Comment by ddyett** [comment]
tracked as part of updating on kiota
