### ISSUE TITLE
Replace Gulp.

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#382]
Replace gulp with another dependency or process to perform tasks present in the gulpfile.js.  
[AB#7633](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7633)

**Comment by baywet** [comment]
Out of curiosity, why do you want to replace gulp?

**Comment by nikithauc** [comment]
https://www.npmjs.com/package/gulp last update was two years ago. There are security alerts related to this dependency. 
Proposal to use something more up-to-date.

**Comment by baywet** [comment]
It looks like the only thing we're using gulp for is to update the version constants in TS from the package.json. It surely is a big dependency to do just that... A PS script should be more than enough :)

**Comment by ddyett** [comment]
closing older issue.
