### ISSUE TITLE
Update design for  task classes like LargeFileTaskUpload and PageIterator task.

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#383]
Currently, when creating the `LargeFileUpload` object or the `PageIterator` object, we are passing a `Client` object which is used to make the requests. 
The current design creates limitations in customizing the `GraphRequest` object options.
Example - To pass custom headers in the `PageIterator`, we pass a `requestOptions` parameter while creating the `PageIterator` object.
Another problem I came across was when working on #359. The response format of Outlook and OneDrive are different and I need to customize the `ResponseType` in the `GraphRequest` object.

Related to - https://github.com/microsoftgraph/msgraph-sdk-design/issues/37

The design of the task classes should be updated to allow easy customizations and changeability. The relations between the classes can be reengineered.  Example - use a behavioral design pattern.

 
[AB#7642](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7642)

**Comment by nikithauc** [comment]
To be considered with #500 and #499

**Comment by ddyett** [comment]
tracked now in sdk design
