### ISSUE TITLE
GraphResponse object design update

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#384]
[AB#7643](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7643)

**Comment by nikithauc** [comment]
https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/112/files

**Comment by nikithauc** [comment]
Current Implementation - for any request example `const response = await client.api("/me").select(url).get()`, the [GraphResponseHandler ](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a26c288b3463c49bf9862e32865bd0beed72753a/src/GraphResponseHandler.ts#L125) processes the Graph API response and returns just the response body. 
To access the other response properties like the headers, status code we need to set the `responseType` of a request to `ResponseType.RAW` -> https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/GettingRawResponse.md.

* Some APIs are expected to not have any content/body. Currently, a JS SDK request to such APIs returns an empty response when the responseType of the request is not set` ResponseType.RAW`. 
Example of a issue reported - https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/344#issuecomment-719645580.
* It would be natural in such cases to return the headers or the complete response object, rather than the empty body as response. Why specify the responseType when there is no body expected from that API?
* In some cases, there can be information in both the headers and the body or the user might want to access the status code.
* Another example - Currently when using LargeFileTaskUpload we are returning the response body which works in case of OneDrive as the body contains the `location` information. However, in Outlook the body is empty and the headers contain the `location` information. We could set the ResponseType as RAW when making an Outlook request. However, the ideal expectation would be that the LargeFileTaskUploads requests for Outlook and OneDrive should have a similar format.

Proposal -
* Provide a GraphResponse object which provides access to the response properties - headers, statuscode and body.
* To add value, we can deserialize or process the response body, as we currently do, and set that value to the content property of the GraphResponse object. 
* Maintain consistency with the upcoming GraphResponse object feature in the dot-net sdk.

Questions -
Why do we always return the response body in most cases? Why are the headers and status code information not accessible?

**Comment by nikithauc** [comment]
[2:42 PM] Darrel Miller
    

I think I had this conversation previously with Muthu and he didn't believe it was necessary to have the GraphResponse object.  Is there a specific problem that we are trying to solve by creating this interface?

​[2:43 PM] Darrel Miller
    I think the argument was that this https://developer.mozilla.org/en-US/docs/Web/API/Response has all of those properties.

**Comment by MIchaelMainer** [comment]
> Some APIs are expected to not have any content/body
There are some responses that return headers with no response body. So how is a customer supposed to know that 1) the response has no body, 2) when it has no body, they need to use ResponseType.RAW. The client API signature doesn't help the dev determine that the response has no body. So the customer has to depend on the docs to get this info (some percentage won't search in the docs and will ask questions here). Still, the docs won't have guidance that they need to use ResponseType.RAW. We could update snippet generation to inspect docs for actionable response headers when status code is 204, and then generate a snippet based on that information. But even if we do that, then we will have two different experiences, one for getting the response body, and one for getting the response headers.  There is an additional experience where if you want the response body and headers, you have to use ResponseType.RAW, and will need to work with native Response object. 

We could consider the ResponseType.RAW as the default response type so that the body has to be explicitly accessed, but what about BLOB return types? Does RAW return the BLOB in the Response object?

**Comment by darrelmiller** [comment]
> There are some responses that return headers with no response body. So how is a customer supposed to know that 1) the response has no body, 2) when it has no body, 

@MIchaelMainer If the customer calls UpdateCustomer(customer) and there is no response body then UpdateCustomer will return null.  If it fails it will throw an exception.  What information would a customer get from the Response that is useful?

The main scenario I am aware of that is a problem is calling CreateCustomer and the response is a 201 with no body and just a location header.  In this case the user wants to access the Location header and retrieve the created customer.  It's worth noting that a 201 response status doesn't tell you whether there is a body or not.  Nor do you have any guarantees that the body is a representation of the created customer.  If someone wants to create the customer and then retrieve the result, then they know that in advance and can request RAW to get the Location header.

In the case of Update, the client already knows the URL they called to do the update so if they want an updated copy they can call Get using the same request builder they used to call PATCH.

Until we start building generic paging and annotation extraction code, I don't see what GraphResponse is going to do for us.

**Comment by MIchaelMainer** [comment]
> If the customer calls UpdateCustomer(customer) and there is no response body then UpdateCustomer will return null. If it fails it will throw an exception. What information would a customer get from the Response that is useful?

@darrelmiller I argue that returning null is not a helpful result. From the customer perspective, null does not indicate success. Returning null, by itself, without the benefit of experience, documentation or a subsequent call, is an indeterminate result. An http status code would indicate success. Without the status code, the customer has to learn that a returned null means that the update was a success. So, they would then have to make another query to confirm that the update indeed did succeed. We know that null is success and an exception is a failure, but will the customer?

> If someone wants to create the customer and then retrieve the result, then they know that in advance and can request RAW to get the Location header.

How would they know that they need to use request RAW in advance or that they will get a location header? The client library will not provide the hint that 1) there is a potential 201 result which 2) indicates that they need to access the location header, which by the way, 3) they need to know to use the request RAW option. The customer has to learn this information which won't be easily learned by using the client library. They will need Fiddler, logging middleware, snippet, and/or read the documentation. Is responseType.RAW discoverable in this case? 

GraphResponse<T> provides consistency for accessing status, headers, and body. I think we'll want something like this when we have fluent API for JS.

**Comment by darrelmiller** [comment]
@MIchaelMainer Without the benefit of experience or documentation, the HTTP status code isn't going to be helpful either.  The SDKs return the payload as an object if one is returned.  If the HTTP payload is empty, the null is the most natural response.  Having a method that sometimes returns the payload as an object, and other times returns the HTTP response is an unnatural experience.

> How would they know that they need to use request RAW in advance or that they will get a location header? 

Our documentation shows that a 201 response with a location header and an empty body.  We should consider updating the snippets to show how you get the Location header on the response to a create and retrieving the result.  If we can't write a code snippet that looks good, then I am all for trying to find a better way of modelling the call.

Are you suggesting returning GraphResponse so that we can have a Value property that has the deserialized type?  That does have value.  But we need to look at what that does to our default user experience.

**Comment by MIchaelMainer** [comment]
I thought I was replying to you in teams.

**Comment by nikithauc** [comment]
> GraphResponse provides consistency for accessing status, headers, and body. I think we'll want something like this when we have fluent API for JS.

+1 on this point by @MIchaelMainer.

We can have a GraphResponse object -
1. Allows user to access the response properties - header, body, statusCode. 
2. Provides API's example - `graphResponse.raw()`, `graphResponse.getDeserializedBody()` allowing customizations on the GraphResponse. This way the user has more control on the response and it allows extensibility of the functionality in the future. A user can debug the response and process as per their requirement. It avoids the confusion of not knowing why a response is empty until Response Type.RAW is defined. 
3. A minor advantage of a GraphResponse object is having a stricter return type while making requests rather than simply returning `Promise<any>`. 

@darrelmiller 
> Having a method that sometimes returns the payload as an object, and other times returns the HTTP response is an unnatural experience. 
I agree on this. We should be uniform with what we return. But I also think that we should have a uniform pattern while making requests and independent of the response formats. This makes the use of SDK to make requests intuitive and simple.

**Comment by nikithauc** [comment]
> [2:42 PM] Darrel Miller
> 
> I think I had this conversation previously with Muthu and he didn't believe it was necessary to have the GraphResponse object. Is there a specific problem that we are trying to solve by creating this interface?
> 
> ​[2:43 PM] Darrel Miller
> I think the argument was that this https://developer.mozilla.org/en-US/docs/Web/API/Response has all of those properties.

Having a GraphResponse object could also help in bringing in abstraction and making it simpler to move to a new HTTPClient.

**Comment by darrelmiller** [comment]
@MIchaelMainer wrote 
> GraphResponse provides consistency for accessing status, headers, and body. I think we'll want something like this when we have fluent API for JS.

I think we will have a use for this in the TypeScript Service Library.  However, I am not convinced that we should change our core library unless there is a non-breaking way to do it.

@nikithauc wrote
> Why specify the responseType when there is no body expected from that API?

Expecting anything specifically in an HTTP response is a broken assumption.  To match our other SDKs, every response from making a call in core should return a RAW response.  However, that's not the pattern we started with and changing it significantly would disrupt our current users.
