### ISSUE TITLE
Not able to get the Login Screen in Android API level 30

### ISSUE THREAD

**Issue by prorohit** [microsoftgraph/msgraph-sdk-javascript#386]
# Bug Report
We are not able to get the login screen on the API level 30 devices of Android using this library. However, it works fine in the devices below API level 30.

## Prerequisites

We are using the below version of library in packag.json of our React Native Application.
"@microsoft/microsoft-graph-client": "^2.0.0"

For more information, see the `CONTRIBUTING` guide.

## Description

When I am trying to use the login feature on Android API Level 30, in app browser is not opening to enter the credentials for login. However it worked fine in the below API levels 30.

Exception getting on the terminal:
{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"**message":"Error not specified.","code":"browser_not_found"**,"line":2144,"column":45,"sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}

**Expected behavior:** [What you expected to happen]
<img width="342" alt="11" src="https://user-images.githubusercontent.com/25680719/105711266-c3538900-5f31-11eb-8e6f-4d68ef3d1655.png">

**Actual behavior:** [What actually happened]
<img width="344" alt="22" src="https://user-images.githubusercontent.com/25680719/105711273-c5b5e300-5f31-11eb-85c7-7ebf84053cfe.png">

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - [SDK version you are using]
"@microsoft/microsoft-graph-client": "^2.0.0"
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 24.21 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: ^0.61.5 => 0.61.5 
[AB#7745](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7745)

**Comment by nikithauc** [comment]
@prorohit Thanks for getting in touch! 

1. What is the Auth Provider that you are using with the Graph JavaScript library client ? 
2. When you say login is not working , do you mean login of a user into  your application or to access the Graph API?

**Comment by prorohit** [comment]
Hi @nikithauc 

I am using Oauth2 Auth provider.

When I say login not working on Api level 30 devices of Android, then I meant the the in app browser is not coming when I do the initialisation  of the login process. However same is working on the Api level 30 devices, which means browser is getting opened for filing the Microsoft credentials .

If you need any other information please let me know .

Thanks

**Comment by nikithauc** [comment]
@prorohit 
Are you able to debug or produce an error pointing any part the code in the Microsoft Graph JavaScript library? That would be helpful if you can provide that.

I think that the problem with the login process might have something to do with authentication library. The Graph JS library does not  provide any login functionality.

**Comment by prorohit** [comment]
@nikithauc 

**Following auth library is being used**
"react-native-app-auth": "6.0.2"

**Usage:**
import {authorize, refresh} from 'react-native-app-auth'
....
....
 static signInAsync = async () => {
    **const result = await authorize(config)**
    await AsyncStorage.setItem(
      AppConstants.appConstants.accessToken,
      result.accessToken,
    )
    await AsyncStorage.setItem(
      AppConstants.appConstants.refreshToken,
      result.refreshToken,
    )
    await AsyncStorage.setItem(
      AppConstants.appConstants.expireTime,
      result.accessTokenExpirationDate,
    )
}


**Exception thrown:**

{"framesToPop":1,"nativeStackAndroid":[],"userInfo":null,"message":"Error not specified.","code":"browser_not_found","line":2144,"column":45,"sourceURL":"http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false"}

I hope this helps.

**Comment by nikithauc** [comment]
@prorohit 

Apparently, this is an issue with the react-native-app-auth and not in the Graph JS SDK. It would be helpful to create an issue in the react-native-app-auth repo.

**Comment by nikithauc** [comment]
@prorohit  Please free to reopen this issue if you have more questions or concerns. I am closing this issue as it is not related to the Graph JS SDK.
