### ISSUE TITLE
Limit users with a sharing link to only view and may not download

### ISSUE THREAD

**Issue by kangqiwang** [microsoftgraph/msgraph-sdk-javascript#387]
# Feature Request

## Is your feature request related to a problem? Please describe

Limit users with a sharing link to only view and may not download the contents of a shareddriveItem on OneDrive for Business or SharePoint.

 I'm always frustrated when I can not invite a specific user to a file with only view permission and not download the contentes

## Describe the solution you'd like

I hope we can add another value, like "view_only" in parameter roles Collection, or we can add another boolean parameter to control if block download.

here is your documentation, you can find the parameter I mentioned
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_invite?view=odsp-graph-online

## Additional context

I just screenshot the graph functionality in your SharePoint, I think we can do some similar things in OneDrive as well. however, I hope we can do some similar things through Microsoft Graph API.

![image](https://user-images.githubusercontent.com/32779723/106010926-e2792480-60b1-11eb-936f-dcb2e14ee320.png)

Thanks for reading  
[AB#7819](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7819)

**Comment by nikithauc** [comment]
[2:07 PM] Michael Mainer
    Thank you for opening this issue. This appears to be a a feature request for the Microsoft Graph API. Please use the [Microsoft Graph User Voice](https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests) to search for existing feature requests, and to open new feature requests.
