### ISSUE TITLE
CORS issue when accessing shared DriveItems content

### ISSUE THREAD

**Issue by snebjorn** [microsoftgraph/msgraph-sdk-javascript#388]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [ ] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Requests to 
```http
GET /shares/{shareIdOrUrl}/driveItem/content
```
https://docs.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http

Will result in a redirect that will fail with a CORS error

```ts
this.graphClient.api(`/shares/${encodeShareableLink}/driveItem/content`).get();
```

This is the error:

> Access to fetch at 'https://{my org}.sharepoint.com/sites/{my site}/_layouts/15/download.aspx?UniqueId={guid}&Translate=false&tempauth={token}&ApiVersion=2.0' 
> (redirected from 'https://graph.microsoft.com/v1.0/shares/{encoded shareable link}/driveItem/content') 
> from origin 'https://localhost:5001' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

## Steps to Reproduce

1. Call `GET /shares/{shareIdOrUrl}/driveItem/content` from javscript
2. Watch CORS

**Expected behavior:**
I expected to be able to either intercept the location header or download the file.

**Actual behavior:**
A CORS error was thrown

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - [SDK version you are using]
"@microsoft/microsoft-graph-client": "^2.2.1"

-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]
Chrome

> Version - [The version of the browser you are using]
88.0.4324.104 
[AB#7930](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7930)

**Comment by nikithauc** [comment]
This is a known isssue - to microsoftgraph/microsoft-graph-docs#43.
@snebjorn  Please check if the workaround suggested in the comment works for you.

Please check if the following workaround works for you
Get the download URL for the item you wish to access as follows -

Example -
https://graph.microsoft.com/v1.0/sites('${siteId}')/drives('${driveId}')/items('${fileId}')?$select=@microsoft.graph.downloadUrl and use the URL to download the file.

**Comment by snebjorn** [comment]
I see. Using the `@microsoft.graph.downloadUrl` link from `GET /shares/{shareIdOrUrl}/driveItem` worked, thank you.

However `GET /shares/{shareIdOrUrl}/driveItem?$select=@microsoft.graph.downloadUrl` doesn't seem to limit the response

**Comment by nikithauc** [comment]
@snebjorn  can you explain what you mean by limit the response?

**Comment by snebjorn** [comment]
it doesn't select the @microsoft.graph.downloadUrl property. It still returns everything

**Comment by finsharp** [comment]
@snebjorn I was able to reproduce the issue, turns out its a [known issue](https://stackoverflow.com/questions/45502275/microsoftgraph-querying-for-microsoft-graph-downloadurl-returns-character-i), please use `content.downloadUrl` instead. 
Repro in GE:-
`
https://graph.microsoft.com/v1.0/shares/<redacted>/driveItem?$select=id,@microsoft.graph.downloadUrl
`
Produces: Does not filter
![image](https://user-images.githubusercontent.com/1641829/106733737-4d32de80-6623-11eb-8c72-df7046b90846.png)
However using `@content.downloadUrl` filters as expected. 
![image](https://user-images.githubusercontent.com/1641829/106733847-6d629d80-6623-11eb-8eae-49608f716f34.png)

**Comment by snebjorn** [comment]
I'm closing this as the original issue and follow up issue are both known
