### ISSUE TITLE
Support of Audio/Video calls with graph APIs on browser using Angular or JavaScript

### ISSUE THREAD

**Issue by siva1545** [microsoftgraph/msgraph-sdk-javascript#393]
Hello
I am trying to create teams plugin for single page application using Angular.
Have used SDK https://github.com/microsoftgraph/msgraph-sdk-javascript to send/receive text messages.
Now want to add support of audio & video calls.

1. Do you have sample Angular or Javascript code for the same?
2. How audio/video calls are rendering in browser?

I think following graph API links supports the same, but I don't see any sample code in Angular or JavaScript
https://docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0

**Comment by nikithauc** [comment]
@siva1545 Did the samples showing create call , get call , answer call  as in the documentation -> https://docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-1.0&tabs=http work for you?

**Comment by siva1545** [comment]
@nikithauc 
Document provided explains how to use the Graph API. Samples provided are request and response not sample code.
It is not addressing my questions

1. I am asking for sample code in Angular/JavaScript consuming those APIs.
2. APIs provided are kind of signaling APIs only (like SIP). Want to know how the actual call voice/video (Like WebRTC) are rendered in web page

For example, I am referring similar interface provided by ZOOM.
They are providing SDK and how to use it.
In fact they are expecting some pre-defined DIV tags for rendering ZOOM menus, video and all other required tools.
https://marketplace.zoom.us/docs/sdk/native-sdks/web/build 

I want similar things from Microsoft graph APIs as Microsoft teams supports audio/video/share screen like ZOOM.

Thanks

**Comment by nikithauc** [comment]
@siva1545  Looks like the call support via Graph API is applicable in scenarios using a bot. 
https://github.com/microsoftgraph/microsoft-graph-comms-samples I saw that you closed your issue  here but I recommend reopening this  or opening the same issue for more information. 
I also suggest posting this question in StackOverFlow or Microsoft Q & A with Teams, Graph API tags.

**Comment by siva1545** [comment]
@nikithauc 
You mentioned 3 points and I am re-iterating what I am expecting

1. Graph API supports Audio calls only for Bot, but I want to have the same in SPA (Single Page Application) using Angular. Raised the same in this forum as this sdk is meant for Angular
2. I closed the same issue on BOT SDK. As this is related to JavaScript SDK, so I raised here (this issue) and closed BOT SDK issue.
3. Even though this feature is using Graph API and Teams, this SDK needs to add the required support/code. Would like to track this under this github issues only.

Thanks

**Comment by nikithauc** [comment]
The communications APIs are not designed for client side support.  They drive server to server scenarios (recording, voice response, voice mail, etc...).  There is no way to do client web app integration using the communications APIs.

More information and requirement gathering is needed to understand if and how `server to server` support can be provided by the SDKs.

We currently have this issue in our backlog and we don't yet have a timeline for this issue , but once we do we'll add more information to this issue.
