### ISSUE TITLE
What's the recommended way to dynamically request the necessary permissions?

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-sdk-javascript#395]
Say I have a JavaScript app that allows users to show their email, among other things. Ideally, during sign in, we'd ask only the basic access to their profile and wait with requesting permissions for accessing email until they use that portion of the app.

Would something like the following snippet be the recommended way of implementing it or is there a better way?

```js
// setup Graph SDK + MSAL; based on https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=Javascript
const clientId = "INSERT-CLIENT-APP-ID"; // Client Id of the registered application
const callback = (errorDesc, token, error, tokenType) => {};
// An Optional options for initializing the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#configuration-options
const options = {
	redirectUri: "Your redirect URI",
};
const graphScopes = ["user.read"]; // An array of graph scopes

// Initialize the MSAL @see https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics#initialization-of-msal
const userAgentApplication = new UserAgentApplication(clientId, undefined, callback, options);
const authProvider = new MSALAuthenticationProvider(userAgentApplication, graphScopes );

//
// called when user chooses to show emails in the app
//
function loadEmails() {
  if (graphScopes.indexOf('mail.read') < 0) {
    graphScopes.push('mail.read');
  }

  // call graph here to request emails
}
``` 
[AB#8310](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8310)

**Comment by baywet** [comment]
Thanks for posting here @waldekmastykarz .
To recap some of the conversation we've had offline, the scopes array reference is [kept all the way down to the moment the token is requested](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a26c288b3463c49bf9862e32865bd0beed72753a/src/ImplicitMSALAuthenticationProvider.ts#L93).
So I believe that keeping that reference and changing the content of the array should allow you to change the scopes and have the MSAL lib request a new token without having to discard the graph client.
I haven't tested that theory though and @nikithauc can probably provide additional details about this scenario.

**Comment by baywet** [comment]
[Our documentation](https://docs.microsoft.com/en-us/graph/sdks/create-client?tabs=Javascript) looks outdated since the [provider has been renamed](https://github.com/microsoftgraph/msgraph-sdk-javascript/commit/fe072046f273b7c3dc2d035364de4a7c8b0400fd#diff-47d67d04f0a75dcbb467d04a6c29df69c422e86885f8c41e6b7ce171cd898466) though. CC @nikithauc

**Comment by nikithauc** [comment]
@waldekmastykarz  
Graph Explorer does something similar to your requirement. We can modify and update permissions for different services after login and it works with a single instances of the JS SDK Client.
Something that might help at - 
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/20f67242038e4e1ea1b879ff1d2b6b73fcf14d1a/src/app/services/graph-client/msal-service.ts#L122

Here in this function when refreshing the access token we take the scopes and store
https://github.com/microsoftgraph/microsoft-graph-explorer-v4/blob/20f67242038e4e1ea1b879ff1d2b6b73fcf14d1a/src/index.tsx#L72

Thank you @thewahome for this information.

**Comment by waldekmastykarz** [comment]
Thanks for the pointer @nikithauc. When trying to get the code to work, I came across another issue, that we'd need to sort our first.

I noticed that we show devs two ways to instantiate the Graph client: one that I mentioned above which is in our docs on the JS SDK page, and the other one in the tutorial @ https://docs.microsoft.com/en-us/graph/tutorials/javascript?tutorial-step=3. The main difference between them is that the second one uses a custom auth provider whereas the first one uses `ImplicitMSALAuthenticationProvider` from the Graph SDK. Which of these approaches would be the recommended way forward?

**Comment by nikithauc** [comment]
@waldekmastykarz

Are you writing a browser application ?

If yes, I suggest using the Authorization Code flow with PKCE. Implicit flow is not recommended anymore.
https://tools.ietf.org/html/draft-ietf-oauth-browser-based-apps-00. 

I know of two packages that support PKCE flow -
1. MSAL 2.0 or the MSAL browser.
2. @azure/identity - This is what we will be using and we are planning to be release a 'TokenCredentialAuthProvider' in `3.0.0`. 
https://www.npmjs.com/package/@azure/identity
https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/identity/identity/interactive-browser-credential.md
https://github.com/Azure/azure-sdk-for-js/issues/13080

Please let me know if you have more questions. I am happy to help you in the implementation of your authentication component.

**Comment by waldekmastykarz** [comment]
Thank you for the additional information @nikithauc. Let me try everything you've shared so far and get back to you if I have any more questions 👍
