### ISSUE TITLE
Mail folder delta - get endpoint missing skiptoken query parameter

### ISSUE THREAD

**Issue by kairiruutel** [microsoftgraph/msgraph-sdk-javascript#399]
Requesting mail folder deltas it does not seem to be possible to pass `skiptoken` query parameter.

Endpoint: `/me/mailFolders/delta`
Method: `get`

`skiptoken` is not available from query parameters: https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/QueryParameters.md

https://docs.microsoft.com/en-us/graph/api/mailfolder-delta?view=graph-rest-1.0&tabs=http

Am I missing something? Is there a possible workaround I could use to make the request?
 
[AB#8470](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8470)

**Comment by kairiruutel** [comment]
It can be closed, I realised there is `.query()` for adding additional query parameters. 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/OtherAPIs.md#query

**Comment by markfields** [comment]
I actually do see a `skipToken` member on `GraphRequest`, but no `deltaToken` member (I'm on v `2.2.1`). So if you're going to have one, why not both?

Also it looks like the documentation is missing `$skiptoken`:  https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/QueryParameters.md

cc @nikithauc (I know it's not nice to comment on closed issues...)

**Comment by markfields** [comment]
btw - while thinking about this I opened #407 (and proposal draft PR #408) which would make these not really necessary in most cases
