### ISSUE TITLE
Is there a helper to calculate the orderHint for Planner tasks and buckets?

### ISSUE THREAD

**Issue by chauey** [microsoftgraph/msgraph-sdk-javascript#4]
We are not able to find here or online about how reorder buckets/tasks for the Planner. Is there a library/helper that can help with that and should it be in this sdk? thanks!

**Comment by dan-silver** [comment]
Hey chauey that's a great idea for this SDK and we're considering adding some helper utilities that make calls easier.  I'll investigate an orderHint helper further this week. Thank you
