### ISSUE TITLE
Getting a 'UnableToDeserializePostBody' when creating a recurring event

### ISSUE THREAD

**Issue by codeRuth** [microsoftgraph/msgraph-sdk-javascript#404]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

When creating a recurring calendar event, the graph client throws a ` {"code":"UnableToDeserializePostBody","message":"were unable to deserialize "}` error. I tried creating a normal event, works fine, but fails for a recurring event. 

POST payload - 

`{
  subject: 'Flute - Beginners S By Divyansh',
  body: { contentType: 'HTML', content: 'Flute - Beginners S By Divyansh' },
  start: { dateTime: '2021-03-14T07:00:00Z', timeZone: 'India Standard Time' },
  location: { displayName: 'Online' },
  attendees: [],
  recurrence: {
    pattern: { type: 'weekly', interval: 1, daysOfWeek: [Array] },
    range: { type: 'endDate', startDate: '14/03/2021', endDate: '14/12/2021' }
  },
  isOnlineMeeting: true,
  onlineMeetingProvider: 'teamsForBusiness'
}
`
Here's the snippet

`try {
    return await clientAPI
      .api(`/users/${process.env.AZURE_TECH_USER}/calendar/events`)
      .post(event);
  } catch (error) {
    console.log(error);
  }`

**Screenshots:** 
![image](https://user-images.githubusercontent.com/9111393/111888538-7ce74b80-8a03-11eb-8a73-2828b6dfe4b4.png)

`requestId: null`

SDK Version - 2.2.1
-   [x] Node (Check, if using Node version of SDK)
> Node Version - v12.18.3

 
[AB#8688](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8688)

**Comment by nikithauc** [comment]
Hello @codeRuth. Thank you for getting in touch! 

I was not able to validate the json in the POST payload that you mentioned in the issue.
```
{ subject: 'Flute - Beginners S By Divyansh', body: { contentType: 'HTML', content: 'Flute - Beginners S By Divyansh' }, start: { dateTime: '2021-03-14T07:00:00Z', timeZone: 'India Standard Time' }, location: { displayName: 'Online' }, attendees: [], recurrence: { pattern: { type: 'weekly', interval: 1, daysOfWeek: [Array] }, range: { type: 'endDate', startDate: '14/03/2021', endDate: '14/12/2021' } }, isOnlineMeeting: true, onlineMeetingProvider: 'teamsForBusiness' }
```
Can you please verify that and provide a valid json payload which is producing the same `UnableToDeserializePostBody` error?

The following is a small sample that I tried  and it worked -
```json
{
    "subject": "My event",
    "start": {
        "dateTime": "2021-03-22T17:55:08.910Z",
        "timeZone": "UTC"
    },
    "end": {
        "dateTime": "2021-03-29T17:55:08.910Z",
        "timeZone": "UTC"
    },
    "recurrence": {
        "pattern": {
            "type": "weekly",
            "interval": 1,
            "daysOfWeek": [
                "Monday"
            ]
        },
        "range": {
            "type": "endDate",
            "startDate": "2017-09-04",
            "endDate": "2017-12-31"
        }
    }
}
```

Please check the following link for the examples of creating a recurring event -
https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#example

**Comment by codeRuth** [comment]
Hello @nikithauc, fixed the issue, it had got to do with the date format, which was not very clear in the documentation. Thank You.

**Comment by piboistudios** [comment]
I'd just like to know in what world is this acceptable error handling?
Broken english
No _meaningful_ stack trace
And why would it be trying to deserialize the _request_ body (the request body is already in memory as an object... deserialization takes a string and converts it into an object... so does that mean the request body is being serialized and then deserialized for validation..? I wouldn't be surprised) 

ETA: Oh, I guess the client doesn't do request validation, so it's just passing though whatever object to the server and responding with this... which leads me to another point: 

God forbid the error message include _what_ is actually wrong with the request body..? I mean it's coming straight from the Graph API... the Graph API isn't capable of figuring this out? All of that information should be in the same context the error is thrown from.. In fact I _know_ it is, if it's not, it's being obscured by anti-patterns.

~The message isn't even right.. it has me thinking the Graph response is malformed when it's actually the request body apparently, based on this thread.~


Typical Microsoft...
