### ISSUE TITLE
Add a getDelta function to GraphRequest

### ISSUE THREAD

**Issue by markfields** [microsoftgraph/msgraph-sdk-javascript#407]
# Feature Request

## Is your feature request related to a problem? Please describe

Working with a `/delta` endpoint (like `me/calendarView/delta` in my case) is kind of painful, unless I'm missing something. e.g. here's how I'm extracting the `skiptoken`:

```typescript
const skipToken = new URL(response["@odata.nextLink"]).searchParams.get("$skiptoken") ?? undefined;
```

I have to do the same for `deltatoken`, then check if either is undefined and then proceed accordingly.

## Describe the solution you'd like

See draft PR #408

## Describe alternatives you've considered

If the proposed function "doesn't fit" on `GraphRequest` then I'll just keep it as my own private helper in my code, no worries.

Another approach is to also take a dependency on a vanilla HTTP Client package, set the auth header and call the nextLink/deltaLink directly, but that feels like a bummer.

## Additional context

Taking a step back, the point of this whole SDK is to provide an abstraction over simple HTTP requests to the Graph. You can use it instead of a typical HTTP Client, specifying the auth token, other headers, and URL structure through API calls instead of directly on a request object. But then in the case of a `/deltas` request, the response contains raw URLs to call (`@odata.nextLink` and `@odata.deltaLink`). These are unusable in the context of the SDK!  So you're left calling those links using a vanilla HTTP Client package (and manually setting the auth token), or awkwardly extracting the skip/delta token to pass to the SDK again.

A much nicer experience as an SDK consumer is to have the SDK take care of those details and present a nice API to encapsulate the semantics of a `/delta` request.
 
[AB#8733](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8733)

**Comment by nikithauc** [comment]
@markfields  Thank you for the contribution! I will review the PR and the approaches proposed in this issue and get back to you.

**Comment by nikithauc** [comment]
@markfields 
FYI, the PageIterator task has a [getDeltaLink API](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/c239b7cd652d636648445139b6b5df1523640916/src/tasks/PageIterator.ts#L169) which gives access to the delta link when working with a collection of items. 

The requirement you stated in this issue expects additional capabilities such as a 
1. getDeltaToken()
2. getSkipToken()
while working with paged collection or `/delta` query. 
Am I right? 

Also, can you please elaborate more on your comment ?

> You can use it instead of a typical HTTP Client, specifying the auth token, other headers, and URL structure through API calls instead of directly on a request object. But then in the case of a /deltas request, the response contains raw URLs to call (@odata.nextLink and @odata.deltaLink). These are unusable in the context of the SDK! So you're left calling those links using a vanilla HTTP Client package (and manually setting the auth token), or awkwardly extracting the skip/delta token to pass to the SDK again

Are you suggesting for more capabilities other than the access to `deltaToken` and the `skipToken`?

**Comment by MIchaelMainer** [comment]
We shouldn't return just the deltatoken or skiptoken. You still have to then build the resource path. We should return deltalink and nextlink without the **host** + **endpoint** part of the URL. This way, I can do `client.api(deltalink).get()`.

**Comment by ddyett** [comment]
closing older issue
