### ISSUE TITLE
No reference documentation found in docs.microsoft.com/javascript/api

### ISSUE THREAD

**Issue by ramya-rao-a** [microsoftgraph/msgraph-sdk-javascript#424]
While discussing how to create service principals in https://github.com/Azure/azure-sdk-for-js/issues/14833, @diberry found that we don't have any reference documentation in https://docs.microsoft.com/javascript/api for the package `@microsoft/microsoft-graph-client`. I couldnt find any either.

I would have expected these reference docs to be at https://docs.microsoft.com/en-us/javascript/api/@microsoft/microsoft-graph-client
 
[AB#9016](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9016)

**Comment by nikithauc** [comment]
Thank you @ramya-rao-a for bringing up this point!

I will have to learn more about this issue and I will get back to you.
