### ISSUE TITLE
3.0.0 version - ETA of release

### ISSUE THREAD

**Issue by mdybich** [microsoftgraph/msgraph-sdk-javascript#431]
We are waiting for the stream support for the Large File Upload Task (added as a part of this PR https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/401) which seems to be included in the upcoming 3.0.0 version.

Do you have any ETA when the 3.0.0 version will be officially released and ready to use?  
[AB#9100](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9100)

**Comment by nikithauc** [comment]
@mdybich 3.0.0 will be released by the end of  May, 2021 at the latest.

**Comment by mdybich** [comment]
Ok. Thank you for your answer.

**Comment by nikithauc** [comment]
@mdybich Here is a preview of the 3.0.0 version - 
https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.1

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/changelogs/v3-upgrade-guide.md
