### ISSUE TITLE
CDN link

### ISSUE THREAD

**Issue by tarunchopra** [microsoftgraph/msgraph-sdk-javascript#44]
Can we get CDN link for this library? We want to access graph using this library from ScriptLab (https://github.com/OfficeDev/script-lab) but we need JavaScript CDN to do that. ScriptLab does not support TypeScript

**Comment by Zlatkovsky** [comment]
@tarunchopra , Script Lab does support TypeScript... but in any case, you can always make _any_ NPM package into a CDN location by using a service like https://unpkg.com:

https://unpkg.com/@microsoft/microsoft-graph-client@1.0.0/lib/graph-js-sdk-web.js

That being said, we don’t currently have a way to authenticate to Graph from Script Lab.  Issues
https://github.com/OfficeDev/script-lab/issues/430 and an older https://github.com/OfficeDev/script-lab/issues/85 are tracking it.
