### ISSUE TITLE
Try out the preview of 3.0.0 version of the JS client library! 📢 📢

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#444]
[@microsoft/microsoft-graph-client 3.0.0-Preview.1](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.1) is released!!

3.0.0 version introduces the `TokenCredentialAuthenticationProvider` enabling the use of `@azure/identity` `credential classes` for authentication purposes. 
The `TokenCredentialAuthenticationProvider` enables support for multiple authentication flows. And with that, 3.0.0 introduces support for server-side authentication!!

Enhancements are introduced to the large file upload feature enabling support for Node.js Stream upload, capabilities to track the upload progress.

Learn more about changes in this release which are documented in the [3.0.0 Upgrade Guide](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/changelogs/v3-upgrade-guide.md). 
[AB#9211](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9211)

Update - 
[@microsoft/microsoft-graph-client 3.0.0-Preview.2](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.2) has been released. 
- Added `customHosts` options -The `AuthenticationHandler` and `TelemetryHandler` will add or update the request headers only if the request URL is a Graph endpoint or a custom endpoint. `customHosts` property in `IOptions`, `IClientOptions` takes in a `Set` of custom hosts. 
- Fixed #452. 

7/28/2021 Update - 
[@microsoft/microsoft-graph-client 3.0.0-Preview.3](https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.3)  has been released. 
- This preview contains the new AuthCodeMSALBrowserAuthenticationProvider to support authentication using [MSAL Browser](https://www.npmjs.com/package/@azure/msal-browser).
-  Removing `ImplicitMSALAuthenticationProvider` in 3.0.0 and thereby, ending the support for MSAL V1.

8/9/2021 Update - 
3.0.0 is out!!! - https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0

**Comment by jeroenvdmeer** [comment]
Thanks for already updating the documentation! This allowed me to learn about `TokenCredentialAuthenticationProvider` while I'm currently looking into implementing the Microsoft Graph JavaScript Client Library. However, as being new to this library, it did took me half an hour to find this issue and realize I needed the `@3.0.0-Preview.1` version of the npm package instead of `@latest`. Maybe it'd be worth mentioning `TokenCredentialAuthenticationProvider` is only available as of verion 3?

Also, I noticed the links to TokenCredentialAuthenticationProvider and ImplicitMSALAuthenticationProvider were broken on [the doc about CreatingClientInstance](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CreatingClientInstance.md). Maybe worth fixing?

**Comment by nikithauc** [comment]
Thank you @jeroenvdmeer ! 

Appreciate your feedback and will work on fixing the links.

**Comment by andrew-hwahin** [comment]
Hi @nikithauc can I use version 3.0.0 on the front-end React client? Or can it only run on backend Node.js?

**Comment by nikithauc** [comment]
> Hi @nikithauc can I use version 3.0.0 on the front-end React client? Or can it only run on backend Node.js?

@andrew-hwahin you can use the library with your front-end React application. The library is isomorphic :)

**Comment by dennisameling** [comment]
This is working great in a NodeJS backend service! [Was having issues with v2](https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/455) of this SDK in combination with Client Credentials, but v3 works perfectly 🚀

For anyone who's interested in some demo code (NestJS/TypeScript), here it is: https://github.com/dennisameling/msgraph-nodejs-issue/blob/msgraph-v3/src/app.service.ts - steps to test in my demo repo are here: https://github.com/dennisameling/msgraph-nodejs-issue/tree/msgraph-v3#readme

**Comment by nikithauc** [comment]
@dennisameling Thank you so much for your feedback and for sharing the demo code!

**Comment by TenBuck** [comment]
> TokenCredentialAuthenticationProvider

I just spent 3 hours looking for it! I'd recommend updating the docs to reflect that TokenCredentialAuthenticationProvider isn't available yet

**Comment by nikithauc** [comment]
Microsoft Graph JavaScript Client Library 3.0.0 is released - https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0
