### ISSUE TITLE
Invalid x5t claim

### ISSUE THREAD

**Issue by andrew-hwahin** [microsoftgraph/msgraph-sdk-javascript#451]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

This is my first time trying to integrate Microsoft Graph API into my web app.
I received `Invalid x5t claim.` while using `@microsoft/microsoft-graph-client`. 
I assumed this error means my accessToken is invalid, but when I verify the accessToken in https://jwt.ms/ it shows my accessToken is valid.

**Console Errors:** 
```
{
    "errors": [
        {
            "message": "Invalid x5t claim.",
            "locations": [
                {
                    "line": 33,
                    "column": 3
                }
            ],
            "path": [
                "activeDirectoryUsers"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "statusCode": 401,
                    "code": "InvalidAuthenticationToken",
                    "requestId": "19f4bcb0-6290-43a9-a780-cc3f2e9e4407",
                    "date": "2021-05-10T18:01:26.000Z",
                    "body": "{\"code\":\"InvalidAuthenticationToken\",\"message\":\"Invalid x5t claim.\",\"innerError\":{\"date\":\"2021-05-11T02:01:26\",\"request-id\":\"19f4bcb0-6290-43a9-a780-cc3f2e9e4407\",\"client-request-id\":\"d54cf0f2-708c-93f2-56cc-51a5883554b9\"}}",
                    "stacktrace": [
                        "Error: Invalid x5t claim.",
                        "    at new GraphError (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\src\\GraphError.ts:59:3)",
                        "    at Function.GraphErrorHandler.constructErrorFromResponse (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\src\\GraphErrorHandler.ts:62:18)",
                        "    at Function.<anonymous> (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\src\\GraphErrorHandler.ts:89:31)",
                        "    at step (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\node_modules\\tslib\\tslib.js:141:27)",
                        "    at Object.next (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\node_modules\\tslib\\tslib.js:122:57)",
                        "    at C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\node_modules\\tslib\\tslib.js:115:75",
                        "    at new Promise (<anonymous>)",
                        "    at Object.__awaiter (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\node_modules\\tslib\\tslib.js:111:16)",
                        "    at Function.GraphErrorHandler.getError (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphErrorHandler.js:88:24)",
                        "    at GraphRequest.<anonymous> (C:\\Users\\andrew_lam\\GitHub\\worker-transfer-redwoodjs\\node_modules\\@microsoft\\microsoft-graph-client\\src\\GraphRequest.ts:386:55)"
                    ]
                }
            }
        }
    ],
    "data": null
}
```

**Screenshots:** 
I found out that line 13 is producing the error.
![image](https://user-images.githubusercontent.com/61768800/117752015-a7f25c80-b248-11eb-8659-f94520cb22ac.png)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Return a list of all active directory users.

**Actual behavior:** Throws an error of `Invalid x5t claim.`

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - 19f4bcb0-6290-43a9-a780-cc3f2e9e4407

SDK Version - 2.2.1

-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - Google Chrome on Windows

> Version - 90.0.4430.93 (Official Build) (64-bit)
 
[AB#9376](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9376)

**Comment by andrew-hwahin** [comment]
I tried to replace the accessToken with an invalid value such as "sdkfjsdklfjsd", then the error produced is:

> CompactToken parsing failed with error code: 80049217

But when I use a valid accessToken, the error produced was `Invalid x5t claim.`. What does the error mean?

**Comment by nikithauc** [comment]
@andrew-hwahin 
Is your app set up under Azure AD B2C? Are using an access token for an AAD B2C user to lists users in an AAD tenant? 

Following are similar to the issue you have reported:

https://docs.microsoft.com/en-us/answers/questions/246207/34upn-from-claims-with-value-null-is-not-a-valid-u.html?childToView=249533#comment-249533
https://stackoverflow.com/questions/67058760/azure-b2c-ropc-token-not-valid-for-microsoft-graph-api-missing-x5t-claim

**Comment by andrew-hwahin** [comment]
Hi @nikithauc thanks for helping 🙏

My app is not using Azure AD B2C, it is a single-tenant setup.

I realised that my app is using MSAL v1 library to sign the user in, is it compatible? Or must I use MSAL v2?

**Comment by nikithauc** [comment]
@andrew-hwahin MSAL v1 uses the Implicit flow. Implicit flow is not recommended anymore.

Please choose an authentication flow which works for your app set up. [Guidance to choose the authentication flow](https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=Javascript)

I recommend using MSAL v2 or @azure/identity.

**Comment by andrew-hwahin** [comment]
ok noted thanks for the help, the issue is resolved 🙏😁
