### ISSUE TITLE
Large File Upload - retry doesn't work for StreamUpload 

### ISSUE THREAD

**Issue by mdybich** [microsoftgraph/msgraph-sdk-javascript#452]
# Bug Report

## Description

It looks like the retry for the large file upload doesn't work for `StreamUpload`.
When the [`resume`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/ed06eb73cf8ed819ca2b9938cb077416e3e25334/src/tasks/LargeFileUploadTask.ts#L356) is invoked, in the first step the [`getStatus`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/ed06eb73cf8ed819ca2b9938cb077416e3e25334/src/tasks/LargeFileUploadTask.ts#L344) method is called in order to update `expiry` and `nextRange` properties - at this step everything is fine. 

After properties are properly updated, the [`upload`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/ed06eb73cf8ed819ca2b9938cb077416e3e25334/src/tasks/LargeFileUploadTask.ts#L243) is called and then [`sliceFile()`](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/ed06eb73cf8ed819ca2b9938cb077416e3e25334/src/tasks/LargeFileUploadTask.ts#L252) from the StreamUpload that is causing a problem - it should read the bytes that should be retried, but instead, it's just getting next portion of bytes which seems to be not correct since the bytes that should be retired are not read from the stream.

## Steps to Reproduce

Call `resume` method when the `StreamUpload` is passed to the `LargeFileUploadTask`:
```
function test(): Promise<any> {
   const fileObject = new StreamUpload(readStream, data.fileName, data.fileSize);
   const uploadTask = new LargeFileUploadTask(client, fileObject, uploadSession);

  try {
    await uploadTask.upload();
  } catch(error) {
    await uploadTask.resume();
  }
}
```

  

**Expected behavior:** The upload is properly resumed for the stream data. 

**Actual behavior:** The retry doesn't work for the stream data.

## Usage Information

SDK Version - 3.0.0-Preview.1

 
[AB#9415](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9415)

**Comment by nikithauc** [comment]
@mdybich Thank you for reporting this issue! I will take a look at it.

**Comment by nikithauc** [comment]
@mdybich A fix for this has been released in https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.2.
