### ISSUE TITLE
Is there any chatting app sample code?

### ISSUE THREAD

**Issue by chakravarthi-vl** [microsoftgraph/msgraph-sdk-javascript#454]
# Feature Request

## Additional context

 
[AB#9485](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9485)

**Comment by nikithauc** [comment]
@chakravarthi-vl Can you please provide more details about your requirements? 
What is the specific data that you are looking to fetch from/ post to the Graph API?

**Comment by chakravarthi-vl** [comment]
Hi, @nikithauc thanks For the Reply,

I have a requirement to integrate the Teams chat in my angular application. Is there any lib that I can integrate directly?

**Comment by nikithauc** [comment]
@chakravarthi-vl 
I recommend checking this - https://answers.microsoft.com/en-us/msteams/forum/msteams_tfb-msteams_chatg-msteams_chatgr/integrating-microsoft-teams-to-an-angular/1e215213-2839-494b-b983-b6f1da6b2aa2.

May be you can post this question https://github.com/OfficeDev/microsoft-teams-library-js#readme?

**Comment by nikithauc** [comment]
Closing this due inactivity. @chakravarthi-vl  Please feel free to open a new issue if there are more questions.
