### ISSUE TITLE
ECONNRESET on Node 12+ after 2 mins (but connection to MS Graph works)

### ISSUE THREAD

**Issue by dennisameling** [microsoftgraph/msgraph-sdk-javascript#455]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When using this library to connect to Azure AD B2C for getting/creating/updating users, after 2 mins the error below is thrown on NodeJS 12+. In the meantime, it's possible to execute as many requests as you want (and they return data successfully), but as soon as the error pops up, the application stops working completely.

**Console Errors:**

```
node:events:342
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:211:20)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Screenshots:** [If applicable, add screenshots to help explain your problem]

The application is able to get data from Azure AD B2C correctly (until the console error pops up):

![image](https://user-images.githubusercontent.com/17739158/118708544-2720fb00-b81c-11eb-9a8d-aa07e91f78f4.png)

## Steps to Reproduce

1. Install NodeJS 12, 14, 15 or 16
1. `git clone https://github.com/dennisameling/msgraph-nodejs-issue && cd msgraph-nodejs-issue`
1. Copy `.env.dist` to `.env` and set the Client ID, Client Secret, and Access Token URL [as described in the Azure AD docs](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret) (can be either Azure AD or Azure AD B2C)
1. Run `npm install`
1. Run `npm start`
1. Open your browser and navigate to `http://localhost:3000/users/{ID}`, where `{ID}` is a UUID of a user that actually exists in Azure AD (B2C). You will get the response in <1s and you can repeat the request multiple times if you want. This demonstrates that a connection with Microsoft's servers is possible.
1. Wait for ~2 minutes. You'll see the error above pop up in your console.

**Expected behavior:** [What you expected to happen]

Shouldn't throw an `ECONNRESET` error after 2 mins

**Actual behavior:** [What actually happened]

Throws an `ECONNRESET` error after 2 mins, blocking the whole application

## Additional Context

Minimal repo for reproducing the issue: https://github.com/dennisameling/msgraph-nodejs-issue

## Usage Information
Request ID - N/A

SDK Version - 2.2.1 (also tried with the 3.0 preview)

-   [x] Node

> Node Version - 12, 14, 15 and 16 
[AB#9503](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9503)

**Comment by dennisameling** [comment]
Just tried with the SDK v3 preview, and thanks to the new `ClientSecretCredential` I no longer have to have a custom `AuthProvider`! 🎉 

Can confirm that this issue is not present when using the v3 preview in combination with the `ClientSecretCredential` 👍🏼 

For anyone who's interested in the code, here it is: https://github.com/dennisameling/msgraph-nodejs-issue/blob/msgraph-v3/src/app.service.ts - steps to test in my demo repo are here: https://github.com/dennisameling/msgraph-nodejs-issue/tree/msgraph-v3#readme

So I think this issue can be closed now, assuming that v3 will be released soon 😊

**Comment by nikithauc** [comment]
@dennisameling were you using a custom authprovider with version 2.x of the Graph library?

**Comment by nikithauc** [comment]
Closing this as solution will be present in 3.0.0 version.
