### ISSUE TITLE
Issue with using custom authentication provider

### ISSUE THREAD

**Issue by sibi-ghl** [microsoftgraph/msgraph-sdk-javascript#469]
The documentation says that the `getAccessToken()` method is called every time before we make a request with the client API. 
But, how do we determine which user's access token we are supposed to return from that method? Each user has a unique access token that is stored in our database. 

![image](https://user-images.githubusercontent.com/67587425/121345305-4d7d1680-c942-11eb-988e-ef50b034800b.png)

When we get a request, we need to be able to pass in an ID to the method dynamically which will allow us to write logic to query the access token for that user.

The documentation isn't very clear on that one. It would be really helpful if the documentation can be improved here. 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/CustomAuthenticationProvider.md 

Thanks!
 
[AB#9817](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9817)

**Comment by nikithauc** [comment]
@sibi-ghl Thank you for the feedback!

In most cases, the a single user is logged in or the application is registered to a single entity and the request made involves a  single account. 

Following is a sample you can use - 

Consider an implementation of the `AuthenticationProvider` interface and `AuthenticationProviderOptions` interface. 

```typescript
export interface AuthenticationProvider {
	/**
	 * To get access token from the authentication provider
	 * @param {AuthenticationProviderOptions} [authenticationProviderOptions] - The authentication provider options instance
	 * @returns A promise that resolves to an access token
	 */
	getAccessToken: (authenticationProviderOptions?: AuthenticationProviderOptions) => Promise<string>;
}

export interface AuthenticationProviderOptions {
	scopes?: string[];
}
```
 

You custom implementation can be as follows -

```typescript
export interface MyCustomAuthenticationProviderOptions extends AuthenticationProviderOptions {
	scopes?: string[]; // set the scope for the request here. the scopes will be specific to the user
        userId: number; // you can set your user id here
}

import { AuthenticationProvider } from "../IAuthenticationProvider";

export class MyCustomAuthenticationProvider  implements AuthenticationProvider{
  public async getAccessToken(authenticationProviderOptions?: MyCustomAuthenticationProviderOptions): Promise<string> {
    const userid = authenticationProviderOptions.userId.
    // Implement user logic to retrieve the access token for that userId.
    // Return the accessToken
  }
}
```

I agree that the documentation on this needs to be improved. Thank you for pointing that out! 

Please let me know if you have any more questions.
