### ISSUE TITLE
Dependency on package.json breaks ability to webpack

### ISSUE THREAD

**Issue by anpetral-msft** [microsoftgraph/msgraph-sdk-javascript#47]
GraphRequest.js depends on the ability to open ../../package.json. This breaks the ability to package the script easily with tools like webpack or host the scripts on a CDN, and takes an external dependency on the packaging of the scripts (NPM).

I should clarify that it can be made to work with webpack, but it requires the use of json-loader.

**Comment by dan-silver** [comment]
Thanks @anpetral-msft for reporting this. We depend on the package.json file for getting the version number. We can create a constants file instead of depending on package.json.

**Comment by anpetral-msft** [comment]
Thanks for looking into this! That would address the concern.

**Comment by balbany** [comment]
Any update to this? Those using things like create-react-app will encounter significant pain...

**Comment by muthurathinam** [comment]
This was fixed with this commit: https://github.com/microsoftgraph/msgraph-sdk-javascript/commit/355fbcd77286629277ea226a486c08b12c405c95
