### ISSUE TITLE
Documentation for using Graph SDK with MSAL.js

### ISSUE THREAD

**Issue by derisen** [microsoftgraph/msgraph-sdk-javascript#470]
# Feature Request

## Is your feature request related to a problem? Please describe

We have implemented a set of samples (see below) demonstrating how to use MSAL.js as a custom authentication provider for this library. Would it be possible to document these or mention them in the wiki?

- [Vanilla JS SPA using MSAL Browser](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/tree/main/2-Authorization-I/1-call-graph)
- [Angular SPA using MSAL Angular](https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/2-Authorization-I/1-call-graph)
- [React SPA using MSAL React](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/2-Authorization-I/1-call-graph)
 
[AB#9843](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9843)

**Comment by nikithauc** [comment]
@derisen  This is awesome! 
I will add these in the ReadMe. Thank you for the samples!
