### ISSUE TITLE
not able to upload large files using upload session

### ISSUE THREAD

**Issue by swapnilshinde48** [microsoftgraph/msgraph-sdk-javascript#474]
# Bug Report
For more information, see the `CONTRIBUTING` guide.

## Description
-   Not able to upload large file by creating upload session in react js, does any one have readymade code for this

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** large file should upload or if anyone having working code to upload file using upload session

**Actual behavior:** [What actually happened]

## Additional Context

Add any other context about the problem here..

SDK Version -3.0 preview 2

-   [ ] Node (Check, if using Node version of SDK)

> Node Version -latest

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - chrome

 
[AB#9954](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9954)

**Comment by nikithauc** [comment]
@swapnilshinde48 Thanks for reaching out :) 

Please find the documentation here - https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/LargeFileUploadTask.md

The following is a code snippet demonstrating how to upload a large file.

```

const uploadSession = await new MicrosoftGraph.LargeFileUploadTask.createUploadSession(client, CREATE_UPLOAD_SESSION_URL, payload);
const file = fs.createReadStream('./test.pdf');


const stats = fs.statSync(`./test.pdf`);
const totalsize = stats.size;

const stream = new MicrosoftGraph.StreamUpload(file,'test.pdf',totalsize);
const task = new MicrosoftGraph.LargeFileUploadTask(client,stream,uploadSession,options);
const uploadResult = await task.upload();
console.log(uploadResult); 

```

Can you please provide answers to the following:
- Are you trying a stream or a file upload? 
- What is the service you are trying to upload to - Outlook or OneDrive?  
- What is the error you are facing when trying to upload? 
- Can you please provide steps to reproduce?

**Comment by MIchaelMainer** [comment]
No repro here. I'm able to upload using this code.

**Comment by nikithauc** [comment]
@swapnilshinde48 Please feel free to open a new issue if you have more questions
