### ISSUE TITLE
Assertion has expired error

### ISSUE THREAD

**Issue by sibi-ghl** [microsoftgraph/msgraph-sdk-javascript#475]
![image](https://user-images.githubusercontent.com/67587425/123219072-1b46e980-d4ea-11eb-85d9-600b94f1d9ae.png)

We are occasionally getting this error. Any insight on what is causing this?
This comes up all of a sudden and the only way to make it go is to integrate again.  
[AB#10034](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10034)

**Comment by nikithauc** [comment]
@sibi-ghl 

This does not look like a Graph JS client library issue. 

Looking at the error I think it would be best if you can post this question in:  
- https://github.com/AzureAD/microsoft-authentication-library-for-js
- Microsoft Q & A
- StackOverFlow.com
