### ISSUE TITLE
Using teams as a saas conferencing solution 

### ISSUE THREAD

**Issue by mullwaden** [microsoftgraph/msgraph-sdk-javascript#479]
# Feature Request

## Is your feature request related to a problem? Please describe
Our need is quite simple, via API create and reschedule online meetings with web links and dial-in numbers. The issue is that teams is centered around users, it's always a "user" that creates a meeting room.

_(We are a smallish company that currently uses Twilio to provide a solution where our users can interview experts. However many of our corporate customers are used to teams and often don't have the necessary whitelists for twilio to work properly. So we are looking into if teams is an option.)_

## Describe the solution you'd like

Ability to create meeting rooms based on a pool of users (or ideally without a user at all, paying instead for total meeting time or max number of simultaneous meetings or some such)

## Describe alternatives you've considered

One potential way to work around that is to

-  create a bunch of users
-  for any new or rescheduled meeting, in our back-end find a user that does not have a meeting at the given meeting time
-  create a meeting using that user and send links to our users in turn

 
[AB#10102](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10102)

**Comment by MIchaelMainer** [comment]
@nkramer

**Comment by MIchaelMainer** [comment]
@mullwaden Thank you for the question. This issue list is for feature requests and bugs in the client library. 

Feature requests should go here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft%20Graph
Q & A should go here: https://aka.ms/askgraph
