### ISSUE TITLE
Null response -  Content-Type: image/jpeg

### ISSUE THREAD

**Issue by tmszyman** [microsoftgraph/msgraph-sdk-javascript#48]
I have React app and I'm using msgraph-sdk-javascript to connect with Microsoft Graph API. I saw that response with content type - image/jpeg returns null value, so I can not decode the image and share in the app.

Sample query: '/me/contacts/' + id + '/photo/$value'

**Comment by MIchaelMainer** [comment]
Can you confirm that the user has an image set for them?

**Comment by tmszyman** [comment]
Yes, the user has an image. Graph API Explorer returns photo and Postman too, but this library returns null value.

**Comment by MIchaelMainer** [comment]
Can you provide me with a HTTP capture of both the request sent by the client and the response received by it?

**Comment by tmszyman** [comment]
Response:

> HTTP/1.1 200 OK
> Cache-Control: private
> Transfer-Encoding: chunked
> Content-Type: image/jpeg
> ETag: "89C63EA8"
> request-id: **
> client-request-id: **
> x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"SliceB","ScaleUnit":"003","Host":"AGSFE_IN_17","ADSiteName":"AMS"}}
> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: ETag, Location, Preference-Applied, Content-Range, request-id, client-request-id
> Duration: 163.2847
> Date: Mon, 04 Sep 2017 14:18:07 GMT

It's like captured response is good, but why I can't access it from code...
Response in console is null:
```
client
			.api('/me/photo/$value')
			.get()
			.then((res) => {
				console.log(res);
			}).catch((err) => {
				console.log(err);
			});
```

**Comment by MIchaelMainer** [comment]
I expect that this is the proper way to get a photo stream. Can you try this and tell us if this works for you:

client
    .api('https://graph.microsoft.com/v1.0/me/photo/$value')
    .getStream((err, downloadStream) => {
        let writeStream = fs.createWriteStream('../myPhoto.jpg');
        downloadStream.pipe(writeStream).on('error', console.log);
    });

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/master/samples/node/node-sample.js#L246

**Comment by tmszyman** [comment]
It works... thanks.
