### ISSUE TITLE
Update docs with deprecation statement and new token credential

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-sdk-javascript#482]
Update docs to show the new way to authorize a SPA. The following docs needs updates:

https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=Javascript#ImplicitProvider

Add statement of deprecation to docs/ImplicitMSALAuthenticationProvider.md:
https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/480/files#diff-42a01a1d95962f034481a79e189d141925cf41ae2968856098374be0d8023d15R1
 
[AB#10189](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10189)

**Comment by nikithauc** [comment]
This issue was addressed in the 3.0.0 release
