### ISSUE TITLE
Problem when listing managers

### ISSUE THREAD

**Issue by vincepunkrock** [microsoftgraph/msgraph-sdk-javascript#487]
I'm trying to make this request:
https://graph.microsoft.com/v1.0/me?$expand=manager($levels=max;$select=id,displayName)&$select=id,displayName&$count=true

as shown in the example here:
https://docs.microsoft.com/en-us/graph/api/user-list-manager?view=graph-rest-1.0&tabs=http#example-2-get-manager-chain-up-to-the-root-level

This is my code:
`
this.props.msGraphClientFactory.getClient().then((client: MSGraphClient): void => {
    client.api("/me?$expand=manager($levels=max;$select=displayName)&$select=id,displayName&$count=true").get();
});
`

**Expected behavior:** [What you expected to happen]
I would expect the request to work as it does in the graph explorer

**Actual behavior:** [What actually happened]
I doesn't work when called using the sdk.
I get this error:
Parsing OData Select and Expand failed: Found an unbalanced bracket expression.

It seems to cut the url right after "levels", before the equal sign.

SDK Version - [SDK version you are using]
2.2.1

-   [x] Browser (Check, if using Browser version of SDK)

Chrome

Version 92.0.4515.107 (Official Build) (32-bit)
 
[AB#10424](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10424)

**Comment by nikithauc** [comment]
@vincepunkrock Thank you for reaching out! 

I am not able to reproduce this issue. 
Tried this and it was able to receive the response: 

const res  = await gclient.api("/me?$expand=manager($levels=max;$select=displayName)&$select=id,displayName&$count=true").get(); 
    console.log(res);

Graph Explorer uses the Graph Client SDK to make the calls.

Can you please provide the following ? 
-  code snippet of how the client is initialized and the code making the Graph API calls
- Browser you are testing in and the framework or library you are using for development.

**Comment by vincepunkrock** [comment]
@nikithauc The code is used in a webpart and the client is initialized by SPFx. 

"msGraphClientFactory" is available in the webpart context.
I then pass it to my React component as a property.

This is in my react component in the componentDidMount method:

this.props.msGraphClientFactory.getClient().then((client: MSGraphClient): void => {
         client.api(\`/me?$expand=manager&$select=id,displayName,mail\`).get()
});

Notice I removed the part in the parenthesis after manager and it started working. 
The parsing of the url with the "($levels=max;$select=displayName)" part seems to be the problem.

**Comment by nikithauc** [comment]
@vincepunkrock 
Can you please verify the version of the Graph client that is returned by the `msGraphClientFactory`? 
SPFX uses the 1.x version of the Graph SDK library. There was a URL parsing issue in the older versions of the Graph SDK which was corrected in 2.1 version of Graph SDK.

Refer:
https://www.sebastienlevert.com/2021/04/18/latest-microsoft-graph-client-spfx/

**Comment by vincepunkrock** [comment]
@nikithauc Indeed, sp-http 1.12.1 still uses @microsoft/microsoft-graph-client": "~1.1.0
Thank you for your help.
