### ISSUE TITLE
Please provide the Readable Stream content, name of the file and size of the file

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-javascript#491]
# Bug Report
I am trying to use "@microsoft/microsoft-graph-client": "^3.0.0-Preview.3" in A SPFx web part.
By Adopting the code from msgraph-sdk-javascript/samples/typescript/tasks/LargeFileUploadTask.ts example

for some reason. the fs from `import * as fs from "fs";` breaks the code 
In any way, I will need to get the files from the user so I use `<input type="file" onChange={onFileChange} />`
which gives me a 'File' type 
So to get something like "Readable"
I do `const file: any = await  reader.readAsBinaryString(Myfile);`
but the line ` const fileObject = new StreamUpload(file, fixFileName , totalsize);` errors with:
Error: Please provide the Readable Stream content, name of the file and size of the file
I also tried `const file: any = await Myfile.stream().getReader().read();` but got Type script errors.

How can I make a "Readable" type from the 'File' type I get from the input?

Thank you!

 
[AB#10463](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10463)

**Comment by nikithauc** [comment]
@Ofer-Gal Thank you for reaching out! 

What framework of library are you using to develop the application? 

Readable is part of the Node  Stream feature.  More on this -> https://nodejs.org/api/stream.html#stream_class_stream_readable
Stream-browserify - https://www.npmjs.com/package/stream-browserify can be used to make it available in the browsers. 

Alternatively, you can also use the `FileUpload` class in the Graph JS library.
Please refer to this sample - 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/typescript/tasks/LargeFileUploadTask.ts

```typescript
import * as fs from "fs";
const file = fs.readFileSync();
const fileObject = new FileUpload(file, 'test.pdf', totalsize);
```

**Comment by Ofer-Gal** [comment]
I use SPFx for web part so Node is not included see [here](https://sharepoint.stackexchange.com/questions/219558/spfx-unable-to-use-fs-module)

I am using the same example you said but I can't us the fs module 
What else can I use to feed the FILE to the fileObject?

**Comment by Ofer-Gal** [comment]
I managed to figure out how to pump my file as "ArrayBuffer" to `new FileUpload`
So, I am good there.
But everything works accept the line `const uploadResult = await task.upload();`
which errors with:
TypeError: Cannot read properties of undefined (reading 'get')
    at Function.<anonymous> (GraphResponseHandler.js:94)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72)
    at Function.convertResponse (GraphResponseHandler.js:88)
    at Function.<anonymous> (GraphResponseHandler.js:168)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76
    at new Promise (<anonymous>)
------------------
Do you have an Idea what is wrong?
Thanks

**Comment by nikithauc** [comment]
@Ofer-Gal  looks like you encountered this error a while back https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/456#issuecomment-848303846.

Can you please verify if an upload session is being created and also if the Graph API is being called? 

I would check the network calls or use fiddler to inspect the response that causes this error. 
It looks like the response you are getting is `undefined`.

**Comment by Ofer-Gal** [comment]
upload session is being created with no error

**Comment by nikithauc** [comment]
Can you please provide the code snippet?

**Comment by Ofer-Gal** [comment]
try {
        const uploadSession: LargeFileUploadSession = await LargeFileUploadTask.createUploadSession(graphIds.client, requestUrl, payload);
        const fileObject = new FileUpload(Myfile, fixFileName, totalsize);
        const task = new LargeFileUploadTask(graphIds.client, fileObject, uploadSession, options);
        const uploadResult = await task.upload(); //Error comes here
        return uploadResult;
    } catch (error) {
        console.log(error);
    }

**Comment by nikithauc** [comment]
@Ofer-Gal I am not sure what is causing this issue.
It looks like you are not getting a response. Did you get a chance to verify the network calls and check if the upload request is being made?  
I would recommend posting this issue in Microsoft Q & A -  https://docs.microsoft.com/en-us/answers/index.html with the appropriate Sharepoint tag or the tag for the platform you are trying to upload to. 

Are you able to upload a file to the location manually?

**Comment by Ofer-Gal** [comment]
Will not use Graph for SharePoint action anymore.
Thank you
