### ISSUE TITLE
Retrieving the threads and posts giving 403 error in ms graph

### ISSUE THREAD

**Issue by chanakya-1984** [microsoftgraph/msgraph-sdk-javascript#506]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem? 
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository? 
-   [x] Did you perform a cursory search?

## Description
In our application there is a requirement to retrieve and display the replies on a threads. When ever we try to retrieve the thread and replies for guest user it gives 403 error for members can retrieve the same without any error. Guest can post a reply to threads without any issue. 
[Description of the bug or feature]

**Console Errors:** 
{"error":{"code":"ErrorAccessDenied","message":"Access is denied. Check credentials and try again."}}

## Steps to Reproduce

1. Create a new thread in a group which has a guest member
2. Guest adds a reply to the thread
3. Guest tries to retrieve the thread and posts (this returns 403)

**Expected behavior:** 
As the guests are able to post a reply they should be able to retrieve the replies too 

**Actual behavior:** 
guest are not able to retrieve the replies

## Additional Context

end point used to retrieve the thread with post is 
`https://graph.microsoft.com/beta/groups/<<groupid>>/threads/<<threadId>>?$expand=posts`

## Usage Information
Request ID - 80ac411f-bc1d-44dc-b56a-7aec8fb5f98e

**Comment by nikithauc** [comment]
@chanakya-1984 Thanks for getting in touch! 

It looks like the permissions might not be set correctly. Check https://docs.microsoft.com/en-us/graph/api/group-get-thread?view=graph-rest-1.0&tabs=http#permissions.

Are you getting this error after the scope and permissions have been set?

**Comment by chanakya-1984** [comment]
> @chanakya-1984 Thanks for getting in touch!
> 
> It looks like the permissions might not be set correctly. Check https://docs.microsoft.com/en-us/graph/api/group-get-thread?view=graph-rest-1.0&tabs=http#permissions.
> 
> Are you getting this error after the scope and permissions have been set?

I don't think that permission is an issue here. For posting guest need **Group.ReadWrite.All** and guest can post replay without any issue. We get 403 only while guest tries to retrieve the threads which only require **Group.Read.All.**

**Comment by nikithauc** [comment]
@chanakya-1984 

What is the authentication flow is being used in your app? The authentication flow set up might be the cause of the issue similar to https://stackoverflow.com/questions/45673636/microsoft-graph-api-403-forbidden-error-when-getting-groups-conversations.

Can you please provide more details on the type of application and the code snippet of how you are using the Graph JavaScript Client?
