### ISSUE TITLE
A TypeError occurred when mocks BatchResponseContent via jest.spyOn()

### ISSUE THREAD

**Issue by karamem0** [microsoftgraph/msgraph-sdk-javascript#514]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

Test failed when I upgraded SDK version from 2.2.1 to 3.0.0.

**Console Errors:** TypeError: Cannot redefine property: BatchResponseContent

**Screenshots:**
![Screenshots](https://user-images.githubusercontent.com/4537204/133218100-bf0f7749-93ec-4734-bc14-7f859cbb1865.PNG)

## Steps to Reproduce

1. Create a new project. `npm init`
2. Install packages.
  - `@microsoft/microsoft-graph-client@3.0.0`
  - `@types/jest@26.0.24`
  - `jest@26.6.0`
  - `ts-jest@26.5.6`
  - `typescript@4.3.5`
3. Write a test script. `index.test.ts`
```
import * as microsoftGraph from '@microsoft/microsoft-graph-client';
it('test', () => {
    jest.spyOn(microsoftGraph, 'BatchResponseContent');
});
```

**Expected behavior:** Test passed.

**Actual behavior:** Test failed because cannot mock `BatchResponseContent`.

## Additional Context

It works with `@microsoft/microsoft-graph-client@2.2.1`. Was it any changes?

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - 3.0.0

-   [x] Node (Check, if using Node version of SDK)

> Node Version - 14.17.6

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by nikithauc** [comment]
@karamem0 There are no changes to BatchResponseContent in 3.0.0.

**Comment by karamem0** [comment]
@nikithauc Thank you for replying. Did you try to reproduce the issue? In actual there might be no changes to BatchResponseContent but something causes the error.

**Comment by nikithauc** [comment]
@karamem0 I was able to reproduce the issue. Will have to look more into this to understand the cause of the issue.

Thank you for reporting this!

Are you able to use the `BatchResponseContent` otherwise?

**Comment by nikithauc** [comment]
@karamem0

**Comment by karamem0** [comment]
@nikithauc 
Thanks a lot! I understood the reason is the change of typescript build systems.
I will use `jest.mock` instread of `jest.spyOn`.

```
jest.mock('@microsoft/microsoft-graph-client');
import { BatchResponseContent } from '@microsoft/microsoft-graph-client';
it('test', () => {
  const MockBatchResponseContent = BatchResponseContent as unknown as jest.Mock;
  MockBatchResponseContent.mockImplementation(() => ({
    getResponses: jest.fn()
  }));
});
```

**Comment by karamem0** [comment]
My suggestion to avoid this error is as follows.

before:
```
export * from "./content/BatchRequestContent";
```
after:
```
export { BatchRequestContent } from "./content/BatchRequestContent";
```
