### ISSUE TITLE
Reference to sample secrets file which doesn't exist 

### ISSUE THREAD

**Issue by sjha2048** [microsoftgraph/msgraph-sdk-javascript#516]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

## Description

In ```/msgraph-sdk-javascript/blob/dev/samples/javascript/clientInitialization/tokenCredentialAuthenticationProvider/index.js``` on L#11 
some secrets are imported 
`const { clientId, clientSecret, scopes, tenantId } = require("./secrets");`
I looked up in the repo and secrets.js doesn't exist but, secrets are defined in `index.js` only 

It's a little bit confusing and gives an error when the user tries to run the file, also documentation is also a little bit ambiguous about defining the secrets.

## Steps to Reproduce

Try running the sample without removing [secrets import line](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/4edb1e02830b3840de498bf67c2806fbbfc5a62c/samples/javascript/clientInitialization/tokenCredentialAuthenticationProvider/index.js#L11) 

SDK Version - [SDK version you are using]

-   [x] Node (Check, if using Node version of SDK)

> Node Version - v16.10.0

Happy to update the documentation and secrets file.

**Comment by nikithauc** [comment]
@sjha2048 Thanks for reporting this! PRs are always welcome :)
