### ISSUE TITLE
Invalid ECMAScript modules

### ISSUE THREAD

**Issue by simonyarde** [microsoftgraph/msgraph-sdk-javascript#519]
# Bug Report

## Issue

I'd like to write valid isomorphic ECMAScript but the following import fails

```js
import { Client } from "./node_modules/@microsoft/microsoft-graph-client/lib/es/src/index.js"
```

## Discussion

Package `@microsoft/microsoft-graph-client` has invalid ECMAScript modules due to missing file extensions, e.g.

```js
// node_modules\@microsoft\microsoft-graph-client\lib\es\src\index.js
export * from "./content/BatchRequestContent";
```

Node gives the following error, which is counter-intuitive since the package documentation appears to say it contains ECMAScript modules but node defaults to common-js

```
import { Client } from "./node_modules/@microsoft/microsoft-graph-client/lib/es/src/index.js"
         ^^^^^^
SyntaxError: Named export 'Client' not found. The requested module './node_modules/@microsoft/microsoft-graph-client/lib/es/src/index.js' is a CommonJS module, which may not support all module.exports as named exports.
```

If we hack package.json with `"type": "module"` we'll obviously get

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...node_modules\@microsoft\microsoft-graph-client\lib\es\src\content\BatchRequestContent'
```

## Almost workaround for Node (but not browser)

In node, we can work around with flag `--experimental-specifier-resolution=node` and by hacking the `@microsoft/microsoft-graph-client/package.json` (making deployment difficult)

```js
// index.mjs
import { Client } from "./node_modules/@microsoft/microsoft-graph-client/lib/es/src/index.js"
console.log("OK")
```

```json
// node_modules\@microsoft\microsoft-graph-client\package.json
// ..
  "type": "module",
// ...
```

```bash
node --experimental-specifier-resolution=node index.mjs
OK
```

In Azure Web Apps we can get this behaviour via `package.json`

```json
// package.json
{
  "scripts": {
    "start": "node --experimental-specifier-resolution=node index.mjs",
  },
}
```

I've spent a little time googling, but can't see if Azure Functions should support `package.json` scripts.

## Related discussion

https://github.com/microsoft/TypeScript/issues/42151

**Comment by simonyarde** [comment]
@nikithauc Now please show me how to write your example isomorphically so that it will run in a browser.

**Comment by ddyett** [comment]
closing out some older issues.

**Comment by simonyarde** [comment]
I lost hope this would ever get sorted and moved to different tools.

My understanding is that the graph client remains unusable without typescript because the .mjs files contain non-valid javascript import statements.

**Comment by onionhammer** [comment]
@simonyarde it's unusable for compiled typescript as well

**Comment by DanielMarquesz** [comment]
It's still happening, be able to make it work with the workaround provided by @simonyarde
