### ISSUE TITLE
Outlook resources invited via API do not respond the inviation

### ISSUE THREAD

**Issue by nedyalkov** [microsoftgraph/msgraph-sdk-javascript#523]
## Bug Report

When creating events via Calendar API, the events are created successfully, but the resources being invited never respond to the invitation. This used to work in the past.

### Prerequisites
* [yes] Can you reproduce the problem?
* [yes] Are you running the latest version? (^2.2.1)
* [yes] Are you reporting to the correct repository?
* [yes] Did you perform a cursory search?

### Steps to Reproduce
1. Create meeting room resource
2. Create an event via the API, inviting the meeting room
3. Check the invitation response in Outlook (i.e. what the resource have responded to the invitation)

Actual behavior: The status stays None

### Additional Context
When you follow the same steps, but via the web client, everything works as expected. Also, this used to work correctly via the API and it stopped recently.

### Usage Information
Request ID - Value of the requestId field if you are receiving a Graph API error response

**Comment by nedyalkov** [comment]
Hey, @nikithauc @roinochieng do you have any updates on this issue? It is quite important for us as it breaks one of the most important use cases for our customers.

**Comment by nikithauc** [comment]
@nedyalkov This seems to be related to #522. I have reached out to the service team with this issue. I will keep you posted on the progress.

**Comment by nikithauc** [comment]
@nedyalkov 
> When creating events via Calendar API, the events are created successfully, but the resources being invited never respond to the invitation. This used to work in the past.

- Can you please tell me when you noticed the error first? 
- Did you update the SDK version or make any changes to the code or settings?

**Comment by nedyalkov** [comment]
@nikithauc it makes sense this to be a service issue as we haven't updated the SDK and the issue just started happening. We've noticed the incorrect behavior on 28th of October when we tried to demo our product to a customer and it wasn't behaving correctly.

After some troubleshooting, we found out the issue is the meeting room doesn't respond to the RSVP invitation when submitted through the Application/SDK and does, when we do it through the application UI. When getting both booking from the API, the look the same, so we decided to submit the issue.

Also, I've looked into #522 and it also seems like a service issue, but it is very different from what we noticed. Our issue is not that we do not see the calendar of the meeting room, but that the meeting room itself doesn't respond to the RSVP invitation we send along with the event we create in the user's calendar.

If this is a service issue, what would be the right way to report it to the team working on the Outlook service or you did this already?

**Comment by nikithauc** [comment]
@nedyalkov I am still waiting on an update from the service team. The  last update I received was that a similar issue was reported and being looked at first. 

I will keep you posted.

**Comment by nedyalkov** [comment]
Hey @nikithauc is there any news on this or we should be looking for another way to achieve what we need?

**Comment by sebastienlevert** [comment]
Hey @nedyalkov! Thanks for keeping us honest on this! 😎 Can you confirm that the resource is setup to automatically respond to the invite? We're working on investigating the service internally, but it seems like configuration can be a variable in this case. Thanks!

**Comment by sebastienlevert** [comment]
@nedyalkov If you could also provide the request and the request-id + timestamp of it, this would be great as we would be able to dive a bit deeper to see if there is an issue with the service. Thanks!

**Comment by nedyalkov** [comment]
Hi @sebastienlevert I tried to reproduce the issue, so I can capture the request ID, but this time the meeting room responded. Have your team changes something? This wasn't working (consistently) for months and it started working again. If you fixed the issue, that's a very good news :)

**Comment by sebastienlevert** [comment]
It's great news then! Either a config on your side or on the service side might have helped with this! I'll close it for now, feel free to reopen it if this becomes an issue again! Thanks!

**Comment by nedyalkov** [comment]
@sebastienlevert we haven't changed anything, so I'd guess it was a change on the Service Side. It was definitely not an issue with the library as it get fixed without updating the library :)
