### ISSUE TITLE
Update docs for PageIterator: missing `await` for pageIterator.iterate() and pageIterator.resume()

### ISSUE THREAD

**Issue by jstott** [microsoftgraph/msgraph-sdk-javascript#524]
Sample code for the PageIterator [Iterate over all the messages]( https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/PageIterator.md#iterate-over-all-the-messages) and [Stopping and Resuming the iteration](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/tasks/PageIterator.md#stopping-and-resuming-the-iteration) is missing `await` for pageIterator.iterate()

## Current iterate-over-all-the-messages
```
// This iterates the collection until the nextLink is drained out.
pageIterator.iterate();
```

Should be: 
```
// This iterates the collection until the nextLink is drained out.
await pageIterator.iterate();
```

## Current stopping-and-resuming-the-iteration
```
// This stops iterating over for 1000 entities.
pageIterator.iterate();

// Resuming will do start from where it left off and iterate for next 1000 entities.
// Check and resume is likely to be called in any user interaction requiring to load more data.
if (!pageIterator.isComplete()) {
	pageIterator.resume();
}
```

Should be: 
```
// This stops iterating over for 1000 entities.
await pageIterator.iterate();

// Resuming will do start from where it left off and iterate for next 1000 entities.
// Check and resume is likely to be called in any user interaction requiring to load more data.
if (!pageIterator.isComplete()) {
	await pageIterator.resume();
}
```

**Comment by nikithauc** [comment]
@jstott Thank you for bringing this to attention! I have made the corrections.
