### ISSUE TITLE
Buffer() deprecation error (node 14)

### ISSUE THREAD

**Issue by fr-an-k** [microsoftgraph/msgraph-sdk-javascript#528]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

console.error log is generated (triggering alarms in our environment).

**Console Errors:**
(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

Only workaround is to overrule console.error before the call (& restore afterward).

## Steps to Reproduce
Occurred when patching a subscription on 'users' (using Azure msal-node 1.3.1 for confidential client authentication)

**Expected behavior:**
Develop/test using latest stable version and don't use deprecated techniques
**Actual behavior:**
Deprecated techniques used, triggering error

## Usage Information
Subscription id: e0e04953-f303-4887-b8b2-ac4c83d91d5e

SDK Version - [SDK version you are using]
2.2.1
-   [x] Node (Check, if using Node version of SDK)
> Node Version - 14.18.0

**Comment by nikithauc** [comment]
@frank-unovica Thank you for reporting this! Will look into this.

**Comment by ddyett** [comment]
closing stale issues.
