### ISSUE TITLE
Error: The value of parameter 'StartDateTime'/'EndDateTime' is invalid.

### ISSUE THREAD

**Issue by moinkhanif** [microsoftgraph/msgraph-sdk-javascript#529]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]

I was following the [Microsoft Graph steps](https://docs.microsoft.com/en-us/graph/tutorials/node?tutorial-step=4) and stumbled upon this issue at step 5 of "Get calendar events from Outlook". 
The page `/calender` is supposed to return a JSON value. However, I get the following error:
```json
{"stack":"Error: The value '2021-01-01T19:00:00 05:30' of parameter 'EndDateTime' is invalid.\n at new GraphError (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphError.js:32:28)\n at Function.GraphErrorHandler.constructErrorFromResponse (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphErrorHandler.js:62:22)\n at Function. (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphErrorHandler.js:89:48)\n at step (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\tslib\\tslib.js:143:27)\n at Object.next (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\tslib\\tslib.js:124:57)\n at C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\tslib\\tslib.js:117:75\n at new Promise ()\n at Object.__awaiter (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\tslib\\tslib.js:113:16)\n at Function.GraphErrorHandler.getError (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphErrorHandler.js:85:24)\n at GraphRequest. (C:\\Users\\offic\\Documents\\testing\\graph-tutorial\\node_modules\\@microsoft\\microsoft-graph-client\\lib\\src\\GraphRequest.js:315:84)","message":"The value '2021-01-01T19:00:00 05:30' of parameter 'EndDateTime' is invalid.","statusCode":400,"code":"ErrorInvalidParameter","requestId":null,"date":"2021-11-10T14:47:12.751Z","body":"{\"code\":\"ErrorInvalidParameter\",\"message\":\"The value '2021-01-01T19:00:00 05:30' of parameter 'EndDateTime' is invalid.\"}"}
```

My code is exactly as suggested by Microsoft. Still, for your reference, 

the function call in `calendar.js` is:

```js
     var weekStart = zonedTimeToUtc(startOfWeek(new Date()), timeZoneId.valueOf());
      var weekEnd = addDays(weekStart, 7);
      console.log(`Start: ${formatISO(weekStart)}`);

      try {
        // Get the events
        const events = await graph.getCalendarView(
          req.app.locals.msalClient,
          req.session.userId,
          formatISO(weekStart),
          formatISO(weekEnd),
          user.timeZone);

        res.json(events.value);
      } catch (err) {
        res.send(JSON.stringify(err, Object.getOwnPropertyNames(err)));
      }
```

and the related code in `graph.js` is:

```js
getCalendarView: async function(msalClient, userId, start, end, timeZone) {
    const client = getAuthenticatedClient(msalClient, userId);
  
    const events = await client
      .api('/me/calendarview')
      // // Add Prefer header to get back times in user's timezone
      .header("Prefer", `outlook.timezone="${timeZone}"`)
      // // Add the begin and end of the calendar window
      .query({ startDateTime: start, endDateTime: end })
      // // Get just the properties used by the app
      .select('subject,organizer,start,end')
      // // Order by start time
      .orderby('start/dateTime')
      // // Get at most 50 results
      .top(50)
      .get();
  
    return events;
  },
```

[Investigation]

I noticed that when I manually entered the start date/end date it still failed to work:

```js
.query({ startDateTime: '2020-01-01T19:00:00+05:30', endDateTime: '2021-01-01T19:00:00+05:30' })
```

But then again the moment I change the timezone within this ISO Format to `-05:30` instead of `+05:30`, it started to work:

```js
.query({ startDateTime: '2020-01-01T19:00:00-05:30', endDateTime: '2021-01-01T19:00:00-05:30' })
```

[Conclusion]

I suppose there is an issue parsing this sign `+` and if you notice the error, it simply replaces the `+` with an empty spaced string:

![image](https://user-images.githubusercontent.com/6555800/141158090-2b16ab8c-8067-4621-b745-7b68ba885421.png)

**Console Errors:** [Is there any console error] - None

**Screenshots:** [If applicable, add screenshots to help explain your problem] - Provided

## Steps to Reproduce

1. [First Step]
    follow the steps until step 5 "Get calendar events from Outlook" : [https://docs.microsoft.com/en-us/graph/tutorials/node?tutorial-step=4](https://docs.microsoft.com/en-us/graph/tutorials/node?tutorial-step=4)
2. [Second Step]
    login and proceed to the calendar page

**Expected behavior:** [What you expected to happen]

The page should return a json object(could be empty)

**Actual behavior:** [What actually happened]

Getting an error message as mentioned above

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

`null`

SDK Version - [SDK version you are using] - `3.0.0`

-   [x] Node (Check, if using Node version of SDK) 

> Node Version - [The version of Node you are using] - `v16.13.0`

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK] - Microsoft Edge

> Version - [The version of the browser you are using] - `95.0.1020.44 (Official build) (64-bit)`

**Comment by nikithauc** [comment]
@moinkhanif 

This seems to be a bug in the service. Thanks for bringing this to attention!

**Comment by nikithauc** [comment]
@moinkhanif I recommmend you to please post this question in [Microsoft Q & A ](https://docs.microsoft.com/en-us/answers/index.html) with the tags for Graph, Outlook, calendar to bring more light to this issue :)

**Comment by moinkhanif** [comment]
@nikithauc Thank you Nikitha, I have created a new question 👍🏼 Hope it's resolved soon. https://docs.microsoft.com/en-us/answers/questions/628924/ms-graph-sdk-javascipt-error-the-value-of-paramete.html

**Comment by sebastienlevert** [comment]
Thanks for adding me to the converation @nikithauc!

@moinkhanif, can you share with us the full Graph API endpoint this call generates? I want to be sure I have an exact understand of the issue and then I'll see with our teams internally! Thanks!

**Comment by sebastienlevert** [comment]
With my repro, I'm getting a similar result. I tried with both Graph Explorer and Postman to ensure this was not SDK related. 

`GET https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2020-01-01T19:00:00+05:30&endDateTime=2022-01-01T19:00:00+05:30`

And I'm getting the following : 

```js
{
    "error": {
        "code": "ErrorInvalidParameter",
        "message": "The value '2020-01-01T19:00:00 05:30' of parameter 'StartDateTime' is invalid."
    }
}
```

**Comment by sebastienlevert** [comment]
Coming back to this topic. It seems like the + sign needs to be URL encoded. I was able to execute the query using the following : 

`GET https://graph.microsoft.com/v1.0/me/calendarView?startDateTime=2020-01-01T19:00:00%2B05:30&endDateTime=2021-01-01T19:00:00%2B05:30`

@moinkhanif can you validate this works for your using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=me%2FcalendarView%3FstartDateTime%3D2020-01-01T19%3A00%3A00%252B05%3A30%26endDateTime%3D2021-01-01T19%3A00%3A00%252B05%3A30&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com)?

@nikithauc do you think this could be handled directly by the SDK?

**Comment by acristu** [comment]
Hi, 

I've hit this issue too following the 3 min Getting Started...

Got past this error using this quickfix: https://github.com/microsoftgraph/msgraph-sdk-javascript/pull/625/files

**Comment by nikithauc** [comment]
Unfortunately, the library expects an encoded URI to be passed as a parameter. We have customers passing in an encoded URI and I would recommend this as a workaround now.
