### ISSUE TITLE
Proxy Configuration

### ISSUE THREAD

**Issue by ScottGuymer** [microsoftgraph/msgraph-sdk-javascript#53]
Is there any support for configuring proxy settings on this library?

**Comment by MIchaelMainer** [comment]
Hello @ScottGuymer 

I don't think so since this library wraps superagent and super agent doesn't have a proxy setting. You might need to fallback to superagent and use this.

https://www.npmjs.com/package/superagent-proxy

**Comment by ScottGuymer** [comment]
If the package was to expose the superagent as part of the client then it
could be configured to use superagent proxy.

But as it stands superagent isnt accessible.

**Comment by MIchaelMainer** [comment]
I agree. I think this should be done. I've opened this in our backlog to expose more of superagent so that we aren't hiding functionality.

**Comment by flurin** [comment]
Meanwhile you can use a workaround like this:

```
const superagentProxy = require("superagent-proxy");

function proxyRequest(graphRequest) {
  if(!process.env.HTTPS_PROXY) {
    return graphRequest;
  }

  graphRequest.unproxiedConfigureRequest = graphRequest.configureRequest;
  graphRequest.configureRequest = function(requestBuilder, accessToken) {
    const request = this.unproxiedConfigureRequest(requestBuilder, accessToken);
    return superagentProxy(request, process.env.HTTPS_PROXY);
  }
  return graphRequest;
}

  const client = MicrosoftGraph.Client.init({
    authProvider: (done) => { // do your stuff here
    }
  });

// Wrap the .api call with out proxyRequest function
const api = proxyRequest(client.api(`/me/calendars`))

// Use the API as you normally would
api.get()
 ```

**Comment by mannharleen** [comment]
The previous answer is not longer valid.
The msgraph-sdk has moved onto using node-fetch instead of superagent.

Now setting proxt is even simpler. One way is to pass fetchptions.agent:
```
const client = graph.Client.init(
        {
            authProvider: (done) => { done(null, accessToken); },
            fetchOptions: { agent: new HttpsProxyAgent('http://xx.xx.xx.xx:8080') }
        }
    );
```

**Comment by piotrlech** [comment]
Ok, but how to set proxy for msalClient.getAuthCodeUrl(urlParameters) ?

**Comment by dineshsecret** [comment]
Hi 
Please refer last part of [msal-node] Issues when server is behind proxy #2600. below is the url for that blog post
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2600
That blog post explains how to configure networkClient which configure with proxy. 

However above fetchOption didn't work for me. What is the IP address I have to use there? is that the proxy server IP and port?
do I have to use user name and password combination like below, with IP address?
http://username:password@xxx.xxx.xxx.xxx:8080

highly appriciated you help.

**Comment by dineshsecret** [comment]
Hi, I want to add further comments to above comment.
  I have tried above fetchOptions with username password combination like below

 fetchOptions:{agent: new HttpsProxyAgent('http://username:password@xxx.xxx.xxx.xxx:8080')},

where username and password are my credentials to the proxy server, and it worked.
