### ISSUE TITLE
Sending emails, app only authentication

### ISSUE THREAD

**Issue by Nikola-Milovic** [microsoftgraph/msgraph-sdk-javascript#534]
Hello everyone, after a dozen pages of documentation and these examples I am left a bit confused. 

I am trying to have my Nodejs Server ( a backend service ), communicate with Microsoft Graph API and send emails on behalf of our organization. So basically, we have a shared inbox and I'd like to send emails to and from that inbox based on requests coming into the server. 

So this should **NOT**  require any human interaction, user authentication or anything of the sorts

 I tried registering my App in the Azure AD and gave it send email permission and consent. AFter that I am lost. What do I do from here? Why do I need redirect urls and such for server to server communication? [Refering to this ](https://docs.microsoft.com/en-us/graph/auth-v2-service). When I used other providers like google/ aws they all provide some kind of credentials and an SDK that you can use and be ready to go, but here I just cannot get around to that point. 
 
 From the README
 > Application only authentication represents only the application itself when calling the Microsoft Graph, without any notion of user. This type of authentication is best suited for background services, daemons or other kind of applications users are not directly interacting with.
 
How do I create a client to achieve Application only authentication? What is the config, credentials?

From the above references docs 

>In the OAuth 2.0 client credentials grant flow, you use the Application ID and Application Secret values that you saved when you registered your app to request an access token directly from the Microsoft identity platform /token endpoint.
You specify the pre-configured permissions by passing https://graph.microsoft.com/.default as the value for the scope parameter in the token request. See the scope parameter description in the token request below for details.

How do I do this with this library?  How would we handle the token expiring (as this is happening on the server its bound to expire), and refreshing it, where do we store the token? 

All of this is usually handled by the SDK from my experience. An example would be greatly appreciated, as I haven't been able to find any Application only examples

Summary: Part of an organization that uses Microsoft, I want to send emails from and to our shared inbox, this is all happening on a backend service with no user authentication. Need Application only authentication to get access token to use in graph apis.

**Comment by nikithauc** [comment]
@Nikola-Milovic  Thank you for reaching out!

You can use client credentials flow using the @azure/identity library with the Graph JS library. 

Refer to the following for more information:

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/TokenCredentialAuthenticationProvider.md

https://github.com/microsoftgraph/msgraph-sdk-javascript/tree/dev/samples/javascript/clientInitialization/tokenCredentialAuthenticationProvider

[Sample](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/javascript/clientInitialization/tokenCredentialAuthenticationProvider/index.js)
