### ISSUE TITLE
Client never returns

### ISSUE THREAD

**Issue by markgarrigan** [microsoftgraph/msgraph-sdk-javascript#535]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

A call to the graph client never returns

**Console Errors:** [Is there any console error]

There are no errors. The client never returns.

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

const client = getAuthenticatedClient(msalClient, userId);
const user = await client.api('/me').get();

**Expected behavior:** [What you expected to happen]

The client will return with something even if it's an error.

**Actual behavior:** [What actually happened]

Nothing happens.

## Usage Information
SDK Version - [SDK version you are using]

"@azure/msal-node": "^1.3.3",
"@microsoft/microsoft-graph-client": "^3.0.1",

node -v
v14.17.0

**Comment by pcnate** [comment]
Using pretty identical code I am getting `client.api is not a function`. I have a logger function below (if that helps you @markgarrigan) that gives the following output:

```
[Thu, 16 Dec 2021 17:26:27 GMT] : @azure/msal-node@1.4.0 : Info - acquireTokenByClientCredential called
[Thu, 16 Dec 2021 17:26:27 GMT] : @azure/msal-node@1.4.0 : Verbose - initializeRequestScopes called
[Thu, 16 Dec 2021 17:26:27 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-node@1.4.0 : Verbose - buildOauthClientConfiguration called
[Thu, 16 Dec 2021 17:26:27 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-node@1.4.0 : Verbose - building oauth client configuration with the authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
[Thu, 16 Dec 2021 17:26:27 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-node@1.4.0 : Verbose - createAuthority called
[Thu, 16 Dec 2021 17:26:27 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-node@1.4.0 : Verbose - Client credential client created
[Thu, 16 Dec 2021 17:26:28 GMT] : [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] : @azure/msal-common@5.2.0 : Verbose - No client info in response
(node:27492) UnhandledPromiseRejectionWarning: TypeError: client.api is not a function
    at Function.<anonymous> (C:\github\utilities\node_modules\@microsoft\microsoft-graph-client\lib\src\tasks\LargeFileUploadTask.js:74:30)
```

My stack:
"@azure/msal-node": "^1.4.0",
"@microsoft/microsoft-graph-client": "^3.0.1",

node -v
v14.17.5

I am using this library in javascript.


```js
    const msalConfig = {
      auth: {
        clientId: process?.env?.ms_graph_client_id,
        authority: process?.env?.ms_graph_aad_endpoint + '/' + process?.env?.ms_graph_tenant_id,
        clientSecret: process?.env?.ms_graph_client_secret,
      },
      system: {
        loggerOptions: {
          loggerCallback( loglevel, message, containsPii ) {
            console.log( message );
          },
          piiLoggingEnabled: false,
          logLevel: msal.LogLevel.Verbose,
        }
      }
    };
```

I had based my code on the work of another dev here but he was using `@microsoft/microsoft-graph-client@2.2.1` which does not have the function I was trying to use. Client initialization seems to me to be where the issues lies but it digging through the Client.js file I not understanding what the issues seems to be.

**Comment by nikithauc** [comment]
@markgarrigan 

Thanks for reaching out!

The `client` need to be initialized as seen in this line https://github.com/microsoftgraph/msgraph-training-nodeexpressapp/blob/33884188941caa1c309c0716142c8d663e11d341/demo/graph-tutorial/graph.js#L89

Can you please share the  `getAuthenticatedClient()` code?  

Can you please share the client instance that is being returned by the `getAuthenticatedClient` method?
