### ISSUE TITLE
Forbidden 403 error 

### ISSUE THREAD

**Issue by athapliyal** [microsoftgraph/msgraph-sdk-javascript#57]
Hello,

I am trying to access skills for a particular user which can be retrieved from `https://graph.microsoft.com/beta/me/skills` (tested at https://developer.microsoft.com/en-us/graph/graph-explorer)

However, when I write a function in my react app for the same:

`  getSkills(callback) {
    this.client
      .api('/me/skills')
      .get((err, res) => {
        if (!err) {
          callback(null, res);
        }
        else this._handleError(err);
      });
  }
`
the response is always 403 (Forbidden). I have updated the application and delegated permissions and have logged in as a user.

I am able to run simple GET requests like `https://graph.microsoft.com/beta/me` or `GET /users` etc.

Is there something else that needs to be done to enable access to additional endpoints?

Thanks,
Abhi

**Comment by MIchaelMainer** [comment]
Thank you for contacting us. Please post questions to StackOverflow with the tag [microsoftgraph]. Provide a link to your question for this repo issue.
