### ISSUE TITLE
Proxy issue when running behind corporate proxy

### ISSUE THREAD

**Issue by suresh1271** [microsoftgraph/msgraph-sdk-javascript#58]
Hi, I'm working under corporate proxy. It is not allowing Client to request microsoftGraph.Client.init(). Can anyone please suggest me where to add my proxy and port.

var microsoftGraph = require("microsoft/microsoft-graph-client"); 
var token=<Microsoft Access Token>;
var client = microsoftGraph.Client.init({ 
        authProvider: (done) => { 
          // Just return the token 
          done(null, token); 
        }
      });

**Comment by flurin** [comment]
Sadly there is no support for that yet. But there is a workaround: https://github.com/microsoftgraph/msgraph-sdk-javascript/issues/53#issuecomment-349249537

**Comment by suresh1271** [comment]
Thank you @flurin , It's working. I got it.
