### ISSUE TITLE
Response from API hangs

### ISSUE THREAD

**Issue by guylissak** [microsoftgraph/msgraph-sdk-javascript#588]
# Bug Report

## Prerequisites

-   [v] Can you reproduce the problem?
-   [x ] Are you running the latest version?
-   [v] Are you reporting to the correct repository?
-   [v] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description
Im using the lib to fetch messages, '/me/messages'.
I run on large amount of tokens and sometimes (like happens for 1 out of 500 users) i get no response back from the API.
Need to mention before reaching the API i successfully refresh the user's token and being able to reach other endpoints.
however when reaching the API me/messages with  await this.client.api('me/messages').get(); the response hangs in high probability and the only way to recover is by manually ending the process
[Description of the bug or feature]

**Console Errors:** [Is there any console error]

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - [SDK version you are using]
v2.2.1
-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]
v14.6
-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by guylissak** [comment]
@sebastienlevert Hi,
I can't give you a request-id for this call because i don't get any response back! so no error, the process hangs when i call the API with the library get wrapper!
I can give you the request-id of the request before it but it belongs to another user so i don't know if this can help.
here it is anyways 239a5d78-b5e6-4efa-92d4-6b189c412465.
about the timestamp, timestamp is: 2022-01-27 00:18:17,776

Thanks!

**Comment by sebastienlevert** [comment]
I just saw you are using v2 of the SDK. Can you update to the latest and see if this fixes it?

I was unable to reproduce on my end. Do you have a sample project you could share with us so we can repro on our side?

Thanks!
