### ISSUE TITLE
V4 update node requirements

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#591]

**Comment by sebastienlevert** [comment]
Should support Node 14-18

**Comment by sebastienlevert** [comment]
Node 18 should support native `fetch` as it's now not marked as experimental.

**Comment by baywet** [comment]
node 14 support ends this April, I suggest we drop node 14 support. Node 16 EOL is this September, dropping that would be "harsh" but it'd solve a lot of polyfills issues :)

**Comment by sebastienlevert** [comment]
I don't know if a library like ours should trigger Node updates to folks upstream. What are we losing with dropping 14?

**Comment by baywet** [comment]
My expectation is that most cloud providers are going to match node's support policy [see azure](https://azure.microsoft.com/en-ca/updates/node16support/) and [aws hasn't announced v14 EOL yet, but 12 EOL matched nodejs support policy + 1 year](https://aws.amazon.com/blogs/developer/announcing-the-end-of-support-for-node-js-12-x-in-the-aws-sdk-for-javascript-v3/)
Other than that, we should get updated industry numbers, PMs gotta PM :P

**Comment by sebastienlevert** [comment]
Updates to this issue. V4 will support Node 18-20. This is already done.
