### ISSUE TITLE
Paging / Pagination request

### ISSUE THREAD

**Issue by warrenmcquinn** [microsoftgraph/msgraph-sdk-javascript#62]
Hey there,

Thanks for open-sourcing this library!

It'd be great if someone updated the Readme to address pagination. 

For example, accessing a user's contacts with an MS Graph query to `/contacts` returns 10 results per page by default. It's possible to add a `$top` query parameter to increase that page size.

However, it should definitely be mentioned that the `result["@odata.nextLink"]` URL (returned with the query response) needs to be queried in order to get the rest of the user's contacts (as well as all additional `result["@odata.nextLink"]`s!).

I know it's basic pagination 101, but this library's documentation should really include an overview of paging.

**Comment by MIchaelMainer** [comment]
Thank you @warrenmcquinn.  I agree that we should have documentation on paging. 2123467

**Comment by mahpour** [comment]
How is the `@OData.nextLink` going to be self-consumed by this library to get the next batch of items?

**Comment by MIchaelMainer** [comment]
@mahpour You'll use the @OData.nextlink value as the url to make the next call to get the next page of results.

**Comment by mahpour** [comment]
I understand that, but aren’t we using this JavaScript library to not deal with http requests directly? It doesn’t make sense to make some of the calls using Microsoft client and some via direct http methods...

**Comment by MIchaelMainer** [comment]
Yes, I agree with you. It hasn't been implemented yet.

**Comment by aslanovsergey** [comment]
Would be nice to have it

**Comment by kriede** [comment]
:+1: +1 for implementing this

**Comment by muthurathinam** [comment]
Fixed in this release: https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/1.4.0
