### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-javascript#640]
# Feature Request

The current library should support HTTP/2 natively. Investigate if current library works flawlessly on both Node and JS.

**Comment by baywet** [comment]
for context the technical details on how to test it + a checklist of what to look out for are available on [this teams convo](https://teams.microsoft.com/l/message/19:354607201cf540fe8e8e851a24753081@thread.skype/1642444590226?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1fc2aa55-29ee-4d2e-90cc-4b2ffa6c4f7e&parentMessageId=1642444590226&teamName=Graph%20Client%20Tooling&channelName=General&createdTime=1642444590226)

**Comment by ddyett** [comment]
@nikithauc  have we looked at this yet.  This is one we should prioritize.

**Comment by nikithauc** [comment]
Yes this is in progress

**Comment by ddyett** [comment]
it's marked done on the board, should it be closed?

**Comment by nikithauc** [comment]
Ran unit tests in this process against canary endpoint. The tests worked well. 
Browsers and fetch libraries normalize the headers before sending the request.
