### ISSUE TITLE
Upload image as a stream to one drive

### ISSUE THREAD

**Issue by kritika28saxena** [microsoftgraph/msgraph-sdk-javascript#65]
When uploading an image as a stream from node app, it results in Error: read ECONNRESET, so not able to upload image more than 120KB

**Comment by MIchaelMainer** [comment]
Can you provide more details:
- [ ] Fiddler capture of request and response.
- [ ] code used when you encounter the issue. 
- [ ] stack trace
- [ ] app information like platform

**Comment by muthurathinam** [comment]
Its fixed in the dev branch and will be available in the next release !

**Comment by muthurathinam** [comment]
Fixed in the release https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/1.1.0
