### ISSUE TITLE
How to get a refresh token using the Microsoft graph JavaScript client library?

### ISSUE THREAD

**Issue by naissa12** [microsoftgraph/msgraph-sdk-javascript#651]
I am using the Microsoft graph Javascript client library to get a refresh token for a user. I created an app that connects doctors and patients. I want to create and delete events on the doctors' calendars. I first need their authorization to access their outlook account. Unfortunately, when I make the api call to get the refresh token, I get back an access token and an id token but no refresh token. Can someone please help?

Here's my code

 ```
   const msalConfig = {
        auth: {
            clientId: process.env.OUTLOOK_OAUTH_CLIENT_ID,
            authority: process.env.OUTLOOK_OAUTH_AUTHORITY,
            clientSecret: process.env.OUTLOOK_OAUTH_CLIENT_SECRET
        },
        system: {
            loggerOptions: {
                loggerCallback(loglevel, message, containsPii) {
                    console.log(message);
                },
                piiLoggingEnabled: false,
                logLevel: msal.LogLevel.Verbose,
            }
        }
    };
    
    // Create msal application object
    const ouathClient = new msal.ConfidentialClientApplication(msalConfig);
    
    const response = await ouathClient.acquireTokenByCode(tokenRequest);

```

I am using node js.

**Comment by sebastienlevert** [comment]
Thanks for the question @naissa12! This is more of a msal-node question as we are simply leveraging the dependency on their side. Though, you can look at this reference and it might help with how to get the refresh token via the silient acquisition of the token. https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-node/docs/caching.md

Hope this helps! Thanks!
