### ISSUE TITLE
How to convert dates to timestamps

### ISSUE THREAD

**Issue by naissa12** [microsoftgraph/msgraph-sdk-javascript#655]
I'm building an app that allows patients to book a call with a doctor. I first check the doctor's calendar for any conflicts. I used the code below to get all of the events on the doctor's calendar, but I get the start dates in a weird format that I don't understand.

I need to convert these dates into UTC timestamps, but even though timeZone value is UTC, I'm not able to do so. Here's what I do:

```
getCalendarView: async function(msalClient, userId, start, end, timeZone) {
  const client = getAuthenticatedClient(msalClient, userId);

  return client
    .api('/me/calendarview')
    // Add Prefer header to get back times in user's timezone
    .header("Prefer", `outlook.timezone="UTC"`)
    // Add the begin and end of the calendar window
    .query({
      startDateTime: encodeURIComponent(start),
      endDateTime: encodeURIComponent(end)
    })
    // Get just the properties used by the app
    .select('subject,organizer,start,end')
    // Order by start time
    .orderby('start/dateTime')
    // Get at most 50 results
    .top(50)
    .get();
},
```

then I do this

```
var parseISO = require('date-fns/parseISO');

var timestamp = parseISO(i.start.dateTime).getTime()
```

Shouldn't calling parseISO and then calling getTime() on that give me the timestamp. The i.start.dateTime comes from calling getCalendarView.

**Comment by nikithauc** [comment]
Hello @naissa12 .

Thank you for reaching out! 

I apologize I am not familiar with the date-fns library. But this issue looks related to https://github.com/date-fns/date-fns/issues/2160 which looks like an issue related with the date-fns library and not the Graph library. 

Can you please elaborate on the problem with `start.dateTime` that is not working for you?
