### ISSUE TITLE
Web-pack/Typescript warnings:  Emitted value instead of an instance of Error - Cannot find source file 

### ISSUE THREAD

**Issue by ak99372** [microsoftgraph/msgraph-sdk-javascript#67]
using [microsoft-graph-client] npm in typescript file like so...

`import * as MsGraph from '@microsoft/microsoft-graph-client';`
...
`let graphClient: MsGraph.Client = MsGraph.Client.init({
			authProvider: (done) => {
				done(null, graphToken);
			}
		});`

I receive a lot of warnings from web-pack when compiling...

> /node_modules/@microsoft/microsoft-graph-client/lib/src/GraphRequest.js
> (Emitted value instead of an instance of Error) Cannot find source file '../../src/GraphRequest.ts': Error: Can't resolve '../../src/GraphRequest.ts' in 'C:\Work\_projects\JavaScript\_react\framework-demo\node_modules\@microsoft\microsoft-graph-client\lib\src'

> ./node_modules/@microsoft/microsoft-graph-client/lib/src/ResponseHandler.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/ResponseHandler.ts': Error: Can't resolve '../../src/ResponseHandler.ts' in 'C:\Work\_projects\JavaScript\_react\framework-demo\node_modules\@microsoft\microsoft-graph-client\lib\src'

> ./node_modules/@microsoft/microsoft-graph-client/lib/src/common.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/common.ts': Error: Can't resolve '../../src/common.ts' in 'C:\Work\_projects\JavaScript\_react\framework-demo\node_modules\@microsoft\microsoft-graph-client\lib\src'

> ./node_modules/@microsoft/microsoft-graph-client/lib/src/index.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in 'C:\Work\_projects\JavaScript\_react\framework-demo\node_modules\@microsoft\microsoft-graph-client\lib\src'

There are no actual errors but I'm wondering if there is something missing

**Comment by muthurathinam** [comment]
@ak99372 
1. What version of @microsoft/microsoft-graph-client did you use ?
2. What version of typescript that you use ?
3. Are you getting this warning on every compilation ?
4. Can you provide any other specific information that will help in debugging the issue ?

**Comment by muthurathinam** [comment]
Closing this issue as no response from the user.

**Comment by erinha** [comment]
I'm getting this exact error. @muthurathinam to answer your questions above:

1. Version 1.7.0
2. We're using TS version 3.4.5
3. We are getting this warning on every compilation using webpack.

Our webpack.config.js looks like this:
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: "./src/index.tsx",
    output: {
        filename: "bundle.js",
        path: __dirname + "/build"
    },
    mode: 'development',
    devtool: "source-map",
    devServer: {
        contentBase: './dist'
    },
    resolve: {
        extensions: [".css", ".js", ".json", ".ts", ".tsx" ]
    },
    module: {
        rules: [
            { test: /\.tsx?$/, loader: "ts-loader" },
            { enforce: "pre", test: /\.js$/, loader: "source-map-loader" },
            {
                test: /\.css$/,
                loader: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            localsConvention: 'camelCase',
                            modules: true,
                            sourceMap: true,
                        },
                    },
                ],
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            favicon: './favicon.ico',
            template: './index.html'
        })
    ],

    // When importing a module whose path matches one of the following, just
    // assume a corresponding global variable exists and use that instead.
    // This is important because it allows us to avoid bundling all of our
    // dependencies, which allows browsers to cache those libraries between builds.
    externals: {
        "react": "React",
        "react-dom": "ReactDOM"
    }
};
```

I've looked on disk and the files the error says it cannot find are indeed not present. Here's an example of a warning on my compile:
```
WARNING in F:/Source/Repos/Violet/violet/node_modules/@microsoft/microsoft-graph-client/lib/es/index.js
Module Warning (from F:/Source/Repos/Violet/violet/node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in 'F:\Source\Repos\Violet\violet\node_modules\@microsoft\microsoft-graph-client\lib\es'raph-client\lib\es'
```

It's complaining it can't find F:/Source/Repos/Violet/violet/node_modules/@microsoft/microsoft-graph-client/src/index.ts and indeed, there is no src folder under node_modules/@microsoft/microsoft-graph-client.

Any ideas how to fix these warnings? Thanks!
