### ISSUE TITLE
client.headers is not a function

### ISSUE THREAD

**Issue by Muthuprasanth** [microsoftgraph/msgraph-sdk-javascript#68]
I need to set timezone in headers.If i use either header or headers it returns client.header is not a function or client.header is not a function.How and where to set headers

**Comment by MIchaelMainer** [comment]
Here's an example:
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/c91286e354a5d70c22f0a4b5b53afcefad263e84/samples/node/node-sample.js#L204
