### ISSUE TITLE
Developers should be able to leverage a simple Authentication Provider to integrate with their own token

### ISSUE THREAD

**Issue by sebastienlevert** [microsoftgraph/msgraph-sdk-javascript#682]
[AB#13253](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/13253)

**Comment by baywet** [comment]
@ddyett we're back to the AB board or this repo still has remnant of the configuration for some reason?

**Comment by sebastienlevert** [comment]
@baywet we are back. We are exploring right now but this will be a mix between Github and ADO and it really helps with reporting. We'll probably share more on the process soon!

**Comment by nikithauc** [comment]
#590
