### ISSUE TITLE
Is it possible to upload a file (.put) from the browser, or only Node?

### ISSUE THREAD

**Issue by dancampbell691** [microsoftgraph/msgraph-sdk-javascript#7]
In the examples for uploading (.put), you make use of fs.createReadStream, which is specific to Node and not available in the browser.  I've tried everything I can come up with to pass in a local file, including all options of FileReader.  But all result in the error _stream.pipe is not a function_.  My searching has just about lead me to believe it is impossible to create a readable stream from the browser.  But I just can't believe there's no way to upload via the js SDK from the browser?  Am I missing something obvious?

If it can be done, an example would be most useful.  (I can attest that there is not one anywhere on the entirety of the internet.)

**Comment by dan-silver** [comment]
The SDK is currently limited to only accepting file streams for uploading files with .put().  You're correct that this approach won't work in the browser so we're moving towards two methods, .put() and .putStream().  In the future, we might automatically detect if it's a stream or not so developers could always call .put().

`.put()` will accept any binary blob, such as an HTML file upload form.
```javascript
var file = document.querySelector('input[type=file]').files[0];

client
    .api('/me/photo/$value')
    .put(file, (err, res) => {
        console.log("We've updated your picture!");
    });
```

Feel free to try this out on the stream-refactor branch and we should have this merged in soon. There's also updated samples (/samples/browser) and clarification in the README file in that branch. Let me know if it works or if you run into any issues!

**Comment by dan-silver** [comment]
@dancampbell691 This is now available in the master branch and will be published to NPM in the next update. Please reopen this thread if you find any other issues with files uploads from the browser.
