### ISSUE TITLE
Incremental Auth

### ISSUE THREAD

**Issue by baykingsea** [microsoftgraph/msgraph-sdk-javascript#72]
Can I do incremental Auth with this library?  For example, a user signs in only with the profile but later authorizes access to to their email account or calendar.

**Comment by MIchaelMainer** [comment]
This library's focus is on making the calls to Microsoft Graph. You can use any auth library that will support making calls to our auth endpoints. Please read more 
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios

You will need to use v2 auth for incremental consent.
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-compare#incremental-and-dynamic-consent
