### ISSUE TITLE
GraphRequest path parsing causes wrong request

### ISSUE THREAD

**Issue by stijndeschuymer** [microsoftgraph/msgraph-sdk-javascript#730]
Hi, the path parsing in GraphRequest.ts is causing the `joinUrl` to be wrong in the following request
```
https://graph.microsoft.com/v1.0/me/onlineMeetings?$filter=JoinWebUrl%20eq%20'https://teams.microsoft.com/l/meetup-join...'
```
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/12cab04be663986bd07a911ef44ba8a1f3ce0415/src/GraphRequest.ts#L134

https://docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&tabs=http

**Comment by sebastienlevert** [comment]
Hello @stijndeschuymer! Can you confirm the version of the SDK you are using?

Thanks!

**Comment by stijndeschuymer** [comment]
Sorry no issue here, I should just URIencode the querystring 🤦
