### ISSUE TITLE
bad Content-Type in patch() call?

### ISSUE THREAD

**Issue by tomjebo** [microsoftgraph/msgraph-sdk-javascript#74]
I've been trying to use the following code: 

        client
            .api('/planner/tasks/' + task.id)
            .header("If-Match", task["@odata.etag"])
            .patch(patchString).then(function (res) {
                // refresh the data
                loadContextData();

                $("#pivotContainer").find("*").prop('disabled', false);
                $('#spinnerLoading').css({ "display": "none" });

                showNotification('Success!', 'Update the new task');
            }).catch(function (err) {
                // catch any error that happened so far
                console.log("Error: " + err.message);
            });

To update a Planner task. In Graph Explorer the basic REST call with all the same parameters returned status 204 and the task was updated. In my code using the Graph SDK js, the status 204 came back but the task was not updated. 

I found that the Content-Type used by the SDK patch call was "application/x-www-form-urlencoded" and not "application/json" like the Graph Explorer and as I would expect.

I added: 

            .header("Content-Type", "application/json")

and the task was updated as expected. 

Is this a bug in Graph SDK js patch() call? Should "application/json" be the default header used or is it more common to use this other Content-Type?

**Comment by muthurathinam** [comment]
Yeah the content type should be "application/json" by default. Its fixed in the dev branch and will be available in the next release.

**Comment by muthurathinam** [comment]
Fixed in the release https://github.com/microsoftgraph/msgraph-sdk-javascript/releases/tag/1.1.0
