### ISSUE TITLE
Call Graph API without user login 

### ISSUE THREAD

**Issue by SudipRai** [microsoftgraph/msgraph-sdk-javascript#779]
# Feature Request
Call Graph API without user login 
## Is your feature request related to a problem? Please describe
I have a access token provided by admin which is acquired on behalf of users. So while calling an API with the access token in header I am getting thefollowing error:
"code": "InvalidAuthenticationToken",
"message": "Access token has expired or is not yet valid."

**Comment by nikithauc** [comment]
Hi @SudipRai,

Are you using a node app or a web app? Which version of the SDK are you using? 
You would need to select an authentication flow and an auth provider based on your usage.

Following could help you with the selection:

https://docs.microsoft.com/en-us/graph/sdks/choose-authentication-providers?tabs=CS
https://docs.microsoft.com/en-us/graph/auth/auth-concepts

Please let me know if you have any questions

**Comment by SudipRai** [comment]
I am using the web app and SDK 1.8 version.
To get the access token I have used Authenticate on behalf of user with authorization code grant flow. 
Note: the access token is generated through the python using O365 module.

Using same access token to call graph API I am getting the above error.

**Comment by nikithauc** [comment]
If you have an access token you can simply  do something as follows 

```
const error = "error throw by the authentication handler";

const client = Client.init({
	defaultVersion: "v1.0",
	debugLogging: true,
	authProvider: (done) => {
		done(error, "ACCESS_TOKEN");
	},
});
```
See, the complete example: 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/javascript/clientInitialization/ClientWithOptions.js


I would also check for the scopes that are used to retrieve the access token.

**Comment by SudipRai** [comment]
> https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/samples/javascript/clientInitialization/ClientWithOptions.js

How can we implement this using Java/vert.x?
