### ISSUE TITLE
Cannot view entire message body

### ISSUE THREAD

**Issue by Rwiju** [microsoftgraph/msgraph-sdk-javascript#80]
![capture](https://user-images.githubusercontent.com/40265419/41407245-717ddeaa-6fec-11e8-9983-92b2892573a7.PNG)

 
The api only shows me the preview of the message. What do I need to do in order to view the whole message body on click?

**Comment by Rwiju** [comment]
https://stackoverflow.com/questions/50855479/view-full-message-body-with-outlook-api 
Link to Stackoverflow question

**Comment by muthurathinam** [comment]
The guide is to provide sample setup that to make calls to the outlook api through msgraph. If you want to get the whole message body of the mails you may have to change the snippet in [this call](https://docs.microsoft.com/en-us/outlook/rest/javascript-tutorial#the-getuserinboxmessages-function) by selecting body in the select query and utilize that response to achieve the functionality you desire.
