### ISSUE TITLE
Cannot add $select query to item within batch request content 

### ISSUE THREAD

**Issue by henhal** [microsoftgraph/msgraph-sdk-javascript#822]
# Bug Report

## Prerequisites

-   [X] Can you reproduce the problem?
-   [ ] Are you running the latest version?
-   [X] Are you reporting to the correct repository?
-   [ ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When using batch requests, each `BatchRequestStep` contains a plain `Request` object.
However, if some of the steps should include query parameters such as `$select`, something strange is happening: if a step has a request like `users/foo@bar.com?$select=mail,accountEnabled`, then `$select` will disappear, and the request will become `users/foo@bar.com?=mail,accountEnabled`, which means the desired selected fields won't be there.

**Console Errors:** N/A

**Screenshots:** N/A

## Steps to Reproduce

```
const content = await new BatchRequestContent([{
    id: 'foo',
    request: new Request('/users/foo@bar.com?$select=mail,accountEnabled')
}]).getContent();

const res = await client.api('/$batch').post(content);

for (const [id, response] of await new BatchResponseContent(await res.json()).getResponsesIterator()) {
  if (response.ok) {
    console.log('Batch item', id, await response.json());
  } else {
    console.error('Batch error', id, response.status);
  }
}

```
**Expected behavior:** 

It should be possible to add `$select` queries to items within batch requests.

**Actual behavior:** 

The `$select` query was malformed and ignored.

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response

SDK Version - [SDK version you are using]

-   [X] Node (Check, if using Node version of SDK)

> Node Version - 14

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by sebastienlevert** [comment]
Hello @henhal! Can you confirm the version of the SDK you are using?

Thanks!

**Comment by henhal** [comment]
I realized that if manually URL encoding the dollar sign in `$select`, it works:

```
const content = await new BatchRequestContent([{
    id: 'foo',
    request: new Request('/users/foo@bar.com?%24select=mail%2caccountEnabled')
}]).getContent();
```

So this was my fault.
However, I think it's unfortunate that the SDK has helper methods for building `select` params etc for single item queries, but for batch queries, all you have is standard `Request` objects. How about exposing similar API methods as for building single item requests to each item in a batch, e.g. by allowing a `GraphRequest` object instead of a `Request`? This could look something like:

```
const content = await new BatchRequestContent([{
    id: 'foo',
    request: client.api('/users/foo@bar.com).select(['mail', 'accountEnabled'])
}]).getContent();
```

My apologies if this is already addressed in v3. :)

**Comment by nikithauc** [comment]
Created #823 to verify if encoding issues can be fixed.
