### ISSUE TITLE
Encoding support in the Graph JS client library and documentation

### ISSUE THREAD

**Issue by nikithauc** [microsoftgraph/msgraph-sdk-javascript#823]
Users are expected to manually encode and pass the url to the `.api()` method. Related issues #625, #529.

- Check if a solution is possible.
- Provide documentation on the encoding/decoding practices.

**Comment by sebastienlevert** [comment]
We absolutely should look into this. The SDK experience will be greatly improved!

**Comment by sebastienlevert** [comment]
This won't be necessary in the latest version of the SDK with Kiota.
