### ISSUE TITLE
Run sample code

### ISSUE THREAD

**Issue by franferns** [microsoftgraph/msgraph-sdk-javascript#83]
I have downloaded and installed "npm install" . How do i run the sample code ?

**Comment by muthurathinam** [comment]
Refer this: https://github.com/microsoftgraph/msgraph-sdk-javascript#running-node-samples

**Comment by muthurathinam** [comment]
@franferns For running node samples refer the [README.md](https://github.com/microsoftgraph/msgraph-sdk-javascript#running-node-samples)
