### ISSUE TITLE
How to get calender's events by calendar name?

### ISSUE THREAD

**Issue by SudipRai** [microsoftgraph/msgraph-sdk-javascript#832]
I have tried this but does not work.
GET /me/calendars/{name}/calendarView?startDateTime={start_datetime}&endDateTime={end_datetime}
It throws this error.

"error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed."
    }

**Comment by sebastienlevert** [comment]
Based on the API documentation, getting a calendar by name is not possible, it needs to be via its id.

https://docs.microsoft.com/en-us/graph/api/calendar-list-calendarview?view=graph-rest-1.0&tabs=http

I'll close this issue as it's not an SDK issue but a capability request. You can use https://aka.ms/graphrequests to create a new idea of something we should consider for the Microsoft Graph API!
