### ISSUE TITLE
What is error 503 "SystemMemoryProtectionUtilizationMonitor is unhealthy"?

### ISSUE THREAD

**Issue by iqoOopi** [microsoftgraph/msgraph-sdk-javascript#854]
I'm sending out emails via MsGraph from my own node Azure function. From the azure function log, I found out that it happens from time to time that I received a 503 "SystemMemoryProtectionUtilizationMonitor is unhealthy" error when calling the MsGraph API. The api works most of the time but gets this error occasionally.

Wondering anyone knows what this error means and how to fix it?

Thanks

I also posted this question in stackoverflow: https://stackoverflow.com/questions/72703689/get-503-systemmemoryprotectionutilizationmonitor-is-unhealthy-error-when-try

**Comment by nikithauc** [comment]
@iqoOopi 

- Can you please provide the request URL and the details of the request body?
- Are you getting a request id from the API which the request?

cc: @sebastienlevert

**Comment by sebastienlevert** [comment]
503 errors are errors from the server. They are going to happen (not very frequently, but definitely to be expected) and your code should catch them and retry. Some of our retry handling features should do it for you also!

Can you share a request id and timestamp?
