### ISSUE TITLE
How to create a Graph Client from an Azure AD access token? 

### ISSUE THREAD

**Issue by diberry** [microsoftgraph/msgraph-sdk-javascript#875]
How do I go from an Azure AD bearer token to a Graph Client on behalf of a user? 

I have the following KeyVault code and not sure how to switch in the Graph SDK to replace the KeyVault. 

```
const { OnBehalfOfCredential } = require("@azure/identity");
const { Client } = require("@microsoft/microsoft-graph-client");

// read the AD access token from the bearer token value
  const bearerToken = (req.headers['authorization'] || "no authorization header found").toString();
 accessToken = bearerToken.substring(7, bearerToken.length);

 const tokenCredential = new OnBehalfOfCredential({
  AZURE_TENANT_ID,
  AZURE_CLIENT_ID,
  AZURE_CLIENT_SECRET, 
  userAssertionToken: accessToken
});

const client = new KeyClient("vault-url", tokenCredential);
await client.getKey("key-name");

```

I'm working on Azure App Service docs E2E scenario. 

```
const { OnBehalfOfCredential } = require("@azure/identity");
const { Client } = require("@microsoft/microsoft-graph-client");

// read the AD access token from the bearer token value
  const bearerToken = (req.headers['authorization'] || "no authorization header found").toString();
 accessToken = bearerToken.substring(7, bearerToken.length);

 const tokenCredential = new OnBehalfOfCredential({
  AZURE_TENANT_ID,
  AZURE_CLIENT_ID,
  AZURE_CLIENT_SECRET, 
  userAssertionToken: accessToken
});

/// add code to get Graph Client here

const client = new Graph(some params?);

// use client to get /me

```

**Comment by nikithauc** [comment]
@diberry Thank you for reaching out!

Here is sample to create  `TokenCredentialAuthenticationProvider` instance.

```
const credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
const authProvider = new TokenCredentialAuthenticationProvider(credential, { scopes: [scopes] });
const client = Client.initWithMiddleware({
	debugLogging: true,
	authProvider,
});
``` 

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/eb540eb03593876a45d5cd6c8ffef5c03b22a061/samples/javascript/clientInitialization/tokenCredentialAuthenticationProvider/index.js#L20

Doc ; 
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/docs/TokenCredentialAuthenticationProvider.md


Please let me know if you have more questions.

**Comment by diberry** [comment]
@nikithauc Your example code doesn't actually show how to go from an AD access token to a Graph Client. There is no access token in the code. An access token identifies an AD account, while a tenant/client/clientsecret identify the app the AD account wants to connect to. 

I have a user's access token, and I need to create a Graph Client to access that person's information. While I do need the app registration information as _part_ of that solution, it isn't the entire solution until the user is acted on behalf of with the access token.

**Comment by nikithauc** [comment]
I see. Please let me know if the following way to pass a callback returning an access token at the time of client creation works for you:

```
const client = Client.init({
	defaultVersion: "v1.0",
	debugLogging: true,
	authProvider: (done) => {
		done(error, "ACCESS_TOKEN");
	},
});
```
https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/eb540eb03593876a45d5cd6c8ffef5c03b22a061/samples/javascript/clientInitialization/ClientWithOptions.js#L13

**Comment by diberry** [comment]
I need to pass in the access token somewhere to eventually get the Graph SDK Client. The code you are showing doesn't take in an access token but instead returns it.

**Comment by nikithauc** [comment]
Let me know if the options works for you:

1.   Using a callback


```
const accessToken = ()=>{

from your logic
    return "user'acessToken";
}

export const client = Client.init({
	defaultVersion: "v1.0",
	debugLogging: true,
	authProvider: (done) => {
		done(error, accessToken());
	},
});

```

2. Write your custom authentication provider implementing the `IAuthenticationProvider` and pass it using `Client.initWithMiddleware`

```
class MyAuthProvider implements AuthenticationProvider {
    public async getAccessToken(authenticationProviderOptions?: AuthenticationProviderOptions | undefined): Promise<string> {
        // the custom logic to retrieve this code
        //         const { OnBehalfOfCredential } = require("@azure/identity");
        // const { Client } = require("@microsoft/microsoft-graph-client");

        // // read the AD access token from the bearer token value
        //   const bearerToken = (req.headers['authorization'] || "no authorization header found").toString();
        //  accessToken = bearerToken.substring(7, bearerToken.length);

        //  const tokenCredential = new OnBehalfOfCredential({
        //   AZURE_TENANT_ID,
        //   AZURE_CLIENT_ID,
        //   AZURE_CLIENT_SECRET, 
        //userAssertionToken: accessToken
        //});
        // get the token and return it

        return "USER_ACCESS_TOKEN";
    }

}
export const client = Client.initWithMiddleware({
    defaultVersion: "v1.0",
    debugLogging: true,
    authProvider: new MyAuthProvider()
});
```
