### ISSUE TITLE
Bug - LargeFileUploadTask will not report 100% upload progress

### ISSUE THREAD

**Issue by ChikyChan** [microsoftgraph/msgraph-sdk-javascript#915]
# Bug Report

## Prerequisites
-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

[Description of the bug or feature]

I was following the [Upload large files using the Microsoft Graph SDKs](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=typescript) sample to implement file upload function, and when I use this implemented function to file upload, I found that the `uploadEventHandlers.progress` will not be triggered while the last slice uploaded.

I checked the source code, found that if the last slice uploaded, Graph API will respond the `driveItem` information with `201 Created` status code, and in source code, if Graph API return `201`, it will return the response immediately.

**Console Errors:** None

**Screenshots:** [If applicable, add screenshots to help explain your problem]
The network requests
![Network requests](https://user-images.githubusercontent.com/100360506/183381829-8fca0616-9e35-4aac-a419-0e2c986ea0db.png)

LargeFileUplaodTask source code
[LargeFileUploadTask.ts](https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/dev/src/tasks/LargeFileUploadTask.ts)
![Source Code](https://user-images.githubusercontent.com/100360506/183381331-1d6daa88-4cbe-40e7-932e-853dca61bd15.png)

## Steps to Reproduce

1. Follow the steps [Upload large files using the Microsoft Graph SDKs](https://docs.microsoft.com/en-us/graph/sdks/large-file-upload?context=graph%2Fapi%2F1.0&view=graph-rest-1.0&tabs=typescript) 
2. Login my application and proceed file upload.

**Expected behavior:**
LargeFileUploadTask report 100% after file upload finished

**Actual behavior:**
LargeFileUploadTask will not report 100% after file upload finished, like dotnet client did.

## Additional Context

Add any other context about the problem here..

## Usage Information
Request ID - Value of the `requestId` field if you are receiving a Graph API error response
None

SDK Version - [SDK version you are using] 3.0.2

-   [ ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [x] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]
Edge

> Version - [The version of the browser you are using]
Version 104.0.1293.47 (Official build) (64-bit)

**Comment by rkodev** [comment]
Hi @ChikyChan thanks for reporting this. 

This issue is currently being looked at and will be updated accordingly when fixed.

**Comment by nikithauc** [comment]
Fix released in 3.0.3
