### ISSUE TITLE
Error when implementing continuous access evaluation

### ISSUE THREAD

**Issue by salman90** [microsoftgraph/msgraph-sdk-javascript#932]
# Bug Report

## Prerequisites

-   [ x ]  Can you reproduce the problem?
-   [ x ] Are you running the latest version?
-   [ x ] Are you reporting to the correct repository?
-   [ x ] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

I am trying to implement [continuous access evaluation](https://docs.microsoft.com/en-us/azure/active-directory/develop/app-resilience-continuous-access-evaluation?tabs=JavaScript#the-code) using graph SDK. The issue is when I call graph utilizing the SDK, I get the error object, but I do not receive the complete response with the wwwAuthenticate header so I can extract the claims challenge from the 401 error. 

- Error Object when using SDK:
![cae-sdk](https://user-images.githubusercontent.com/18670157/186507512-4dcae9a7-5e39-4e93-9f73-055d17fa0027.png)

-  Desired response error:
```console
HTTP 401; Unauthorized
WWW-Authenticate=Bearer
  authorization_uri="https://login.windows.net/common/oauth2/authorize",
  error="insufficient_claims",
  claims="eyJhY2Nlc3NfdG9rZW4iOnsibmJmIjp7ImVzc2VudGlhbCI6dHJ1ZSwgInZhbHVlIjoiMTYwNDEwNjY1MSJ9fX0="
```

Is there a way to receive the complete error response using the SDK? Thanks!

SDK Version - 3.0.2

-   [ v14.16.1 ] Node (Check, if using Node version of SDK)

> Node Version - [The version of Node you are using]

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - chrome

> Version 104.0.5112.102

**Comment by nikithauc** [comment]
@salman90 Would getting the raw response help in this case?

https://github.com/microsoftgraph/msgraph-sdk-javascript/blob/a26c288b3463c49bf9862e32865bd0beed72753a/docs/GettingRawResponse.md#getting-raw-response-by-setting-responsetype

**Comment by salman90** [comment]
@nikithauc That works. Thanks for the help!
