### ISSUE TITLE
Creating app password does not set displayName

### ISSUE THREAD

**Issue by zane-atomus** [microsoftgraph/msgraph-sdk-javascript#960]
# Bug Report

## Prerequisites

-   [x] Can you reproduce the problem?
-   [x] Are you running the latest version?
-   [x] Are you reporting to the correct repository?
-   [x] Did you perform a cursory search?

For more information, see the `CONTRIBUTING` guide.

## Description

When adding a password credential for an app registration using `POST /applications/{id}/addPassword`, the `displayName` property of the credential is not set.

**Console Errors:** [Is there any console error]
N/A

**Screenshots:** [If applicable, add screenshots to help explain your problem]

## Steps to Reproduce

1. Create a password and print the result: `console.log(await client.api("/applications/${appId}/addPassword\").post({ displayName: "Password display name" }))`

**Expected behavior:**

The created password's `displayName` property should equal "Password display name"

**Actual behavior:**

The created password's `displayName` property equals `null`

## Additional Context

The created app password also does not show a Description/Display Name in the portal.

If you create a password in the Azure portal with a display name, and then retrieve it using the graph sdk (i.e. `console.log(await client.api("/applications/${id}").select("id,displayName,passwordCredentials"))`, the display name property will equal the name you gave in the portal for that password (expected behavior).

## Usage Information

SDK Version - 3.0.2

-   [x] Node (Check, if using Node version of SDK)

> Node Version - 16.15.1

-   [ ] Browser (Check, if using Browser version of SDK)

> Browser Name - [The name of Browser that you are using for SDK]

> Version - [The version of the browser you are using]

**Comment by nikithauc** [comment]
@zane-atomus  Thank you for reporting this issue! This is a service issue.

I will get in touch with the service team and get some update.

**Comment by madansr7** [comment]
@zane-atomus thanks for reporting the issue. I was able to repro on my end and will open a bug for the team to look into it.

**Comment by nikithauc** [comment]
Closing this issue as this will be taken care of by the workload team.
