### ISSUE TITLE
Simplify using the Graph JS SDK as ESM in the browser

### ISSUE THREAD

**Issue by waldekmastykarz** [microsoftgraph/msgraph-sdk-javascript#970]
Since modern browsers support ESM these days, we should consider improving the developer experience of using the Graph JS SDK as ESM in their client-side apps. The biggest benefit of using ESM is increased modularity of the app (not polluting the global namespace) and a modern programming style that's closer to TypeScript and server-side JavaScript.

The main struggle with using the Graph JS SDK as ESM right now, are references to tslib and other modules, that require using importmaps. I've put together an [example](https://github.com/waldekmastykarz/js-graph-101/blob/main/index_esm.html) that shows a minimal app based on ESM. It would be helpful if we could simplify the developer experience around ESM in the browser.

**Comment by sebastienlevert** [comment]
Definitely for our future version of the SDK. I would make sure we have a fully working ESM version with v4.0 when available!

**Comment by nikithauc** [comment]
@waldekmastykarz can you please provide a sample snippet of a simplified developer experience?

**Comment by waldekmastykarz** [comment]
@nikithauc please see the link I included in message earlier for a minimal working app.

**Comment by sebastienlevert** [comment]
This is taken care of in Kiota. It's now an ESM only module!
