### ISSUE TITLE
nextLink with /delta doesn't work for /users

### ISSUE THREAD

**Issue by InternetExplorer8** [microsoftgraph/msgraph-sdk-javascript#99]
`nextLink` does not work with `/delta` for `/users/**`. The first request (first page) works fine, but as soon as we want to load more data via nextLink, we get the following error message:

`
{  
   code:'SyncStateNotFound',
   message:'The sync state root folder is not found.'
}
`

Same issue:
https://stackoverflow.com/questions/49935297/microsoft-graph-get-delta-changes-in-meeting-room-calendars?rq=1

**Comment by muthurathinam** [comment]
@InternetExplorer8 
Thank you for reporting this issue, I will look into this.

**Comment by MIchaelMainer** [comment]
Is this issue still open? I'm able to perform a /delta call on /users with no problem and then use the nextlink to get the subsequent pages. Please open this issue if you are still seeing this error.
